### ISSUE TITLE
Injection does not work in library projects

### ISSUE THREAD

**Issue by jrgonzalezg** [JakeWharton/butterknife#100]
I am having problem with ButterKnife injections on library projects. Whenever i try any view injection such as:

``` java
@InjectView(R.id.content_frame)
protected FrameLayout contentFrame;
```

I get a compile time error: "error: attribute value must be constant" on the "R.id.content_frame". This occurs both using Android Studio and latest gradle plugin builds.

Any idea why?

**Comment by Limitin** [comment]
Jake, is there any way to support library projects in the future? I love Butterknife in my other projects, but I am currently working on one that uses a shared "library" codebase to make three apps that mostly do style and resource overrides. Having Butterknife supporting the library project would be amazing.

**Comment by suyambu** [comment]
Jake, Shall we expect any improvements on this?

**Comment by JakeWharton** [comment]
No. It's unlikely to ever be supported.

**Comment by Limitin** [comment]
Aw. I would love to be using this for a library module I am working on for my company. The library serves as the base application project with all of the shared code between most of the apps my company makes.

**Comment by steffandroid** [comment]
As Butterknife won't support this, the next best option is probably ![Butterfork](https://github.com/oguzbabaoglu/butterfork).

**Comment by kongsonida** [comment]
The lib version 7.0.1 is not support @InjectView(name = "content_frame")

What should we do ?

**Comment by peacepassion** [comment]
Butterfork is a solution. But I found another solution which used more easier. Ref [ButterCookie](https://github.com/JackCho/ButterCookie).

**Comment by mrfluency** [comment]
I want to use it in libary with R2,but when i user the binded view ,report nullpointException,why?

**Comment by JakeWharton** [comment]
That isn't enough information to be an actionable bug report.

**Comment by rogerhu** [comment]
The README instructions are somewhat misleading, the Gradle plugin for library projects only create a seperate R2 class.  I believe you still need to include the Dagger compiler too as well right?

**Comment by mohamed-elwy** [comment]
i followed the README, but i get an error (cannot resolve symbol 'R2'), did i miss something?!

**Comment by davidandreoletti** [comment]
Same issue as @mohamed-elwy. R2 file not generated & resolved.

Env: 
Butterknife 8.2.1 (and also tried with 8.2.0)
No dagger dependency

**Comment by elye** [comment]
Great to have now Butterknife supported in Library using R2.

I face a new issue, where if I have library A viewX, inheriting from library B viewY... I notice my butterknife injected in library B viewY is not working. (If I move viewY to library A, everything works).

Is this expected issue? or it shouldn't be an issue. i.e. my code issue somewhere.

**Comment by nethergrim** [comment]
This is also relates to Android Instant App. Just figured out that feature modules in the Instant App also don't put constants to R.java, so butterknife prevents code from being compiled.

**Warning!**

If you have a large project, and you want to break it to few modules/instant apps, you can't use ButterKnife in any of those modules.
