### ISSUE TITLE
java.lang.NoSuchMethodError: butterknife.internal.ListenerClass.remover()Ljava/lang/String;

### ISSUE THREAD

**Issue by luziming** [JakeWharton/butterknife#1004]
![image](https://user-images.githubusercontent.com/22277157/27828586-69266dd8-60ef-11e7-9c5f-4d54e57caaff.png)

**Comment by Abdelalim-dev** [comment]
@luziming did you find anything yet?

**Comment by JakeWharton** [comment]
It was added in 8.1.0. Maybe ProGuard is removing it. Please provide a sample that demonstrates the problem.

**Comment by luziming** [comment]
I have solved this problem, because there are 8.1.0 before the jar forget to delete, it may be repeated

**Comment by JakeWharton** [comment]
Great!
