### ISSUE TITLE
how to use butterknife in a library module?

### ISSUE THREAD

**Issue by yummyChina** [JakeWharton/butterknife#1008]
Now, I have put my baseactivity in a serparated module,and I inject the butterknife in the baseactivity,Then I would implements the baseactivity in my app module, The problem is that it throw NullPointerException  on widgets which defined by butterknife,anyone can help me?

**Comment by JakeWharton** [comment]
This configuration is not supported. Dupe of #808.

**Comment by dinukapj** [comment]
Hi @JakeWharton any updates on this yet? May I ask what's the issue that's blocking this configuration? Thanks.
