### ISSUE TITLE
Unable to bind views inside RecyclerView.ViewHolder in last version 8.7

### ISSUE THREAD

**Issue by BahaaIddinSharqawi** [JakeWharton/butterknife#1009]
There is problem when binding views from recyclerview adapter inside ViewHolder.

When I assigned values to views inside bind method, the below exception is thrown

 "java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference"

    public class VH extends RecyclerView.ViewHolder {
        @BindView(R.id.title)
        TextView mTitle;
        @BindView(R.id.subtitle)
        TextView mSubTitle;
        @BindView(R.id.description)
        TextView mDescription;
        @BindView(R.id.rating_image)
        ImageView mRatingImage;
        @BindView(R.id.rating)
        TextView mRating;

        public VH(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);
        }
        public void bind(Movie movie){
            mTitle.setText(movie.getTitle());
            mSubTitle.setText(movie.getReleaseDate());
            mDescription.setText(movie.getOverview());
            mRating.setText(String.valueOf(movie.getVoteAverage()));
        }
    }

Note: I tried use older version of Butterknife such as 6.0.0 and the code works properly.

**Comment by JakeWharton** [comment]
Enable debug logging and paste what it prints. Also do you see the generated code in the build directory?

**Comment by BahaaIddinSharqawi** [comment]
@JakeWharton 

 07-16 09:58:47.065 17112-17112/com.clogica.retrofitsample D/ButterKnife: Looking up binding for com.clogica.retrofitsample.adapter.MoviesAdapter$VH
07-16 09:58:47.075 17112-17112/com.clogica.retrofitsample D/ButterKnife: Not found. Trying superclass android.support.v7.widget.RecyclerView$ViewHolder
07-16 09:58:47.075 17112-17112/com.clogica.retrofitsample D/ButterKnife: MISS: Reached framework class. Abandoning search.

There is no generated code for Butterknife in the build directory...

**Comment by JakeWharton** [comment]
That indicates that you have not correctly configured the compiler. Have
you followed the instructions in the README?

**Comment by BahaaIddinSharqawi** [comment]
Thank you, it's working now. I forgot to add **annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'** to dependencies in app build.gradle file.

Another question if possible, how to apply optional annotation (@Optional) to specific filed?

**Comment by JakeWharton** [comment]
Use `@Nullable`
