### ISSUE TITLE
Unable to add butterknife

### ISSUE THREAD

**Issue by Maverick7V** [JakeWharton/butterknife#1010]
I am getting the following error when I am syncing the project after adding dependencies
Error:(27, 0) Could not find method annotationProcessor() for arguments [com.jakewharton:butterknife-compiler:8.7.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by JakeWharton** [comment]
The `annotationProcessor` configuration has been present since Android Gradle plugin 2.2.0. Ensure you are using the latest version which is 2.3.3.
