### ISSUE TITLE
null exception on binding

### ISSUE THREAD

**Issue by mehdi-salehi** [JakeWharton/butterknife#1011]
07-17 14:44:01.292: D/ButterKnife(31927): Looking up binding for ir.mehdisalehi.serviceprovider.ui.component.main.MainActivity
07-17 14:44:01.292: D/ButterKnife(31927): Not found. Trying superclass ir.mehdisalehi.serviceprovider.ui.base.BaseActivity
07-17 14:44:01.293: D/ButterKnife(31927): Not found. Trying superclass com.hannesdorfmann.mosby3.mvp.MvpActivity
07-17 14:44:01.293: D/ButterKnife(31927): Not found. Trying superclass android.support.v7.app.AppCompatActivity
07-17 14:44:01.293: D/ButterKnife(31927): MISS: Reached framework class. Abandoning search.
07-17 14:44:01.355: I/zzai(31927): Making Creator dynamically
07-17 14:44:01.375: D/ButterKnife(31927): Looking up binding for ir.mehdisalehi.serviceprovider.ui.component.home.MainMapFragment
07-17 14:44:01.376: D/ButterKnife(31927): Not found. Trying superclass ir.mehdisalehi.serviceprovider.ui.base.BaseFragment
07-17 14:44:01.376: D/ButterKnife(31927): Not found. Trying superclass com.hannesdorfmann.mosby3.mvp.MvpFragment
07-17 14:44:01.377: D/ButterKnife(31927): Not found. Trying superclass android.support.v4.app.Fragment
07-17 14:44:01.377: D/ButterKnife(31927): MISS: Reached framework class. Abandoning search.

07-17 14:44:01.427: E/UncaughtException(31927): java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.mehdisalehi.serviceprovicer/ir.mehdisalehi.serviceprovider.ui.component.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void ir.mehdisalehi.serviceprovider.mapApi.Map.setCallback(ir.mehdisalehi.serviceprovider.mapApi.MapCallBack)' on a null object reference

**Comment by JakeWharton** [comment]
Either you haven't configured your build properly (see the README) or a tool is removing the generating code from your APK. Either way, this isn't an issue with the library. Please ensure proper configuration such that the generated code appears in your `build/` dir and use tools like APK inspector to ensure that generated code winds up in the final APK. Also if you are using multidex ensure it's configured correctly. No action for Butter Knife to take here.
