### ISSUE TITLE
Is it possible to make butterknife work with scala sbt build tool?

### ISSUE THREAD

**Issue by yuiopt** [JakeWharton/butterknife#1013]

**Comment by JakeWharton** [comment]
Sure. Put the butterknife artifact on the compilation classpath and in the APK and put the butterknife-compiler artifact on the annotation processor classpath. How you do that exactly, however, is for the sbt people to document.

**Comment by yuiopt** [comment]
I have one android project written in Java code, in this project I used the butterknife framework, there is another Scala android project, I have to put two projects together, but I don't know if butterknife could( and I don't know how if it could) work with sbt  to process the annotation of the source code.
