### ISSUE TITLE
Generate Kotlin extension functions for calling the generated ViewBindings

### ISSUE THREAD

**Issue by vanniktech** [JakeWharton/butterknife#1016]
Given a class `AboutActivity` it would be cool to have a generated extension function `AboutActivity.bind()` that just calls `AboutActivity_ViewBinding(this)`

The same could also be applied for Dialogs / Views.

What do you think?

**Comment by JakeWharton** [comment]
I like it. Can we do this as part of the normal processor and just have the
kt files ignored by javac? Or do we need a second processor?

**Comment by vanniktech** [comment]
Aren't `kt` files ignored by javac by default?

**Comment by JakeWharton** [comment]
It's more complicated than that. If kapt will accept non-source file
outputs suffixed with .kt files then it's as easy as that, but if it
requires source file outputs and javac also tries to compile them as java
then it won't.

**Comment by JakeWharton** [comment]
https://medium.com/the-fabulous/kotlin-extension-methods-generation-15b5e6499dc8

**Comment by blipinsk** [comment]
@JakeWharton moving my question from reddit here:
I can create a PR with those changes, would you rather have the `ButterKnifeKtx.bind(this)` or the "original" `Activity.bindViews()` with specialized receiver type?

**Comment by JakeWharton** [comment]
This will work well with the reflection-based backend, too. It means you can have direct references when the processor is used and reflection for IDE builds. No `Class.forName` anywhere.

**Comment by vanniktech** [comment]
Using ViewBinding now
