### ISSUE TITLE
click event does not take effect

### ISSUE THREAD

**Issue by jdsjlzx** [JakeWharton/butterknife#1020]
I'm running:

Android Studio 2.3.3
Butterknife 8.7.0
My project has an app module and a library module, in the library module I have:

apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'

android {
    ...
}
dependencies {
    ...
     compile "com.jakewharton:butterknife:$butterknife_version"
    annotationProcessor 'com.jakewharton:butterknife-compiler:$butterknife_version'
}

In the library, the following code is no problem:

@OnClick(R2.id.submit)
public void sayHi(View view) {
  button.setText("Hello!");
}

**but the click event cannot respond below, I don't know why.**

@OnClick({ R2.id.button1, R2.id.button2, R2.id.button3 })
public void pickDoor(View view) {
 switch (view.getId()) {
            case R2.id.button1:
                ...
                break;
            case R2.id.button2:
                ...
                break;
            case R2.id.button3:
                ...
                break;
            default:
                break;
        }
}

 Is this a bug?

Hope to get to reply as soon as possible! Thank you!

**Comment by JakeWharton** [comment]
Do not use `R2.id` when checking the view ID. Use the normal `R.id.` reference. There should be a lint check that prevents this which you should run on your CI builds.

**Comment by jdsjlzx** [comment]
thank you!

**Comment by yangfuzhi** [comment]
the question is fix？ why i use R.id is not help!
