### ISSUE TITLE
Occasionally  NullPointException

### ISSUE THREAD

**Issue by nanchen2251** [JakeWharton/butterknife#1021]
In Fragment, We traced the null pointer through bugly, it only in fragment. However, only a small number of users will experience this.

**Comment by JakeWharton** [comment]
There is not enough information to make this report actionable. If you believe there is a library bug please provide a failing test case, a sample that reproduces, or more information about your setup.

**Comment by nanchen2251** [comment]
I think my usage mode is correct. Because it doesn't always appear, I found a great deal of customization in View.

I'm in onCreate method bind, and in onDestroy method unbind.

Basically custom view in fragment
