### ISSUE TITLE
Please update jquery-maven-artifact to avoid mixed-content error on HTTPS

### ISSUE THREAD

**Issue by argen666** [JakeWharton/butterknife#1023]
Please update jquery-maven-artifact to avoid mixed-content error on HTTPS.
Link: https://jakewharton.github.io/butterknife/

Details about this issue below:
https://github.com/JakeWharton/jquery-maven-artifact/pull/4

Thanks
![image](https://user-images.githubusercontent.com/2426839/28574805-cf7b1ed0-7170-11e7-881b-8cd1891e7ffe.png)

**Comment by TheWildHorse** [comment]
Still a problem :)
