### ISSUE TITLE
Getting Null on @BindView

### ISSUE THREAD

**Issue by goyalzz** [JakeWharton/butterknife#1030]
Hi, I am getting null object reference on bind view as shown below

Gradle Dependencies:
```
compile 'com.jakewharton:butterknife:8.7.0'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'
```

Packaging Options:
```
exclude 'META-INF/services/javax.annotation.processing.Processor'
```

Proguard:
```
# Retain generated class which implement Unbinder.
-keep public class * implements butterknife.Unbinder { public <init>(**, android.view.View); }
-keep public class * implements butterknife.internal.ViewBinder { public <init>(); }

# Prevent obfuscation of types which use ButterKnife annotations since the simple name
# is used to reflectively look up the generated ViewBinding.
-keep class butterknife.*
-keepclasseswithmembernames class * { @butterknife.* <methods>; }
-keepclasseswithmembernames class * { @butterknife.* <fields>; }
-keep class **$$ViewBinder { *; }
-keep class **$ViewHolder { *; }
-keep class butterknife.**$Finder { *; }
```

Code Snippet for initializing Activity:
```
*****

@BindView(R.id.username_activity_login)
public EditText et_username;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);
        ButterKnife.setDebug(true);
        ButterKnife.bind(this);
*****
```

Gradle version:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
```

By using above code and configuration @BindView doesn't work, Please help to resolve this issue.

Thanks.

**Comment by JakeWharton** [comment]
The ProGuard rules and packaging options can be deleted in their entirety.

Is there generated code in the `build/` folder? Without a representative sample it's impossible to know what's going on.

**Comment by goyalzz** [comment]
Only DataBindingInfo class found in build/dataBinding
```
package android.databinding.layouts;

import android.databinding.BindingBuildInfo;

@BindingBuildInfo(buildId="ef51ef81-e3ba-45df-9e6b-5cf48e3a5201")
public class DataBindingInfo {}
```
And also found ```data-binding-compiler```, ```data-binding-info```, ```data-binding-layout-out``` in the intermediates

And here are the ButterKnife debug logs

**Comment by JakeWharton** [comment]
The compiler is not running and generating the code. Without a representative sample project it's impossible to know why, but it's a build problem and not a problem with this libary.

**Comment by goyalzz** [comment]
Hi @JakeWharton 
Here is the Sample Application that contains the issue
https://github.com/goyalzz/ButterKnifeDemo.git

And here is the invite for this repo
https://github.com/goyalzz/ButterKnifeDemo/invitations

**Comment by goyalzz** [comment]
Hi @JakeWharton,
Please help me to resolve this issue.

**Comment by JakeWharton** [comment]
This is not a support forum. When I get time, I'll look at your sample and
determine if it's a bug or not.

**Comment by colinrtwhite** [comment]
@goyalzz You're trying to use `apt` and `annotationProcessor` at the same time, which isn't supported. Remove the dependency on `apt` and change your Dagger dependency to:

    annotationProcessor 'com.google.dagger:dagger-compiler:2.11'
    compile 'com.google.dagger:dagger:2.11'

**Comment by goyalzz** [comment]
Thanks @colinrtwhite, It's working fine.
