### ISSUE TITLE
BindView returns null

### ISSUE THREAD

**Issue by lawloretienne** [JakeWharton/butterknife#1033]
I am trying to use the latest version of Butterknife 8.7.0.  I have turned debugging on and it logs the following.

```
D/ButterKnife: Looking up binding for com.sampleapp.android.ui.main.MainActivity
D/ButterKnife: Not found. Trying superclass com.sampleapp.android.ui.base.PreMainActivity
D/ButterKnife: Not found. Trying superclass android.support.v7.app.AppCompatActivity
D/ButterKnife: MISS: Reached framework class. Abandoning search.
```

I don't see any generated code in the `/build` directory.  I am getting a null pointer exception on the view that i have tried to bind with the `@BindView` annotation.

I have read the https://github.com/JakeWharton/butterknife/blob/master/README.md and set up the configuration as you have it there : 

```
dependencies {
  compile 'com.jakewharton:butterknife:8.7.0'
  annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'
}
```

This is not a library project.  I am running Android Studio 3.0 Canary 8. I am using the following version of the gradle plugin  :
`classpath 'com.android.tools.build:gradle:3.0.0-alpha8'` 
Any ideas what could be the issue?

**Comment by JakeWharton** [comment]
If there is no generated code then the processor isn't running. Without a representative sample there's no way to know what's wrong.

**Comment by lawloretienne** [comment]
How do I check that?

**Comment by lawloretienne** [comment]
What is the lowest version of ButterKnife that works on this version of Android Studio ?

**Comment by JakeWharton** [comment]
The Android Studio version is irrelevant. Every version of ButterKnife works with every version of Android Studio and every version of the Android Gradle plugin.

**Comment by lawloretienne** [comment]
What can i do on my end to try to track this down and debug the problem?

**Comment by JakeWharton** [comment]
Create a representative sample that I can play with. The problem is in Butter Knife but in the build tools you are using to run it. I don't have a problem with any of the versions you are using currently.

**Comment by lawloretienne** [comment]
Would you prefer to have an APK ?

**Comment by JakeWharton** [comment]
No. There's nothing interesting about the APK except that the classes are
missing and that has everything to do with the build tools.

**Comment by lawloretienne** [comment]
So I can temporarily give you access to my private repo if that would work.  Then i can tell you the branch to checkout.

**Comment by JakeWharton** [comment]
A standalone project would be better, as creating one might identify the
problem.

**Comment by lawloretienne** [comment]
So i created a new Android Studio project with an Activity with only one TextView and setup butterknife and everything works.  So now im trying to slowly add to this project to see where the issue lies.  Maybe there is a conflicting dependency or some build.gradle configuration that is tripping things up.

**Comment by lawloretienne** [comment]
I am getting these warning when i build the project : 
```
Warning:android-apt plugin is incompatible with future version of Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.
Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
```

However I have not used `android-apt` anywhere in my `build.gradle` file.

**Comment by lawloretienne** [comment]
So i believe the issue was i had an older version of the realm plugin in my project

https://stackoverflow.com/questions/42736720/android-studio-2-3-update-warningusing-incompatible-plugins-for-the-annotatio

`Older versions of Realm use android-apt`

After updating to the latest Realm plugin everything worked.

So it looks like other 3rd party libraries that still use android-apt can affect ButterKnife.

**Comment by JakeWharton** [comment]
It'll affect all annotations processes defined with `annotationProcessor` and not `apt` in that case, but upgrading is the better solution.
