### ISSUE TITLE
Screen orientation change call @OnFocusChange... any workaround?

### ISSUE THREAD

**Issue by HowardSchmaeu** [JakeWharton/butterknife#1034]
if i use `@OnFocusChange` on a button then i got an issue after rotate the screen:

- i hit the button
- i rotate the screen
- i got `@OnFocusChange`

i have the same behavior also with the `button.setOnFocusChangeListener(...)` but i found a workaround:

i put the creation of the listener in `onViewCreated(View view, Bundle savedInstanceState)` instead to use the butterknife `@OnFocusChange` ... now i can check `savedInstanceState`... is it not null i can avoid the call in `onFocusChange(...)`

is there anything i can do like this also in butterknife to avoid the call at `@OnFocusChange` too?

**Comment by JakeWharton** [comment]
The best you can do is the same thing, except store the boolean in a field so that it can be accessed from the focus method. Just make sure you write it out before calling Butter Knife's `bind` method.
