### ISSUE TITLE
Android ListView Adapter addFooterView(); Butterknife

### ISSUE THREAD

**Issue by TeodorKolev** [JakeWharton/butterknife#1035]
My target is to use Butterknie on ListView addFooterView(). How is that possible? Working code so far (without ButterKnife):

```
ArrayAdapter<String> adapter = new ArrayAdapter<>(getContext(), R.layout.some_layout);
View footer = View.inflate(this.getContext(), R.layout.footer_layout, null);
sitView.addFooterView(footer);
sitView.setAdapter(adapter);

btn = (Button) footer.findViewById(R.id.btn);
btn.setOnClickListener(new View.OnClickListener() {
    public void onClick(View v) {
        method();
    }
});
```
How can I use ButterKnife on this? Note that this is my fragment view. I can create separate class for adapter, but I cannot bind footer view buttons there, because they are not in list view item.

**Comment by JakeWharton** [comment]
You have to create a separate object with only `@BindView`s for the footer. Then, use the two-argument version of `bind()` to bind an instance of that object to the `footer` view.

**Comment by TeodorKolev** [comment]
I do not understand
