### ISSUE TITLE
Font binding 

### ISSUE THREAD

**Issue by SakheCodes** [JakeWharton/butterknife#1036]
From which  android studio version on wards  must one be on to use the font binding ?

**Comment by JakeWharton** [comment]
Any version works. This project has no dependency on your IDE version.

**Comment by SakheCodes** [comment]
Oh because i've tried using the @Bindfont(R.font) doesn't recognise the the font folder within res

**Comment by JakeWharton** [comment]
You'll have to consult the IDE documentation for what versions work with
fonts then. Butter Knife just exposes the built-in functionality in a
different way. It doesn't require anything itself.

**Comment by SakheCodes** [comment]
is there any documentation for how to use the font binding ?

**Comment by JakeWharton** [comment]
Once fonts are working normally, it's just "@BindFont(R.font.whatever)
Typeface whatever;"
