### ISSUE TITLE
Compiler error for @BindFont - generated code passes Resources instead of Context to ResourcesCompat.getFont()

### ISSUE THREAD

**Issue by dominikgold** [JakeWharton/butterknife#1041]
Hi,
I updated to 8.7.0 and wanted to use @BindFont for custom font binding.

`@BindFont(R.font.brandon_text_medium)
  Typeface mBoldTypeface;`

Unfortunately, the generated code produces a compiler error at ResourcesCompat.getFont():

`Context context = source.getContext();`
`Resources res = context.getResources();`
`target.mBoldTypeface = ResourcesCompat.getFont(res, 2131296257);`
`target.mItalicTypeface = ResourcesCompat.getFont(res, 2131296256);`

I'm on support library version 26.0.0.

**Comment by JakeWharton** [comment]
Wow, huge fail on my part.
