### ISSUE TITLE
[Question] How to use processor options? (8.8.0)

### ISSUE THREAD

**Issue by Gounlaf** [JakeWharton/butterknife#1046]
Hi,

I wish to use the new `butterknife.debuggable` options, but I don't find how to use it.
Tried to set it directly in `android -> buildTypes -> release` block, but it doesn't work.

I got two `buildTypes`: `debug` and `release`, and I want to turn off debuggable in `release` build.

Thanks for your help,
Regards.

**Comment by gim-** [comment]
See similar question about `butterknife.minSdk`: #855

**Comment by Gounlaf** [comment]
Hi @gim-,

Thanks!

**Comment by Tolriq** [comment]
Since I had some trouble to find how to do that per buildTypes I add here a comment with full solution :)

1) Global configuration
```groovy
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                argument('butterknife.debuggable', 'false')
            }
        }
    }
```

2) Build type configuration

```groovy
    buildTypes {
        ...
        debug {
            ...
            javaCompileOptions.annotationProcessorOptions.argument('butterknife.debuggable', 'true')
        }
    }
```

**Comment by gim-** [comment]
Setting this option to `false` didn't do much in one of my apps where I tried it. The difference in APK size is only 4 KB (ProGuard active), so I don't know if it's worth it.

**Comment by Tolriq** [comment]
It's not only about app size, it's also about code optimization, it avoids no more necessary casts / checks allowing inlining of code by proguard and certainly other goodies at the expense of less verbose stacktraces.

IMO a 1 line optimisation for release builds is always worthy ;)
