### ISSUE TITLE
Missing View bind casts when "butterknife.debuggable" is set to false

### ISSUE THREAD

**Issue by gim-** [JakeWharton/butterknife#1047]
build.gradle:
```
defaultConfig {
    // ...
    javaCompileOptions {
        annotationProcessorOptions {
            argument('butterknife.debuggable', 'false')
        }
    }
}
```
I get bunch of compile time errors similar to this:
```
Error:(25, 40) error: incompatible types: View cannot be converted to TextView
Error:(32, 48) error: incompatible types: View cannot be converted to Spinner
...
```
There seem to be missing casts in the generated sources:
```java
target.mTitle = source.findViewById(R.id.title);
target.mDescription = source.findViewById(R.id.description);
```

**Comment by JakeWharton** [comment]
What does your `@BindView` look like so I can write a test?

**Comment by gim-** [comment]
@JakeWharton Just a regular bindings:
```java
@BindView(R.id.text_view)
TextView mTextView;
```
Here is the simple example application that you can inspect: [MyApplication2.zip](https://github.com/JakeWharton/butterknife/files/1212184/MyApplication2.zip)

> MyApplication2/app/build/generated/source/apt/debug/com/android/myapplication/MainActivity_ViewBinding.java
Error:(23, 43) error: incompatible types: View cannot be converted to TextView
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```java
  @UiThread
  public MainActivity_ViewBinding(MainActivity target, View source) {
    this.target = target;

    target.mTextView = source.findViewById(R.id.text_view);
  }
```
