### ISSUE TITLE
Binding failed in parent class

### ISSUE THREAD

**Issue by stridercheng** [JakeWharton/butterknife#1054]
this is my code:

`
public class BaseActivity extends AppCompatActivity {

    public enum ToolbarMode {
        MODE_BACK,
        MODE_NONE
    }

    @BindView(R.id.toolbar)
    Toolbar mToolbar;

    @BindView(R.id.toolbar_title)
    TextView tvToolbarTitle;
    @Override
    public void setContentView(@LayoutRes int layoutResID) {
        super.setContentView(layoutResID);
        ButterKnife.setDebug(true);
        ButterKnife.bind(this);
    }
    public void setContentView(@LayoutRes int layoutResID, @StringRes int titleID) {
        setContentView(layoutResID, titleID, ToolbarMode.MODE_BACK);
    }
    public void setContentView(@LayoutRes int layoutResID, @StringRes int titleID, ToolbarMode mode) {
        setContentView(layoutResID);
        tvToolbarTitle.setText(titleID);
`
and this is the log:

D/ButterKnife: Looking up binding for cn.com.xx..MainActivity 
D/ButterKnife: Not found. Trying superclass cn.com.xx.base.BaseActivity 
D/ButterKnife: Not found. Trying superclass android.support.v7.app.AppCompatActivity 
D/ButterKnife: MISS: Reached framework class. Abandoning search. 

what should i do

**Comment by JakeWharton** [comment]
Do you see the generated ViewBinder classes in your build/generated/ folder?

**Comment by stridercheng** [comment]
There is no such file. I can only find a R.java in butterKnife package, and it's empty.

**Comment by JakeWharton** [comment]
Have you followed the instructions in the README for setting up the
annotation processor?

**Comment by stridercheng** [comment]
Yes, that's the reason. I'm very sorry to bother you.  I got used to the old version.
