### ISSUE TITLE
Don't work in kotlin

### ISSUE THREAD

**Issue by hippyk** [JakeWharton/butterknife#1058]
I added the @JvmField annotation to the view, but it is still null after ButterKnife.bind(this).

**Comment by piotrek1543** [comment]
@hippyk there's a kotlin implementation of `Butterknife` wirriten by Jake called [kotterknife](https://github.com/JakeWharton/kotterknife). 

Please, check it out.

**Comment by JakeWharton** [comment]
There's not enough information to make this report actionable. If you're having a problem the easiest way to get it resolved is by creating a standalone sample that demonstrates it in isolation. Otherwise it's impossible to know what you're doing.

**Comment by hippyk** [comment]
@piotrek1543 Thank u! But My situation is special. There are too many codes to change if I use kotterknife instead.

**Comment by hippyk** [comment]
@JakeWharton I found the "_ViewBinding" class for the kt class was not generated.

**Comment by JakeWharton** [comment]
Are you using kapt?

**Comment by hippyk** [comment]
@JakeWharton No, but I'm using “kotlin-android-extensions”

**Comment by JakeWharton** [comment]
Without kapt Butter Knife will not work with Kotlin.

**Comment by hippyk** [comment]
@JakeWharton Thank you very much！

**Comment by hippyk** [comment]
I found another solution. Before converting the java file to kt, copy the method “xxxActivity_ViewBinding”  that is generated and then add it to the kt file directly.

**Comment by PaulWoitaschek** [comment]
@hippyk That kind of defeats the purpose of this library as you now have to maintain the stuff yourself. Just use kapt, that's what it's meant for.
