### ISSUE TITLE
@bindString Generate Signed APK 

### ISSUE THREAD

**Issue by zZ-GitHub** [JakeWharton/butterknife#1059]
### I use butterknife-7.0.1

on MainActivity

```
@BindString(R.string.app_name)
String app_name;
```
then 

## I  Generate Signed APK 

then I got a error 

```
Error:Error: Expected resource of type string [ResourceType]
```

# somebady help me

**Comment by zZ-GitHub** [comment]
## Now I want to know that which version kill this Issues

**Comment by JakeWharton** [comment]
This is fixed in the latest versions. Please upgrade to 8.8.1.

**Comment by Sainathhiwale** [comment]
implementation 'com.jakewharton:butterknife:10.2.0'
    annotationProcessor 'com.jakewharton:butterknife:10.2.0'
    when i signed apk click event is not working 
   could you please tell me how to fix this things
