### ISSUE TITLE
java.lang.ClassNotFoundException  Android 7.1.1,level 25 ROM blackberry/bbb100emea CPU arm64-v8a

### ISSUE THREAD

**Issue by masterqyw** [JakeWharton/butterknife#1060]
# main
java.lang.ClassNotFoundException
Didn't find class "butterknife.ButterKnife" on path: DexPathList[[dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "/data/app/com.ifavine.appkettle-1/oat/arm/base.odex", dex file "null", dex file "null", dex [Message over limit siz...too long be cutted!

**Comment by JakeWharton** [comment]
This is not a problem with Butter Knife but something in the packaging of your app. Ensure that if you're using ProGuard it's configured correctly. If you're using legacy multidex ensure that it's configured correctly. Etc.
