### ISSUE TITLE
@onClick 

### ISSUE THREAD

**Issue by kingning1** [JakeWharton/butterknife#1064]
可以在绑定事件时添加多绑定事件吗？
上代码

    @OnClick(R.id.button2,R.id.button3,R.id.button4,R.id.button5)
    public void btnClick(View v) {
        switch (v.getId()){
            R.id.button2:
            break;
            ...
        }
    }

**Comment by JakeWharton** [comment]
Yes. `@OnClick` accepts an array:
```java
@OnClick({R.id.button2, R.id.button3, R.id.button4, R.id.button5})
```

**Comment by kingning1** [comment]
哦，谢谢，看来我写错了。
