### ISSUE TITLE
Could not find method apt()

### ISSUE THREAD

**Issue by tenSunFree** [JakeWharton/butterknife#1067]
![01](https://user-images.githubusercontent.com/23090085/30002869-3ff34dc4-90e6-11e7-9e75-4f37e9bc4473.jpg)
![02](https://user-images.githubusercontent.com/23090085/30002872-4dc26066-90e6-11e7-8911-0ea0bd34e980.jpg)

How should I solve this problem?

**Comment by JakeWharton** [comment]
Use annotationProcessor, per the docs.
