### ISSUE TITLE
 W/System.err( 2038): java.lang.IllegalStateException: View 'bt_bind_gao' with ID 2131493005 for field 'btBindGao' was of the wrong type. See cause for more info.

### ISSUE THREAD

**Issue by MaicooYang** [JakeWharton/butterknife#1068]
**Exception**
08-29 10:48:28.575 W/System.err( 2038): java.lang.IllegalStateException: View 'bt_bind_gao' with ID 2131493005 for field 'btBindGao' was of the wrong type. See cause for more info.
08-29 10:48:28.575 W/System.err( 2038): at butterknife.internal.Utils.castView(Utils.java:113)
08-29 10:48:28.575 W/System.err( 2038): at gaei.trumpchiassistant.ui.fragment.MyProfileFragment_ViewBinding.<init>(MyProfileFragment_ViewBinding.java:52)
08-29 10:48:28.575 W/System.err( 2038): at java.lang.reflect.Constructor.constructNative(Native Method)
08-29 10:48:28.575 W/System.err( 2038): at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08-29 10:48:28.575 W/System.err( 2038): at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
08-29 10:48:28.575 W/System.err( 2038): at butterknife.ButterKnife.bind(ButterKnife.java:172)
08-29 10:48:28.575 W/System.err( 2038): at gaei.trumpchiassistant.base.BaseFragment.onCreateView(BaseFragment.java:48)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
08-29 10:48:28.575 W/System.err( 2038): at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
08-29 10:48:28.575 W/System.err( 2038): at android.view.View.measure(View.java:16518)
08-29 10:48:28.575 W/System.err( 2038): at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
08-29 10:48:28.575 W/System.err( 2038): at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
08-29 10:48:28.585 W/System.err( 2038): at android.view.View.measure(View.java:16518)
08-29 10:48:28.585 W/System.err( 2038): at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
08-29 10:48:28.585 W/System.err( 2038): at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
08-29 10:48:28.585 W/System.err( 2038): at android.view.View.measure(View.java:16518)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
08-29 10:48:28.585 W/System.err( 2038): at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
08-29 10:48:28.585 W/System.err( 2038): at android.view.View.measure(View.java:16518)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
08-29 10:48:28.585 W/System.err( 2038): at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
08-29 10:48:28.585 W/System.err( 2038): at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
08-29 10:48:28.585 W/System.err( 2038): at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
08-29 10:48:28.585 W/System.err( 2038): at android.view.View.measure(View.java:16518)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
08-29 10:48:28.585 W/System.err( 2038): at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
08-29 10:48:28.585 W/System.err( 2038): at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
08-29 10:48:28.585 W/System.err( 2038): at android.view.View.measure(View.java:16518)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1923)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1120)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1302)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1007)
08-29 10:48:28.585 W/System.err( 2038): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5698)
08-29 10:48:28.585 W/System.err( 2038): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
08-29 10:48:28.585 W/System.err( 2038): at android.view.Choreographer.doCallbacks(Choreographer.java:574)
08-29 10:48:28.585 W/System.err( 2038): at android.view.Choreographer.doFrame(Choreographer.java:544)
08-29 10:48:28.595 W/System.err( 2038): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
08-29 10:48:28.595 W/System.err( 2038): at android.os.Handler.handleCallback(Handler.java:733)
08-29 10:48:28.595 W/System.err( 2038): at android.os.Handler.dispatchMessage(Handler.java:95)
08-29 10:48:28.595 W/System.err( 2038): at android.os.Looper.loop(Looper.java:136)
08-29 10:48:28.595 W/System.err( 2038): at android.app.ActivityThread.main(ActivityThread.java:5031)
08-29 10:48:28.595 W/System.err( 2038): at java.lang.reflect.Method.invokeNative(Native Method)
08-29 10:48:28.595 W/System.err( 2038): at java.lang.reflect.Method.invoke(Method.java:515)
08-29 10:48:28.595 W/System.err( 2038): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:843)
08-29 10:48:28.595 W/System.err( 2038): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:658)
08-29 10:48:28.595 W/System.err( 2038): at dalvik.system.NativeStart.main(Native Method)
08-29 10:48:28.595 W/System.err( 2038): Caused by: java.lang.ClassCastException: maicoo.com.mylibrary.component.MRoundRectButton cannot be cast to maicoo.com.mylibrary.component.MRoundRectButton
08-29 10:48:28.595 W/System.err( 2038): at java.lang.Class.cast(Class.java:1278)
08-29 10:48:28.595 W/System.err( 2038): at butterknife.internal.Utils.castView(Utils.java:110)
08-29 10:48:28.595 W/System.err( 2038): ... 57 more

**JavaCode：**
public class MRoundRectButton extends Button {

	private MaterialDetector mDetector;

	public MRoundRectButton(Context context) {
		this(context, null);
	}

	public MRoundRectButton(Context context, AttributeSet attrs) {
		super(context, attrs);
		init();
	}

	public MRoundRectButton(Context context, AttributeSet attrs, int defStyle) {
		super(context, attrs, defStyle);
		init();
	}

	protected void init() {
		mDetector = new MaterialDetector(getContext(), this, null,
				MaterialDetector.DEFAULT_COLOR, MaterialDetector.ShapeType.ROUNDRECT, 30f);
	}
}

**XML:**
        <maicoo.com.mylibrary.component.MRoundRectButton
                    android:id="@+id/bt_bind_gao"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@+id/tv_plate_num"
                    android:layout_marginStart="@dimen/account_bind_gao_btn_marginLeft"
                    android:layout_marginTop="@dimen/account_bind_gao_btn_marginTop"
                    android:layout_toEndOf="@+id/tv_gao_account"
                    android:background="@drawable/radius_btn_normal"
                    android:text="@string/bind_gao"
                    android:textColor="@color/white_color"
                    android:textSize="@dimen/account_bind_gao_btn_textSize"
                    android:visibility="visible"/>

**Comment by JakeWharton** [comment]
Looks like you have two classloaders with the same class. Are you able to reproduce in a sample app? Otherwise there's no way to diagnose what's going on.
