### ISSUE TITLE
Could not find butterknife-annotations.jar 

### ISSUE THREAD

**Issue by HarrisonLin** [JakeWharton/butterknife#1069]
![image](https://user-images.githubusercontent.com/10679283/30043621-0206c82e-922b-11e7-8728-595437547b49.png)

**Comment by JakeWharton** [comment]
It's in Maven central. Add `mavenCentral()` to your `repositories` block.

**Comment by HarrisonLin** [comment]
I had add `mavenCentral().`， it not ok

![image](https://user-images.githubusercontent.com/10679283/30043775-133546d8-922c-11e7-84ac-4ceefaca688b.png)

**Comment by HarrisonLin** [comment]
Whether it depends on the SDK  Build Tools version？

**Comment by JakeWharton** [comment]
Did you add it to the non-buildscript repositories block?

**Comment by JeckChou** [comment]
`apt 'com.jakewharton:butterknife-compiler:8.8.1'
 ’compile 'jp.wasabeef:recyclerview-animators:2.2.5'`

**Comment by HarrisonLin** [comment]
the project `build.gradle`  fragment. 

![image](https://user-images.githubusercontent.com/10679283/30044080-eda0136a-922d-11e7-9002-72063bb4241d.png)

**Comment by JakeWharton** [comment]
The IDE message indicates that it is not searching in more than one
repository. Does it work from the command line?

**Comment by HarrisonLin** [comment]
command line report: `The SDK Build Tools revision (23.0.2) is too low for project ':app'. Minimum required is 25.0.0`。

If del `butterknife` component ,  command `gradle build` is OK.

so butterknife  need vervision 25+?

**Comment by JakeWharton** [comment]
That error is from the Gradle plugin, not butter knife.

**Comment by HarrisonLin** [comment]
the project sync faild cause that error。 

the problem has been fixed.  Thx
