### ISSUE TITLE
lib project can`t use to butterknife component.

### ISSUE THREAD

**Issue by HarrisonLin** [JakeWharton/butterknife#1071]
My Lib Project use butterknife component。  

That error  when main project   include  lib project . 

![image](https://user-images.githubusercontent.com/10679283/30094008-b535159c-92fb-11e7-80ef-c8c4219eadcd.png)

that error `The element value must be a constant expression`。

butterknife create R file:

![image](https://user-images.githubusercontent.com/10679283/30094128-a0036650-92fc-11e7-9030-62a6d2ce7d86.png)

Android create R file:

![image](https://user-images.githubusercontent.com/10679283/30094132-a79edfd4-92fc-11e7-878d-61c588aa53da.png)

Is there a way to solve this problem?

**Comment by JakeWharton** [comment]
Details are in the README for library use.
