### ISSUE TITLE
Conflict with dependency :: (com.android.support:support-v4:21.0.3)

### ISSUE THREAD

**Issue by 5-digits** [JakeWharton/butterknife#1073]
when add the butterKnife dependency with (com.android.support:support-v4:21.0.3) it generate a conflict 

`All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes).`
when ignore this issue to generate an apk i get this error Message 

```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
```

**Comment by JakeWharton** [comment]
The correct way to avoid dependency conflicts between the main source set and the android test source set is by forcing the versions of all support libraries to be the same.

See https://github.com/JakeWharton/u2020/blob/9870fa4291f5c813ed929aec26c94bee2b92d2b7/build.gradle#L105-L113 for an example
