### ISSUE TITLE
Obsolete custom lint check w/ gradle:3.0.0-beta5

### ISSUE THREAD

**Issue by laminr** [JakeWharton/butterknife#1077]
Goodday

After having updated our project with the **gradle:3.0.0-beta5** (and Android Studio 3.0 Beta 5),
 we have a new _"Obsolete custom lint"_ error.

_Lint found one or more custom checks using its older Java API; these checks are still run in compatibility mode, but this causes duplicated parsing, and in the next version lint will no longer include this legacy mode. Make sure the following lint detectors are upgraded to the new API: butterknife.lint.**InvalidR2UsageDetector**_

What can we do to avoid  to use a SuppressLint ;-)

**Comment by gabrielittner** [comment]
duplicate of #1074

**Comment by laminr** [comment]
sorry have seen it :(
