### ISSUE TITLE
自定义的RadioGroup的@onCheckedChanged下用Inject有问题

### ISSUE THREAD

**Issue by billllll1llllll** [JakeWharton/butterknife#1080]
版本：7.0.1
问题：自定义了一个内部RadioButton可以换行的RadioGroup，但想要用@onCheckedChanged获取到RadioButton的id，此时会出现，第二行RadioButton有选中的时候没有回调，如果需要我可以写一个demo放到github上。

**Comment by JakeWharton** [comment]
Dupe of #148
