### ISSUE TITLE
Butterknife not work if mission annotationProcessor in main project

### ISSUE THREAD

**Issue by ledangtuanbk** [JakeWharton/butterknife#1084]
Hi Team. 
I got an issue related to ButterKnife. I have a library. I add dependencies for It like that

`api 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'`

I am import to my project, Binding function not working if I do not add annotation to "app" project.

Please contact me if you need more infomation.

**Comment by JakeWharton** [comment]
Every module using the annotations needs the processor declared, yes.

**Comment by ledangtuanbk** [comment]
Ok I got it. thanks
