### ISSUE TITLE
butterknife-gradle-plugin:8.8.1 build failed

### ISSUE THREAD

**Issue by shingohu** [JakeWharton/butterknife#1086]
The root build.gradle
 dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        //lambda
        classpath 'me.tatarka:gradle-retrolambda:3.7.0'

        classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'

        classpath 'com.antfortune.freeline:gradle:0.8.7'
        classpath 'io.objectbox:objectbox-gradle-plugin:1.0.1'
        //classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' // add plugin
        // NOTE: Do not place your application base here; they belong
        // in the individual module build.gradle files
        classpath 'com.bugtags.library:bugtags-gradle:latest.integration'
    }

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':man:processAllDebugResources'.
> com.github.javaparser.ast.CompilationUnit.getTypes()Lcom/github/javaparser/ast/NodeList;

but The com.jakewharton:butterknife-gradle-plugin:8.5.1 is ok

**Comment by JakeWharton** [comment]
Paste the entire stack trace

**Comment by shingohu** [comment]
Executing tasks: [:app:generateTtDebugSources, :app:mockableAndroidJar, :app:prepareTtDebugUnitTestDependencies, :app:generateTtDebugAndroidTestSources, :jsbridge:generateAllDebugSources, :jsbridge:generateAllDebugAndroidTestSources, :jsbridge:prepareAllDebugUnitTestDependencies, :jsbridge:mockableAndroidJar, :man:generateAllDebugSources, :man:prepareAllDebugUnitTestDependencies, :man:mockableAndroidJar, :man:generateAllDebugAndroidTestSources]

Parallel execution with configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
:app:objectboxPrepareBuild
:jsbridge:preBuild UP-TO-DATE
:man:preBuild UP-TO-DATE
:man:preAllDebugBuild UP-TO-DATE
:jsbridge:preAllDebugBuild UP-TO-DATE
:man:checkAllDebugManifest
:jsbridge:checkAllDebugManifest
:jsbridge:prepareAllDebugDependencies
:man:preAllDebugAndroidTestBuild UP-TO-DATE
:man:preAllDebugUnitTestBuild UP-TO-DATE
:jsbridge:compileAllDebugAidl
:man:extractProguardFiles
:man:preAllReleaseBuild
:man:preAllReleaseUnitTestBuild UP-TO-DATE
:man:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:jsbridge:compileLint
:jsbridge:copyAllDebugLint UP-TO-DATE
:jsbridge:mergeAllDebugShaders
:man:prepareComAndroidSupportAppcompatV72531Library
:man:prepareComAndroidSupportDesign2531Library
:jsbridge:compileAllDebugShaders
:man:prepareComAndroidSupportRecyclerviewV72531Library
:man:prepareComAndroidSupportSupportCompat2531Library
:jsbridge:generateAllDebugAssets
:jsbridge:mergeAllDebugAssets
:man:prepareComAndroidSupportSupportCoreUi2531Library
:app:preBuild
:man:prepareComAndroidSupportSupportCoreUtils2531Library
:app:preTtDebugBuild
:app:checkTtDebugManifest
:app:preProductDebugBuild
:man:prepareComAndroidSupportSupportFragment2531Library
:app:extractProguardFiles
:app:preProductReleaseBuild
:app:preTtReleaseBuild
:app:prepareComAliyunAmsAlicloudAndroidPush3011Library
:man:prepareComAndroidSupportSupportMediaCompat2531Library
:man:prepareComAndroidSupportSupportV42531Library
:man:prepareComAndroidSupportSupportVectorDrawable2531Library
:app:prepareComAliyunAmsAlicloudAndroidThirdPush304Library
:jsbridge:mergeAllDebugProguardFiles
:app:prepareComAliyunDpaOssAndroidSdk242Library
:jsbridge:packageAllDebugRenderscript UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:jsbridge:compileAllDebugRenderscript
:app:prepareComAndroidSupportAppcompatV72531Library
:app:prepareComAndroidSupportDesign2531Library
:app:prepareComAndroidSupportExifinterface2531Library
:app:preProductDebugAndroidTestBuild
:app:preTtDebugAndroidTestBuild
:app:prepareComAndroidSupportMultidex101Library
:jsbridge:generateAllDebugResValues
:app:prepareComAndroidSupportPercent2531Library
:jsbridge:generateAllDebugResources
:jsbridge:packageAllDebugResources
:app:prepareComAndroidSupportRecyclerviewV72531Library
:app:prepareComAndroidSupportSupportCompat2531Library
:man:prepareComAndroidSupportTransition2531Library
:app:prepareComAndroidSupportSupportCoreUi2531Library
:man:prepareComApkfunsLogutilsLibrary151Library
:app:prepareComAndroidSupportSupportCoreUtils2531Library
:app:prepareComAndroidSupportSupportFragment2531Library
:app:prepareComAndroidSupportSupportMediaCompat2531Library
:app:prepareComAndroidSupportSupportV42531Library
:app:prepareComAndroidSupportSupportVectorDrawable2531Library
:app:prepareComAndroidSupportTransition2531Library
:app:prepareComApkfunsLogutilsLibrary151Library
:app:prepareComBinaryforkSpanny104Library
:app:prepareComBirbitAndroidPriorityJobqueue201Library
:man:prepareComBlankjUtilcode190Library
:app:prepareComBlankjUtilcode190Library
:man:prepareComBugtagsLibraryBugtagsLib231Library
:app:prepareComBugtagsLibraryBugtagsLib231Library
:man:prepareComGithubYatatsuAutobundle410Library
:app:prepareComGithubChrisbanesPhotoviewLibrary124Library
:man:prepareComGithubYatatsuAutobundleCommon410Library
:app:prepareComGithubCymChadBaseRecyclerViewAdapterHelper2928Library
:app:prepareComGithubDouglasjuniorAndroidSimpleTooltip020Library
:app:prepareComGithubLuckSiegePictureSelectorLightV207Library
:app:prepareComGithubYatatsuAutobundle410Library
:app:prepareComGithubYatatsuAutobundleCommon410Library
:man:prepareComJakewhartonButterknife881Library
:app:prepareComGoogleAndroidFlexbox030Library
:app:prepareComJakewhartonButterknife881Library
:app:prepareComJakewhartonRxbinding2Rxbinding200Library
:app:prepareComJakewhartonTimberTimber451Library
:app:prepareComMakeramenRoundedimageview230Library
:app:prepareComSquareupLeakcanaryLeakcanaryAndroid151Library
:app:prepareComTbruyelleRxpermissions2Rxpermissions094Library
:app:prepareComTheartofdevEdmodoAndroidImageCropper246Library
:app:prepareComTrelloRxlifecycle2RxlifecycleAndroid210Library
:man:prepareComJakewhartonTimberTimber451Library
:app:prepareComTrelloRxlifecycle2RxlifecycleComponents210Library
:man:prepareComSquareupLeakcanaryLeakcanaryAndroid151Library
:app:prepareComTubbSmrvSwipemenuRecyclerview540Library
:man:prepareComTbruyelleRxpermissions2Rxpermissions094Library
:man:prepareComTrelloRxlifecycle2RxlifecycleAndroid210Library
:man:prepareComTrelloRxlifecycle2RxlifecycleComponents210Library
:app:prepareIoObjectboxObjectboxAndroid101Library
:man:prepareIoReactivexRxjava2Rxandroid201Library
:app:prepareIoReactivexRxjava2Rxandroid201Library
:man:prepareMeYokeywordFragmentationCore116Library
:man:prepareMeYokeywordFragmentationSwipeback116Library
:app:prepareMeGrantlandAutofittextview021Library
:app:prepareMeYokeywordFragmentationCore116Library
:man:prepareAllDebugDependencies
:man:compileAllDebugAidl
:app:prepareMeYokeywordFragmentationSwipeback116Library
:app:prepareTechMichaelxAuthcodeAuthcode101Library
:app:generateTtDebugBuildConfig
:man:compileLint
:man:copyAllDebugLint UP-TO-DATE
:man:mergeAllDebugShaders
:man:compileAllDebugShaders
:man:generateAllDebugAssets
:man:mergeAllDebugAssets
:man:mergeAllDebugProguardFiles
:man:packageAllDebugRenderscript UP-TO-DATE
:man:compileAllDebugRenderscript
:app:generateTtDebugResValues
:man:generateAllDebugResValues
:man:generateAllDebugResources
:man:packageAllDebugResources
:jsbridge:processAllDebugManifest
:app:mockableAndroidJar
:app:preTtDebugUnitTestBuild
:app:prepareTtDebugUnitTestDependencies
:app:prepareComAndroidSupportMultidexInstrumentation101Library
:app:prepareComAndroidSupportTestEspressoEspressoCore222Library
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:app:prepareComAndroidSupportTestRules05Library
:app:prepareComAndroidSupportTestRunner05Library
:app:prepareTtDebugAndroidTestDependencies
:app:compileTtDebugAndroidTestAidl
:app:processTtDebugAndroidTestManifest
:man:processAllDebugManifest
:man:bundleAllDebug
:jsbridge:bundleAllDebug UP-TO-DATE
:man:bundleAllDebug UP-TO-DATE
:jsbridge:generateAllDebugBuildConfig
:man:generateAllDebugBuildConfig
:jsbridge:processAllDebugResources
:man:mergeAllDebugResources
:app:prepareTtDebugDependencies
:app:compileTtDebugAidl
:app:compileTtDebugRenderscript
:app:generateTtDebugResources
:app:mergeTtDebugResources
:jsbridge:generateAllDebugSources
:jsbridge:preAllDebugAndroidTestBuild UP-TO-DATE
:jsbridge:prepareAllDebugAndroidTestDependencies
:jsbridge:compileAllDebugAndroidTestAidl
:jsbridge:processAllDebugAndroidTestManifest
:jsbridge:compileAllDebugAndroidTestRenderscript
:jsbridge:generateAllDebugAndroidTestBuildConfig
:jsbridge:generateAllDebugAndroidTestResValues
:jsbridge:generateAllDebugAndroidTestResources
:jsbridge:mergeAllDebugAndroidTestResources
:jsbridge:processAllDebugAndroidTestResources
:jsbridge:generateAllDebugAndroidTestSources
:jsbridge:preAllDebugUnitTestBuild UP-TO-DATE
:jsbridge:prepareAllDebugUnitTestDependencies
:jsbridge:mockableAndroidJar
:man:processAllDebugResources
:app:processTtDebugManifest
[com.aliyun.ams:alicloud-android-push:3.0.11] /Users/hujie/.android/build-cache/aae2b3830b075d2fc3b91e6fa96e2738977b22c1/output/AndroidManifest.xml:26:5-81 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at [com.aliyun.ams:alicloud-android-push:3.0.11] AndroidManifest.xml:26:5-81 duplicated with element declared at [com.aliyun.ams:alicloud-android-push:3.0.11] AndroidManifest.xml:16:5-81
:app:processTtDebugResources
:man:processAllDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':man:processAllDebugResources'.
> com.github.javaparser.ast.CompilationUnit.getTypes()Lcom/github/javaparser/ast/NodeList;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.086 secs

**Comment by shingohu** [comment]
Executing tasks: [:app:generateTtDebugSources, :app:mockableAndroidJar, :app:prepareTtDebugUnitTestDependencies, :app:generateTtDebugAndroidTestSources, :jsbridge:generateAllDebugSources, :jsbridge:generateAllDebugAndroidTestSources, :jsbridge:prepareAllDebugUnitTestDependencies, :jsbridge:mockableAndroidJar, :man:generateAllDebugSources, :man:prepareAllDebugUnitTestDependencies, :man:mockableAndroidJar, :man:generateAllDebugAndroidTestSources]

Parallel execution with configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
:app:objectboxPrepareBuild
:jsbridge:preBuild UP-TO-DATE
:jsbridge:preAllDebugBuild UP-TO-DATE
:app:preBuild
:app:preTtDebugBuild
:app:checkTtDebugManifest
:app:preProductDebugBuild
:app:extractProguardFiles
:app:preProductReleaseBuild
:app:preTtReleaseBuild
:app:prepareComAliyunAmsAlicloudAndroidPush3011Library
:jsbridge:checkAllDebugManifest
:jsbridge:prepareAllDebugDependencies
:jsbridge:compileAllDebugAidl
:app:prepareComAliyunAmsAlicloudAndroidThirdPush304Library
:app:prepareComAliyunDpaOssAndroidSdk242Library
:jsbridge:compileAllDebugAidl UP-TO-DATE
:jsbridge:compileAllDebugNdk UP-TO-DATE
:jsbridge:compileLint
:app:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:man:preBuild UP-TO-DATE
:jsbridge:compileLint UP-TO-DATE
:jsbridge:copyAllDebugLint
:man:preAllDebugBuild
:app:prepareComAndroidSupportAppcompatV72531Library
:man:preAllDebugBuild UP-TO-DATE
:jsbridge:copyAllDebugLint UP-TO-DATE
:jsbridge:mergeAllDebugShaders
:man:checkAllDebugManifest
:app:prepareComAndroidSupportDesign2531Library
:jsbridge:mergeAllDebugShaders UP-TO-DATE
:app:prepareComAndroidSupportExifinterface2531Library
:jsbridge:compileAllDebugShaders
:man:preAllDebugAndroidTestBuild UP-TO-DATE
:man:preAllDebugUnitTestBuild
:jsbridge:compileAllDebugShaders UP-TO-DATE
:man:preAllDebugUnitTestBuild UP-TO-DATE
:app:preProductDebugAndroidTestBuild
:jsbridge:generateAllDebugAssets UP-TO-DATE
:man:extractProguardFiles
:app:preTtDebugAndroidTestBuild
:jsbridge:mergeAllDebugAssets
:app:prepareComAndroidSupportMultidex101Library
:jsbridge:mergeAllDebugAssets UP-TO-DATE
:app:prepareComAndroidSupportPercent2531Library
:jsbridge:mergeAllDebugProguardFiles UP-TO-DATE
:jsbridge:packageAllDebugRenderscript UP-TO-DATE
:jsbridge:compileAllDebugRenderscript UP-TO-DATE
:jsbridge:generateAllDebugResValues UP-TO-DATE
:jsbridge:generateAllDebugResources UP-TO-DATE
:jsbridge:packageAllDebugResources UP-TO-DATE
:jsbridge:processAllDebugManifest UP-TO-DATE
:jsbridge:generateAllDebugBuildConfig UP-TO-DATE
:jsbridge:processAllDebugResources UP-TO-DATE
:jsbridge:generateAllDebugSources UP-TO-DATE
:jsbridge:incrementalAllDebugJavaCompilationSafeguard
:app:prepareComAndroidSupportRecyclerviewV72531Library
:app:prepareComAndroidSupportSupportCompat2531Library
:app:prepareComAndroidSupportSupportCoreUi2531Library
:app:prepareComAndroidSupportSupportCoreUtils2531Library
:man:preAllReleaseBuild
:man:preAllReleaseUnitTestBuild
:app:prepareComAndroidSupportSupportFragment2531Library
:man:preAllReleaseUnitTestBuild UP-TO-DATE
:man:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:app:prepareComAndroidSupportSupportMediaCompat2531Library
:app:prepareComAndroidSupportSupportV42531Library
:man:prepareComAndroidSupportAppcompatV72531Library
:man:prepareComAndroidSupportDesign2531Library
:app:prepareComAndroidSupportSupportVectorDrawable2531Library
:man:prepareComAndroidSupportRecyclerviewV72531Library
:app:prepareComAndroidSupportTransition2531Library
:man:prepareComAndroidSupportSupportCompat2531Library
:app:prepareComApkfunsLogutilsLibrary151Library
:man:prepareComAndroidSupportSupportCoreUi2531Library
:jsbridge:javaPreCompileAllDebug
:jsbridge:compileAllDebugJavaWithJavac
:man:prepareComAndroidSupportSupportCoreUtils2531Library
:app:prepareComBinaryforkSpanny104Library
:app:prepareComBirbitAndroidPriorityJobqueue201Library
:man:prepareComAndroidSupportSupportFragment2531Library
:app:prepareComBlankjUtilcode190Library
:app:prepareComBugtagsLibraryBugtagsLib231Library
:jsbridge:compileAllDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:prepareComGithubChrisbanesPhotoviewLibrary124Library
:man:prepareComAndroidSupportSupportMediaCompat2531Library
:app:prepareComGithubCymChadBaseRecyclerViewAdapterHelper2928Library
:man:prepareComAndroidSupportSupportV42531Library
:app:prepareComGithubDouglasjuniorAndroidSimpleTooltip020Library
:man:prepareComAndroidSupportSupportVectorDrawable2531Library
:app:prepareComGithubLuckSiegePictureSelectorLightV207Library
:man:prepareComAndroidSupportTransition2531Library
:app:prepareComGithubYatatsuAutobundle410Library
:man:prepareComApkfunsLogutilsLibrary151Library
:app:prepareComGithubYatatsuAutobundleCommon410Library
:app:prepareComGoogleAndroidFlexbox030Library
:man:prepareComBlankjUtilcode190Library
:man:prepareComBugtagsLibraryBugtagsLib231Library
:app:prepareComJakewhartonButterknife881Library
:man:prepareComGithubYatatsuAutobundle410Library
:app:prepareComJakewhartonRxbinding2Rxbinding200Library
:man:prepareComGithubYatatsuAutobundleCommon410Library
:app:prepareComJakewhartonTimberTimber451Library
:man:prepareComJakewhartonButterknife881Library
:app:prepareComMakeramenRoundedimageview230Library
:man:prepareComJakewhartonTimberTimber451Library
:app:prepareComSquareupLeakcanaryLeakcanaryAndroid151Library
:man:prepareComSquareupLeakcanaryLeakcanaryAndroid151Library
:app:prepareComTbruyelleRxpermissions2Rxpermissions094Library
:app:prepareComTheartofdevEdmodoAndroidImageCropper246Library
:man:prepareComTbruyelleRxpermissions2Rxpermissions094Library
:man:prepareComTrelloRxlifecycle2RxlifecycleAndroid210Library
:app:prepareComTrelloRxlifecycle2RxlifecycleAndroid210Library
:man:prepareComTrelloRxlifecycle2RxlifecycleComponents210Library
:man:prepareIoReactivexRxjava2Rxandroid201Library
:app:prepareComTrelloRxlifecycle2RxlifecycleComponents210Library
:app:prepareComTubbSmrvSwipemenuRecyclerview540Library
:man:prepareMeYokeywordFragmentationCore116Library
:man:prepareMeYokeywordFragmentationSwipeback116Library
:app:prepareIoObjectboxObjectboxAndroid101Library
:man:prepareAllDebugDependencies
:app:prepareIoReactivexRxjava2Rxandroid201Library
:man:compileAllDebugAidl
:app:prepareMeGrantlandAutofittextview021Library
:app:prepareMeYokeywordFragmentationCore116Library
:app:prepareMeYokeywordFragmentationSwipeback116Library
:man:compileAllDebugAidl UP-TO-DATE
:app:prepareTechMichaelxAuthcodeAuthcode101Library
:man:compileAllDebugNdk
:app:generateTtDebugBuildConfig
:man:compileAllDebugNdk UP-TO-DATE
:man:compileLint UP-TO-DATE
:man:copyAllDebugLint UP-TO-DATE
:man:compileAllDebugRenderscript
:app:generateTtDebugBuildConfig UP-TO-DATE
:man:compileAllDebugRenderscript UP-TO-DATE
:app:generateTtDebugResValues
:man:generateAllDebugBuildConfig
:app:generateTtDebugResValues UP-TO-DATE
:app:mockableAndroidJar
:man:generateAllDebugBuildConfig UP-TO-DATE
:app:mockableAndroidJar UP-TO-DATE
:man:generateAllDebugResValues
:app:preTtDebugUnitTestBuild
:man:generateAllDebugResValues UP-TO-DATE
:app:prepareTtDebugUnitTestDependencies
:man:generateAllDebugResources UP-TO-DATE
:man:mergeAllDebugResources
:app:prepareComAndroidSupportMultidexInstrumentation101Library
:app:prepareComAndroidSupportTestEspressoEspressoCore222Library
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:app:prepareComAndroidSupportTestRules05Library
:app:prepareComAndroidSupportTestRunner05Library
:app:prepareTtDebugAndroidTestDependencies
:app:compileTtDebugAndroidTestAidl UP-TO-DATE
:app:processTtDebugAndroidTestManifest UP-TO-DATE
:app:compileTtDebugAndroidTestRenderscript
:app:generateTtDebugAndroidTestBuildConfig
:app:generateTtDebugAndroidTestResValues
:app:generateTtDebugAndroidTestResources
:app:mergeTtDebugAndroidTestResources
:app:processTtDebugAndroidTestResources
:man:mergeAllDebugResources UP-TO-DATE
:man:processAllDebugManifest UP-TO-DATE
:man:processAllDebugResources
:app:generateTtDebugAndroidTestSources

注: /Users/hujie/MEGA/SVN/xgs/android/shenluntiku/shenluntiku/jsbridge/src/main/java/com/github/lzyzsd/jsbridge/BridgeWebViewClient.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

:jsbridge:processAllDebugJavaRes UP-TO-DATE
:jsbridge:transformResourcesWithMergeJavaResForAllDebug
:jsbridge:transformClassesAndResourcesWithSyncLibJarsForAllDebug
:jsbridge:mergeAllDebugJniLibFolders
:jsbridge:transformNativeLibsWithMergeJniLibsForAllDebug
:jsbridge:transformNativeLibsWithStripDebugSymbolForAllDebug
:jsbridge:transformNativeLibsWithSyncJniLibsForAllDebug
:jsbridge:bundleAllDebug UP-TO-DATE
:jsbridge:preAllDebugAndroidTestBuild UP-TO-DATE
:jsbridge:prepareAllDebugAndroidTestDependencies
:jsbridge:compileAllDebugAndroidTestAidl UP-TO-DATE
:jsbridge:processAllDebugAndroidTestManifest UP-TO-DATE
:jsbridge:compileAllDebugAndroidTestRenderscript UP-TO-DATE
:jsbridge:generateAllDebugAndroidTestBuildConfig UP-TO-DATE
:jsbridge:generateAllDebugAndroidTestResValues UP-TO-DATE
:jsbridge:generateAllDebugAndroidTestResources UP-TO-DATE
:jsbridge:mergeAllDebugAndroidTestResources UP-TO-DATE
:jsbridge:processAllDebugAndroidTestResources UP-TO-DATE
:jsbridge:generateAllDebugAndroidTestSources UP-TO-DATE
:jsbridge:preAllDebugUnitTestBuild UP-TO-DATE
:jsbridge:prepareAllDebugUnitTestDependencies
:jsbridge:mockableAndroidJar UP-TO-DATE
:man:processAllDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':man:processAllDebugResources'.
> com.github.javaparser.ast.CompilationUnit.getTypes()Lcom/github/javaparser/ast/NodeList;

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':man:processAllDebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoSuchMethodError: com.github.javaparser.ast.CompilationUnit.getTypes()Lcom/github/javaparser/ast/NodeList;
	at butterknife.plugin.FinalRClassBuilder.brewJava(FinalRClassBuilder.java:41)
	at butterknife.plugin.ButterKnifePlugin$applyPlugin$1$1$1.execute(ButterKnifePlugin.kt:34)
	at butterknife.plugin.ButterKnifePlugin$applyPlugin$1$1$1.execute(ButterKnifePlugin.kt:15)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more


BUILD FAILED

Total time: 2.882 secs

**Comment by JakeWharton** [comment]
Can you paste the output of `./gradlew :app:dependencies`? (or at least the annotation processor configuration of it?)

**Comment by JakeWharton** [comment]
From that message it looks like you have a too-old or too-new version of JavaParser on the classpath. Or maybe none at all.
