### ISSUE TITLE
Can't find view when super class overrides setContentView(int) and injects some views?

### ISSUE THREAD

**Issue by halcightx** [JakeWharton/butterknife#109]
I have a super class S which overrides "setContentView(int)". Inside it, S calls "super.setContentView(int)" with its own layoutResId, followed by "ButterKnife.inject(this)". And it will inflate the layoutResId from subclasses and add the inflated view to an injected viewgroup.

The problem is when a class C extends S and use "ButterKnife.inject(this)" after calls "setContentView(int)", there will be a java.lang.IllegalStateException - can't find the inject view in class C. 

It seems the subclass can't find the view in a layout which will be inflated and added to the layout by super class' "setContentView(int)". 

When I remove the "ButterKnife.inject(this)" in the super class and use "findViewById(int)" to find the viewgroup and do the rest (inflate the layoutResId from subclasses and add it to the viewgroup), the subclasses can inject its views. 

Not sure whether I made this clear. And wonder why is that.

Thank you.

**Comment by HackerMaple** [comment]
Did you resolve this Problem？
