### ISSUE TITLE
Can't use ConstraintLayout.

### ISSUE THREAD

**Issue by danilobertelli** [JakeWharton/butterknife#1091]
Hello guys,

I'm having issue when trying to use both contraint library and butterknife:

compile 'com.android.support.constraint:constraint-layout:1.0.2'
compile 'com.jakewharton:butterknife:8.8.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'

It gives me an error saying that all android.support libraries must use the same version.

For while I just suppressed the issue, but it seems that need some upgrade on Gradle.

**Comment by JakeWharton** [comment]
You can fix this by forcing them all to the latest version: https://github.com/JakeWharton/u2020/blob/68a5f3109ee585df276b3f541fdef31360331433/build.gradle#L105-L113
