### ISSUE TITLE
API changes review for Butterknife

### ISSUE THREAD

**Issue by lvc** [JakeWharton/butterknife#1092]
The review of API changes for the Butterknife library since 1.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/butterknife/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-compliance-checker and https://github.com/lvc/japi-tracker tools.

Thank you.

![butterknife-2](https://user-images.githubusercontent.com/1517837/31002555-75b268da-a4fc-11e7-995e-f1df5e1160f3.png)
![butterknife-1](https://user-images.githubusercontent.com/1517837/31002556-75b4edee-a4fc-11e7-9205-f01e94ed5a96.png)

**Comment by JakeWharton** [comment]
Lint changes.
