### ISSUE TITLE
Split reflection and direct-reference frontends.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/butterknife#1094]
This will create a butterknife-reflect artifact with `bind` and friends. It'll probably also necessitate a static `bind` method on the view binding since a side-effecting constructor is weird...

**Comment by WellingtonCosta** [comment]
Someone working on this? I had a similar idea to my library for field validation, which also generate code, were the classes was generated at compile time and the classes was instantiated by the reflective method ```Convalida.init(this);``` (similar to ```ButterKnife.bind(this);```). I improved the generated code and, currently, the generated classes are instantiated from a static method of the class itself.

Maybe I could help with this.

**Comment by JakeWharton** [comment]
This happened. `butterknife` is `Class.forName`-based. `butterknife-runtime` is an upstream dependency that the generated code needs. Depend only on the latter if you want to avoid reflection altogether and reference the generated types directly.
