### ISSUE TITLE
butterknife not working for gradle:3.0.0-beta7

### ISSUE THREAD

**Issue by S2606** [JakeWharton/butterknife#1098]
`@BindView` and `@onclick` not working in butterknife version 8.8.1

```
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 26
    }
}
```

**Comment by JakeWharton** [comment]
This is not enough information to be actionable. What is "not working"? Are the sources being generated? What version of Gradle are you using?

Please provide a small sample project that reproduces the issue.

**Comment by S2606** [comment]
``What is "not working"? ``
After building the app if we take button for eg:-
```
@BindView(..)
Button b;
```

Its throwing NullPointerExcepton.

What version of Gradle are you using?
3.0.0-beta7

**Comment by S2606** [comment]
And i didnt get ``Are the sources being generated? ``

**Comment by S2606** [comment]
Nevermind,it seems to be working well.Thank you @JakeWharton sir for your quick response and Sorry for wasting your time.
