### ISSUE TITLE
Theme.AppCompat theme to be lost

### ISSUE THREAD

**Issue by litianjiaodongjie** [JakeWharton/butterknife#1103]
I use the latest version of butterknife, which causes the Theme.AppCompat theme to be lost and how to solve it

**Comment by JakeWharton** [comment]
Butter Knife cannot affect the theme that is being used. If you believe you have found a bug, please provide a failing test case or standalone executable sample that demonstrates the problem.

**Comment by JemyZou** [comment]
![tim 20171102170949](https://user-images.githubusercontent.com/13834392/32318987-f25733f4-bff3-11e7-9221-55abcd7c47b7.png)
Hi，I meat the same problem.When I use it in a library module,it happened.remove it,work fine.attach is my sample project,please check it.Thanks.
[ButterKnifeDemo.zip](https://github.com/JakeWharton/butterknife/files/1437145/ButterKnifeDemo.zip)

**Comment by qq596670409** [comment]
Do you solve this problem? i also meet it.
