### ISSUE TITLE
Required view 'menu' with ID 2131624089 for method 'onClick' was not found

### ISSUE THREAD

**Issue by CzmZomBie** [JakeWharton/butterknife#1106]
Error:
Caused by: java.lang.IllegalStateException: Required view 'menu' with ID 2131624089 for method 'onClick' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

this is my BaseFragment

 @Optional
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(getLayoutId(), container, false);
        ButterKnife.bind(this, view);
        return view;
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        initData();
    }

Fragment A OnClick：

    @OnClick(R.id.saveContacts)
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.saveContacts:
                initdate();
                break;
        }
    }

What should I do？

**Comment by JakeWharton** [comment]
The exception message tells you what to do. Either the view needs to always be available or you need to annotate it as being nullable.
