### ISSUE TITLE
UnusedIds lint warning when using R2

### ISSUE THREAD

**Issue by scottkennedy** [JakeWharton/butterknife#1108]
Every view whose id is only referenced through `@BindView` reports an `UnusedIds` lint warning if I use the Gradle plugin and R2.

Ideally, there'd be a way to tie this back to the original `R.id` entry so that lint only reports ids that are actually unused.

**Comment by JakeWharton** [comment]
The generated code references the real ID, so that sounds like a lint bug.

**Comment by scottkennedy** [comment]
I'll report it to Google too, but for reference:
https://github.com/scottkennedy/lintunusedids
`./gradlew lintDebug` shows an `UnusedIds` warning.  If I use `R` instead of `R2`, the warning does not occur.

**Comment by JakeWharton** [comment]
The reference is correctly put in the generated code:
```
$ grep -r 'R.id.textview' app/build/generated/source/apt/release/
app/build/generated/source/apt/release//ca/skennedy/unusedids/MainActivity_ViewBinding.java:25:    target.mTextView = Utils.findRequiredViewAsType(source, R.id.textview, "field 'mTextView'", TextView.class);
```
so definitely a lint bug.
