### ISSUE TITLE
ButterKnife in Feature module 

### ISSUE THREAD

**Issue by emillime** [JakeWharton/butterknife#1113]
We are trying to convert our app to work as an Instant app. But are encountering problems when using ButterKnife in feature modules (com.android.feature). What is the correct way use ButterKnife when converting from an application module to feature module?

If I use it exactly as when we had com.android.application, without the library plugin. I get an error when trying to bind a view.

```java
@BindView(R.id.layout)
RelativeLayout mLayout;
```
I get the error on `R.id.layout` saying `error: element value must be a constant expression`.

I also tried applying the plugin like in a library, but got the exact same error. And if I try to use `R2.id.layout` I get `error: package R2 does not exist`.

In the feature module I have this:

```
...
dependencies {
    implementation 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'
}
...
```

And then tried adding this as well:

```
buildscript {
    repositories {
        ...
        maven { url "http://oss.sonatype.org/content/groups/public" }
        jcenter()
    }

    dependencies {
        ...
        classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'
    }
}

apply plugin: 'com.android.feature'
apply plugin: 'com.jakewharton.butterknife'

...
```

I'm using ButterKnife 9.0.0-SNAPSHOT, which should be possible to use with feature modules. How should I use ButterKnife in a feature module?

**Comment by JakeWharton** [comment]
I have reports of it working correctly so I'm not sure what to tell you. If the R2 class isn't being generated then something about the plugin isn't configured correctly.

**Comment by emillime** [comment]
When using it from a feature module I should use the plugin and R2 class right?
What should I look at to get the plugin to work?

**Comment by JakeWharton** [comment]
Yes. Do you see the R2 task run in that module? Does the R2 file get
generated in your build/ folder?

**Comment by dazza5000** [comment]
We were able to get this working. Were you able to get this working @emillime ?

**Comment by kassim** [comment]
`error: package R2 does not exist` makes it seem like an import is missing

**Comment by dominolog** [comment]
+1 to this. Which version of Butterknife is working with feature modules and Gradle version 3.0.0? I have tried 9.0.0 from snapshot but was not able to build it correctly? Any hints or a reference project? Especially would be nice to see if it works in InstantApps feature modules. Thanks.

**Comment by dazza5000** [comment]
I have it working with instant apps base features, but haven't tried
feature modules yet.

**Comment by dominolog** [comment]
@dazza5000 could you hint me your build.gradle files for your base feature?

**Comment by dazza5000** [comment]
Relevant parts here (the butterknife version is 9.0 snapshot or something
like that)

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()
        jcenter()
        google()
        maven { url "http://oss.sonatype.org/content/groups/public" }
        maven { url "https://maven.google.com" }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:' + rootProject.FABRIC_VERSION
        classpath 'com.jakewharton:butterknife-gradle-plugin:' +
rootProject.BUTTERKNIFE_VERSION
        classpath 'com.newrelic.agent.android:agent-gradle-plugin:' +
rootProject.NEW_RELIC_VERSION
    }
}

apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}




implementation 'com.jakewharton.timber:timber:' + rootProject.TIMBER_VERSION
implementation 'com.jakewharton:butterknife:' + rootProject.BUTTERKNIFE_VERSION
api 'io.reactivex.rxjava2:rxandroid:' + rootProject.RXANDROID_VERSION
implementation 'com.google.dagger:dagger:' + rootProject.DAGGER_VERSION
implementation 'android.arch.lifecycle:extensions:' +
rootProject.ARCH_LIFECYCLE_VERSION
implementation 'android.arch.persistence.room:runtime:' +
rootProject.ARCH_ROOM_VERSION
annotationProcessor "android.arch.lifecycle:compiler:" +
rootProject.ARCH_LIFECYCLE_VERSION
annotationProcessor "android.arch.persistence.room:compiler:" +
rootProject.ARCH_ROOM_VERSION
annotationProcessor 'com.google.dagger:dagger-compiler:' +
rootProject.DAGGER_VERSION
annotationProcessor 'com.jakewharton:butterknife-compiler:' +
rootProject.BUTTERKNIFE_VERSION

**Comment by Emeritus-DarranKelinske** [comment]
As we added more feature modules things started falling apart. Going to back out butterknife for the time being. Android Databinding is also kind of a no go right now too with feature modules. findViewById forevs <3 at least for now <3

**Comment by JakeWharton** [comment]
Should work with 9.0
