### ISSUE TITLE
在PopUpWindow和Dialog上的使用

### ISSUE THREAD

**Issue by llol** [JakeWharton/butterknife#1117]
在PopUpWindow和Dialog等这些需要使用LayoutInflater.from(R.layout.xx)解析来的View，怎么使用BindView和onClick注解

**Comment by qinxianyuzou** [comment]
保存一个view，然后ButterKnife.bind(this, view)，其他都一样

> 在PopUpWindow和Dialog等这些需要使用LayoutInflater.from(R.layout.xx)解析来的View，怎么使用BindView和onClick注解

**Comment by JakeWharton** [comment]
Can you express the problem in English? Or perhaps with a failing test case or small, reproducing sample project?

**Comment by qinxianyuzou** [comment]
That he needs to use in PopUpWindow and Dialog in,but he did not know how to use it.

> Can you express the problem in English? Or perhaps with a failing test case or small, reproducing sample project?

**Comment by JakeWharton** [comment]
Without a failing test case or sample project it's not clear what the problem is, sorry.
