### ISSUE TITLE
当使用v8.8.1版本的时候proguard-rules失效了 -- Proguard Rules failed when V8.8.1 used 

### ISSUE THREAD

**Issue by ruidalin** [JakeWharton/butterknife#1119]
当使用v8.8.1版本的时候proguard-rules失效了 , 如果去掉ButterKnife-v8.8.1的时候混淆正常 , 否侧一点混淆效果都没有 , 请求得到帮助

**Comment by ruidalin** [comment]
proguard is successed when used v7.0.1 but fail when used v8.+ , i don't know how to do that let the pgrguard build apk success

**Comment by JakeWharton** [comment]
You haven't supplied any info indicating what you think the problem is.

**Comment by ruidalin** [comment]
I have send a Email(with  picture ) to you , i can't describe my problem   , so sorry for my bad English .

**Comment by ruidalin** [comment]
i mean the ButterKnife version let the code can't useful proguard-rules.pro , when i use 7.0.1 version the proguard-rules.pro is useful but 8.8.1 version is not useful .

**Comment by JakeWharton** [comment]
The rules are embedded in the aar as of 8.0. Delete and other rules you are
using.
