### ISSUE TITLE
appcompat-v7:23.+ 和butterknife:8.8.1 错误

### ISSUE THREAD

**Issue by ruidalin** [JakeWharton/butterknife#1120]
appcompat-v7:23.+ 和butterknife:8.8.1这什么错误 , 该如何解决 (appcompat-v7:26.+ 则没有报错)
```
    compile 'com.android.support:appcompat-v7:23.+'
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
```

Warning:Exception while processing task java.io.IOException: Can't write [E:\Application\MyApplication\app\build\intermediates\transforms\proguard\debug\jars\3\1f\main.jar] (Can't read [C:\Users\Admin\.android\build-cache\afefd4741cd56a370b6dd313befcc4640dcfbd5a\output\jars\libs\internal_impl-23.4.0.jar(;;;;;;**.class)] (Duplicate zip entry [android/support/v4/h/m.class == internal_impl-23.4.0.jar:android/support/v4/view/LayoutInflaterFactory.class]))

**Comment by JakeWharton** [comment]
This is not a problem with the library. You are including two copies of a class in your build system. You can use the `dependencies` task to try and narrow where the duplicates are coming from.
