### ISSUE TITLE
Butterknife bind views to different sources

### ISSUE THREAD

**Issue by yashasvigirdhar** [JakeWharton/butterknife#1121]
In my activity, I am using two types of views : X type and Y type.

X type views are directly defined in the xml layout file with which I am calling setContentView(). For Y type of views, they are present in a dialog which I am inflating in the activity and then adding it as a header view in my listview (which is present in activity xml).

Now, how do I use butterknife to inject both of these view types. If I call Butterknife.bind(@NonNull Activity target), it'd inject only those views which are present in activity xml. And if I call Butterknife.bind(@NonNull Object target, @NonNull Dialog source), it would inject only the views present in that dialog.

Hope I've clearly explained the problem.

Let me know if anything else is needed

**Comment by JakeWharton** [comment]
Create a view holder class for each layout and bind an instance of each individually. There's no way to support binding two layouts into one class.
