### ISSUE TITLE
Feature Request : Bind XML Fragments

### ISSUE THREAD

**Issue by rupinderjeet** [JakeWharton/butterknife#1133]
**fragment in xml**

    <fragment
        android:id="@+id/parent_fragment"
        android:name="com.app.example.ParentFragment"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

**binding in activity**

     @BindView(R.id.parent_fragment)
     ParentFragment parentFragment;

**gradle build error message**

> @BindView fields must extend from View or be an interface

Can we have something like @BindFragment for binding XML fragments using @+id?

https://stackoverflow.com/questions/47050414

**Comment by JakeWharton** [comment]
Fragments are not UI elements and Android supporting defining them in XML is a mistake.

There's a really old issue about this where it's discussed more if you want more info.
