### ISSUE TITLE
Android Studio 3.0 support  kotlin  And Butterknife also support 

### ISSUE THREAD

**Issue by Tforandroid** [JakeWharton/butterknife#1137]
Android Studio 3.0 support  kotlin  And Butterknife also support   
i think  it  cause this promble

Error:Unable to find method 'com.android.build.gradle.internal.variant.BaseVariantData.getOutputs()Ljava/util/List

**Comment by JakeWharton** [comment]
Use 9.0.0-SNAPSHOT for now.
