### ISSUE TITLE
what is this?  android studio3.0

### ISSUE THREAD

**Issue by JamesMarts** [JakeWharton/butterknife#1141]
`Error:Failed to resolve: com.jakewharton:butterknife:9.0.0-SNAPSHOT
<a href="openFile:H:/NewProject/CommonFramework/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>`

**Comment by JakeWharton** [comment]
See the README for the link to the snapshot repository you have to add.
