### ISSUE TITLE
Theme.AppCompat missing

### ISSUE THREAD

**Issue by JemyZou** [JakeWharton/butterknife#1144]
Hi，I meet the same problem.When I use it in a library module,it happened.remove it,work fine.Attach is my sample project,please check it.Thanks.
![32318987-f25733f4-bff3-11e7-9221-55abcd7c47b7](https://user-images.githubusercontent.com/13834392/32587208-0a36734c-c542-11e7-871c-35e2b86dc807.png)
[ButterKnifeDemo.zip](https://github.com/JakeWharton/butterknife/files/1456208/ButterKnifeDemo.zip)

**Comment by JakeWharton** [comment]
This theme comes from AppCompat, not ButterKnife.

**Comment by JemyZou** [comment]
but this problem appears when butterknife was integrated.remove,work fine.so can i guest butterknife apt reslut in some style missing?

**Comment by JakeWharton** [comment]
The library depends on AppCompat in 9.0, yes, but doesn't include any styles. So any such problem is one in your build configuration or in Android Studio.
