### ISSUE TITLE
Gradle sync error with gradle 3.0 and butterKinfe plugin 8.8.1 in library

### ISSUE THREAD

**Issue by voiddog** [JakeWharton/butterknife#1146]
first set classpath in root project gradle
```
 dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath "com.jakewharton:butterknife-gradle-plugin:8.8.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
}
```

apply plugin in library module
```
apply plugin: 'com.jakewharton.butterknife'

dependencies {
     // butter knife
    implementation "com.jakewharton:butterknife:8.8.1"
    annotationProcessor "com.jakewharton:butterknife-compiler:8.8.1"
}
```

then I got gradle sync error:

--------

Error:Unable to find method 'com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by JakeWharton** [comment]
You'll have to use 9.0.0-SNAPSHOT for now.

**Comment by niteshverma09** [comment]
This is still not working.

**Comment by LonelyPluto** [comment]
when I user the 8.8.1 version,I have the same problem.

**Comment by HymanYang** [comment]
when I use the 10.2.3 version ,I have the same problem
