### ISSUE TITLE
Obsolete custom lint check

### ISSUE THREAD

**Issue by autonomousapps** [JakeWharton/butterknife#1147]
![screenshot from 2017-11-10 13-10-22](https://user-images.githubusercontent.com/5402301/32678791-b832cf78-c618-11e7-81ef-96a1384204d5.png)

> Lint found one or more custom checks using its older Java API; these checks are still run in compatibility mode, but this causes duplicated parsing, and in the next version lint will no longer include this legacy mode. Make sure the following lint detectors are upgraded to the new API: butterknife.lint.InvalidR2UsageDetector

It's listed as priority 10/10.

**Comment by JakeWharton** [comment]
This is fixed on master and will be released in the next version. Try 9.0.0-SNAPSHOT for now.

**Comment by egek92** [comment]
can overriding get current API method fix this? I'm currently developing a custom lint in Kotlin and getting the same error.

so I did:

```
override val api: Int
        get() = CURRENT_API
```

`import com.android.tools.lint.detector.api.CURRENT_API`
