### ISSUE TITLE
ButterKnife view unbind in fragment onDistroyview() causes null view on screen rotation and crashes.

### ISSUE THREAD

**Issue by muhammedrameez** [JakeWharton/butterknife#1150]
I use butterknife library to bind my view in a fragment. and when i rotate my screen i get the null poninter exception on view components of the fragments. i wrote unbind method in ondistroyview() in fragment.

**Comment by JakeWharton** [comment]
The views will be null'd out in onDestroyView and re-bound when onCreateView is called again. You cannot touch the views between those two events.
