### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lbutterknife/ButterKnife;

### ISSUE THREAD

**Issue by gurudshet76** [JakeWharton/butterknife#1151]
Found this issue in Galaxy Tab A, Samsung Note 4 and Galaxy S6 Edge devices.
We are currently using version 8.7.0. Any specific version to use?

**Comment by JakeWharton** [comment]
This is a build issue or device issue, not a library issue. That class is present in the jar we provide and as a library we assume it will be present in the APK and at runtime. You should check with APK inspector to make sure the class is present in your APK and if you're using multidex ensure that it's set up correctly.
