### ISSUE TITLE
How to Bind a TextView which is in an NavigationView in an Activity

### ISSUE THREAD

**Issue by afattahi54** [JakeWharton/butterknife#1153]
We are using android sdk 26 with butterknife 8.8.1

The HomeActivity has a navigation header, the navigation header also contains some text view. Is it possible to bind the TextViews in HomeActivity ?!

Here are some codes which describes my problem

The HomeActivity class has below layout

```xml
<android.support.v4.widget.DrawerLayout ....
    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        .....
        app:headerLayout="@layout/nav_header"
        app:menu="@menu/activity_navigation_drawer" />
</android.support.v4.widget.DrawerLayout>
```

The nav_header has some TextView in it

```xml
<LinearLayout ....
    <TextView
        android:id="@+id/userinfo_vo_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="TextView" />
</LinearLayout>
```
Is it possible to bind the id of userinfo_vo_name text view in HomeActivity, the simple BindView fails

```java
//fails 
@BindView(R.id.userinfo_vo_name)
TextView userinfoName;
```

Of course, I have called ButterKnife.bind(this); in onCreate method, but it seems not enough.

**Comment by JakeWharton** [comment]
Header views are not locatable via findViewById on the root layout and thus won't work via @BindView on it either. You can call getHeaderView(0) and use that View to bind to a view holder object that contains your @BindViews for the header.

**Comment by afattahi54** [comment]
@JakeWharton thanks ! I am very new in Android.
I see some descriptions at https://stackoverflow.com/questions/33194594/navigationview-get-find-header-layout

But can you explain this a little more:

I am using the `sdk 26.0.2` , and support library `4:26.1.0`  
The normal `this.findViewById(R.id.userinfo_vo_name);` returns correct `TextView`  ! But the `@BindView` is not working
