### ISSUE TITLE
android studio 3.0  module Library can not use butterknife。

### ISSUE THREAD

**Issue by jikun2008** [JakeWharton/butterknife#1155]
hello 3q for your butterknife

i found a bug when use butterknife 8.8.1  in 
android stuido 3.0 gradle4.1 
my project have a module Library  must  use R2，when I gradle it will have a  error  
ex:
![image](https://user-images.githubusercontent.com/5136612/33068725-2425ee72-ceed-11e7-8e11-96d855557095.png)
 
when i remove apply plugin: 'com.jakewharton.butterknife'  it will be fine.(gradle OK)
![image](https://user-images.githubusercontent.com/5136612/33068947-d408e2ea-ceed-11e7-91c8-3a35eb3a88e1.png)

but  module Library  can not find R2 class so module  libary can not use butterknife too;

![image](https://user-images.githubusercontent.com/5136612/33069015-1703445a-ceee-11e7-9c94-886b7adea583.png)

i am  sure it can not work in module Library 

if you need more info please tell me   i can give you a project 
thank you

**Comment by jikun2008** [comment]
I use butterknife 8.8.1

**Comment by JakeWharton** [comment]
You need to use 9.0.0-SNAPSHOT for now until a new version is released.

**Comment by JakeWharton** [comment]
See the README for a link to the snapshot repo

**Comment by jikun2008** [comment]
ok  thank you

**Comment by tianlin95310** [comment]
hey, i have the same question with this issue ,can you show your app module and libs module configs, thanks! @jikun2008 @JakeWharton
