### ISSUE TITLE
java.lang.NullPointerException:Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference

### ISSUE THREAD

**Issue by lifuyuan123** [JakeWharton/butterknife#1158]
Is the binding control successful in some of the destruction reuse of controls because the reasons for the use of the same ID binding in different layouts

**Comment by JakeWharton** [comment]
You're either accessing a view before calling `bind` (or after calling `unbind`) or it's marked as `@Nullable` and you're not null checking it. Or you're forgetting to call `bind` altogether.

**Comment by lifuyuan123** [comment]
The null pointer appears occasionally, with different models. The binding view is bound in the OnCreat method, and the call to the bound view in some callbacks is the occasional null-pointer, not every time.

**Comment by manburenshenglu** [comment]
so do i, when use in fragment

**Comment by siavashabdoli** [comment]
100 percent sure that is not nullable and I'm in the view But I get npe in fragment.
@JakeWharton
