### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by baltixx** [JakeWharton/butterknife#1171]
I met this error:

Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write [C:\Users\BaltIx\Desktop\helpcube\app\build\intermediates\multi-dex\debug\componentClasses.jar] (Can't read [C:\Users\Baltix\.gradle\caches\transforms-1\files-1.1\support-compat-25.2.0.aar\17c30fe09f5c0042f424d784f1ebd6b6\jars\classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/v4/view/ViewCompat.class]))

**Comment by JakeWharton** [comment]
This is a problem with your local build, not with Butter Knife. You're somehow including two copies of the support library.
