### ISSUE TITLE
use butterknife 9.0.0-snapshot, R2 is not exist

### ISSUE THREAD

**Issue by joisephine** [JakeWharton/butterknife#1173]
use butterknife 9.0.0-snapshot, and  gradle tools version is 3.0.1. 
I sufferr compile error: @BindView(R2.id.xxx) , R2 is not exist...

**Comment by JakeWharton** [comment]
Please provide a sample which demonstrates the problem.

**Comment by joisephine** [comment]
Hey, JakeWharton, I wanna to upgrade my gradle tool to version 3.0.1, and I suffer butterknife problem.  So I upgrade butterknife to 9.0.0-snapshot, but I suffer this "R2" problem.
What can I do , when I wanna to upgrade my gradle too to version 3.0.1?
Thank you very much.

**Comment by joisephine** [comment]
sample:
build.gradle:
classpath 'com.android.tools.build:gradle:3.0.1'
 classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'.

after compile:
Task :module_house:compileDevDebugDevNHJavaWithJavac
/Users/xxx/projects/module/xxx//src/main/java/com/android//album/GalleryPanoramaAdapter.java:12: 错误:不到符号
import com.android.R2;

**Comment by JakeWharton** [comment]
Is your manifest package "com.android"?

**Comment by joisephine** [comment]
no, it is just a sampe. my package is "com.xx.android.xxx"

**Comment by joisephine** [comment]
similar to issue #1159

**Comment by joisephine** [comment]
it doesn't generate R2.java under path: build/generated/source/r/xx/debug/com/xxx/android/xxx
why?

**Comment by JakeWharton** [comment]
Please provide a sample project which demonstrates the problem.

**Comment by joisephine** [comment]
i resolved, thank you very much.

**Comment by JakeWharton** [comment]
Great!

**Comment by FutureHere** [comment]
How to resolove this problem?

**Comment by Jafar396** [comment]
@joisephine @FutureHere 
How to resolve?
