### ISSUE TITLE
Consider use reflection instead of apt in debug build

### ISSUE THREAD

**Issue by zjhuang0** [JakeWharton/butterknife#1174]
Apt takes a lot time to generate code while building

**Comment by JakeWharton** [comment]
I mean I guess this might be interesting for debug builds but I would _never_ enable this for release builds. No one has suggested this in the 5 years this has been a library so I'm not eager to add it.

**Comment by vanniktech** [comment]
This will only be beneficial when all annotation processors use reflection in debug builds and we get Gradles incremental compilation, right?

**Comment by JakeWharton** [comment]
It would be beneficial regardless. The magnitude of the benefit will
correlate with whether or not you have other processors or not.

**Comment by JakeWharton** [comment]
This has started. See `butterknife-reflect/`.
