### ISSUE TITLE
怎么避免混淆的？

### ISSUE THREAD

**Issue by aosyee** [JakeWharton/butterknife#1179]
在我的项目里，使用butterknife注入了view，在混淆文件里没有设置keep。
butterKnife是怎么做到的没被混淆？

**Comment by jugutier** [comment]
This says:

"How to avoid confusion?"
"In my project, using butterknife into the view, in the confusion file did not set keep.
butterKnife did not be confused?"

**Comment by JakeWharton** [comment]
Unfortunately that's not enough information to diagnose any problem. The easiest way to convey a problem is with a failing test case or sample project which demonstrates the broken behavior. Without this, I don't know what action to take.

**Comment by fuqiang915** [comment]
@aosyee  项目里面已经加了proguard-rules
 https://github.com/JakeWharton/butterknife/blob/master/butterknife/proguard-rules.txt
