### ISSUE TITLE
ButterKnife plugin: R2 file's resources not corresponding to actual resource id

### ISSUE THREAD

**Issue by abyrnes** [JakeWharton/butterknife#1182]
I'm currently working on a project where I've begin splitting up the features into separate android modules. I was getting an inflation error when referencing one of the layout resources in the generated R2 file. The reason being that the id in the R2 file was different from the one in the R file.

The application itself was using [chuck](https://github.com/jgilfelt/chuck) and the ids in chuck were appearing before the layout id I was referencing in the R file but not in the R2 file, causing a mismatch between the values.

I was able to resolve the issue by simply removing chuck but have so far been able to come up with a solution that allows me to keep chuck.

Thoughts?

**Comment by JakeWharton** [comment]
R2 is only for ButterKnife annotations. You shouldn't be using it anywhere else and should prefer R instead.

**Comment by abyrnes** [comment]
Sorry, forgot to mention. I'm also using epoxy, which requires using the ButterKnife plugin and using R2 for their annotations.

**Comment by JakeWharton** [comment]
Hmm I don't really know how their usage works. Is it only in annotations as
well?

**Comment by abyrnes** [comment]
Yup. The module in fact doesn't use butterknife annotations, just the gradle plugin as epoxy requires it if you're using their annotations in a library/module.

**Comment by JakeWharton** [comment]
Can you create a small sample that reproduces the problem so that it can be investigated further?

**Comment by abyrnes** [comment]
I tried to recreate the issue in a sample project but was unable to reproduce it :/
Furthermore, the other person I'm working on the project with didn't have the issue on his machine. So I'm not sure what the issue is but for the time being I have forgone using the butterknife gradle plugin for epoxy's use in my project as it's optional.

If I come across the issue again and it looks like it's not just a problem with my environment I'll be sure to let you know.

**Comment by pdog18** [comment]
I only used butterknife gradle plugin in the library (the Host module is not used,(application))

They generate different R2, R values, and they crash when they're used

![481528714146_ pic_hd](https://user-images.githubusercontent.com/17060376/41227754-8bfe8cf2-6da8-11e8-8338-e8c8b7a55baa.jpg)
@JakeWharton
