### ISSUE TITLE
9.0.0-SNAPSHOT Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by furiousbuilder** [JakeWharton/butterknife#1183]
Hi,
I update Gradle to 3.0.1 so I had to update Butterknife to 9.0.0-SNAPSHOT.
Unfortunately this is providing erros as you can see:
![screenshot 56](https://user-images.githubusercontent.com/10899984/35215504-bca2a8a0-ff64-11e7-8aac-90005b6e9a71.png)

Here is my build.gradle

> `buildscript {
>     repositories {
>         jcenter()
>         google()
>         maven { name 'Sonatype SNAPSHOTs'; url 'https://oss.sonatype.org/content/repositories/snapshots/' }
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.0.1'
>         classpath "com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT"
>     }
> }
> 
> allprojects {
>     repositories {
>         jcenter()
>         google()
>         maven { name 'Sonatype SNAPSHOTs'; url 'https://oss.sonatype.org/content/repositories/snapshots/' }
>     }
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }`

Library's build.gradle: 

> `apply plugin: 'com.android.library'
> apply plugin: 'com.jakewharton.butterknife'
> 
> android {
>     compileSdkVersion 27
>     buildToolsVersion "27.0.3"
> 
>     defaultConfig {
>         minSdkVersion 16
>         targetSdkVersion 27
>         versionCode 1
>         versionName "1.0"
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     compile 'com.android.support:appcompat-v7:27.0.2'
>     compile 'com.android.support:recyclerview-v7:27.0.2'
>     compile 'com.android.support:design:27.0.2'
> 
>     //RX
>     compile('io.reactivex:rxandroid:1.1.0') {
>         exclude module: 'rxjava'
>     }
>     compile 'io.reactivex:rxjava:1.1.0'
>     compile 'com.jakewharton.rxbinding:rxbinding:0.4.0'
>     compile 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
>     annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'
> }
> `

I already tried `./gradlew clean build` and `gradlew --refresh-dependencies`

Do you know where it come from? Thanks!

**Comment by JakeWharton** [comment]
I cannot see how this is related to Butter Knife or how a change to Butter Knife could solve this problem. It looks like a generic misconfiguration on your part or an Android Gradle plugin problem.

If you can create a standalone executable example that demonstrates the problem is from Butter Knife I can take a look, but as of now there's no indication the library is at fault.
