### ISSUE TITLE
Compile time annotation classes lookup 

### ISSUE THREAD

**Issue by jugutier** [JakeWharton/butterknife#1186]
Hi @JakeWharton ,

This project looks really interesting! Have you experimented with annotation processors and library projects? 

Say we had:

App
-> some annotated classes

MyLib
-> some annotated classes

(code that depends on finding annotated classes from both targets with a **compile time annotation**)

Seems like the annotationProcessor gradle directive will only catch them from either project but not both. The goal would be to provide support to butterknife and other annotation processors (like [this one](https://github.com/atteo/classindex)) to users of some library I am working on, while having some mechanism to retrieve annotated classes outside the library from within the library. Hope that makes sense :)

**Comment by JakeWharton** [comment]
I don't understand what problem you're trying to solve. #808?

**Comment by jugutier** [comment]
Yes, that's actually pretty close! and also #1008. basically providing a way for a 'myLibrary' (that uses butterknife and classindex annotation processors) to pass on the functionality to classes outside myLibrary module. 

Is this a limitation with gradle annotationProcessor directive? 

Can you point me to where to start looking if I wanted to start working on support for this?

Basically having a compile time annotation that maps out the annotated classes to a txt file living under META-INF/myAnnotatedClasses.txt to later be accessible both from the app target and from the library project. 

This to me is the core issue, because we could access the file at runtime with basic Java I/O but multidex makes this very complicated specially on Samsung devices.

**Comment by JakeWharton** [comment]
I don't understand what you're trying to achieve nor how it relates to Butter Knife or what you're proposing be changed or added to this library.
