### ISSUE TITLE
The MainModule cannot use the butterknife in the BaseModule

### ISSUE THREAD

**Issue by edifangyi** [JakeWharton/butterknife#1187]
![image](https://user-images.githubusercontent.com/12421552/35374858-a65482bc-01df-11e8-9c4c-e4d81ea9c54e.png)
![image](https://user-images.githubusercontent.com/12421552/35374950-0a832e28-01e0-11e8-9d28-ebaca4e1ee42.png)

I can only rely on butterknife in these two places, and I can use it in MianModule.
I also refer to what I do in the document, but it doesn't work.

Android Studio 3.0.1
Gradle 3.0.1

===================================

 I saw my leader using butterknife，I think it's amazing, It can work normally in MainModule
,but he forgot how he did it.

Android Studio 3.0.1
Gradle 3.0.1

![image](https://user-images.githubusercontent.com/12421552/35374988-3c184450-01e0-11e8-8cb6-794cc573cc0c.png)
![image](https://user-images.githubusercontent.com/12421552/35375117-cb7f9e86-01e0-11e8-8b19-c517b414a49d.png)

![ry j x s b y0yc z9ac t](https://user-images.githubusercontent.com/12421552/35375081-9ced25ca-01e0-11e8-8361-58bde244ec27.png)

**Comment by edifangyi** [comment]
This is the frame

https://github.com/StannyBing/ZxMvp/tree/58296a49c428b6a4eaeb5c924f400763ce2a0162

**Comment by edifangyi** [comment]
javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }

**Comment by hahahazzz** [comment]
如果MainModule依赖BaseModule,在BaseModule里compile butterknife,在MainModule里只需要添加butterknife的annotationProcessor.
如果两者没有依赖关系,那就得在两个module里分别添加compile和annotationProcessor
如果BaseModule是library,并且需要在BaseModule里使用ButterKnife,那还得添加apply plugin: 'com.jakewharton.butterknife'

**Comment by edifangyi** [comment]
@hahahazzz 我是这样解决的，，，BaseModule(library) 和 MainModule(app)  都在这里这么写

android {
---
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
    }
}

并且 BaseModule(library)  中依赖 butterknife 
必须这样写
    compile 'com.jakewharton:butterknife:8.8.1'
    compile 'com.jakewharton:butterknife-compiler:8.8.1'

=========================================

这样可以保证  在MainModule(app) 中只依赖 BaseModule(library)，就可以使用黄油刀的

android3.0开始，module中引用的依赖如果存在注解
必须使用annotationProcessor 来进行引用
