### ISSUE TITLE
Gradle sync error when I use build gradle version 3.0.0.

### ISSUE THREAD

**Issue by rexyren** [JakeWharton/butterknife#1189]
Unable to find method 'com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;'. 

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project

**Comment by JakeWharton** [comment]
You need to use 9.0.0-SNAPSHOT for now. See the README for a link to the Sonatype snapshots repo that you can add to your `repositories` in your Gradle file.
