### ISSUE TITLE
Fragment unbind NPE issue

### ISSUE THREAD

**Issue by loldma** [JakeWharton/butterknife#1195]
Hello!
We are using a simple setup: We are having a RecyclerView in a SwipeRefreshLayout and a simple ImageView. We unbind the views in the onDestroyView. We also have an onScrollListener for the RecyclerView and we check some property of the ImageView. If we swipe, and quickly go to other page of the ViewPager, the listener still gets called, and the app closes with NPE, because the ImageView is already unbound. Wouldn't it be fixed, if we put the unbind in the onDestroy?\

**Comment by JakeWharton** [comment]
This is not a problem specific to Butter Knife, it's merely the thing doing the binding and unbinding of views. If you used normal `findViewById` and setting them to null you would observe the same behavior.
