### ISSUE TITLE
Target must not be null.

### ISSUE THREAD

**Issue by jordiguzman** [JakeWharton/butterknife#1198]
I use Android Studio 3.0.1 with 'com.jakewharton:butterknife:8.8.1'. When I cast @BindView(R.id.iv_poster_detail)
    ImageView imageView;
and onCreate:
 ButterKnife.bind(this);
the app crashes with the message: "Target must not be null". 
Not only with ImageView also with TextView.

**Comment by JakeWharton** [comment]
"target" is the parameter passed to `bind` which is weird because `this` can never be null.

Please provide a sample which demonstrates this behavior.

**Comment by jordiguzman** [comment]
In this simple test in MainActivity the Bind not work for me. https://github.com/jordiguzman/Parcelable-Example

**Comment by JakeWharton** [comment]
Your build is not configured correct with the annotation processor.
