### ISSUE TITLE
build error with butterknife8.8.1 on gradle 3.0.1

### ISSUE THREAD

**Issue by zhijiazheng123** [JakeWharton/butterknife#1200]
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by JakeWharton** [comment]
This is fixed on `master`. You can use 9.0.0-SNAPSHOT for now.

**Comment by zhijiazheng123** [comment]
thanks for reply, but it still build failed, not sure whether I've set the wrong config:

A problem occurred configuring root project 'AssistantVertu'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT.
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
         https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
         https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar
         https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
         https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar
         http://maven.aliyun.com/nexus/content/groups/public/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
         http://maven.aliyun.com/nexus/content/groups/public/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
         http://maven.aliyun.com/nexus/content/groups/public/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar
     Required by:
         project :

* Try:

**Comment by zhijiazheng123** [comment]
thanks for reply, but after I use 9.0.0-SNAPSHOT, it reports java.lang.NullPointerException
