### ISSUE TITLE
Plugin Window not a usable size.

### ISSUE THREAD

**Issue by z3r08ug** [JakeWharton/butterknife#1202]
Hi attached are screen shots of what the plugin looks like when I try to use it.  The window is so small and the ui components of the window are unable to be interacted with which makes the plugin completely useless.  Even after making the window bigger the ui components are not redrawn and thus remain unusable.  How do I go about fixing this issue?

![2018-02-17 1](https://user-images.githubusercontent.com/4284480/36348085-a6f23c0a-1436-11e8-8bcd-cd276686d88b.png)
![2018-02-17](https://user-images.githubusercontent.com/4284480/36348086-a6feaa26-1436-11e8-9440-da7cd7069d26.png)

**Comment by JakeWharton** [comment]
This library does not contain an IDE plugin. You want https://github.com/avast/android-butterknife-zelezny
