### ISSUE TITLE
Reports java.lang.NullPointerException after using 9.0.0-SNAPSHOT on gradle 3.0.1

### ISSUE THREAD

**Issue by zhijiazheng123** [JakeWharton/butterknife#1203]
[Uploading Kotlin.zip…]()
[Uploading Kotlin.zip…]()

**Comment by JakeWharton** [comment]
Those links don't work and it's not clear how this is different than #1201

**Comment by zhijiazheng123** [comment]
sorry Jake, please ignore #1203, any comments about this NullPointerException?

**Comment by JakeWharton** [comment]
I haven't looked. Not sure when I'll have time to

**Comment by zhijiazheng123** [comment]
that's a bad news for me :(

**Comment by zhijiazheng123** [comment]
do you have any suggestion so that I could try it myself? thanks a lot!
