### ISSUE TITLE
I got this error when I use the "apply plugin: " code to build gradle

### ISSUE THREAD

**Issue by zkx741481546** [JakeWharton/butterknife#1204]
error:(2, 0) Android Gradle plugin 3.0.1 must not be applied to project 'C:\Users\zkx74\AndroidStudioProjects\MyApplication4\app' since version 3.0.1 was already applied to this project
<a href="openFile:C:\Users\zkx74\AndroidStudioProjects\MyApplication4\app\build.gradle">Open File</a>

android studio 3.0.1 
gradle 4.1
how should I work this out?

**Comment by JakeWharton** [comment]
This is not enough information to form an actionable report. It sounds like you're applying the Android plugin twice in that module, which I don't see how it is related to this project.

**Comment by zkx741481546** [comment]
But if I use butterknife 8.4.0, it can word normally. I saw this solution on Github, I guess maybe the new version has some bugs
