### ISSUE TITLE
project not syncing

### ISSUE THREAD

**Issue by Maverick7V** [JakeWharton/butterknife#1205]
Hello, 
After adding butterknife and then syncing the my build fails and I get the following error-
Error:(29, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'MovieManager' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 3.0.1 and sync project</a></li><li>The project 'MovieManager' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

Cannot find any reason as I am a beginner in android programming.Really want to understand what the problem is.
Thank You.

**Comment by JakeWharton** [comment]
This appears to be a usage question. Please ask on StackOverflow with the 'butterknife' tag with more information such as your build configuration.
