### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by kimljx** [JakeWharton/butterknife#1209]
I use dependencies in the app build.gradle

![image](https://user-images.githubusercontent.com/19872214/37586664-036f7d76-2b98-11e8-90ec-a1fed100a66f.png)

Bind the control with the @bindview code.
![image](https://user-images.githubusercontent.com/19872214/36627460-108c456a-197e-11e8-8e67-9426f3de16b3.png)
Occasionally, an item with a bound control (for example, doctorCount in the figure) is empty when the project is running on a phone Crash the app 
(java.lang.NullPointerException: Attempt to call the virtual method 'void android.widget.TextView .setText (java .lang.CharSequence) 'null reference)
Sometimes it worked but sometimes failed

---------------------------
I use Google Translate,  please understand

**Comment by kimljx** [comment]
Sometimes it worked but sometimes failed

**Comment by qingmingmeng** [comment]
I've had this problem, too.

**Comment by nksaroj** [comment]
I had the same issue

**Comment by parsamparpary** [comment]
↔⏩➡↘⬇↙⬅↖↗🔄🔃⤵⤴↪↩↔🔙🔚🔛🔜🔝

**Comment by davyjoneswang** [comment]
any solutions?

**Comment by kimljx** [comment]
I don't have any idea, just  use findViewById()  :(

**Comment by loveRose** [comment]
我也遇到了，同样的问题 NullPosition

**Comment by ttcluo** [comment]
同样的问题,谁解决了，studio3.0，gradle3.0.1,黄油刀8.4.0，运行时报空指针

**Comment by clunyes** [comment]
有时候会报空，什么问题？

**Comment by kimljx** [comment]
@ttcluo 我的问题找到了，是内存泄漏的问题引起的，页面销毁解绑了控件导致持有的引用为空。这个issue可以关了

**Comment by iNoles** [comment]
You can use @Nullable on it.

**Comment by gx0609m** [comment]
> @ttcluo 我的问题找到了，是内存泄漏的问题引起的，页面销毁解绑了控件导致持有的引用为空。这个issue可以关了
能说的详细点吗
