### ISSUE TITLE
Unable to load 'com.android.builder.Version' After Upgrade Gradle version from 4.2 to 4.4

### ISSUE THREAD

**Issue by Xiaojuanmao** [JakeWharton/butterknife#1210]
Android studio force upgrade gradle version to 4.4:
<img width="1116" alt="2018-02-26 3 42 09" src="https://user-images.githubusercontent.com/9401858/36658491-b943efe4-1b0b-11e8-967e-109dc6be2f57.png">

After upgrade gradle version from 4.2 to 4.4, gradle sync failed:

<img width="1137" alt="2018-02-26 3 36 08" src="https://user-images.githubusercontent.com/9401858/36658338-0c247176-1b0b-11e8-92e1-a003371a7677.png">

project gradle : 
`classpath 'com.android.tools.build:gradle:3.0.1'`
`classpath "com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT"`
`buildToolsVersion "26.0.2"`
`compileSdkVersion 26`

Then i found some issues suggest downgrade from 9.0.0 to 8.8.1, but I got this : 
<img width="1161" alt="2018-02-26 3 46 29" src="https://user-images.githubusercontent.com/9401858/36658601-45e8f656-1b0c-11e8-93b1-8f8e59f64998.png">

Then I downgrade to 8.4.0, everything is ok

**Comment by vuongp** [comment]
I had the same issue, looks like there is a new version. https://oss.sonatype.org/content/repositories/snapshots/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/

A quick fix would be to switch to this version.
`classpath 'com.jakewharton:butterknife-gradle-plugin-9.0.0-20180212.024336-29'`

However I chose to add the jar locally in case it happens again or the above version is not available anymore.

**Comment by JakeWharton** [comment]
This is fixed on master. You can use 9.0.0-SNAPSHOT for now, as you discovered.
