### ISSUE TITLE
butterknife and realm useing together problem

### ISSUE THREAD

**Issue by hanliangel** [JakeWharton/butterknife#1212]
I add the realm as my database , but then i received null exception on the view.The binding dosen't work.
I add 
```
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
```
 into my builder.gradle ,  but not work too.
Someone can help me?

**Comment by JakeWharton** [comment]
This is a usage question and not a bug or feature request on the library. Please ask on StackOverflow with the 'butterknife' tag.
