### ISSUE TITLE
How to bind an activity view inside my adapter

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JakeWharton/butterknife#1213]
This view is in the activity (bottom navigation view), but it isn't inside the adapter item layout.

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'butterknife' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
