### ISSUE TITLE
Binding in Service class

### ISSUE THREAD

**Issue by zishanj** [JakeWharton/butterknife#1217]
I am using some string & drawable resources inside `Service` class and trying to bind it with ButterKnife. Is there any supporting `bind` for it? I have tried `ButterKnife.bind(this)` but it does not accept the Service class.

**Comment by JakeWharton** [comment]
You can reference the generated class directly which will not require a `View` but only a `Context`. It should be something like this:
```java
class MyService extends Service {
  @BindString(R.string.hello) String hello;

  @Override public void onCreate() {
    super.onCreate();
    new MyService_ViewBinding(this);
  }
}
```

**Comment by zishanj** [comment]
@JakeWharton I am unable to understand the use of `new MyService_ViewBInding(this)`. Can you please elaborate this a bit or is there any small working example?

**Comment by JakeWharton** [comment]
You might have to pass `this` twice. Here's an example in use in the tests: https://github.com/JakeWharton/butterknife/blob/5b9c6ba807480f72515c7835888f3d62e69d64a9/butterknife/src/androidTest/java/butterknife/functional/BindColorTest.java#L16-L29
