### ISSUE TITLE
ButterKnife with PagerAdapter not working

### ISSUE THREAD

**Issue by nologinatgit** [JakeWharton/butterknife#1220]
I have the following code in my Activity:

    public class DataListActivity extends SherlockFragmentActivity 
    {
      @Override
      protected void onCreate(Bundle savedInstanceState)
      {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_datalist);
        dataSwipeAdapter = new DataSwipeAdapter(values);      
        ViewPager myPager = (ViewPager) findViewById(R.id.viewpager);
        myPager.setAdapter(dataSwipeAdapter);
        myPager.setCurrentItem(0);
      }
    }

Inside the Adapter, I have this code:

    public class DataSwipeAdapter extends PagerAdapter
    {
       @Nullable @BindView(R.id.checkBoxData)
       CheckBox dataCheckbox;  
       ...
    }

In the `instantiateItem` method, I use this code:

  

    @Override
    public Object instantiateItem(View collection, int position)
    {
      LayoutInflater inflater = (LayoutInflater) collection.getContext()
        .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
      int resId = 0;
      switch (position)
      {
        case 0:
          resId = R.layout.dataList;
          break;
        case 1:
          resId = R.layout.mainList;
          break;
      }
      final View view = inflater.inflate(resId, null);
      try
      {
        if (position == 0)
        {
          ButterKnife.bind(this,view);
     
          if(dataCheckbox==null)
          {
             //it is somehow null
          }
       ...
      return view;
    }

The null check always says that my `CheckBox` is null.

What am I doing wrong?

**Comment by JakeWharton** [comment]
It's impossible to know without more information? Have you configured your build correctly? Is the view binder being generated? Can you reproduce it in a small, standalone sample?
