### ISSUE TITLE
Butterknife is not working(@BindView, @OnTextChanged etc) after adding too many drawables in a module.

### ISSUE THREAD

**Issue by sujeetsingh007** [JakeWharton/butterknife#1221]
Hi,

I was struggling with a very weird issue. I have multiple modules in my android app. I have around 250-300 images in drawable folder of one module. I was started getting error in a particular class that butterknife was not able to bind views. UI components remains null (@BindView(id) not working) and there were no callbacks in listeners (@OnTextChange(id)).

After removing a certain number of images from that module it started working fine. This is very strange for me.
Is there any limitation that butterknife can handle beyond certain number of drawable/non-drawable references? 

Thanks,

**Comment by JakeWharton** [comment]
There is no such limitation and the number of resources does not affect the library. If you can create a standalone failing sample that demonstrates this behavior I'd be happy to take a look.
