### ISSUE TITLE
unbind Exception

### ISSUE THREAD

**Issue by PiPiCaptain** [JakeWharton/butterknife#1227]
when I use mUnBinder.unbind() in BaseFragment：
`@Override
    public void onDestroyView() {
        super.onDestroyView();
        mUnBinder.unbind();
    }`
There will be a Exception：
`java.lang.IllegalStateException: Bindings already cleared.`
How I fix it？

(My English is poor, forgive me)

**Comment by PiPiCaptain** [comment]
The use of the scene is ViewPager+Fragment

**Comment by JakeWharton** [comment]
Somehow your code is calling this method twice on the same Unbinder instance. Without a full sample that reproduces the problem it's impossible to know how, though.
