### ISSUE TITLE
DexArchiveBuilderException?

### ISSUE THREAD

**Issue by gzsword** [JakeWharton/butterknife#1234]
InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.	
Stripped invalid locals information from 2 methods.	
InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.	
Invoke-customs are only supported starting with Android O (--min-api 26)	
InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.	
Stripped invalid locals information from 2 methods.	

com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\liangyj3\.gradle\caches\modules-2\files-2.1\com.squareup\javapoet\1.10.0\712c178d35185d8261295913c9f2a7d6867a6007\javapoet-1.10.0.jar	
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.	
com.android.tools.r8.CompilationFailedException: Compilation failed to complete	
com.android.tools.r8.utils.AbortException	

**com.android.tools.build:gradle:3.1.0**
**com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT
com.jakewharton:butterknife:9.0.0-SNAPSHOT
com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT
com.jakewharton:butterknife-annotations:9.0.0-SNAPSHOT**

**gradle.properties
android.enableAapt2=true
android.enableD8=true**

**Comment by JakeWharton** [comment]
JavaPoet should not be going into your APK. Your dependencies are configured incorrectly. Please follow the README for the correct configuration.
