### ISSUE TITLE
Some questions about butterknife

### ISSUE THREAD

**Issue by VernonLee** [JakeWharton/butterknife#1236]
Hi JakeWharton, I have some questions need for help:

first, why generated code in build/generated/source/apt directory, Instead of other directory? eg: inside /src。

second, how does butterknife using those generated code, combine with some activity？

My English is not very good, hope for the answer。

**Comment by JakeWharton** [comment]
We don't control where the generated code goes. The Android Gradle plugin configures the java compiler such that any code generated by an annotation processor goes into that folder.

The generated code can be referenced directly or looked up dynamically by calling `ButterKnife.bind`. If you look at the implementation of `bind`, you'll see it looks up the generated code similar to how a `LayoutInflater` loads views, with `Class.forName`.

**Comment by VernonLee** [comment]
very thankful
