### ISSUE TITLE
Butterknife and dataBinding are used together

### ISSUE THREAD

**Issue by momoc** [JakeWharton/butterknife#1241]
![qq 20180406182003](https://user-images.githubusercontent.com/8325226/38416604-cbd50064-39c7-11e8-8c71-78a527544cfa.png)
Butterknife ver 8.8.1
Butterknife and dataBinding are used together
@BindView acquisition is NULL
But DataBinding is ok
Why??? Please help me………………

**Comment by JakeWharton** [comment]
This is not sufficient information to be an actionable bug report. For example, it's not clear that you're even calling `ButterKnife.bind`. Check to see that the library is configured correctly against the README, that the generated code is showing up in build/generated/source, and that you're calling `ButterKnife.bind`. If there is still a problem when all those things are done correctly, if you can create a small, self-contained project that reproduces the issue I'll take a look.

**Comment by byrav309** [comment]
I am facing the same problem. Even after calling ButterKnife.bind it is not working.
