### ISSUE TITLE
Could not find com.jakewharton:butterknife-gradle-plugin:9.0.0-20171223.061039-23

### ISSUE THREAD

**Issue by dagostinelli** [JakeWharton/butterknife#1243]
I'm trying to use ButterKnife in a library project.  I had been happily using the work around where we reference v9 snapshot.  After a new Android Studio update came down which also included an upgrade to gradle, a little cache clearing and a rebuild, now it doesn't work.

```
classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-20171223.061039-23'
```

```
Could not find com.jakewharton:butterknife-gradle-plugin:9.0.0-20171223.061039-23.
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-20171223.061039-23.pom
    https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-20171223.061039-23.jar
    https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-20171223.061039-23.pom
    https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-20171223.061039-23.jar
    https://repo.maven.apache.org/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-20171223.061039-23.pom
    https://repo.maven.apache.org/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-20171223.061039-23.jar
```
I've tried to go to those https locations directly using the browser and there's no version 9.0 folder present.

**Comment by JakeWharton** [comment]
You have to add the Sonatype snapshot repository. The link is in the README.
```groovy
repositories {
  maven { url 'the url' }
}
```

**Comment by dagostinelli** [comment]
The readme says:

```
To use Butter Knife in a library, add the plugin to your buildscript:

buildscript {
  repositories {
    mavenCentral()
   }
  dependencies {
    classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'
  }
}

and then apply it in your module:

apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
```

**Comment by JakeWharton** [comment]
You don't need the full number. Specifying 9.0.0-SNAPSHOT is enough and it
will auto-resolve the latest.

**Comment by dagostinelli** [comment]
Ah thanks. I see that now.  Like this:

```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        // TODO remove after butterknife 9 graduates to stable
        maven {
            name 'Sonatype SNAPSHOTs';
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'
    }
}
```

**Comment by JakeWharton** [comment]
Yep!

**Comment by RoyalLachinov** [comment]
Could not find com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT.
Searched in the following locations:
    https://plugins.gradle.org/m2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
    https://plugins.gradle.org/m2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
    https://plugins.gradle.org/m2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar
    https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
    https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
    https://jcenter.bintray.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar
    https://repo.maven.apache.org/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
    https://repo.maven.apache.org/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
    https://repo.maven.apache.org/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar
    https://maven.google.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
    https://maven.google.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
    https://maven.google.com/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar
    https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/maven-metadata.xml
    https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.pom
    https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/9.0.0-SNAPSHOT/butterknife-gradle-plugin-9.0.0-SNAPSHOT.jar

**Comment by RoyalLachinov** [comment]
@JakeWharton  When onLick the urls, The requested path was not found. shows on webpage

**Comment by RoyalLachinov** [comment]
the plugin version is :         classpath 'com.android.tools.build:gradle:3.0.1'
and gradle is 4.4
