### ISSUE TITLE
Snapshot 9.0.0 error: Unable to parse @BindView binding. probably due to changes in RScanner

### ISSUE THREAD

**Issue by vashisthg** [JakeWharton/butterknife#1254]
From monday morning today my project which uses Snapshot 9.0.0 (because of https://github.com/JakeWharton/butterknife/issues/1200) has started to not compile. The issue is with kotlin classes having butterknife annotations.
I believe the issue is with some latest changes on Snapshot 9.0.0, probably due to changes in RScanner https://github.com/JakeWharton/butterknife/pull/1244/files cc @kageiit .  The compiler error is as follows

``` 
Unable to parse @BindView binding.
...

java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to com.sun.tools.javac.code.Symbol$VarSymbol
        at butterknife.compiler.ButterKnifeProcessor$RScanner.visitSelect(ButterKnifeProcessor.java:1356)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
```

**Comment by vashisthg** [comment]
Also I am forced to use 9.0.0 snapshot due to https://github.com/JakeWharton/butterknife/issues/1200

**Comment by vashisthg** [comment]
@kassim What do you mean?

**Comment by sagix** [comment]
Same in my project, a NPE is thrown from in RScanner:1356

`e:MyFragment.java: error: Unable to generate view binder for @OnTextChanged.
    void onAfterEmailChanged(Editable editable) {
         ^
  
  java.lang.NullPointerException
  	at butterknife.compiler.ButterKnifeProcessor$RScanner.visitSelect(ButterKnifeProcessor.java:1356)
  	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at com.sun.tools.javac.tree.TreeScanner.visitAssign(TreeScanner.java:231)`

**Comment by kassim** [comment]
Sorry, I had assumed one of those snapshots would be before the break, when in fact that last one (33) is when it first broke. Anyway, I've found some old cached versions in this directory `/Users/kassim/.gradle/caches/modules-2/files-2.1/com.jakewharton` (replace `kassim` with your user name)

**Comment by sagix** [comment]
I rollback to the 33th snapshot and it works again
Here the three specific versions you need to apply:
`
classpath "com.jakewharton:butterknife-gradle-plugin:9.0.0-20180411.055514-33"
implementation "com.jakewharton:butterknife:9.0.0-20180411.055505-33"
kapt "com.jakewharton:butterknife-compiler:9.0.0-20180411.055511-33"`

**Comment by kassim** [comment]
ah cool, I switched mine to 33 but it was failing but perhaps I had accidentally broken something else in my code 🤦‍♂️ 

Thanks @sagix

**Comment by kageiit** [comment]
@vashisthg @sagix can you please post a small snippet of code that has this issue? Will help in creating a repro/test case and to fix it

**Comment by kassim** [comment]
For me it was in Kotlin classes which referenced R2 (Butterknife plugin generated) IDs

**Comment by sagix** [comment]
@kageiit Thanks it's fixed with the 37th snapshot

**Comment by vashisthg** [comment]
@kageiit Fixed for me too. Thanks
