### ISSUE TITLE
  Caused by: java.lang.IllegalStateException: Required view 'rv_content' with ID 2131297021 for field 'rvContent' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

### ISSUE THREAD

**Issue by lovelyYakir** [JakeWharton/butterknife#1262]
i use my code to bind layout ,like this.

@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
@Documented
public @interface BindLayout {
    @LayoutRes
    int value();
}
－－－－－－
public final class AlexBind {
 private static void bindActivityLayout(Activity activity) {
        Class aClass = activity.getClass();
        BindLayout annotation = (BindLayout) aClass.getAnnotation(BindLayout.class);
        if (annotation != null) {
            activity.setContentView(annotation.value());
            ButterKnife.bind(activity);
        }
    }
}
－－－－－－－
@BindLayout(R.layout.activity_team_report_from)
public class TeamReportFromActivity extends SuperBaseActivity {
 　@BindView(R.id.rv_content)
    RecyclerView rvContent;
    @BindView(R.id.rl_bottom)
    RelativeLayout rlBottom;
    @BindView(R.id.left_btn)
    FrameLayout leftBtn;
    @BindView(R.id.title_name)
    TextView titleName;
    @BindView(R.id.iv_author)
    ImageView ivAuthor;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        AlexBind.bindActivity(this);
｝
.....}
－－－－－－－
but,huawei make error.

 Caused by: java.lang.IllegalStateException: Required view 'rv_content' with ID 2131297021 for field 'rvContent' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

**Comment by JakeWharton** [comment]
This is what happened when findViewById returns null for a view ID you have requested. It is not a problem with the library. Either the view isn't available in that configuration, you've inflated the wrong layout, or there's a severe bug in the device.

**Comment by nik1784** [comment]
thanks brother
