### ISSUE TITLE
Android component-based use

### ISSUE THREAD

**Issue by jingzhanwu** [JakeWharton/butterknife#1266]
The way to solve Application and Library at the same time is the way R and R2 are introduced, which is inconvenient to switch between R and R2 when the same Module switches under Application and Library under the component mode. Are there any solutions introduced by R, whether Application or Library?

**Comment by JakeWharton** [comment]
I don't really understand the question. R2 is required since the R IDs are non-final in library projects. And R2 should only be used in the annotations because they intentionally do not correspond to the values of their R ID counterparts.

**Comment by jingzhanwu** [comment]
我的意思就是application 和 library形式的Module中能不能统一都使用R或者R2?

**Comment by jingzhanwu** [comment]
I mean, can application and library Module be used in R or R2?

**Comment by JakeWharton** [comment]
You can use either R or R2 in an application module. It should not make a difference. For a library module you must use R2.
