### ISSUE TITLE
java.lang.NullPointerException'

### ISSUE THREAD

**Issue by gargacharya** [JakeWharton/butterknife#1267]
I am using the butterknife to bind views in my application but I am getting null-pointer exceptions in my app. How can a view becomes null if I already bind it using butterknife in onCreate of the activity.

Is this a known issue? Is any fix for this is released? Please help me out with this.

**Comment by JakeWharton** [comment]
It's not clear what's happening here so it's impossible to provide a recommendation. If you can provide a failing test case or executable sample that demonstrates the problem then it will be easier to diagnose the problem, if any. Best guess without seeing any code is that you are accessing views before onCreate, you are accessing after calling `unbind()`, or the generated isn't being generated and so the fields always remain null.
