### ISSUE TITLE
Lint Warning: declaration access can be weaker 

### ISSUE THREAD

**Issue by Madonahs** [JakeWharton/butterknife#1269]
I am currently Inspecting my code and Lint gave me this warning, so i went ahead and accepted the correct access level which is private. 

**Lint Warning**
![sample](https://user-images.githubusercontent.com/11560987/39685060-9ba99438-5185-11e8-9e7b-c550ccd5f69e.PNG)

**Granted Private Access Level.**

![afterpost](https://user-images.githubusercontent.com/11560987/39685107-d556c606-5185-11e8-8709-f4c91a76d584.PNG)

**> The Error I got**

![erroe](https://user-images.githubusercontent.com/11560987/39685170-3c88723e-5186-11e8-8340-699aabfbdc01.PNG)

So I bet my question is should i just ignore the Lint warning, I have 67 warning. :)

**Comment by JakeWharton** [comment]
The warning shouldn't occur because a class is generated which accesses those fields. I'll take a look at some point...

**Comment by Madonahs** [comment]
Thank you, will appreciate.

**Comment by JakeWharton** [comment]
I can't reproduce this. The generated code is in the same package and prevents the warning for me.

If you can supply a small project that demonstrates the problem I'd be happy to have a look.

**Comment by Madonahs** [comment]
Thanks, I was able to fix it.
