### ISSUE TITLE
Multiple items inside adapter

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JakeWharton/butterknife#1274]
I know how to use butterknife with one itemView, but I don't know how to use if I have multiple itemViews.

It crashes because it can't bind the views. How can I bind them?

**Comment by JakeWharton** [comment]
Each item should be bound to a view holder keyed by index and not to an enclosing object. RecyclerView forces this, for example, if you need a pattern to look at. This isn't specific to Butter Knife. If you tried calling `findViewById` you'd have the same problem.
