### ISSUE TITLE
Content is not allowed in prolog VER 8.8.1

### ISSUE THREAD

**Issue by powellbird** [JakeWharton/butterknife#1281]
Good afternoon, Butterknife is excellent, lately when compiling my project of android studio it marks me the following error

The content is not allowed in the prologue.
Failed to capture snapshot of input files for task ': app: javaPreCompileDebug' property 'annotationProcessorConfiguration' during up-to-date check.
Could not resolve com.jakewharton: butterknife-compiler: 8.8.1.

**Comment by JakeWharton** [comment]
Looks like you're missing `mavenCentral()` in your `repositories` block. Without more information it's impossible to diagnose.
