### ISSUE TITLE
how to use butterknife in small plug ,using BindView in the app module  but the view appears NullPointerException

### ISSUE THREAD

**Issue by zhijinjin** [JakeWharton/butterknife#1286]
I use it
project  gradle
  dependencies {
        ......
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'
    }

library
  apply plugin: 'com.android.library'
  apply plugin: 'com.jakewharton.butterknife'

**Comment by JakeWharton** [comment]
This is not enough information for an actionable report. The README and sample in the repo show a working setup.

If you have a setup that isn't working please create an executable sample or failing test case that demonstrates the problem so that it can be debugged.
