### ISSUE TITLE
Use butterknife with Android Gradle Plugin version 3.1.+  cannot compile ~

### ISSUE THREAD

**Issue by iceyang1989** [JakeWharton/butterknife#1293]
env:
butterknife  version  8.4.0
android gradle plugin 3.1.3

error:
Could not get unknown property 'packageForR' for task ':xxxxxxDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.

**Comment by wenbinke** [comment]
No need to use butterknife in android project, butterknife is deprecated. 
https://kotlinlang.org/docs/tutorials/android-plugin.html

**Comment by JakeWharton** [comment]
Oh wow that's news to me! I guess I'm off the hook from responding to all these bugs and feature requests. See you all at the bar!

**Comment by wenbinke** [comment]
@JakeWharton Yes, you can announce the news to all the developers and tell them move to Kotlin Android Extensions. I have taken a lot of time to remove butterknife from a project. And now I am seeing another guy use butterknife+MVP in another project.

**Comment by JakeWharton** [comment]
Oh I didn't realize you had a sample size of a whole 2 people. I thought it was only 1. I'm doubly convinced.

**Comment by wenbinke** [comment]
@JakeWharton Yes, but did you see my links on the second comment? You can compare them by yourself.

use butterknife
```
class ExampleActivity extends Activity {
  @BindView(R.id.txtWelcome) EditText txtWelcome;
  @BindString(R.string.welcome) String welcomeMessage;

  @OnClick(R.id.submit) void submit() {
    // TODO call server...
  }

  @Override public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_example);
    ButterKnife.bind(this);
    txtWelcome.text = welcomeMessage;
  }
}
```

use kotlin extension
```
import kotlinx.android.synthetic.main.activity_example.*

class ExampleActivity: Activity {
  override fun onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_example)

    txtWelcome.text = resources.getString(R.string.welcome);
    submit.setOnClickListener {
       // TODO call server...
    }
  }
}
```

**Comment by wenbinke** [comment]
kotlin-android-extensions is better for Kotlin. ButterKnife is also good but kotlin-android-extensions is a better and smart choice.
https://stackoverflow.com/questions/46482018/kotlin-android-view-binding-findviewbyid-vs-butterknife-vs-kotlin-android-exten

**Comment by JakeWharton** [comment]
Kotlin extensions are worse, sorry. Now please stop commenting.

**Comment by JakeWharton** [comment]
Using version 9.0.0-SNAPSHOT is required for AGP 3.1 and newer as they made a breaking change to the API that the Gradle plugin relies on. Instructions for accessing the snapshot are in the README.
