### ISSUE TITLE
Butterknife with androidx

### ISSUE THREAD

**Issue by MatyasK** [JakeWharton/butterknife#1296]
I'm using the androidx support library, but I receive this error:

error: package android.support.annotation does not exist |  

I looked at the generated file from Butterknife and it tries to use old support library.

How can I fix this?

edit: I just saw this was implemented 11 days ago, I'm on the latest version but still getting this error...

**Comment by JakeWharton** [comment]
The latest version being 9.0.0-SNAPSHOT?

**Comment by marcin-kozinski** [comment]
I'm not working with Matyas nor using the same project, just an unrelated person with the same (similar?) problem.

I tried migrating our project to AndroidX, and yes bumped Butter Knife to 9.0.0-SNAPSHOT. The build still failed for me.

I am using Butter Knife in a library module, using the `butterknife-gradle-plugin` and the error I've seen was in the library's `R2.java` file. Has this been by any chance missed in the recent PR or should this work as well?

**Comment by MatyasK** [comment]
I was using the 8.1.1 but with the snapshot version is working fine. Thank you!

**Comment by k4dima** [comment]
repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    implementation 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'

**Comment by Harshada22** [comment]
Its still not working.
Same tried with android.support,It works fine. But not giving support to androidx
