### ISSUE TITLE
@OnClick used with @IdRes Java arrays

### ISSUE THREAD

**Issue by soshial** [JakeWharton/butterknife#1298]
If I use it this way:

    @IdRes
    final int[] tabs = {R.id.tvDataProgress, R.id.tvDataToday, R.id.tvDataOverall};
    
    @OnClick(tabs)
    public void onClick(View view) {...};

Then Android Studio compile error `Attribute value must be constant`.
PS. I am **not** using a library project.

**Comment by JakeWharton** [comment]
You're missing `static` on the field, although I can't guarantee that'll work. This is a problem with `javac` and not this library. `javac` limits how values can make it into annotations and you have to adhere to its restrictions.

**Comment by soshial** [comment]
Adding `static` to it still produces this error about constant value.
