### ISSUE TITLE
在华为笔记本上使用插件，显示窗口中的条目特别窄，

### ISSUE THREAD

**Issue by qianqingke** [JakeWharton/butterknife#1299]

**Comment by JakeWharton** [comment]
Based on the Google translate of the issue title, I don't see how this is a butterknife issue. It doesn't affect your layouts, it only binds the reference to fields.

**Comment by qianqingke** [comment]
哦，谢谢，应该是AndroidStudio工具的问题，或者是电脑的分辨率太高，不兼容导致的问题，我使用旧的电脑是没问题的。
