### ISSUE TITLE
Build Failed:8.8.1 ,gradle:3.2.0-alpha14

### ISSUE THREAD

**Issue by srohith900** [JakeWharton/butterknife#1304]
repositories { 
google() 
jcenter() 
mavenCentral() 
} 
dependencies 
{ 
classpath 'com.android.tools.build:gradle:3.2.0-alpha14' 
classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'  
}

Unable to find method 'com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;'.

**Comment by maxxx** [comment]
same with 3.1.3
classpath 'com.android.tools.build:gradle:3.1.3'

**Comment by JakeWharton** [comment]
9.0.0-SNAPSHOT is required for AGP 3.1 or newer as they broke API compatibility.
