### ISSUE TITLE
error observation If this view is optional add '@Nullable' (fields) or '@Optio

### ISSUE THREAD

**Issue by leandro1995** [JakeWharton/butterknife#1309]
good how was trying butterknife for a project in kotlin and I missed something that when I added an id to my editext butternif I did not recognize it because it did not exist provando several ways I decided to clean my project and recognized it when I deleted the id editext volvi to execute the project but this time I said that it was not the id that I deleted from my editext even deleting the BindView and everything clean came back to clean the project and I saw it I recognized it without problem I do not know if it happened in java but in kotlin it has happened to me I know if it's a problem of my code or of the library I wanted to get rid of that duta

**Comment by JakeWharton** [comment]
If you are using Kotlin it should be sufficient to mark the type as nullable which will put the `@Nullable` annotation into the bytecode.

If you believe there is a problem with the library please provide a failing test case or executable sample that demonstrates the problem. It's far from clear what you are seeing.
