### ISSUE TITLE
使用butterKnife7.0，控件绑定后，使用时报空指针

### ISSUE THREAD

**Issue by wisesoftym** [JakeWharton/butterknife#1313]

**Comment by JakeWharton** [comment]
This is not enough information for an actionable bug report. Butter Knife 7.0 is extremely old, though, which only makes it harder to understand what is going on.

If you are using the latest version and have a failing test case or executable sample that demonstrates the failure I can take a look, but without that there isn't much I can do except to say that ensure you have configured it properly and that the generated code is making it into your APK.
