### ISSUE TITLE
AndroidX migration problem with support-annotations

### ISSUE THREAD

**Issue by farhad** [JakeWharton/butterknife#1314]
I've added the 8.8.1 version of butterknife and its annotation processor. Today after migrating my project to AndroidX artifacts, the project build cannot succeed, due to not being able to find `com.android.support:support-annotation` package.

**Comment by JakeWharton** [comment]
AndroidX support is on `master` only. You can use 9.0.0-SNAPSHOT. Note that there's still a problem with listeners #1307 and the Gradle plugin for library projects #1300.

**Comment by Sinapse87** [comment]
Hi, has AndroidX support officially released or is the snapshot production ready?
