### ISSUE TITLE
Android X Compatibility

### ISSUE THREAD

**Issue by gelodgreat** [JakeWharton/butterknife#1318]
Is this compatible with android x right now?

**Comment by JakeWharton** [comment]
No. See #1300 and #1307.

**Comment by getsadzeg** [comment]
What about now?

**Comment by JakeWharton** [comment]
Yes. See #1300 and #1307.

**Comment by getsadzeg** [comment]
Thanks, but is it included in 8.8.1 version of Butterknife?

**Comment by JakeWharton** [comment]
Nope

**Comment by getsadzeg** [comment]
I'll hope we'll get the release soon.
