### ISSUE TITLE
NoSuchMethodException  butterknife.ButterKnife.findBindingConstructorForClass

### ISSUE THREAD

**Issue by ashraf-atef** [JakeWharton/butterknife#1321]
**Fatal Exception: java.lang.RuntimeException
Unable to start activity** ComponentInfo{com.tawseela.eazyapp/com.tawseela.eazyapp.common.presentationlayer.activity.loginRegistrationActivity.GettingStartedActivity}: java.lang.RuntimeException: Unable to find binding constructor for com.tawseela.eazyapp.common.presentationlayer.activity.loginRegistrationActivity.GettingStartedActivity

android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2984)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3045)
android.app.ActivityThread.-wrap14 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1642)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)

**Caused by java.lang.RuntimeException
Unable to find binding constructor for** com.tawseela.eazyapp.common.presentationlayer.activity.loginRegistrationActivity.GettingStartedActivity
butterknife.ButterKnife.findBindingConstructorForClass

butterknife.ButterKnife.findBindingConstructorForClass (ButterKnife.java:237)
butterknife.ButterKnife.createBinding (ButterKnife.java:191)
butterknife.ButterKnife.bind (ButterKnife.java:124)
com.tawseela.eazyapp.common.presentationlayer.activity.baseActivity.BaseActivity.onCreate (BaseActivity.java:58)
com.tawseela.eazyapp.common.presentationlayer.activity.loginRegistrationActivity.GettingStartedActivity.onCreate (GettingStartedActivity.java:45)
android.app.Activity.performCreate (Activity.java:6956)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)

**Caused by java.lang.NoSuchMethodException**
<init> [class com.tawseela.eazyapp.common.presentationlayer.activity.loginRegistrationActivity.GettingStartedActivity, class android.view.View]
butterknife.ButterKnife.findBindingConstructorForClass

java.lang.Class.getConstructor0 (Class.java:2204)
java.lang.Class.getConstructor (Class.java:1683)
**butterknife.ButterKnife.findBindingConstructorForClass (ButterKnife.java:231)**
butterknife.ButterKnife.createBinding (ButterKnife.java:191)
butterknife.ButterKnife.bind (ButterKnife.java:124)
com.tawseela.eazyapp.common.presentationlayer.activity.baseActivity.BaseActivity.onCreate (BaseActivity.java:58)
com.tawseela.eazyapp.common.presentationlayer.activity.loginRegistrationActivity.GettingStartedActivity.onCreate (GettingStartedActivity.java:45)
android.app.Activity.performCreate (Activity.java:6956)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)

**Device**
Brand: samsung
Model: SM-G610F
Orientation: Portrait
RAM free: 429.64 MB
Disk free: 1.99 GB

**Operating System**
Version: 7.0
Orientation: Portrait
Rooted: No

**Comment by JakeWharton** [comment]
And is that class and its constructor in your APK? You can check with APK Inspector in Android Studio.
