### ISSUE TITLE
Use Japicmp to validate API of reflect module

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/butterknife#1332]
It needs to be binary compatible with the traditional, `Class.forName`-based module.

**Comment by JakeWharton** [comment]
Started writing functional tests which use variants to test both frontends. That's effectively the same thing (technically we only need source compatibility anyway). Any bugs are missing tests, and there's a lot of missing test coverage...

**Comment by pepegiu** [comment]
Le mar. 11 sept. 2018 à 21:41, Jake Wharton <notifications@github.com> a
écrit :

**Comment by pepegiu** [comment]
Le mer. 12 sept. 2018 à 02:07, Giuseppe Pirrera <pepi290285@gmail.com> a
écrit :
