### ISSUE TITLE
cannot find method arrayOf or listOf in Utils on version 8.8.1 

### ISSUE THREAD

**Issue by asugar** [JakeWharton/butterknife#1352]
this is error happened in my two project from 2018.9.7.i use grale below:
compile "com.jakewharton:butterknife:8.8.1"
kapt "com.jakewharton:butterknife-compiler:8.8.1"
the error can be fixed by used:
compile "com.jakewharton:butterknife:9.0.0-SNAPSHOT"
kapt "com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT"
i am curious to know why it happen in 8.8.1. this is error log
错误: 找不到符号
符号:   方法 arrayOf(TextView,TextView,TextView,TextView,TextView)
位置: 类 Utils

**Comment by JakeWharton** [comment]
It's definitely in 8.8.1: https://github.com/JakeWharton/butterknife/blob/8.8.1/butterknife/src/main/java/butterknife/internal/Utils.java#L52-L60

**Comment by asugar** [comment]
sorry, it is my fault. in my other module used butterknife 9.0.9-SNAPSHOT,but my app used butterknife-compiler:8.8.1，so happen that error. sorry again
