### ISSUE TITLE
9.0.0-SNAPSHOT mandatory use Gradle 4.6 on AndroidStudio 3.1.x

### ISSUE THREAD

**Issue by lx0758** [JakeWharton/butterknife#1353]
Reproduce steps:

1. Reference compilation plugin
`classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'`

2.build or sync project, report an error
```
Minimum supported Gradle version is 4.6. Current version is 4.4.

Please fix the project's Gradle settings.
Fix Gradle wrapper and re-import project
Gradle settings
````

Although upgrading Gradle is not a problem, the SDK and dependencies are required to be upgraded after the upgrade. It has caused me some trouble.

**Comment by benjaminglatzeder** [comment]
If I may ask did you run into these gradle build errors:

> The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

and

> The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

If so, how did you fix them please?

````
android {
    flavorDimensions "versionCode"
    compileSdkVersion 27
    buildToolsVersion '28.0.2'
    defaultConfig {     
        applicationId "com.appid"    
        minSdkVersion 21  
        targetSdkVersion 27  
        versionCode 1234  
        versionName "1.2.3.4"  
        multiDexEnabled true  
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"  
    }
...
}
````

I already had these values set in the defaultConfig in the gradle file. They only appear in the merged manifest.
