### ISSUE TITLE
Is there any elegant solution for runtime binding and reading strings from config file retrieved from backend?

### ISSUE THREAD

**Issue by MohamedISoliman** [JakeWharton/butterknife#1359]
I know that Butterknife is using generated code to bind string to the proper views via annotations ..
currently we have a requirement that all strings of the app will be retrieved from the backend, we already using Butterknife for binding the strings.
my question is there any way to make Butterknife read from singleton that have the retrieved strings .. so we don't have change the bindings code.
if no, is there any elegant solution so we doesn't break the current implementation and minimize the effort to migrate to the new technique.

**Comment by JakeWharton** [comment]
Not really, no. You can write your own annotation processor and use a different annotation like `@DynamicString` with whatever keys you are using in it. Android doesn't provide a hook into `Resources` so there's no way to intercept loading.
