### ISSUE TITLE
ButterKnife sometimes stops working on Android 8.x

### ISSUE THREAD

**Issue by nightmaregiba** [JakeWharton/butterknife#1367]
Hi, 
Thanks for great library! I have used ButterKnife for 2 years but recently I have had a problem on Android 8. When I am in Activity A, I start Activity B and finish Activity B, then start Activity B and finish Activity B again and again. Sometimes @OnClick in all Activities doesn't work anymore. It is really weird because it just happens in some devices such as Nokia X6 (Android 8.1), Xiaomi Note 5 (Android 8.1) and really hard to reproduce.

```
// This function is not called anymore
@OnClick({R.id.btn1, R.id.btn2})       
public void onViewClick(View v) {
    switch (v.getId()) { 
       // Handle clicks
    }
}
```

Can anyone help? Thanks in advance!

**Comment by nightmaregiba** [comment]
I have found the cause:
In Activity B, I have `mHandler.postDelayed(mRunnable, 2000)` and if I quickly finish Activity B (< 2000ms), this will cause ButterKnife @OnClick stop working!

So I put `mHandler.removeCallbacksAndMessages(null)` and everything works well

**Comment by rohankandwal** [comment]
It is happening for me too, tried your solution @nightmaregiba , it does help. However, it is happening for me if I am using GreenRobot's EventBus sticky event.

```
final Handler handler = new Handler();
						handler.postDelayed(() -> {
							final BookingGroupEvent groupEvent = new BookingGroupEvent();
							groupEvent.groupId = bookingGroupSelectionRecyclerAdapter.selectedGroupId;
							groupEvent.groupName = bookingGroupSelectionRecyclerAdapter.selectedGroupName;
							EventBus.getDefault().postSticky(groupEvent);

							handler.removeCallbacksAndMessages(null);
							}, 5000);

						setResult(RESULT_OK, intent);
						finish();
```

If I pass Sticky event directly, the click stops working on the entire app. Using handler also caused this issue but after adding removeCallbacksAndMessages, the clicks have started working again. It is happening on Pixel devices too.

@JakeWharton This might be a bug, let me know if more information is needed.
