### ISSUE TITLE
kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by WangZhilinIT** [JakeWharton/butterknife#1368]
I got this exception after updated ViewPager

**Comment by JakeWharton** [comment]
It's not clear why you think this is a butterknife issue.

**Comment by rcd27** [comment]
Well, I have the same. This is the code to make it more clear:
```
class VehicleDetailsViewBinder(root: View) {

    @BindView(R.id.carsVinValue)
    lateinit var vin: TextView

    init {
        ButterKnife.bind(root)
    }
...
    private fun showVehicleDetails(vehicle: Vehicle) {
        vin.text = vehicle.vin
    }
```

When calling `showVehicleDetails(..)` I've got `lateinit property vin has not been initialized` exception.

After debugging Butterknife `bind(View)` method, I've figured out that it finds `Framelayout` constructor is null and returns `Unbinder.EMPTY`:

```
...
Constructor<? extends Unbinder> constructor = findBindingConstructorForClass(targetClass);

    if (constructor == null) {
      return Unbinder.EMPTY;
    }
...
```

Further debugging leads to `findBindingConstructorForClass` method where:
```
if (clsName.startsWith("android.") || clsName.startsWith("java.")
        || clsName.startsWith("androidx.")) {
      if (debug) Log.d(TAG, "MISS: Reached framework class. Abandoning search.");
      return null;
    }
```
