### ISSUE TITLE
No resource identifier found for attribute 'appComponentFactory' in package 'android'

### ISSUE THREAD

**Issue by ooftf** [JakeWharton/butterknife#1370]
9.0.0-SNAPSHOT   This error will occur.

**Comment by JakeWharton** [comment]
You need to compile against API 28

**Comment by JakeWharton** [comment]
The library doesn't target 28, it compiles against 28. You can compile
against 28 while still targeting 27.

**Comment by rdugue** [comment]
Hi, I appreciate the quick response on this.

Unfortunately I am realizing now that I misspoke when I said "target"
when what I mean is that currently this project currently cannot compile
against 28. I've tried to push for a move to API 28 but it is ultimately
out of my control. Would you have any suggestion that doesn't involve
removing Butterknife from the entire project? Again, open to all
suggestions.

Thanks for your time.

**Comment by JakeWharton** [comment]
BK 9 supports AndroidX 1.0 and support library 28 which requires
compilation against API 28. Compiling against the latest is usually always
required.

**Comment by rdugue** [comment]
Jake I’m with you 100%, but we are an SDK in another eco system and they
won’t budge. It has put us in a really tough spot. Any chance you can
help us for this short term fix while the other partner gets 28 on the
road map? I've tried downgrading to a version below 9, but I always run
into issue #1130. I'm just looking for any option that doesn't mean
refactoring a fairly large library project. I’m getting killed by the
client here…

Thanks again for the feedback.

**Comment by JakeWharton** [comment]
You are free to fork the project and make any necessary changes to support
your use case.
