### ISSUE TITLE
Butterknife Gradle Plugin + AGP 3.3 Alpha 12 fails due to R.jar generation

### ISSUE THREAD

**Issue by ParthPadg** [JakeWharton/butterknife#1377]
Using AGP 3.3 alpha 12 with `android.enableSeparateRClassCompilation = true` and Butterknife's Gradle plugin 9.0.0-SNAPSHOT causes a build error. 

On my machine, it generates the following while compiling a module: 

```
Failed to capture fingerprint of input files for task ':august-commons:generateDebugR2' property '$1' during up-to-date check.
> Could not get file details of /Users/parthpadgaonkar/luna/august-commons/build/intermediates/compile_only_not_namespaced_r_class_jar/debug/generateDebugRFile/R.jar/com/august/luna/commons/R.java: could not stat file (errno 20: Not a directory)
```

I suspect this is due to 3.3a12's new R.jar generation, since if you set `enableSeparateRClassCompilation=false`, everything compiles just fine. 

cc @kageiit

**Comment by gildor** [comment]
The same problem with 9.0.0-Rc1

**Comment by cdongieux** [comment]
I have the same problem with AS 3.3 Beta2 and Butterknife 9.0.0-rc1.
