### ISSUE TITLE
Bindings already cleared

### ISSUE THREAD

**Issue by Youngjim77** [JakeWharton/butterknife#1379]
it will crash at using FragmentStatePagerAdapter(but not FragmentPagerAdapter)
There will be a Exception：
java.lang.IllegalStateException: Bindings already cleared.

and i use mUnBinder.unbind() in BaseFragment
@Override public void onDestroyView() { 
super.onDestroyView(); 
if ( mUnBinder!=null){
mUnBinder.unbind();} 
}

**Comment by pumba210** [comment]
J
