### ISSUE TITLE
Butter Knife compiler 9.0.0-rc1 conflicts with Squidb annotation processor 

### ISSUE THREAD

**Issue by lpellegr** [JakeWharton/butterknife#1387]
I have an Android app written in Java that makes use of [Squidb](https://github.com/yahoo/squidb) as described in the [_Getting Started_ readme](https://github.com/yahoo/squidb#getting-started). 

Recently, I wanted to use Butter Knife. Since the app relies on AndroidX, I followed the [README](https://github.com/JakeWharton/butterknife#download) with version _9.0.0-rc1_. Unfortunately, when I compile the app I am getting errors about Squidb auto-generated models which are not found. 

As a quick test, I commented the following line:

```
annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-rc1'
```

Upon recompilation, Squidb models are generated when Butter knife annotation processor is disabled.

The app also makes use of other annotation processors (androidx, glide) with no problems.

I am not 100% sure that the problem comes from Butter knife but since the problem only appears when I enable its annotation processor, there may be something related.

**Comment by buttplugz12** [comment]
Sorry I just woke up

**Comment by JakeWharton** [comment]
Can you provide a sample that reproduces the issue? There's not really any information here to base anything on.

**Comment by Grohden** [comment]
I'm getting this error too after using the `migrate to AndroidX`:
```
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:19:5-137:19 to override.
```
As you see, the error message is the most helpful message i've seen in my life.
I had to comment every dependency on my project to find that commenting this two:
```
implementation "com.jakewharton:butterknife:9.0.0-rc1"
kapt "com.jakewharton:butterknife-compiler:9.0.0-rc1"
```

Made the build/sync work again, but i need the butterknife for old sources..
So i just changed to the `8.8.1` version:
```
implementation "com.jakewharton:butterknife:8.8.1"
kapt "com.jakewharton:butterknife-compiler:8.8.1"
```
And the build/sync started to work again \o/

**Comment by JakeWharton** [comment]
The message is pretty clear to me. You have both the new androidx and support libraries being put in the APK which means you don't have jetifier configured properly or it would have replaced the old support library dependency with the androidx one.

**Comment by Grohden** [comment]
@JakeWharton my `gradle.properties` is with jetfier enabled (by the migration tool):
```
android.android.enableJetifier=true
android.useAndroidX=true
```
The `migrate to AndroidX` tool migrated the support libs to the x ones for me.. and enabling the jetfier should solve some problems with libraries using the support libs (i think)

**Comment by JakeWharton** [comment]
Should be `android.enableJetifier=true`

**Comment by Grohden** [comment]
:o damn... middle mouse click for pasting...
now i'm getting 'Invalid byte of the UTF-8 sequence of byte 3', but is probably not related to butterknife
Thx for seeing that.. 9.0.0-rc1 works

**Comment by zhupengxiang** [comment]
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-25:19 to override.

**Comment by voghDev** [comment]
This also happened to me with butterknife 10.0.0. Another quick way to remove the error message was downgrading to 9.0.0. My project is now working fine :)
