### ISSUE TITLE
findBindingConstructorForClass does not cache null result returned when there are no bindings

### ISSUE THREAD

**Issue by maciej-kaznowski** [JakeWharton/butterknife#1388]
If there are no bindings in a class, but `Butterknife.bind()` is called, then it will go through `findBindingConstructorForClass` without storing the null result in the binding cache:

> D/ButterKnife: Looking up binding for com.innercirclesoftware.reddit.shared.ui.RecyclerViewSpinnerPopupAdapter$ViewHolder
> D/ButterKnife: Not found. Trying superclass com.innercirclesoftware.reddit.shared.base.BaseViewHolder
> D/ButterKnife: Not found. Trying superclass android.support.v7.widget.RecyclerView$ViewHolder
> D/ButterKnife: MISS: Reached framework class. Abandoning search.

This can happen when for example you add the `Butterknife.bind() `call to a base class which you extend from, to decrease boilerplate. Therefore, I think it would make sense to store null in the BINDINGS Map since this could be invoked many times, and is extremely expensive. For me it causes a significant lag (500ms) when attempting to bind ~20 Views with no bindings. 

Currently `Butterknife.BINDINGS` uses a `LinkedHashMap` which doesn't allow null, so it would have to be replaced to support this.

**Comment by JakeWharton** [comment]
PR for this would be welcome

**Comment by JakeWharton** [comment]
Merged as e9c1533e2af2b26bf26ce13c139ae6ffdeb3a7c5
