### ISSUE TITLE
butterknife & ConstraintLayout  doesn't work

### ISSUE THREAD

**Issue by jianlin00000** [JakeWharton/butterknife#1390]
I'm trying to use both contraint library and butterknife like that:
implementation 'com.android.support.constraint:constraint-layout:1.1.3'
implementation 'com.jakewharton:butterknife:8.8.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'

When I do that operation "Generate ButterKnife Injections" with the layout ,it doesn't work and there is no tips or logs. But when I do with the same operation which layout doesn't use ConstraintLayout it works. I can't find the problem,please help.

**Comment by JakeWharton** [comment]
Sounds like you're talking about https://github.com/avast/android-butterknife-zelezny, not this project.

**Comment by jianlin00000** [comment]
yeah,I have got it wrong, thank you for your mind
