### ISSUE TITLE
Make ButterKnife accept a Context to load Resources on ViewModels

### ISSUE THREAD

**Issue by feinstein** [JakeWharton/butterknife#1394]
With the new Android Architecture Components in Jetpack, there is a greater separation between the Activities and Fragments, from the code that modifies them. The ViewModel very often need access to `String` resources and `@BindString` is very useful.

It would be most welcome to have a `@BindString` inside an `AndroidViewModel` which is a `ViewModel` that gets an `Application` on the constructor.

This `bind(object, context)` method could only accept Resources annotations, such as `@BindString`, and generate errors if it finds `@BindView` annotations.

**Comment by JakeWharton** [comment]
This already works if you reference the generated code directly, for what it's worth. The constructor won't require a `View` if there's no view bindings.

**Comment by feinstein** [comment]
So I could make a `ButterKinfe.bind(this, null)` and it will work? Where would it get the `resource` from then?

**Comment by JakeWharton** [comment]
No, you have to reference the generated code directly.

**Comment by feinstein** [comment]
> The constructor won't require a View if there's no view bindings.

Got it, so you mean the generated code constructor, such as:

    MyClass_ViewBinding(MyClass target, View source) 

I got a bit confused on which constructor where you talking about.

I will use this for now, but I think an extra `bind()` method would be useful for this.

**Comment by JakeWharton** [comment]
Maybe. It introduces yet another place where a runtime failure could occur
which undermines the safety that the generated code otherwise provides.
Currently calls to bind will always succeed regardless of your use of view
bindings. That is not true of your proposal.

**Comment by feinstein** [comment]
But can't this be validated at compile time by the code generator? 

Currently `ButterKnife.bind()` has methods for `Activity`, `View` and `Dialog`, if we pass a `Context`, like an `Application` class, that not an instance of `Activity` and there is a `@BindView` annotation, than `ButterKnife` can trigger a compile time error.

Maybe this can be made even more explicit with `bindContext()`, so people will be sure to know why they are using it?

**Comment by JakeWharton** [comment]
It cannot be validated. Processors only see structure, not statements.

**Comment by feinstein** [comment]
hmm interesting... I don't have much experience with code generation, good to know.
