### ISSUE TITLE
Butterknife looks not compatible with kotlin 1.3

### ISSUE THREAD

**Issue by sunshinehu** [JakeWharton/butterknife#1398]
when I use ButterKnife 9.0 and kotlin 1.3, it generates R2 with const id just like this:

    target.view = Utils.findRequiredViewAsType(source, 2131493301, "field 'view'", TextView.class);

and it cannot find view when run the app,I don't know whitch library cause the problem,when I change the kotlin version to 1.2.71,the problem is fixed

**Comment by willks** [comment]
Yep, getting it too after updating to Kot 1.3 (and androidx)

**Comment by willks** [comment]
Actually, got around it. Make sure you have kapt and @JvmField for the binded properties. Works now.

**Comment by sunshinehu** [comment]
> Actually, got around it. Make sure you have kapt and @JvmField for the binded properties. Works now. YMMV - I was migrating an older Java based app to Kotlin/Coroutines. Old developers used Butterknife, and this was an incremental change (not a green app)

however,it doesn't work for me , can you show an example for me ,thank you!

**Comment by epool** [comment]
Kotlin ported issue https://youtrack.jetbrains.net/issue/KT-27334 seems to be fixed until `1.3.20` I just checked `1.3.20-dev-1612` and works on that version.

**Comment by JakeWharton** [comment]
Thanks! Hopefully 1.3.20 is out soon. 1.3.10 was just released.

**Comment by T-Spoon** [comment]
> Kotlin reported issue https://youtrack.jetbrains.net/issue/KT-27334 seems to be fixed until `1.3.20` I just checked `1.3.20-dev-1612` and works on that version.

Hmm, I've also switched to `1.3.20-dev-1612`, but it doesn't seem to be working :/

It only works initially because the version bump nukes the build cache (you can do the same by changing the butterknife version e.g. `9.0.0-SNAPSHOT` -> `9.0.0-rc1`, and the issue will resolve temporarily).
