### ISSUE TITLE
compile error。。。help

### ISSUE THREAD

**Issue by xdjm** [JakeWharton/butterknife#1399]
so- -
use the new version 9.0.0-rc1

![11-05 image003](https://user-images.githubusercontent.com/23008997/47986927-16568100-e119-11e8-8881-36c1765a87cf.png)

**Comment by JakeWharton** [comment]
You are including multiple copies of the old Android support library architecture component named 'core'. This library does not use architecture components, so I cannot see how it could be the cause.

**Comment by Carlz04** [comment]
Can you please unsubscribe me from this thread
