### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by jinmyang** [JakeWharton/butterknife#1400]
Genrate Butterknife injections  ：Android ButterKnife Zelezny threw an uncaught NullPointerException. Disable Plugin

**Comment by JakeWharton** [comment]
You want https://github.com/avast/android-butterknife-zelezny, not this project.

**Comment by jinmyang** [comment]
Sorry, thank you.

**Comment by jinmyang** [comment]
Sorry, thank you
