### ISSUE TITLE
依赖最新版的9.0.0-rc2运行报错

### ISSUE THREAD

**Issue by moneeWong** [JakeWharton/butterknife#1408]
Error: Static interface methods are only supported starting with Android N (--min-api 24): void butterknife.Unbinder.lambda$static$0()

**Comment by Lyons-Hoo** [comment]
you can use old version.

**Comment by JakeWharton** [comment]
As per the release notes (https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-900-rc2-2018-11-19), all artifacts are built with Java 8 and so you need to set your consuming projects to use Java 8 as well.

**Comment by elirehema** [comment]
@moneeWong Add this to your build.gradle

android {
 
    ...........................

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

**Comment by comaksr** [comment]
Here it works, thank you

**Comment by bukunmialuko** [comment]
Thanks

**Comment by natansalda** [comment]
who thank you @elirehema

**Comment by zgq105** [comment]
thank you @elirehema

**Comment by IsabellaVel** [comment]
@elirehema your solution worked for me, thanks

**Comment by bambanghariantosianturi** [comment]
thank you @elirehema

**Comment by 1cornerstone** [comment]
it works for me ,kudos

**Comment by NoumanBaig** [comment]
Thanks @elirehema

**Comment by EmadKOo** [comment]
Thanks @elirehema

**Comment by HoussemBenmammar** [comment]
thanks a lot bro ,it works

**Comment by pavvvan** [comment]
Thanks

**Comment by thiagomonteiro03** [comment]
thanks @elirehema , it worked for me
