### ISSUE TITLE
İdRes annotation problem

### ISSUE THREAD

**Issue by mstf-arici** [JakeWharton/butterknife#1409]
Hi;

The project is synchronizing while R2.java changes its contents. There are two annotations in this file. These are IdRes and IntegerRes. but when grad is synchronized, it turns to İdRes and İntegerRes. This causes an error and causes an error in the project. The same thing happens when I manually sync the file, but syncing again.

I'm waiting for your help.

**Comment by Canoncul** [comment]
Change your regional settings to US

**Comment by kngfrhzs** [comment]
@Canoncul Thanks for your help, but unfortunately I couldn't find that where I should change this settings to US. And this seems a version specific problem because at 8.4.0 it works without any problem.
