### ISSUE TITLE
Apksigner verify warnings

### ISSUE THREAD

**Issue by ric-g** [JakeWharton/butterknife#1410]
I got below warning when i verify my apk. Could someone provide some advice what i should do?

WARNING: META-INF/services/javax.annotation.processing.Processor not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.

**Comment by JakeWharton** [comment]
Seems like you have erroneously put `butterknife-compiler` on the compilation classpath instead of `annotationProcessor` as the readme states. There's not enough information to figure out what's going on, though, or even if Butter Knife is the culprit.

**Comment by ric-g** [comment]
@JakeWharton We are still using the old version 6.0 and we know we should upgrade to latest version but not now. So for 6.0, do you have any approach to avoid this warning?

**Comment by JakeWharton** [comment]
Nope. That would be a request for the Android tools team.
