### ISSUE TITLE
 Manifest merger failed

### ISSUE THREAD

**Issue by StephenYoungYang** [JakeWharton/butterknife#1413]
When there are "androidx libraries" in my project. It always builds failed.  Such like this
"
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:52:5-106:19 to override."

**Comment by JakeWharton** [comment]
You need to enable jetifier by specifying `android.enableJetifier=true` in `gradle.properties`. This message will always occur when mixing AndroidX with legacy support dependencies and is not specific to Butter Knife.

**Comment by StephenYoungYang** [comment]
Thanks for your answer😀😀😀

**Comment by anubhavgupta1** [comment]
You need to enable jetifier by specifying 
android.useAndroidX=true
android.enableJetifier=true
` in `gradle.properties`

**Comment by LiDevil** [comment]
but i got a new error:ERROR: [TAG] Failed to resolve variable '${project.groupId}'

**Comment by pearlmaknun** [comment]
I am sorry, but i tried the solution like you guys write: 
android.useAndroidX=true
android.enableJetifier=true

and it turns out all of activity got red, AppCompatActivity got red

**Comment by ekohere** [comment]
> I am sorry, but i tried the solution like you guys write:
> android.useAndroidX=true
> android.enableJetifier=true
> 
> and it turns out all of activity got red, AppCompatActivity got red
> all of my activity suddenly does not recognized as activity

me too

**Comment by LiDevil** [comment]
i solve my question by reduce the butterknife version to :
implementation 'com.jakewharton:butterknife:8.8.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
and i try to update my android studio to 3.3.1version,build an androidx demo,then the newest butterknife version(10.1.0) is working,and builld success
(forgive my bad english)

**Comment by akramul-hasan-m4** [comment]
### Same error  with 10.1.0 ....

implementation 'com.jakewharton:butterknife:10.1.0'
annotationProcessor 'com.jakewharton:butterknife-compiler:10.1.0'
![Sstudioversion](https://user-images.githubusercontent.com/34574028/55797673-dabc4a80-5aee-11e9-9e7c-bae504eec482.png)
![buttererror2](https://user-images.githubusercontent.com/34574028/55797691-e445b280-5aee-11e9-85e7-57aee9a4701b.png)

**Comment by J6ey** [comment]
> android.enableJetifier=true

What if I don't want to use AndroidX?

**Comment by JakeWharton** [comment]
Use version 9.0.0

**Comment by JungTa** [comment]
i got error when using version 9.0.0.
then i used version 8.6.0.
i got success
