### ISSUE TITLE
The given artifact contains a string literal with a package reference 'android.support.v4.content' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.

### ISSUE THREAD

**Issue by cepv2010** [JakeWharton/butterknife#1415]
I'm Trying to implement butterknife:9.0.0-rc2 with Dagger 2.19 and Jetifier = enable, but i get the next error:

> The given artifact contains a string literal with a package reference 'android.support.v4.content' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.

How can solve this issue?

thanks for your kind help.

**Comment by JakeWharton** [comment]
See https://github.com/JakeWharton/butterknife/issues/1395#issuecomment-439776056 for a workaround of this jetifier problem. No action to take on our side.

**Comment by AltonDsouza** [comment]
I get the same error , I migrated my existing project to androidx thats when i got this error, tried upgrading version to 10.2.0 and added compileOptions in build.gradle. 
The findById is not recognized. Some workAround for this?? Thank you.

**Comment by rakeshbaral92** [comment]
Is there any solution yet. I have stuck after migrating my project to androidx.

**Comment by ldavidsp** [comment]
Change to these parameters in build.gradle, it worked for me using version `butterknife:10.2.1`

`testImplementation 'junit:junit:4.12'
 androidTestImplementation 'androidx.test.ext:junit:1.1.1'
 androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'`

**Comment by Srikanth9792** [comment]
Hi
I am also facing same issue after made below changes also & I am not able to run test cases

testImplementation 'junit:junit:4.12'
androidTestImplementation 'androidx.test.ext:junit:1.1.1'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

**Comment by endlesstech** [comment]
I also got the same issue. Please share the best solution for it.

The given artifact contains a string literal with a package reference 'android.support.v4.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.

**Comment by surajsahani** [comment]
> Change to these parameters in build.gradle, it worked for me using version `butterknife:10.2.1`
> 
> `testImplementation 'junit:junit:4.12'`
> `androidTestImplementation 'androidx.test.ext:junit:1.1.1'`
> `androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'`

The given artifact contains a string literal with a package reference 'android.support.v4.content' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.
i am getting this error

**Comment by MohamedAboAdel** [comment]
I had exactly the same problem

I have made the following changes namely 

    implementation 'com.jakewharton:butterknife:9.0.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0'

to
    implementation 'com.jakewharton:butterknife:10.2.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.1'

**Comment by JR-Asif** [comment]
changing the version worked to 10.2.1 worked for me. Thankyou.
