### ISSUE TITLE
Androidx annotation

### ISSUE THREAD

**Issue by ElmirSecerbegovic** [JakeWharton/butterknife#1417]
Please,

if we use com.jakewharton:butterknife:9.0.0-rc2 we will get another error regarding min-api version (states 26). Our project have to be with minimal api version 19.

So, does this mean that we can not use androidx support with version of api below 24 ?

Is there any workaround ?

**Comment by JakeWharton** [comment]
The project supports down to API 14. Per the release notes, the artifacts are all now built using Java 8 and requires that all consumers also enable Java 8 in their project

**Comment by ElmirSecerbegovic** [comment]
Thank you for response.

We were missing

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

in our android project.
