### ISSUE TITLE
build time out

### ISSUE THREAD

**Issue by smtrz** [JakeWharton/butterknife#1418]
Hi,
after adding 9.0.0-rc2 ,gradle build time out occurs but working fine with 8.8.1

Why this might be happening ?

thanks

**Comment by JakeWharton** [comment]
A timeout fetching the artifacts is between you and Maven Central where the artifacts are hosted. I don't have any control over that. You can try increasing Gradle's timeouts, but you'll have to consult the Gradle documentation to figure out how to do that.
