### ISSUE TITLE
I hava a Question。

### ISSUE THREAD

**Issue by ShuaiXiu** [JakeWharton/butterknife#1421]
Why working with the butter knife and ARouter of alibaba would invalidate the butter knife's annotation, and the control that USES the annotation would report a null pointer exception. I hope god help me, I will be tortured to death!

**Comment by JakeWharton** [comment]
There's no way to know what's going on based on your description. Can you produce a sample that exhibits the bad behavior you're seeing?

**Comment by ShuaiXiu** [comment]
To be honest, I didn't know what had happened. I had relied on 'butterknife' and everything was fine, so if I had added 'ARouter', 'butterknife' I wouldn't have been able to annotate 'view' properly.

**Comment by JakeWharton** [comment]
Without more information I don't have any way to know what's happening or what a fix could be. If you're able to create a sample I'll take a look, but closing for now.

**Comment by ShuaiXiu** [comment]
https://github.com/ShuaiXiu/ARouterDemo.git.You can have a detailed look at the 'ARouterDemo' in this one. Thank you very much for replying to my email.
