### ISSUE TITLE
apply function removed with version 10.0.0

### ISSUE THREAD

**Issue by damienvaz** [JakeWharton/butterknife#1422]
Hey everyone :)
With version 10.0.0, some functions were deprecated and one of them `apply()` is not anymore available.
What is the workaround now ? I think the documentation is not updated yet and I don't know what to do.

**Comment by dvdmunckhof** [comment]
Use `ViewCollections.run(...)` or `ViewCollections.set(...)`. More info is in [the commit that deprecated them](https://github.com/JakeWharton/butterknife/commit/eb7e695d4f04b4d3998f67a5c6db8375323476c5#diff-437956f262bfd97cb56963e664c90de6) and in [the commit that removed them](https://github.com/JakeWharton/butterknife/commit/8eb5280c4a7dce8f023d7a29585a2417b82a607e#diff-437956f262bfd97cb56963e664c90de6).

**Comment by JakeWharton** [comment]
If you first jumped to 9.0 you would have seen these as deprecated with pointers to the `ViewCollections` class. I'll add a note to the 9.0.0 release notes.

**Comment by damienvaz** [comment]
Thanks a lot ! :)

**Comment by sickmartian** [comment]
https://jakewharton.github.io/butterknife/ is still showing apply fyi

**Comment by knezmilos13** [comment]
As previous poster said, still showing apply, which is confusing.
