### ISSUE TITLE
Custom View inflating failed

### ISSUE THREAD

**Issue by TeeEmJee** [JakeWharton/butterknife#1423]
I want to use Butterknife (v. 8.8.1) for my custom view (`ImageViewNumber extends ConstraintLayout`)
This is how I inflate my layout and bind all of my views:

    @BindView(R.id.view_imagenumberview_number) EditText mEditTextNumber;
    @BindView(R.id.view_imagenumberview_image) TextView mTextViewImage;
    @BindView(R.id.view_imagenumberview_title) TextView mTextViewTitle;

    public ImageViewNumber(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context, attrs);
    }

    [...]

    private void init(final Context context, final AttributeSet attrs) {
        final LayoutInflater inflater = LayoutInflater.from(context);
        final View view = inflater.inflate(R.layout.view_imagenumberview, this, false);
        ButterKnife.bind(this, view);

        [...]
    }

Unfortunately I get an exception:

    Caused by: android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class com.me.mel.myapp.ImageViewNumber
    Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class com.me.me.myapp.ImageViewNumber

How do I inflate correctly?

**Comment by murageden** [comment]
Did you try to bind using the Context passed during init as in: `Butterknife.bind(context, view)`. Also please provide the statement on the specific line #21

**Comment by JakeWharton** [comment]
Line 21 is the view tag. What's needed is the whole exception trace.

**Comment by TeeEmJee** [comment]
Thanks for the comments! I have solved the problem by cleaning and rebuilding my project. Since then there are no more bugs. 
Apparently the problem had to do with Android Studio.
