### ISSUE TITLE
Activity in library facing Resources NotFoundException

### ISSUE THREAD

**Issue by hahahazzz** [JakeWharton/butterknife#1424]
hi,JakeWharton!
I use butterknife 10.0.0 in my project,my project contains 4 modules(3 library and 1 application module)
butterknife can generate R2 file,but i still facing Resources NotFoundException when i open page in library module.( App Module.A -> library Module.B )
my project is a kotlin project .
and my IDE info : Android Studio 3.2.1 + Kotlin 1.3.11 + JDK 1.8.0_181
and i create a project 
https://github.com/hahahazzz/MultiModuleDemo
need your help !
thanks !!!  :D
or this may caused by kotlin ???

**Comment by hahahazzz** [comment]
I try other ways
such as : upgrade kotlin plugin , use butterknife 9.0.0-rc3 ,add an empty java Activity ...,
but all do not worked

**Comment by liulinjie1990823** [comment]
Kotlin 1.2.71 is ok,and has a bug in 1.3+

**Comment by hahahazzz** [comment]
> Kotlin 1.2.71 is ok,and has a bug in 1.3+

ok. Thank you !
