### ISSUE TITLE
androidX Library and Android Support conflict

### ISSUE THREAD

**Issue by huangchunhua13** [JakeWharton/butterknife#1425]
I use version 10.0.0 but it should add "android.useAndroidX=true  android.enableJetifier=true" in gradle.properties，but my project use android support library now，Is there any way to use the latest version of the butter knife under the android support library?

**Comment by hahahazzz** [comment]
you should migrate your support library to androidx library.
such as androidx.appcompat:appcompat  androidx.constraintlayout:constraintlayout
visit here  https://developer.android.google.cn/jetpack/androidx/migrate
and change your code in xml files ,Re-import package to fix compile error.
and My terrible english....

**Comment by JakeWharton** [comment]
9.0.0 and 10.0.0 are exactly the same except 10.0.0 removes support for the old support libraries. If you're still on them, use 9.0.0. Be warned, though, that future work will be on 10.0.0 and won't be backported to 9.0.0. I would recommend you migrate to AndroidX in the near-term.

**Comment by snehazanzane** [comment]
> you should migrate your support library to androidx library.
> such as androidx.appcompat:appcompat androidx.constraintlayout:constraintlayout
> visit here https://developer.android.google.cn/jetpack/androidx/migrate
> and change your code in xml files ,Re-import package to fix compile error.
> and My terrible english....

Thanks . This is very good solution. working for me
