### ISSUE TITLE
 [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory)

### ISSUE THREAD

**Issue by Jay-YaoJie** [JakeWharton/butterknife#1429]
![image](https://user-images.githubusercontent.com/18596432/51037530-6c4d1680-15eb-11e9-9a68-2738abaff130.png)

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-21:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by JakeWharton** [comment]
As mentioned in [the change log](https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-1000-2019-01-03), 10.0.0 only supports AndroidX-enabled projects. If you have not yet migrated to AndroidX you need to use 9.0.0 for now.

**Comment by wongkevinmanuel** [comment]
It was solved by migrating to AndroidX, and configuring the implementation dependency 'com.jakewharton: butterknife: 8.8.0'
annotationProcessor 'com.jakewharton: butterknife-compiler: 8.8.0'

**Comment by Yangworld4** [comment]
看不懂看不懂
