### ISSUE TITLE
@Onclick annotation throws runtime exception on bind

### ISSUE THREAD

**Issue by daespark** [JakeWharton/butterknife#1434]
I just created a new project targetting 28 , minimum 28. Jetifier enabled and using AndroidX libs.

I created a simple fragment with a button and a webview, and @OnClick annotation makes the app crash on run time.
![bandicam 2019-01-19 23-44-55-396](https://user-images.githubusercontent.com/5368948/51436556-3db2e980-1c44-11e9-8299-ff3f76b61004.jpg)
![bandicam 2019-01-19 23-40-01-825](https://user-images.githubusercontent.com/5368948/51436528-e876d800-1c43-11e9-83db-8524a46d26a8.jpg)
![bandicam 2019-01-19 23-41-24-073](https://user-images.githubusercontent.com/5368948/51436529-ea409b80-1c43-11e9-8b21-6b824e303abf.jpg)
![bandicam 2019-01-19 23-41-31-210](https://user-images.githubusercontent.com/5368948/51436530-eb71c880-1c43-11e9-8afc-b6994df1ede7.jpg)

**Comment by daespark** [comment]
https://github.com/daespark/Buget2 

I tested on pixel 2 xl thinking that it maybe an emulator issue. Same crash

**Comment by JakeWharton** [comment]
ButterKnife requires Java 8. You need to add
```groovy
android {
    compileOptions {
        targetCompatibility = "8"
        sourceCompatibility = "8"
    }
}
```
to your application `build.gradle`.

**Comment by abdullahqutb** [comment]
Thanks alot, after adding the java 8 fix, the issues is fixed.
