### ISSUE TITLE
AGP 3.3 in butterknife

### ISSUE THREAD

**Issue by AlexKrupa** [JakeWharton/butterknife#1436]
I forked the project to add some missing features, however it turned out AGP is still 3.2 and I already upgraded to AS 3.3, which is making AS unable to sync.

Requirements for AGP 3.3:
* Gradle 4.10.1 or higher
* Kotlin 1.3 or higher
* AAPT2 will always be used

Could AAPT2 be an issue since it's disabled with `android.enableAapt2=false` (the flag is removed in AGP 3.3)?

I decided against a PR as I don't know the project enough to know of potential issues that could come up when upgrading 3 dependencies at once.

**Comment by JakeWharton** [comment]
You can download AS 3.2 to work on the project. Update is blocked by https://issuetracker.google.com/issues/73450622 as you've figured out.

**Comment by Androidjent** [comment]
Since I upgraded to Android Studio 3.3, the compiler does not recognize the Dependency "import butterknife.BindView;" anymore. For short term, I also downgraded to 3.2.

Guess there is no current workaround?
