### ISSUE TITLE
using butterknife in library subproject fails to give bound view info. Its asking to 

### ISSUE THREAD

**Issue by vijayanandkh** [JakeWharton/butterknife#1437]
using butterknife in library subproject fails to give bound view info. Its asking to upgrade min sdk to 24.

Can not make min sdk 21 for app having custom library.

**Comment by hongqinghe** [comment]
I can't use in min SDK is 16

**Comment by JakeWharton** [comment]
Per the change log: https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-900-2019-01-03

All artifacts now target Java 8 as of 9.0.0. You need to enable Java 8 source and target versions in order to update.

**Comment by hongqinghe** [comment]
Why after upgrade  this error  [#1435](https://github.com/JakeWharton/butterknife/issues/1435)
