### ISSUE TITLE
After upgrade grade version application getting run time build error

### ISSUE THREAD

**Issue by mesadhan** [JakeWharton/butterknife#1439]
**After upgrade grade v3.3.0, Application throws runtime errors**

**Logs:**

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugManifest'.

Caused by: java.lang.RuntimeException: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).

**Comment by krirk0137** [comment]
I am still use 
   implementation 'com.jakewharton:butterknife:9.0.0-rc1'
^_^   


when I am updated to 
   implementation 'com.jakewharton:butterknife:10.0.0'
   annotationProcessor 'com.jakewharton:butterknife-compiler:10.0.0'
I can't use too T^T

**Comment by JakeWharton** [comment]
Version 10 requires that your project has migrated to AndroidX. This error message indicates that you haven't and are mixing the legacy support dependencies with AndroidX.
