### ISSUE TITLE
Android Studio 3.3 ButterKnife Error

### ISSUE THREAD

**Issue by Handy045** [JakeWharton/butterknife#1442]
# Error-Info
ERROR: The Android Gradle plugin supports only Butterknife Gradle plugin version 9.0.0-rc2 and higher.
The following dependencies do not satisfy the required version:
root project 'XXXXProjectName' -> com.jakewharton:butterknife-gradle-plugin:8.8.1
Affected Modules: app

# Configuration
## gradle-wrapper.properties:
````
#Tue Jan 29 09:24:07 CST 2019
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
````
## project build.gradle:
````
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'
    }
}
````

**Comment by JakeWharton** [comment]
The error message seems pretty clear. You have to use version 9.0.0-rc2 or newer (use 9.0.0 or 10.0.0).
