### ISSUE TITLE
Failuere with manifest file

### ISSUE THREAD

**Issue by hassanjamilah** [JakeWharton/butterknife#1443]
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-32:19 to override.

**Comment by JakeWharton** [comment]
As mentioned in [the change log](https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-1000-2019-01-03), 10.0.0 only supports AndroidX-enabled projects. If you have not yet migrated to AndroidX you need to use 9.0.0 for now.
