### ISSUE TITLE
Compile Error in AndroidX Project

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [JakeWharton/butterknife#1446]
When I use Butter Knife through Gradle in Android Studio, a compilation error occurred which said "it should only work on API >= 26

**Comment by hoordev** [comment]
Please browse earlier reports or [changelog](https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md) and do you get answer.
Any issue that mention this
[1427](https://github.com/JakeWharton/butterknife/issues/1427)
[1416](https://github.com/JakeWharton/butterknife/issues/1416)

**Comment by JakeWharton** [comment]
All artifacts are built with Java 8 and require you enable it in your app in order to consume it on all API levels.
