### ISSUE TITLE
butterknife bind an id from other layouts

### ISSUE THREAD

**Issue by wycCalm** [JakeWharton/butterknife#1474]
This is what I do:
HomeActivity:
`
   @BindView(R2.id.drawer_layout)
   DrawerLayout drawerLayout;
`
but I met a problem :   **Required view 'iv_picture' with ID 2131231223 for field 'drawerLayout' was not found**
HomeActivity_Binding:  the id has changed , and the second below is no problem
`
target.drawerLayout = Utils.findRequiredViewAsType(source, **R.id.iv_picture**, "field 'drawerLayout'", DrawerLayout.class);
target.toolbarLayout = Utils.findRequiredViewAsType(source, com.lington.R.id.toolbar, "field 'toolbarLayout'", ToolbarLayout.class);
`

**Comment by Sky24n** [comment]
怎么解决的，我也遇到同样的问题
