### ISSUE TITLE
@com.jk.kangdi instead of @BindView while generating Butterknife injections

### ISSUE THREAD

**Issue by sivansundar** [JakeWharton/butterknife#1476]
Hello devs. 

Using the butterknife generator plugin for android studio which is pretty useful. While generating Butterknife injections for a couple of views, I get ` @com.jk.kangdi.BindView` instead of `@BindView`. 

Example, 
`@com.jk.kangdi.BindView("R.id.main_content")
RelativeLayout main_content;`

Instead of, 

`@BindView(R.id.main_content)
RelativeLayout main_content;`

This gives me a cannot resolve jk error (obviously) so how do I go about this? Using Butterknife 10.0.1. 

Any suggestions? @JakeWharton

**Comment by JakeWharton** [comment]
The IDE plugin comes from https://github.com/avast/android-butterknife-zelezny and is not part of this project. It sounds like a bug in that project so I would suggest you file an issue there.
