### ISSUE TITLE
Error activity when enable android.useAndroidX=true android.enableJetifier=true

### ISSUE THREAD

**Issue by ekohere** [JakeWharton/butterknife#1479]
i tried the solution :
android.useAndroidX=true
android.enableJetifier=true

and it turns out all of activity got red, AppCompatActivity got red
all of my activity suddenly does not recognized as activity

**Comment by JakeWharton** [comment]
There's no information in this report that indicates this is a problem with Butter Knife. If you just migrated to AndroidX, try restarting the IDE and clearing its caches, etc. Otherwise StackOverflow will be your best bet.
