### ISSUE TITLE
how to use with android source code?

### ISSUE THREAD

**Issue by ctpxyza** [JakeWharton/butterknife#1480]
I'm working at android source code, and an app code with lots of @BindView need to be porting to it. I have written an Android.mk, but it doesn't work, can anyone help me ?

**Comment by ctpxyza** [comment]
OCAL_ASSET_DIR := $(addprefix $(LOCAL_PATH)/, $(asset_dirs))

LOCAL_AAPT_FLAGS += \
    --auto-add-overlay \
    --extra-packages com.android.contacts.common \
    --extra-packages com.android.phone.common \
    --extra-packages android.support.design \
    --extra-packages android.support.transition \
    --extra-packages android.support.v7.appcompat \
    --extra-packages android.support.v7.cardview \
    --extra-packages android.support.v7.recyclerview

# M: for using framework @{
LOCAL_JAVA_LIBRARIES := telephony-common voip-common
LOCAL_JAVA_LIBRARIES += framework
LOCAL_JAVA_LIBRARIES += mediatek-framework
LOCAL_JAVA_LIBRARIES += mediatek-common
LOCAL_JAVA_LIBRARIES += mediatek-telephony-common
LOCAL_JAVA_LIBRARIES += mediatek-telephony-base
LOCAL_JAVA_LIBRARIES += mediatek-telecom-common
# @}
LOCAL_JAVA_LIBRARIES += butterknife-annotations butterknife

LOCAL_STATIC_JAVA_LIBRARIES := \
    android-common \
    android-support-design \
    android-support-transition \
    android-support-v13 \
    android-support-v7-appcompat \
    android-support-v7-cardview \
    android-support-v7-recyclerview \
    android-support-v7-palette \
    android-support-v4 \
    com.android.vcard.mtk \
    guava \
    libphonenumber \
    butterknife-annotations \
    butterknife \
    BaseRecyclerViewAdapterHelper \
    greenrobot-jdt-3.12.2 \
    eventbus-3.1.1 \
    greendao-api-3.2.2

LOCAL_STATIC_JAVA_AAR_LIBRARIES := butterknife BaseRecyclerViewAdapterHelper

PROCESSOR_LIBRARIES_TARGET := \
    butterknife \
    butterknife-annotations

# Resolve the jar paths.
PROCESSOR_JARS := $(call java-lib-deps, $(PROCESSOR_LIBRARIES_TARGET))

# Necessary for annotation processors to work correctly.
LOCAL_ADDITIONAL_DEPENDENCIES += $(PROCESSOR_JARS)
LOCAL_JACK_FLAGS += --processorpath $(call normalize-path-list,$(PROCESSOR_JARS))
LOCAL_JAVACFLAGS += -processorpath $(call normalize-path-list,$(PROCESSOR_JARS))
${warning LOCAL_JAVACFLAGS is $(LOCAL_JAVACFLAGS)}

LOCAL_PACKAGE_NAME := CustomContacts
LOCAL_CERTIFICATE := shared
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Contacts

LOCAL_PROGUARD_ENABLED := disabled
LOCAL_USE_AAPT2 := true
LOCAL_JACK_ENABLED := disabled

LOCAL_DEX_PREOPT := false

LOCAL_DX_FLAGS := --multi-dex
LOCAL_JACK_FLAGS := --multi-dex native

LOCAL_PROGUARD_FLAG_FILES := \
    proguard.flags \
    ../../../frameworks/support/core-ui/proguard-rules.pro \
    ../../../frameworks/support/design/proguard-rules.pro \
    ../../../frameworks/support/v7/recyclerview/proguard-rules.pro

# M: mark for using hide API @{
#LOCAL_SDK_VERSION := current
# @}
LOCAL_MIN_SDK_VERSION := 21

include $(BUILD_PACKAGE)


include $(CLEAR_VARS)
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := \
    butterknife:libs/butterknife-8.8.1.aar \
    BaseRecyclerViewAdapterHelper:libs/BaseRecyclerViewAdapterHelper-2.9.30.aar \
    butterknife-annotations:libs/butterknife-annotations-8.8.1.jar \
    greenrobot-jdt-3.12.2:libs/greenrobot-jdt-3.12.2.jar \
    eventbus-3.1.1:libs/eventbus-3.1.1.jar \
    greendao-api-3.2.2:libs/greendao-api-3.2.2.jar
include $(BUILD_MULTI_PREBUILT)

**Comment by ctpxyza** [comment]
the error msg is 

02-28 09:57:24.160 D/ButterKnife( 2884): Looking up binding for com.bird.oldphone.dialer.CallFragment
02-28 09:57:24.162 D/ButterKnife( 2884): Not found. Trying superclass android.support.v4.app.Fragment
02-28 09:57:24.163 D/ButterKnife( 2884): MISS: Reached framework class. Abandoning search.

**Comment by ctpxyza** [comment]
Environment : ubuntu 18.04
os : android 8.1
platform :  mt6739

**Comment by JakeWharton** [comment]
I have never used make and every ounce of my being works towards a future where I never have to. I would recommend seeking general annotation processor help for make somewhere like StackOverflow where you're like to find people who specialize in it and can figure this out. There shouldn't be anything Butter Knife-specific about your request aside from the fact that it happens to be the annotation processor you're using. This is more a general build configuration question which I am not suited to help with.
