### ISSUE TITLE
After migration to androidx and  updating the library iam when I run the project any view is not getting bind with the view. Views are not getting binded

### ISSUE THREAD

**Issue by shastrikikitchen** [JakeWharton/butterknife#1489]

**Comment by JakeWharton** [comment]
There's no information here to be able to diagnose what the problem is or to even determine if Butter Knife is the problem.

**Comment by MassiveMadness** [comment]
I updated butterknife from 8.8.1 to 10.1.0, and also migrated to androidx. Now it doesn't bind my custom views, and I'm getting NullPointerException

**Comment by elipoultorak** [comment]
Here is a file in the "generated" folder:

> // Generated code from Butter Knife. Do not modify!
import android.support.annotation.CallSuper;
import android.support.annotation.UiThread;

The problem is that it generates code using `android.support.annotation`

**Comment by nocrisis** [comment]
So how did you figure out this problem ? I also met the same unbind views problem without any build error or warning

**Comment by elipoultorak** [comment]
Update butterknife to the latest version
