### ISSUE TITLE
Use a custom OnClickListener with butterknioe

### ISSUE THREAD

**Issue by redmanit** [JakeWharton/butterknife#1495]
There are many cases that we want to use a custom OnClickListener instead of the default one, e.g to prevent fast multiple clicks. Is there a way to do that now?

**Comment by redmanit** [comment]
Oh I just found a @JakeWharton comment 3 years ago: "Someday we'll support custom listeners and you'll be able to specify the callback class, but it's a long way away." https://github.com/JakeWharton/butterknife/issues/432

**Comment by JakeWharton** [comment]
Yep. Tracking at #497.
