### ISSUE TITLE
Explicitly call `unbind()` in Activity if `ListenerClass` has valid `remover`???

### ISSUE THREAD

**Issue by macarthor** [JakeWharton/butterknife#1497]
if `ListenerClass` implementation has a valid `remover`, e.g. `OnPageChange` and `OnTextChanged`, the `remover` method is added in the implementation of `Unbinder.unbind()` method, by `BindingSet.removerOrSetter()` method.

So, for Activities that reference `ListenerClass` implementations with a valid `remover`, I did not see a 
explicit or implicit method to call the `unbind()` method of `ButterKnife.bind()`'s return value.

I wonder if the `remover` or `unbind()` method would be automatically called? How if yes? If no, there would be memory leak.

I believe we ***MUST EXPLICITLY*** call `Unbinder.unbind()`, where `Unbinder` instance is returned by `ButterKnife.bind()`, ***in Activities referencing any `ListenerClass` with a valid `remover`***.

#906 #971

**Comment by macarthor** [comment]
another path is `ButterKnife.bind()` calls `parseOnTextChanged` which returns a `ListenerUnbinder`. It's `unbind()` method calls:

```java
private static final Setter<TextView, TextWatcher> REMOVE_TEXT_WATCHER =
      (view, value, index) -> view.removeTextChangedListener(value);
```

but also, the returned `Unbinder` of `parseOnTextChanged()` method is delegated to `CompositeUnbinder`, which is not called in Activities.

**Comment by JakeWharton** [comment]
You only need to call `unbind()` in fragments in `onDestroyView` because it can cause a leak if the fragment is re-used. For activities you do not need to call the method because the references form a cycle which will be correctly GC'd.

**Comment by macarthor** [comment]
@jakeWharton if we call `addTextChangedListener()` method which has a `TextWatcher` object referencing the activity. The listener is stored in TextView's  `ArrayList<TextWatcher> mListeners`. If we do not call `removeTextChangedListener()` method, there would be a memory leak.

with butterknife, the `addTextChangedListener()` method is replaced by perhaps a method annotated with a `@onTextChanged`. But the concrete implementation is also `addTextChangedListener()`. So we must call `removeTextChangedListener()` method in `unbind()`.

I did not see any calls to `removeTextChangedListener()` in generated `unbind()` method.

**Comment by JakeWharton** [comment]
They're there: https://github.com/JakeWharton/butterknife/blob/0ead8a7b21620effcf78c728089fc16ae9d664c0/butterknife-runtime/src/test/java/butterknife/OnTextChangedTest.java#L63

But like I said, this forms a cycle so it's not a problem for binding activities anyway.

**Comment by macarthor** [comment]
hi @JakeWharton. DO APOLOGIZE IF I AM somewhat verbose... ***BUT I REALLY BELIEVE*** that the `unbind()` method is not called for `_ViewBinding` classes, when it's some `SomeActivity_ViewBinding`: because for activities, we don't call the `unbind()` method of the Unbinder returned by `ButterKnife.bind()` method.

would you please do me a favor to feature out how it's implicitly called? MANY THANKS!!!

**Comment by JakeWharton** [comment]
It isn't. Either you call it or you don't.

**Comment by MihailsKuzmins** [comment]
And what about the case when I use the bind() method in a ViewHolder of the RecyclerView adapter? Calling unbind() in onViewRecycled() might seem like a legit idea, but calling bind() each time an item appears (not in the constructor of a ViewHolder) seems kinda suspicious.

**Comment by JakeWharton** [comment]
You shouldn't unbind in a view holder either. Bind in the constructor and
have the lifetime of the view holder match the lifetime of the view. When
new data comes in just update the local and view state. The views haven't
actually changed and so you don't need to re-bind them.

**Comment by MihailsKuzmins** [comment]
@JakeWharton thanks
