### ISSUE TITLE
Attempt to invoke virtual method 'void com.rengwuxian.materialedittext.MaterialEditText.setText(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by Murtaza22** [JakeWharton/butterknife#1504]
I have error from this function any one help me please?
I call this function inside Oncreate function of activity
`private void editincome(final int position){
        Dialog dialog = new Dialog(this);
        dialog.setTitle("Edite");
        dialog.setContentView(R.layout.edit_income);
        dialog.show();

        final MaterialEditText editincomecase = findViewById(R.id.editincomecase);
        final MaterialEditText editamount= findViewById(R.id.editincomeamount);
        final Button editsave = findViewById(R.id.editesave);

        AndroidNetworking.get(GET_SUM)
                .setTag(this)
                .setPriority(Priority.LOW)
                .build()
                .getAsObjectList(com.webjow.costs.module.GetCost.class, new ParsedRequestListener<List<GetCost>>() {
                    @Override
                    public void onResponse(List<GetCost> costs) {
                        Log.d(TAG, "edite: "+position);
                        String incomecase = costs.get(0).getCosts().get(position).getForthis();
                        editamount.setText(incomecase);

                       Log.d(TAG, "Income case: "+costs.get(0).getCosts().get(position).getAmount());

//                        Log.d(TAG, "sum : "+costs.get(0).getCosts().get().getAmount());

                    }
                    @Override
                    public void onError(ANError anError) {
                        // handle error
                        Log.d(TAG, "ErrorDetail: " + anError.getErrorDetail() );
                        Log.d(TAG, "ErrorBody : " + anError.getErrorBody() );
                        Log.d(TAG, "ErrorCode : " + anError.getErrorCode() );
                    }
                });
    }`

**Comment by JakeWharton** [comment]
I don't see any Butter Knife here
