### ISSUE TITLE
variantOutput.getProcessResources() will be removed at the end of 2019

### ISSUE THREAD

**Issue by laogou** [JakeWharton/butterknife#1508]
hello.
my gradle pjugin version is 3.4.0.
use classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'.

WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.

**Comment by laogou** [comment]
has been out of date

**Comment by alinainai** [comment]
hello，how did you solute the warning，i also get the warning.

**Comment by DovSnier** [comment]
hello, I also have this kind of problem.
