### ISSUE TITLE
Can you add throttleFirst to the Click event?

### ISSUE THREAD

**Issue by Zvirtuey** [JakeWharton/butterknife#1517]
Can you add throttleFirst to the Click event? Like in your RxBinding "throttleFirst(500, TimeUnit.MILLISECONDS);"  We can set the same properties or set properties separately,
 like features  is very good.

    @OnClick({R.id.bt_login,R.id.bt_set,R.id.bt_registered})
    public void onViewClicked(View view) {
        //throttleFirst(500, TimeUnit.MILLISECONDS); ???Unified Settings
        switch (view.getId()) {
            case R.id.bt_login:
                //throttleFirst(500, TimeUnit.MILLISECONDS);???Set up separately
                jumpToActivity(HomeActivity.class);

                break;
           case R.id.bt_set:
               //throttleFirst(600, TimeUnit.MILLISECONDS);???Set up separately
                jumpToActivity(SetActivity.class);

                break;
        }
    }

**Comment by JakeWharton** [comment]
Not as part of Butter Knife, no. The scope of the library is only to bind callbacks to methods. How you react to those events remains up to you the same as it would if you used the listener directly. You can post to a Handler with delay to emulate such behavior, though.
