### ISSUE TITLE
How Can use butterknife in AndroidStudio3.0.0 and gradle3.0.0 for kotlin？

### ISSUE THREAD

**Issue by Richair** [JakeWharton/butterknife#1522]
Follow the documentation to add kotlin dependency library，Hint resources are not found

/Users/xxx/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/9c028bc53bb332bd18047f84c6231dc6/res/values/values.xml
Error:(246, 5) error: resource android:attr/fontVariationSettings not found.
Error:(246, 5) error: resource android:attr/ttcIndex not found.
/Users/xxx/Documents/KotlinTest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Error:(290) resource android:attr/fontVariationSettings not found.
Error:(290) resource android:attr/ttcIndex not found.

This is my configuration 
 compileSdkVersion 26
    defaultConfig {
        applicationId "jiaoshibang.xuebangonline.com.kotlintest"
        minSdkVersion 26
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

**Comment by JakeWharton** [comment]
compileSdkVersion 28 or newer is required for the transitive dependencies of the library. At this point, it should be 29, though.
