### ISSUE TITLE
Error Build Androidx

### ISSUE THREAD

**Issue by FuriosoJack** [JakeWharton/butterknife#1527]
`Task :app:compileDebugJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: butterknife-compiler-10.1.0.jar (com.jakewharton:butterknife-compiler:10.1.0), databinding-compiler-3.4.1.jar (androidx.databinding:databinding-compiler:3.4.1).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
`

**Comment by JakeWharton** [comment]
The absence of incrementalism will not fail the build. The actual error is elsewhere in the logs and it will indicate the actual problem. Without the actual error, it's impossible to know the underlying problem.
