### ISSUE TITLE
Butterknife keeps binding cache after change view from java to kotlin

### ISSUE THREAD

**Issue by limallucas96** [JakeWharton/butterknife#1530]
Hey friends, I have an issue which looks like this:

We had a fragment in Java binding the views from xml using butterknife, then, we decided to migrate this fragment from java to kotlin using synthetic to bind the views, thus, we no longer use butterknife in this fragment class.

What happen is, this application is on play store and currently being used for several users. When we published the new version of the app, somehow, butterknife kept the binding cache of that old Java fragment and it's views components, even though, that old Java view doesn't exist anymore because we have made it in kotlin now and using synthetic.

While developing, we noticed that we could solve this problem by cleaning android studio project cache. But, when we launched the app the problem persist in some users. 

How could we force butterknife to clear its view cache when upgrading app version? Is there a flag we could use in gradle or somewhere else? Any help is appreciated

**Comment by limallucas96** [comment]
Currently, we solved this issue by adding a try catch statement when using Butterknife.bind(), but, we belived is not the nicest solution.

**Comment by JakeWharton** [comment]
There is no cache across versions or even app launches. What you are experiencing is something else, but there isn't enough information to begin to diagnose the problem. For starters, what is the exception?

**Comment by JantHsueh** [comment]
Did you remove Butterknife.bind() in the fragment kotlin? @limallucas96
