### ISSUE TITLE
it seems that library has add final to R.java

### ISSUE THREAD

**Issue by liulinjie1990823** [JakeWharton/butterknife#1531]
![image](https://user-images.githubusercontent.com/8141393/60874652-f01a4f80-a26a-11e9-9700-fe2e1795473b.png)
it seems that library has add "final" to "R.java"。But why also can't I use it like "@BindView(R.id.iv_loading)"?

**Comment by JakeWharton** [comment]
Final IDs for libraries only exist in the app module, not in the library module itself where the code with `@BindView` is being compiled. And the app module will soon use non-final IDs as well.
