### ISSUE TITLE
WARNING: API 'variantOutput.getProcessResources()'

### ISSUE THREAD

**Issue by shubugarg45** [JakeWharton/butterknife#1532]
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by JakeWharton** [comment]
Dupe of #1431

**Comment by shubugarg45** [comment]
> Dupe of #1431


After this 
apply plugin: 'com.android.library' 

ERROR: Android Gradle plugin 3.4.1 must not be applied to project 'E:\DelhiDarbar\app' since version 3.4.1 was already applied to this project
Open File
 this occurs
