### ISSUE TITLE
R2 not being generated in dynamic-feature modules

### ISSUE THREAD

**Issue by elksa** [JakeWharton/butterknife#1533]
Hi, I recently updated my project to user dynamic features and butterknife stopped working. I'm using the latest stable version of Android Studio and gradle plugin, here are the project level dependencies:

```
dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'
    }
```

Now, in my module, which is a dynamic-feature, I cannot get butterknife to work, R2 is missing. Here is the gradle configuration of the module:

```
apply plugin: 'com.android.dynamic-feature'
apply plugin: 'com.jakewharton.butterknife'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':app')
}
```

I've also dropped this question in StackOverflow, but no answers so far, so I'm guessing it is a butterknife issue, since the doc doesn't include the case of `com.android.dynamic-feature` instead of `com.android.library`

[Butterknife not working in dynamic-feature sub-project: error: package R2 does not exist](https://stackoverflow.com/questions/56961759/butterknife-not-working-in-dynamic-feature-sub-project-error-package-r2-does-n)

**Comment by JantHsueh** [comment]
Currently `apply plugin: 'com.android.dynamic-feature'` not supported  generating R2 

Supported   generating R2  plugins
`
apply plugin: 'com.android.feature
`
`
apply plugin: 'com.android.library
`
`
apply plugin: 'com.android.application
`

**Comment by elksa** [comment]
> Currently `apply plugin: 'com.android.dynamic-feature'` not supported generating R2
> 
> Supported generating R2 plugins
> `apply plugin: 'com.android.feature'`
> `apply plugin: 'com.android.library'`
> `apply plugin: 'com.android.application'`

Thanks but your answer pretty much says what doesn't work, not what it does. `R2` is not supported in this kind of module, now the documentation does not say anything about `'com.android.dynamic-feature'`. However I found a had an unrelated issue causing crashes while testing with `R`, which is properly generated and yes, `'com.android.dynamic-feature'` modules works perfectly with `R`, no issues there, **problem solved**.

Just a recommendation to @JakeWharton ...please update the documentation accordingly, and maybe just give a look at newly opened issues, this one's been unattended for weeks. Before I found the real issue I preventively migrated a couple of small personal projects to `data binding` for the lack of support...just saying.

Thanks!
