### ISSUE TITLE
butterknife-reflect behaves differently for @Nullable fields

### ISSUE THREAD

**Issue by simonschiller** [JakeWharton/butterknife#1541]
We recently tried out `butterknife-reflect` to speed up debug builds and found an inconsistency between the reflection and the annotation processor library.

We were binding a view which was marked with `androidx.annotation.Nullable` and it worked correctly with the annotation processor, however when we tried the reflection lib it started to fail. This is because the annotation has a retention policy of `CLASS`, which means it doesn't need to be retained at runtime by the VM, so `butterknife-reflect` does not pick it up and throws an exception because the view is missing. It works when we switch to `javax.annotation.Nullable`, since that one has a retention of `RUNTIME`.

There's nothing Butterknife can do to change this behavior, but I think it should be mentioned either in the `README` of `butterknife-reflect` and/or the website, especially since `androidx.annotation.Nullable` is the recommended annotation.

**Comment by JakeWharton** [comment]
Are you using 10.1.0? The reflection library no longer validates when required views are absent (you'll get an NPE when you try to access it anyway) as of that version.

**Comment by simonschiller** [comment]
We were using 10.0.0, I'll check the new version, thanks for the fast response
