### ISSUE TITLE
Nested duplicated view ids and a way to retrieve them through Butterknife

### ISSUE THREAD

**Issue by metaphore** [JakeWharton/butterknife#155]
The general problem and solution described here:
http://stackoverflow.com/questions/11265150/android-different-ids-for-the-same-include-layout

And my question is how retrieve such views using Butterknife. I've listed site examples and seems there is no solution for now. I suppose it's gonna be a feature request.

So, what do you think about it?

**Comment by grennis** [comment]
I dont think creating a custom view is necessary. Just create a class:

        public class WhateverHolder {
            @BindView(R.id....) TextView some;
            @BindView(R.id....) TextView thing;
        }

Then one extra call to bind views:

    Butterknife.bind(this)
    Butterknife.bind(parentView, holder)

Seems easier and more intuitive.

**Comment by sarayuk** [comment]
@OnClick({ R.id.door1, R.id.door2, R.id.door3 })
public void pickDoor(DoorView door) {
  if (door.hasPrizeBehind()) {
    Toast.makeText(this, "You win!", LENGTH_SHORT).show();
  } else {
    Toast.makeText(this, "Try again", LENGTH_SHORT).show();
  }
}
