### ISSUE TITLE
Onclick, a parent and child class, cannot take effect

### ISSUE THREAD

**Issue by tianshaokai** [JakeWharton/butterknife#1564]
Onclick, a parent and child class, cannot take effect

**Comment by JakeWharton** [comment]
I'm not sure what you're asking but there's far too little of information here. Butter Knife plays no part in the behavior of how Android dispatches click events, it just binds methods to callbacks automatically, no different than you would manually.

Without more information, there's no action to take here.

**Comment by tianshaokai** [comment]
I solved the problem
