### ISSUE TITLE
Layout name conflict

### ISSUE THREAD

**Issue by gh7800** [JakeWharton/butterknife#1565]
ButterKnife 9.0.0
If there are layouts with the same name in the two libraries referenced, an error will be reported, and the view id of the last bind will not be found.
I can only modify the layout name

error 
`No field road_repair_bt of type I in class Lcn/shineiot/work/R$id,or its superclasses (declaration of 'cn.shineiot.work.R$id' appears in /data/app/cn.shineiot.check-1/base.apk:classes2.dex)`

**Comment by JakeWharton** [comment]
Can you reproduce this in a sample and attach it or link to it? I'm not sure what exactly Butter Knife would do wrong here.

**Comment by Kurdenes21** [comment]
Hi
