### ISSUE TITLE
How to modify the directory of generated code by apt?

### ISSUE THREAD

**Issue by qujc** [JakeWharton/butterknife#1566]
I am writing an template java file for testing , and i want it to be generated to src/test/java directory, who knows that how to modify the file directory when i using apt?

**Comment by qujc** [comment]
Help me please!!

**Comment by qujc** [comment]
when i use `System.getProperty("user.dir") ` in annotation processor , it returns "/Users/XXX/Library/Application Support/kotlin/daemon" but not the project working path, i don't known why~

**Comment by JakeWharton** [comment]
The directory is dictated by `javac` and Butter Knife has no control over it.

**Comment by Kurdenes21** [comment]
Hello

**Comment by Kurdenes21** [comment]
#1566

**Comment by Kurdenes21** [comment]
#1566
