### ISSUE TITLE
java error error: '{' expected

### ISSUE THREAD

**Issue by andrehardianto** [JakeWharton/butterknife#1567]
tried to build android app project on using android studio but get this error " error: '{' expected ".
Here is my java script :
package com.android.torajaphotoviewer;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ImageView;

import com.android.TorajaPhotoViewer.R;
import com.bumptech.glide.Glide;

import java.io.File;

/**
 * Created by ANDRE HARDIANTO ON 18/NOV/2019.
 */
public class GalleryPreview extends AppCompatActivity {

    ImageView GalleryPreviewImg;
    String path;
    @Override
    protected class onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getSupportActionBar().hide();
        setContentView(R.layout.activity_main);
        Intent intent = getIntent();
        path = intent.getStringExtra("path");
        GalleryPreviewImg = (ImageView) findViewById(R.id.GalleryPreviewImg);
        Glide.with(GalleryPreview.this)
                .load(new File(path)) // Uri of the picture
                .into(GalleryPreviewImg);
    }
}

someone please help me i am new to java programing :)

**Comment by JakeWharton** [comment]
There is no Butter Knife in this sample. These issues are not a place for general-purpose help with Java or Android, sorry.
