### ISSUE TITLE
Unable to load class 'com.google.common.collect.ImmutableSet'.

### ISSUE THREAD

**Issue by yaochangliang159** [JakeWharton/butterknife#1570]
when i user butterknife 10.2.0,i meet this problem my butterknife version is 10.2.0
in my external library ,I did not find package"com.google.common.xxxxxxx"
<img width="1263" alt="WX20191115-152809@2x" src="https://user-images.githubusercontent.com/13497352/69951733-ca028e00-1530-11ea-9ffe-ecfab52f5b53.png">
<img width="559" alt="WX20191202-182158@2x" src="https://user-images.githubusercontent.com/13497352/69951750-cf5fd880-1530-11ea-9b9d-a751ad03613c.png">

<img width="815" alt="WX20191202-182412@2x" src="https://user-images.githubusercontent.com/13497352/69951839-fe764a00-1530-11ea-9118-e48875ae0b31.png">
<img width="1010" alt="WX20191202-182426@2x" src="https://user-images.githubusercontent.com/13497352/69951848-033afe00-1531-11ea-8ed1-154676a6a540.png">

**Comment by yaochangliang159** [comment]
i am sorry ,i use "annotationProcessor butterknife-compiler" instead of "api butterknife-compiler",it running OK!

**Comment by kelloxu** [comment]
Have you solved this prolem? I met the same problem after updating android studio to 3.5, i don`t know how to solve it.
