### ISSUE TITLE
ViewBinding SOMETIMES not generated in Butterknife 10.2.0

### ISSUE THREAD

**Issue by Lingviston** [JakeWharton/butterknife#1571]
I can see a lot of similar issues in the tracker, but I might have more details so don't won't to have them lost in one of the potential duplicates.

So, I updated Butterknife in the project from 10.1.0 to 10.2.0. Just bumped the version, no other changes. After that sometimes after build ViewBinding class for one of the fragments is not generated. 

Idk it just one fragment suffers from this issue or there're more. I just know that sometimes after rebuild ViewBinding for this fragment gets generated and sometimes not. I have a feeling that it might be related to incremental annotation processing, but we don't declare it explicitly. Gradle 6.0 is being used BTW.

Some specifics of the fragment:
1. Written in Java;
2. Does binding in onViewCreated, not in onCreateView.

Issue is reproducible on several PCs. Sometimes after rebuild all works fine however.

**Comment by JakeWharton** [comment]
It's not clear what action you want the project to take. If it's an incremental annotation processing bug then it should be reported to Kotlin if you are using kapt. Ideally a reproduction project and steps would be included.

**Comment by Lingviston** [comment]
@JakeWharton excuse me for the misleading description. Fragment is written in Java. Fixed.

**Comment by JakeWharton** [comment]
That just means the target for the bug shoud be Gradle instead of Kotlin.

**Comment by Lingviston** [comment]
It is just a suggestion that incremental annotation processing is involved, cause that's the major change in Butterknife 10.2.0, issue appears right after bumping BK version and issue itself is a class not being generated. But I can't know for sure.

Notice, that I don't have incremental annotation processing enabled anywhere in the project. So, again it was just a suggestion that smth might've gone wrong during refactoring to support this feature.

**Comment by JakeWharton** [comment]
Incremental annotation processing is not opt-in. Without a reproduction project and steps it's impossible to know.

**Comment by danielwilson1702** [comment]
My problem must be totally unrelated, but after upgrading to 10.2.0 and shoving some Kotlin into my app, `annotationProcessor` no longer generated Butterknife code and after heeding the build warning about it to use `kapt` instead, it was fixed even though I don't have any Butterknife in Kotlin code.

**Comment by Lingviston** [comment]
@JakeWharton given that this issue has been encountered by other users as well (according to the references above) was it closed because it was fixed?

I'm still struggling to reproduce the problem in sandbox conditions, but I have the in production project, where it can be reproduced easily. Is there a way for me to grab some Butterknife logs for you from that project?
