### ISSUE TITLE
why the annotations change from RUNTIME to CLASS

### ISSUE THREAD

**Issue by DaveBoy** [JakeWharton/butterknife#1572]
hello
i read the source code again to study the principle,but i found the annotations for the [bindView](https://github.com/JakeWharton/butterknife/blob/master/butterknife-annotations/src/main/java/butterknife/BindView.java) have change .
```
@Retention(RUNTIME) @Target(FIELD)
public @interface BindView {
  /** View ID to which the field will be bound. */
  @IdRes int value();
}
```
i think it creat xxx_viewbinding file when build before,what is the reason to make you change it from **RUNTIME** to **CLASS**

**Comment by JakeWharton** [comment]
They changed from class to runtime, not the opposite. It was so that the [butterknife-reflect artifact](https://github.com/JakeWharton/butterknife/tree/master/butterknife-reflect#readme) could read them at runtime.
