### ISSUE TITLE
 it doesn't bind my custom views in Fragment（androidx.fragment.app.Fragment）without error，but normal in Fragment of android.app.Fragment and  Activity

### ISSUE THREAD

**Issue by fqingyang** [JakeWharton/butterknife#1575]
package com.baqiinfo.plugintest;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import butterknife.BindView;
import butterknife.OnClick;

public class HomeFragment extends Fragment {
    @BindView(R.id.tv_hello)
    TextView tvHello;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment_home, container, false);
         //here  not bind this view  and no  'unbinder.unbind()'  in 'onDestroyView' method
        return view;
    }

    @OnClick(R.id.tv_hello)
    public void onViewClicked() {
    }
}

**Comment by goldfish07** [comment]
Butterknife.bind(getContext(),view);

**Comment by JakeWharton** [comment]
Yep, what @goldfish07 said. You need to call `bind` and that will provide you the `Unbinder`.
