### ISSUE TITLE
Feature Request: @OnTouch

### ISSUE THREAD

**Issue by martyglaubitz** [JakeWharton/butterknife#158]
Annotations for injecting touch listeners would be great! The target method of this annotation could llok like this

``` java
@OnTouch(R.id.txt_example)
void exampleTouched(View v, MotionEvent ev) {
    //stuf yo
}
```

**Comment by shobhitpuri** [comment]
@jdreesen It doesn't seem to take `MotionEvent` as a parameter? On the docs, it is not mentioned as one of the options params as well. Does it exist but is undocumented?

**Comment by martyglaubitz** [comment]
@shobhitpuri it's just not mentioned, just ad an MotionEvent parameter...

**Comment by shobhitpuri** [comment]
Awesome. Thanks!

**Comment by abiemann** [comment]
https://github.com/JakeWharton/butterknife/blob/master/butterknife-annotations/src/main/java/butterknife/OnTouch.java
