### ISSUE TITLE
android studio 3.6 id will not refresh

### ISSUE THREAD

**Issue by WTree** [JakeWharton/butterknife#1590]
android studio 3.6 id will not refresh
use kotlin ,
env:
   implementation 'com.jakewharton:butterknife:10.2.1'
    kapt 'com.jakewharton:butterknife-compiler:10.2.1'

**Comment by JakeWharton** [comment]
There is not enough information here to make an actionable bug report. Please consider creating a sample that reproduces the problem or otherwise describing in far more detail what you are seeing.
