### ISSUE TITLE
v10.2.1 Replace implementation with annotationProcessor

### ISSUE THREAD

**Issue by enriquebautista** [JakeWharton/butterknife#1593]
Why?
When migrate to AndroidX

<img width="708" alt="Captura de Pantalla 2020-03-11 a la(s) 16 05 44" src="https://user-images.githubusercontent.com/37681056/76468780-651dc600-63b2-11ea-82b4-f45ec57e3901.png">

**Comment by JakeWharton** [comment]
Seems like an Android Studio bug. File it on them.

**Comment by ronykrell** [comment]
Just as an FYI having this as annotationProcessor caused Android Studio 3.6.1 to not download butterknife as an external library which caused the build to fail
