### ISSUE TITLE
How to resolve multiple choices in Android Studio?

### ISSUE THREAD

**Issue by jimmysuncpt** [JakeWharton/butterknife#1599]
Since using the ButterKnife, my Android Studio always occur such error:

![image](https://user-images.githubusercontent.com/20553676/78105741-73488a80-7424-11ea-8500-10a3852a69da.png)

Although I can run the app, it also affected developing efficiency.

So how to resolve it?

**Comment by JakeWharton** [comment]
This is an IDE bug, please file it on Android Studio. It should not be prompting you for an import to a field inside of an `R.id` class reference.
