### ISSUE TITLE
[Question] How to define butterknife.minSdk via a gradle task?

### ISSUE THREAD

**Issue by andromedcodes** [JakeWharton/butterknife#1600]
Is there any way to setup these args using a gradle task written in Kotlin? I have tried this but it doesn't seem to work:
```
variants.all { variant ->
            variant.javaCompileOptions.annotationProcessorOptions.apply {
                arguments.put("navigator.package.name", "my.package.name")
            }
 }
```

**Comment by JakeWharton** [comment]
You cannot define it from a task. You can define it from the regular DSL though. Here's an example of global and build type-specific: https://github.com/JakeWharton/butterknife/issues/1046#issuecomment-322177287
