### ISSUE TITLE
Website should have deprecation notice

### ISSUE THREAD

**Issue by kierans** [JakeWharton/butterknife#1607]
I've returned to Android dev after a hiatus, and am learning all the major changes in development tools. I remembered Butterknife, but only saw it's deprecation message on the GitHub README, not the website. If I haven't bothered to look at the repo, I would be using Butterknife on my new project instead of View Bindings 😆 

I think it would be a great service to new (or returning) players to put the deprecation message on the website since that's what Google shows up in its results.

**Comment by JakeWharton** [comment]
Makes sense. I'm on vacation, but PR welcome.
