### ISSUE TITLE
butterknife9和gradle4.0冲突

### ISSUE THREAD

**Issue by wangyuan0217** [JakeWharton/butterknife#1614]
as4.0中用gradle4.0.0和butterknife9冲突，
error:
Attempt to use @BindView for an already bound ID 0 on 'xxx'

classpath 'com.android.tools.build:gradle:4.0.0'
classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0'

**Comment by JakeWharton** [comment]
AGP 3.6 or newer requires version 10.2.1 because the `R.txt` changed to use 0 for every resource entry value. In 10.2.1 we now generate our own unique values.

**Comment by wangyuan0217** [comment]
ths, so updated to androidx.
