### ISSUE TITLE
Required view 'fab' with ID 2131362202 for field 'fab' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

### ISSUE THREAD

**Issue by RahatSaqib** [JakeWharton/butterknife#1617]
I tried clean project.setContentView still in position all the other field is ok but in the case of fab field its not working.
This is 46 th line. it shows fine.. I cannot find any fab field. its a editFab field.
![46](https://user-images.githubusercontent.com/37343956/85834593-7c43c080-b7b5-11ea-8ab8-dbba4b8996fc.PNG)

**Comment by JakeWharton** [comment]
This means that calling `source.findViewById(R.id.editFab)` is returning null. This is true regardless of your use of Butter Knife. Your inflated layout is missing a view with that ID, somehow.
