### ISSUE TITLE
What's an alternative for `DebouncingOnClickListener`?

### ISSUE THREAD

**Issue by MyDogTom** [JakeWharton/butterknife#1629]
Butterknife has built-in click debouncing mechanism implemented by `DebouncingOnClickListener` https://github.com/JakeWharton/butterknife/blob/master/butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java

Since now Butterknife is deprecated, I wonder what's is the alternative for debouncing mechanism? Do I need to do any extra setup while using view binding?

**Comment by JakeWharton** [comment]
Copy it into your codebase and use it to create listeners.

This is one of my biggest regrets. I wish it was never included. So consider just not doing anything.
