### ISSUE TITLE
 Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes

### ISSUE THREAD

**Issue by LimeVista** [JakeWharton/butterknife#1634]
About Android Studio 4.1 Warning.
Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes.
More Infomation: http://tools.android.com/tips/non-constant-fields.

**Comment by JakeWharton** [comment]
Non-final resource IDs have been supported for a few years now. Apply the plugin and use R2 as detailed in the readme.

Or, even better, stop using Butter Knife and use view binding!

**Comment by LimeVista** [comment]
Thanks.
