### ISSUE TITLE
 Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes

### ISSUE THREAD

**Issue by tarunsharmaa91** [JakeWharton/butterknife#1635]

**Comment by isuudev** [comment]
![image](https://user-images.githubusercontent.com/14130892/96096095-07ca9400-0f02-11eb-9466-6389204caf10.png)

upgrade gradle & Android Studio 4.1

**Comment by UNDevid** [comment]
Same problem, is this a code-breaking issue?

**Comment by hoordev** [comment]
I have also with Android Studio 4.1 (AI-201.8743.12.41.6858069) and gradle 6.5

**Comment by JakeWharton** [comment]
See #1634. Tl;dr use R2 or migrate to view binding.

**Comment by tarunsharmaa91** [comment]
Thanks, I think migrating to view binding would be better

**Comment by Sylviie** [comment]
> See #1634. Tl;dr use R2 or migrate to view binding.

In fact, I used R2 replacing R. This warning exists always.

**Comment by sebastianharder** [comment]
@JakeWharton, I also get this warning while using R2.

**Comment by piotrros** [comment]
Should I be worry about this warning? Will it break this library?

**Comment by W-quan** [comment]
Problem is the file is not in the `library` after upgrade `Android Studio 4.1`
