### ISSUE TITLE
What is suggested replacement for @OnClick annotation, with butterknife deprecated?

### ISSUE THREAD

**Issue by ridcully99** [JakeWharton/butterknife#1637]
You suggest to switch to JetPack ViewBinding, which seems ok for views, but it is no replacement for butterknife's @OnClick and similar annotations. Is there a suggested / best-practice replacement for those? Also, thank you very much for this great library, which made life much easier for me for many years.

**Comment by JakeWharton** [comment]
Either using a lambda directly
```java
binding.view.setOnClickListener(v -> {
  doSomething();
  doSomethingElse();
});
```
or using a lambda to call a method
```java
binding.view.setOnClickListener(v -> viewClicked());

void viewClicked() {
  doSomething();
  doSomethingElse();
