### ISSUE TITLE
Android butterknife zelezny   plug-in can not be used properly

### ISSUE THREAD

**Issue by qianfeifeio** [JakeWharton/butterknife#1638]
android studio update to version 4.1, butterknife plug-in failure can not be used properly, how to solve ？

**Comment by JakeWharton** [comment]
That plugin is separate maintained in https://github.com/avast/android-butterknife-zelezny. It looks like it's no longer supported so there's little hope in seeing a fix.

Note that butter knife is also in maintenance mode, and that you should probably migrate to view binding in the coming months.
