### ISSUE TITLE
Don't load data from firebase to MainScreen

### ISSUE THREAD

**Issue by thang1234xx** [JakeWharton/butterknife#1640]
I have implemented the above code, no error occurs. However, when running the virtual machine, there is no database displayed. I don't know where my fault is. Can I help you? Thank you

private void loadAllStateFromFireStore() {
        dialog.show();

        allStadiumCollection
                .get()
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        iOnAllStateLoadListener.onAllStateLoadFailed(e.getMessage());
                    }
                }).addOnCompleteListener(new OnCompleteListener<QuerySnapshot>() {
            @Override
            public void onComplete(@NonNull Task<QuerySnapshot> task) {
                if (task.isSuccessful())
                {
                    List<District> districts = new ArrayList<>();
                    for (DocumentSnapshot districtSnapshot:task.getResult())
                    {
                        District district = districtSnapshot.toObject(District.class);
                        districts.add(district);

                    }
                    iOnAllStateLoadListener.onAllStateLoadSuccess(districts);
                }
            }
        });

    }

**Comment by JakeWharton** [comment]
This has nothing to do with Butter Knife.

**Comment by thang1234xx** [comment]
This problem in code or in the library? 
public class MyStateAdapter extends RecyclerView.Adapter<MyStateAdapter.MyViewHolder> {

    Context context;
    List<District> districtList;

    int lasPosition=-1;

    public MyStateAdapter(Context context, List<District> districtList) {
        this.context = context;
        this.districtList = districtList;
    }

    @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(context)
                .inflate(R.layout.layout_state,parent,false);

        return new MyViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(@NonNull MyViewHolder holder, int i) {
        holder.txt_state_name.setText(districtList.get(i).getName());
        setAnimation(holder.itemView,i);

        holder.setiRecyclerItemSelectedListener((view, position) -> {
            Common.state_name = districtList.get(i).getName();
            context.startActivity(new Intent(context, StadiumListActivity.class));
        });

    }

    private void setAnimation(View itemView, int position) {
        if (position>lasPosition)
        {
            Animation animation = AnimationUtils.loadAnimation(context,
                    android.R.anim.slide_in_left);
            itemView.startAnimation(animation);
            lasPosition = position;
        }
    }


    @Override
    public int getItemCount() {
        return districtList.size();
    }

    public class MyViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
        @BindView(R.id.txt_state_name)
        TextView txt_state_name;
        IRecyclerItemSelectedListener iRecyclerItemSelectedListener;

        public void setiRecyclerItemSelectedListener(IRecyclerItemSelectedListener iRecyclerItemSelectedListener) {
            this.iRecyclerItemSelectedListener = iRecyclerItemSelectedListener;
        }

        public MyViewHolder(@NonNull View itemView) {
            super(itemView);
            ButterKnife.bind(this,itemView);

            itemView.setOnClickListener(this);
        }

        @Override
        public void onClick(View view) {
            iRecyclerItemSelectedListener.onItemSelectedListener(view,getAdapterPosition());
        }
    }
}

**Comment by thang1234xx** [comment]
In this project only page MainActivity an MyStateAdapter , I will paste code in this

**Comment by thang1234xx** [comment]
private void init() {
        allStadiumCollection = FirebaseFirestore.getInstance().collection("AllStadium");
        iOnAllStateLoadListener = this;
        dialog = new SpotsDialog.Builder().setContext(this)
                .setCancelable(false)
                .build();
    }

    private void initView() {
        recycler_state.setHasFixedSize(true);
        recycler_state.setLayoutManager(new GridLayoutManager(this,2));
        recycler_state.addItemDecoration(new SpacesItemDecoration(8));


    }

    @Override
    public void onAllStateLoadSuccess(List<District> districtList) {
        adapter = new MyStateAdapter(this,districtList);
        recycler_state.setAdapter(adapter);

        dialog .dismiss();

    }

    @Override
    public void onAllStateLoadFailed(String message) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show();

        dialog .dismiss();

    }
}
