### ISSUE TITLE
When binding some virtual keys, it prompts that the binding fails

### ISSUE THREAD

**Issue by ToFigting** [JakeWharton/butterknife#1653]
When binding some virtual keys, it prompts that the binding fails，For example <com.google.android.material.tabs.TabItem> But adding @Nullable when binding the control, it can run correctly。I want to know what is done inside the code?

**Comment by JakeWharton** [comment]
The material component library removes IDs from TabItem instances. The tracking bug is at https://github.com/material-components/material-components-android/issues/1162. You have to bind the TabLayout and go through its API to access the tabs.

**Comment by ToFigting** [comment]
Thank you for your reply and have a good time








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JakeWharton/butterknife"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 凌晨1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JakeWharton/butterknife] When binding some virtual keys, it prompts that the binding fails (#1653)





 
The material component library removes IDs from TabItem instances. The tracking bug is at material-components/material-components-android#1162. You have to bind the TabLayout and go through its API to access the tabs.
