### ISSUE TITLE
Task :app:processDebugMainManifest FAILED

### ISSUE THREAD

**Issue by Aditya1405** [JakeWharton/butterknife#1656]
please, someone have a look at this error.
i am trying to run a react-native app and i cant seem to run it.

![image](https://user-images.githubusercontent.com/52049053/116738323-e9e0fe80-aa0f-11eb-8ed7-d71b066a3bd0.png)

**Comment by JakeWharton** [comment]
I don't see anything related to this library in that output. Moreover, it's unlikely that we would be able to cause any problems in the manifest processing task since our sum total contribution to the manifest is zero.
