### ISSUE TITLE
Cannot resolve method 'findById' in 'ButterKnife'

### ISSUE THREAD

**Issue by KanwalKhan-20** [JakeWharton/butterknife#1659]
CheckedTextView checkedTextView = ButterKnife.findById(view,view.getId());
It is giving error
Cannot resolve method 'findById' in 'ButterKnife'

**Comment by JakeWharton** [comment]
It was removed in version 9. You can use `view.findViewById`, but calling that with `view.getId()` is useless as it will always return itself.
