### ISSUE TITLE
Could not find com.android.tools.build:gradle:3.3.0. Required by:butterknife-gradle-plugin:10.2.1

### ISSUE THREAD

**Issue by Arick-a** [JakeWharton/butterknife#1661]
Android Studio version 4.2.1
Could not find com.android.tools.build:gradle:3.3.0.
Searched in the following locations:
  - http://15r262l208.51mypc.cn:18081/nexus/content/groups/public/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :base > com.jakewharton:butterknife-gradle-plugin:10.2.1
Add google Maven repository and sync project
Open File

**Comment by JakeWharton** [comment]
It is available in the `google()` repository which you should add to your `repositories { }` block. Or, if you're using a proxy, add it to the list of the repositories which are proxied as https://maven.google.com/.
