### ISSUE TITLE
Change butterknife generating android support annotation to androidx annotation

### ISSUE THREAD

**Issue by guolingege** [JakeWharton/butterknife#1664]
I am changing my project from android support to androidx, but the butterknife is generating android.support.annotation.* codes in *_ViewBinding.java files as following:

<img width="550" alt="WX20210803-143201@2x" src="https://user-images.githubusercontent.com/13193905/127970772-273f169f-a83e-4268-aa5e-ad171d2a424e.png">

How can I correct it?
Hurry, waiting online😂thanks

**Comment by JeckChou** [comment]
you can use viewbinding instead

**Comment by guolingege** [comment]
> you can use viewbinding instead

How to?

**Comment by JeckChou** [comment]
> > you can use viewbinding instead
> 
> How to?

please refer to https://developer.android.com/topic/libraries/view-binding

**Comment by guolingege** [comment]
> > > you can use viewbinding instead
> > 
> > 
> > How to?
> 
> please refer to https://developer.android.com/topic/libraries/view-binding

Thank you

**Comment by JakeWharton** [comment]
The latest version only supports AndroidX. Upgrade to the latest.
