### ISSUE TITLE
Annotations retentions policy

### ISSUE THREAD

**Issue by nilesh1433** [JakeWharton/butterknife#1666]
As far as I understand, annotations like @BindView are used to generate the binding code. 
Also for library modules, R2.java gets generated, which is referenced in the annotation to bind a view. 

The problem with the retention policy set to Runtime is the R2 files need to be packaged in the main app resulting in a bloated app size.

Can we mark all the annotation with retention policy as compile which will help in getting rid of R2.java file since in the end the generated code references R.java?

**Comment by JakeWharton** [comment]
They are runtime to allow butterknife-reflect to work.

Butter Knife is deprecated and will not be changing. Please migrate to view binding: https://developer.android.com/topic/libraries/view-binding
