### ISSUE TITLE
 Could not resolve com.jakewharton:butterknife-compiler:10.2.3.

### ISSUE THREAD

**Issue by Fanoo** [JakeWharton/butterknife#1672]
Could not resolve com.jakewharton:butterknife-compiler:10.2.3.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/jakewharton/butterknife-compiler/10.2.3/butterknife-compiler-10.2.3.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/jakewharton/butterknife-compiler/10.2.3/butterknife-compiler-10.2.3.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect

**Comment by JakeWharton** [comment]
There is nothing this library can do to solve your connectivity issues with Maven Central. In all likelihood it was just a temporary problem, but if it persists you can file an issue on https://issues.sonatype.org/.
