### ISSUE TITLE
Issue with  androidx.annotation:annotation:1.0.0 not being found

### ISSUE THREAD

**Issue by o-glethorpe** [JakeWharton/butterknife#1679]
Hi, I'm having problem when trying to run my application.
It seems to me that one of the dependencies of butterknife is not available anymore.
I already tried to install this dependency separately without success.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugAnnotationProcessorClasspath'.
   > Could not resolve androidx.annotation:annotation:1.0.0.
     Required by:
         project :app > com.jakewharton:butterknife-compiler:10.2.1 > com.jakewharton:butterknife-annotations:10.2.1
      > Could not resolve androidx.annotation:annotation:1.0.0.
         > Could not get resource 'http://dl.bintray.com/amulyakhare/maven/androidx/annotation/annotation/1.0.0/annotation-1.0.0.pom'.
            > Could not HEAD 'http://dl.bintray.com/amulyakhare/maven/androidx/annotation/annotation/1.0.0/annotation-1.0.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by EesiLife** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法回复您的邮件。我将尽快给您回复。
