### ISSUE TITLE
Execution failed for task ':app:processDebugManifest'

### ISSUE THREAD

**Issue by ndpetwar** [JakeWharton/butterknife#1681]
i am getting this issue sice two days and unable to find any solution kindly help

1. Run screen error message-----------------------

[com.google.android.gms:play-services-maps:18.1.0] C:\Users\Jyoti Hooda\.gradle\caches\transforms-2\files-2.1\8abfad32f959105153a685c4bd0cfbb4\play-services-maps-18.1.0\AndroidManifest.xml:33:9-64 Error:
	Missing 'package' key attribute on element package at [com.google.android.gms:play-services-maps:18.1.0] AndroidManifest.xml:33:9-64
[com.google.android.gms:play-services-maps:18.1.0] C:\Users\Jyoti Hooda\.gradle\caches\transforms-2\files-2.1\8abfad32f959105153a685c4bd0cfbb4\play-services-maps-18.1.0\AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
------------------------------------------------------------------------
2.build.gradle file---------------------------------

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 33

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_gstmmobileapp"
        minSdkVersion 20
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
------------------------------------------------------------------------------------------

**Comment by JakeWharton** [comment]
The error message indicates play-services-maps is the problem, not this library.
