### ISSUE TITLE
Android Studio Flamingo(2022.2.1 Patch 1) build issue

### ISSUE THREAD

**Issue by intlzone** [JakeWharton/butterknife#1687]
Cause: superclass access check failed: class butterknife.compiler.ButterKnifeProcessor$RScanner (in unnamed module @0x5a3277f9) cannot access class com.sun.tools.javac.tree.TreeScanner (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x5a3277f9

**Comment by JakeWharton** [comment]
Duplicate of #1686
