### ISSUE TITLE
NullpointerException in onFocusChange (Fragment)

### ISSUE THREAD

**Issue by kjsolo** [JakeWharton/butterknife#170]
Fragment:
@InjectView(R.id.root) KeyboardDetectorRelativeLayout rootView;
@InjectView(android.R.id.edit) CommentEditText editView;

onCreateView:
  View view = ...;
  ButterKnife.inject(this, view);

onActivityCreated:
  editView.setOnFocusChangeListener(this);

onDestroyView:
  ButterKnife.reset(this);

onFocusChange:
  switch (v.getId()) {
            case android.R.id.edit:
                rootView.addKeyboardStateChangedListener(this);
                break;
  }

The order of execution: [Press back/return] -> onFocusChange -> onDestoryView -> onFocusChange -> NullPointerException by rootView.

**Comment by ivashov** [comment]
Why did you close this issue? Is it correct that unbind doesn't clear listeners that was previously set by bind?

**Comment by serj-lotutovici** [comment]
@ivashov in 8.0.0-SNAPSHOT the `unbind()` method moved to `ButterKnife.Unbinder` interface... the binded/generated `Unbinder` class clears out all listeners set by `ButterKnife.bind()`

**Comment by mithepner** [comment]
I think this is still an issue. I'm not using ButterKnife.  onFocusChange gets triggered when the fragment is being cleaned up.  So the views injected by @ViewById are null.  

In the generated code for 4.0.0 the null check for the view has moved to the onViewChanged method.  In previous versions the null check was inside the onFocusChange method.  I have only seen this when my fragment is in the backstack and the activity is finishing.
