### ISSUE TITLE
ButterKnife and ProGuard (again)

### ISSUE THREAD

**Issue by fabiencheret** [JakeWharton/butterknife#18]
Hey.

I'm trying to run proguard on my application, which use butterknife.
I added 
`-keep class **$$ViewInjector`
to the proguard config file, and I have this error

Android Dex: [ctc-mobile-android] Warning: butterknife.Views$InjectViewProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor

I don't know what to do here...
If you guys have a solution...
Thanks.

**Comment by smithliu** [comment]
Thank you
