### ISSUE TITLE
Proposed API naming change: View Binding @BindView and ButterKnife.bindView{s}()

### ISSUE THREAD

**Issue by cgruber** [JakeWharton/butterknife#196]
Injection is an overloaded term.  Maybe re-name everything to View Binding or ViewMapping

I have in mind

    @BindView(R.id.bar) SomeView myView
    // ...
    ButterKnife.bindViews(this)
    // ...
    ButterKnife.bindView(this, view);

This is partly to separate it from the injection of collaborators per JSR-330, and partly to bring it into slightly more consistency with historical UI MVC frameworks who tend to "bind" UI elements to Controller elements, etc.

**Comment by ming13** [comment]
:+1:

The naming is a great joke, but it is terrifying sometimes to hear people who *really* think `DI == BK`.

**Comment by artem-zinnatullin** [comment]
That's the reason why I use `KotterKnife`

**Comment by JakeWharton** [comment]
This is already on `master`
