### ISSUE TITLE
Add Support For Non-Final IDs

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/butterknife#2]
Android's resource system is disaster and to unbreak library projects last year they made the IDs non-final.

`@InjectView(id = "title") TextView title`

``` java
Context context = activity.getApplicationContext();
String packageName = context.getPackageName();
Resources res = context.getResources();
// ...
int id = res.getIdentifier(packageName, "android:id", annotation.id());
```

**Comment by frostymarvelous** [comment]
just run into this issue too. guess butterknife is out of my library then. but ooo, it made my code that much cleaner.

**Comment by sosite** [comment]
Sorry guys for the spam but +1 from me too

**Comment by jaredsburrows** [comment]
+1

**Comment by flywheelms** [comment]
+1000
