### ISSUE TITLE
View Injection Fails with Android Bootstrap 

### ISSUE THREAD

**Issue by donnfelker** [JakeWharton/butterknife#20]
View Injection is failing in [Android Bootstrap](https://github.com/donnfelker/android-bootstrap/issues/33). The error that is happening is: 

java.lang.ClassNotFoundException: com.donnfelker.android.bootstrap.ui.CarouselActivity$$ViewInjector

From what I can tell we're doing everything correctly as according to the docs, but it seems to be broken now. Any ideas what might be causing this? 

Note, the line where the app is bombing out is: https://github.com/JakeWharton/butterknife/blob/master/butterknife/src/main/java/butterknife/Views.java#L109, then an exception is caught and the app moves on, the views are then null .

**Comment by PenguinBlues** [comment]
We also had this exception logged but, so far, only for one Samsung 5.0.1 device. We are also unable to reproduce the exception.
