### ISSUE TITLE
Field is not initialized for Jack and Jill enabled

### ISSUE THREAD

**Issue by misa** [JakeWharton/butterknife#207]
There is a new tool chain for Android (experimental):
http://android-developers.blogspot.cz/2014/12/hello-world-meet-our-new-experimental.html

Field `mTest` is not initialized properly:

``` java
@InjectView(R.id.test) TextView mTest;
```

... when new tool chain is enabled (in build.gradle):

``` gradle
useJack = true
```

**Comment by Baniares** [comment]
now is supported and still not working

http://tools.android.com/tech-docs/jackandjill#TOC-Repackaging-support

**Comment by OlivierGonthier** [comment]
It works now with the last version and by adding this as dependency:
```
annotationProcessor 'com.jakewharton:butterknife-compiler:8.0.1'
```

**Comment by ladia12** [comment]
In order to use Butterknife 8.0.1 
`
apt 'com.jakewharton:butterknife-compiler:8.0.1' `
is required and apt isn't working with Jack. So, I still don't have a clue how to compile Butterknife with Jack

**Comment by JakeWharton** [comment]
Use annotationProcessor instead of apt

**Comment by ladia12** [comment]
Works like a charm.

**Comment by Atrinax** [comment]
I am getting the following error:
Error:(118, 0) Gradle DSL method not found: 'annotationProcessor()'
What should I change?
Thank you in advance.

**Comment by guni82hu** [comment]
Same Here. Which plugin or dsl does contain this dsl? Google shows only this thread.

**Comment by LiangTang-flagman** [comment]
annotationProcessor keyword was implemented in Android plugin for gradle with version 2.2.0 or newer, such as 2.2.0-alpha5

sample as following,
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-alpha5'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
