### ISSUE TITLE
Allow interface types for injected views

### ISSUE THREAD

**Issue by emilsjolander** [JakeWharton/butterknife#212]
Hi, i ran into a slight issue using butterknife just now and thought i would open an issue to discuss it before making a pull request. I would like the ability to inject views into fields declared by just an interface type. Currently butterknife makes sure the type declared is a descendant of `android.view.View`.

A quick example illustrating the issue i ran into which i think a change like this would fix:
```java
public class CheckableLinearLayout extends LinearLayout implements Checkable {

    @InjectView(R.id.checkable)
    Checkable checkable;

    public CheckableLinearLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        ButterKnife.inject(this);
    }

    @Override
    public void setChecked(boolean checked) {
        checkable.setChecked(checked);
    }

    @Override
    public boolean isChecked() {
        return checkable.isChecked();
    }

    @Override
    public void toggle() {
        checkable.toggle();
    }

}
```
This code currently does not compile because butterknife validates that the field annotated with `@InjectView` is a ´android.view.View´ subclass which it is not.

Checkable is just one example of a time when you want to inject a view with a certain type of behaviour but don't want to rely on the actual implementation. The implementation would only be specified in the xml file making it easy to change implementation depending on configurations.

I'm happy to implement this and submit a pull request if you think the idea is good. In that case my plan is to allow either subclasses of ´android.view.View´ or interfaces as declarations of the injected field. Butterknife would still complain if a concrete implementation not subclassing ´android.view.View´ was declared.

**Comment by JakeWharton** [comment]
Yep. Let's kill the check.

**Comment by JakeWharton** [comment]
Let's also catch `ClassCastException` and re-throw it with a message that includes the ID and field name, similar to the message for when a view is `null`.

**Comment by emilsjolander** [comment]
Sounds good, i'll submit a pull as within the next few days

**Comment by JakeWharton** [comment]
Great. Thanks!
