### ISSUE TITLE
java.lang.VerifyError on Lollipop when using release APK

### ISSUE THREAD

**Issue by austynmahoney** [JakeWharton/butterknife#217]
I get this error when I install my release APK on a `5.x` device. The error does not occur when I push the same code from Android Studio to the device, or if I run it on `4.x`.

```java
java.lang.VerifyError: Verifier rejected class com.myapp.android.ui.activity.MainActivity$$ViewInjector due to bad method void com.myapp.android.ui.activity.MainActivity$$ViewInjector.reset(com.myapp.android.ui.activity.MainActivity) (declaration of 'com.myapp.android.ui.activity.MainActivity$$ViewInjector' appears in /data/app/com.myapp.android-2/base.apk)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:308)
       at java.lang.Class.forName(Class.java:272)
       at butterknife.ButterKnife.findInjectorForClass(ButterKnife.java:298)
       at butterknife.ButterKnife.inject(ButterKnife.java:271)
       at butterknife.ButterKnife.inject(ButterKnife.java:184)
       at com.myapp.android.ui.activity.MyDrawerActivity.onCreate(MyDrawerActivity.java:31)
```

Line 31 is just `ButterKnife.inject(this);`. I inject my Toolbar and a custom NavigationDrawer in the class.
```java
@InjectView(R.id.toolbar) Toolbar mToolbar;
@InjectView(R.id.nav_drawer) MyNavigationDrawer mNavigationDrawer;
```

Is there something that would be different with the Butterknife codegen when using `gradle assembleRelease`? I am not using ProGuard at all.

Here are my other Android build settings:
```
# Android SDK settings
ANDROID_BUILD_MIN_SDK_VERSION=14
ANDROID_BUILD_TARGET_SDK_VERSION=21
ANDROID_BUILD_SDK_VERSION=21
ANDROID_BUILD_TOOLS_VERSION=21.1.2
```

**Comment by austynmahoney** [comment]
Checked on a Moto X 2014 running Lollipop, looks like this is related to 5.0, not just Nexus devices.

**Comment by austynmahoney** [comment]
Crash only happens when running ART.

Logcat:
```
I/art     (21354): Verification error in void com.myapp.android.ui.activity.MainActivity$$ViewInjector.inject(butterknife.ButterKnife$Finder, com.myapp.android.ui.activity.MainActivity, java.lang.Object)
I/art     (21354): void com.myapp.android.ui.activity.MainActivity$$ViewInjector.inject(butterknife.ButterKnife$Finder, com.myapp.android.ui.activity.MainActivity, java.lang.Object) failed to verify: register v4 has type Reference: com.myapp.android.ui.activity.MainActivity but expected Reference: com.myapp.android.ui.activity.LoggedInNavActivitya.lang.Object): [0x0]
I/art     (21354): Verification error in void com.myapp.android.ui.activity.MainActivity$$ViewInjector.reset(com.myapp.android.ui.activity.MainActivity)
I/art     (21354): void com.myapp.android.ui.activity.MainActivity$$ViewInjector.reset(com.myapp.android.ui.activity.MainActivity) failed to verify: register v1 has type Reference: com.myapp.android.ui.activity.MainActivity but expected Reference: com.myapp.android.ui.activity.LoggedInNavActivity
E/art     (21354): Verification failed on class com.myapp.android.ui.activity.MainActivity$$ViewInjector in /data/app/com.myapp.android-1/base.apk because: Verifier rejected class com.myapp.android.ui.activity.MainActivity$$ViewInjector due to bad method void com.myapp.android.ui.activity.MainActivity$$ViewInjector.reset(com.myapp.android.ui.activity.MainActivity)
```

**Comment by JakeWharton** [comment]
Are you using ProGuard or retrolambda or something that could be mucking up your bytecode?

**Comment by austynmahoney** [comment]
No proguard or retrolamba.

I see the issue now. `LoggedInNavActivity` is no longer in my codebase. `MainActivity` used to extend it, but I did some refactoring and the file is now deleted. It doesn't show up in a code search in my repo at all.

**Comment by JakeWharton** [comment]
Are you doing clean builds and seeing this?

**Comment by austynmahoney** [comment]
Yes. Let me try to blow out the build folder manually though.

**Comment by austynmahoney** [comment]
That worked. Why would ART have a problem but not Dalvik?

Sounds like the codegen aggressively caches. Is this a Gradle bug, or working as intended?

**Comment by JakeWharton** [comment]
I'm not really sure. It's all completely opaque to butter knife's annotation processor. I'm really surprised that a clean build wasn't adequate enough to clear the output directly. What's worse is that it seems like this was actually a compiled class file since the source files we generate would have just failed the build. I can only guess that it only fails on ART because every class has to go through the AOT compilation whereas on Dalvik everything was lazy.
