### ISSUE TITLE
findOptionalView in enum Finder cannot be applied to given types

### ISSUE THREAD

**Issue by FGoetzAS24** [JakeWharton/butterknife#224]
After updating Butterknife from version 6.0 to version 6.1, we got the following error during the build process:

Error:(70, 18) error: method findOptionalView in enum Finder cannot be applied to given types;
required: Object,int,String
found: Object,int
reason: cannot infer type-variable(s) T
(actual and formal argument lists differ in length)
where T is a type-variable:
T extends Object declared in method <T>findOptionalView(Object,int,String)

It looks like the finder interface of the optional views has changed and the code generation is wrong. 

For example: 
Inside the generated class: 
ResultListItemViewHolder$$ViewInjector

we find something like:

view = finder.findOptionalView(source, 2131428201);

But the new interface is not longer available and requires a string as 3th parameter.

**Comment by JakeWharton** [comment]
With a clean build?

**Comment by FGoetzAS24** [comment]
Yes, with clean build. Maybe i'll try a clean build again.

**Comment by JakeWharton** [comment]
Just checking!

Can you show exactly the code (or similar) which causes the failure. This
will allow me to quickly diagnose and write a test tomorrow. For now, sleep
must be had.

**Comment by FGoetzAS24** [comment]
Okay, thanks! :) Good night i wish.

Short code example:
http://pastebin.com/90RYQeq5

**Comment by JakeWharton** [comment]
Are you sure it's a clean build? The generated code shouldn't have static methods in it.

**Comment by FGoetzAS24** [comment]
When "Clean Project" in AS or deleting the build folder manually means clean build, then yes.

**Comment by JakeWharton** [comment]
Do you have multiple modules which depends on different versions of the library? Your example generated code is impossible if you are truly using v6.1.

**Comment by FGoetzAS24** [comment]
okay, thank you for this hint! 
I looked again into our build.gradle and found that the butterknife version which is set to the apt was wrong. My mistake, sorry -.-

**Comment by JakeWharton** [comment]
No problem. Glad we got it sorted out!
