### ISSUE TITLE
ig-json-parser library problem

### ISSUE THREAD

**Issue by larten** [JakeWharton/butterknife#225]
Hello,

butterknife is a default library to development, so I must use it! Congratulations!

But I would like to use json parser by Instagram (https://github.com/Instagram/ig-json-parser/).
 
And this part of gradle block butterknife:
```gradle
compileJava {
  doFirst {
    // Directory should exists before compilation started.
    generatedSourcesDir.mkdirs()
  }
  options.compilerArgs += [
                       '-processor',
                       'com.instagram.common.json.annotation.processor.JsonAnnotationProcessor',
                       '-s',
                       generatedSourcesDir
  ]
}
```

What is the proper way to use both libraries together?

bg,
Larten

**Comment by JakeWharton** [comment]
Use the [`android-apt` plugin][1]. This is a problem with their library and their very poor recommendation to use that technique.

 [1]: https://bitbucket.org/hvisser/android-apt

**Comment by larten** [comment]
Thank you!
