### ISSUE TITLE
crashes on android L

### ISSUE THREAD

**Issue by Abhinandan-Chada** [JakeWharton/butterknife#227]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.butterknife/com.example.butterknife.SimpleActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

**Comment by JakeWharton** [comment]
This is your code crashing, not ButterKnife. You're trying to call `setText` on a null reference.

**Comment by Abhinandan-Chada** [comment]
ok,I got it.Thanks...

**Comment by Srikanth92** [comment]
Hi !

When I use normal declaration using findviewbyId working fine after i changed to butterknife bind then i got below exception. Let me know where can i miss any dependencies

In dependencies i have added 
compile 'com.jakewharton:butterknife:8.0.1'

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

**Comment by Abhinandan-Chada** [comment]
Did you initialize the butterknife before set text in to textview..

**Comment by Srikanth92** [comment]
yes

 ButterKnife.bind(this, view);

**Comment by Srikanth92** [comment]
when we added below lines i got gradle exception

apply plugin: 'com.neenbedankt.android-apt'

dependencies {
  apt 'com.jakewharton:butterknife-compiler:8.0.1'
}

but itz accepting below dependency

dependencies {
  compile 'com.jakewharton:butterknife:8.0.1'
 }

**Comment by Abhinandan-Chada** [comment]
Check the textview Id......if not solve ....send the screen shot ...

**Comment by Srikanth92** [comment]
Hi same issue to me also when we running my app. please can you look at below url once

https://codedump.io/share/5wTxXTI4pLfX/1/null-pointer-exception---issues-with-butterknife---android-application-development

**Comment by samyakjain** [comment]
+1 . Facing same using. Not able to solve it
