### ISSUE TITLE
Butterknife injection view doesn't work

### ISSUE THREAD

**Issue by wrustel** [JakeWharton/butterknife#230]
Hi everyone, I am using this library but I allways get a null pointeger when I try to use my EditText injected, here is my declaration code, and I don't know why this isnt working, I followed the example from doc:

public class LoginActivity extends BaseSpiceActionBarActivity implements OnClickListener {
	
	private UsuarioService mUsuarioService;
		
	private LoginSpiceRequest mLoginSpiceRequest;
	
	@InjectView(R.id.etCorreo)
	private EditText etCorreo;
	
	@InjectView(R.id.etPassword)	
	private EditText etPassword;

@Override
	protected void onCreate(Bundle savedInstanceState) {		 
		super.onCreate(savedInstanceState);		
		setContentView(R.layout.activity_login);
		ButterKnife.inject(this);

}

**Comment by JakeWharton** [comment]
Turn on logging in `ButterKnife`. What does it say?

**Comment by wrustel** [comment]
02-25 08:36:19.987: E/AndroidRuntime(25001): java.lang.IllegalStateException: Could not execute method of the activity
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.view.View$1.onClick(View.java:4007)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.view.View.performClick(View.java:4756)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.view.View$PerformClick.run(View.java:19749)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.os.Handler.handleCallback(Handler.java:739)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.os.Looper.loop(Looper.java:135)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at java.lang.reflect.Method.invoke(Native Method)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
02-25 08:36:19.987: E/AndroidRuntime(25001): Caused by: java.lang.reflect.InvocationTargetException
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at java.lang.reflect.Method.invoke(Native Method)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at android.view.View$1.onClick(View.java:4002)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	... 10 more
02-25 08:36:19.987: E/AndroidRuntime(25001): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
02-25 08:36:19.987: E/AndroidRuntime(25001): 	at com.wherefriend.activities.LoginActivity.aceptar(LoginActivity.java:141)
02-25 08:36:19.987: E/AndroidRuntime(25001): 	... 13 more

**Comment by JakeWharton** [comment]
That's the exception. Turn on logging on `ButterKnife` and paste its logs when injection is happening.

**Comment by wrustel** [comment]
How can I do it?

**Comment by artem-zinnatullin** [comment]
@wrustel `ButterKnife.setDebug(true)`

**Comment by JakeWharton** [comment]
Yes, that. Thanks.

With this you'll probably see that it cannot find the generated class. This means one of two things: 
 * Annotation processing is not running. If you are building from an IDE there are instructions on the website at the bottom.
 * ProGuard is stripping or renaming the class. There are instructions on the website for preventing that.

**Comment by wrustel** [comment]
I fixed it. Was the Annotation processing configuration. Of couse I didnt find the annotation processing option in my IDE.

To resolve the problem if you are using an older Eclipse IDE ADT of google you must to download the Eclipse Java Development Tools. I go to post an img that show the url and the plugin for the future.

http://i.stack.imgur.com/ewIn8.png

Thank you for your help and your time.

Kind regards.
