### ISSUE TITLE
@Optional in @InjectViews causes null objects in list

### ISSUE THREAD

**Issue by yarian** [JakeWharton/butterknife#233]
Example:
```
 @Optional @InjectViews({R.id.tab1, R.id.tab2}) List<Tab> mTabs;
```

If the tabs are not there, you will get back a list with two null items in it.
Calling `ButterKnife.apply` on this list throws a NullPointer. 

I can't think of a situation where I'd find that behavior useful. Would much rather have `mTabs` be initialized to an empty list, or not initialized at all and be left null.

Is there something I'm missing?

**Comment by yarian** [comment]
Thanks Jake!

**Comment by JakeWharton** [comment]
I'll make a release soon. One or two more things I want to sneak in first.
