### ISSUE TITLE
Error:cannot access ThreadSafe

### ISSUE THREAD

**Issue by mturki** [JakeWharton/butterknife#235]
When I try to import roboguice into my build.gradle dependencies, the project build fails with : 

Error:cannot access ThreadSafe
  class file for org.apache.http.annotation.ThreadSafe not found
Error:Execution failed for task ':app:compileDebugJava'.
Compilation failed; see the compiler error output for details.
Information:BUILD FAILED

Any ideas?

**Comment by artem-zinnatullin** [comment]
How it is associated with `ButterKnife`?

Q: Any ideas?
A: May be `Roboguice` requires `org.apache.http.annotation` and you need to add it to dependencies

**Comment by mturki** [comment]
No idea... But I solved today my problem by adding :
    compile 'org.apache.httpcomponents:httpcore:4.4'
into my build.gradle...

**Comment by william-tran** [comment]
I ran into this too trying to extend SSLSocketFactory (to fix a bug in SC Eureka). SSLSocketFactory is in `httpclient:4.5.2`, which is built against `httpcore:4.4.4`, and so the superclass contains the `@Threadsafe` annotation which has been removed. I solved this by adding
```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.apache.httpcomponents</groupId>
				<artifactId>httpcore</artifactId>
				<!-- Needed for overriding SSLSocketFactory -->
				<version>4.4.4</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
```
