### ISSUE TITLE
Preference injection?

### ISSUE THREAD

**Issue by hzsweers** [JakeWharton/butterknife#238]
This was an idea I had, but not really sure it's significant enough to warrant its own project and wanted to see if you'd be open to a pull request for it. It's not strictly view injection (preferences are mutants), but I feel like it could fall under the sort of swiss army knife of utilities that Butterknife offers.

Often times when dealing with shared preferences, I end up with a case like this.

```java
public class MyPreferenceFragment extends PreferenceFragment {

    CheckboxPreference someCheckbox;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        someCheckbox = (CheckboxPreference) findPreference("key_some_checkbox");    
        someCheckbox.setOnPreferenceChangeListener(new OnPreferenceChangeListener {
            @Override
            public boolean onPreferenceChange(Preference preference, Object newValue) {
                // Do something
                // Return something
            }
        }
    }

}
```

It would be very nice to do something like this instead:

```java
public class MyPreferenceFragment extends PreferenceFragment {

    @InjectPreference("key_some_checkbox")
    CheckboxPreference someCheckbox;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @OnPreferenceChange("key_some_checkbox")
    boolean checkboxChanged(Preference preference, Object newValue) {
        // Do something
        // Return something
    }

}
```

There's also `OnPreferenceClickListener`, binding multiple keys to a listener, and easy casting of the newValue's type as other pros. It's admittedly a niche use-case, but I think it would be a useful tool.

**Comment by JakeWharton** [comment]
This is the same as #209.

**Comment by JakeWharton** [comment]
Actually yours is more logical, but I don't want duplicate issues and they'll be linked anyway.

**Comment by hzsweers** [comment]
Ah oops! I'll chime in on that thread with my examples
