### ISSUE TITLE
Remove @Optional, support any annotation named @Nullable

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/butterknife#239]
The support-annotations library ships with `@Nullable` and there's a whole bunch in [other annotation libraries](http://xkcd.com/927/). Just match on the simple name of the annotation class.

**Comment by JakeWharton** [comment]
This is on `master.

**Comment by voghDev** [comment]
Hi Jake,

so @Nullable @Bind() is the new @Optional @InjectView() ? are these codes correct?

    @Nullable @Bind(R.id.pdf_program_img_cover)
    ImageView pdfCover;

    @Nullable @OnClick(R.id.pdf_program_img_cover)
    public void onClickImageCover(View v){
        handleImageCoverClick(v);
    }

Thanks in advance
