### ISSUE TITLE
Problem with @OnClick without specifying ID

### ISSUE THREAD

**Issue by Taardal** [JakeWharton/butterknife#240]
Hi!

In the documentation for ButterKnife there is the following section:

*'Custom views can bind to their own listeners by not specifying an ID.'*
```
public class FancyButton extends Button {
  @OnClick
  public void onClick() {
    // TODO do something!
  }
}
```

I tried to implement this into my own project but I cannot get it to work. Below is my code for my custom button class:
```
public class FancyButton extends Button {
    public FancyButton(Context context) {
        super(context);
    }

    @OnClick
    public void onClick() {
        // TODO do something!
    }
}
```

As you can see it's not much difference from the documentation, but ```@Onclick``` is underlined with red, and I get the following error: *'value missing though required'*

When I shift+click the ```@Onclick```  annotation i see that it expects one or more integers:
```language
public @interface OnClick {
  /** View IDs to which the method will be bound. */
  int[] value();
}
```

My question is this: is the documentation wrong or have I missed something? How are you supposed to use the ```@Onclick``` annotation without an ID?

I use Android Studio 1.1.0

**Comment by tomxor** [comment]
You should call `ButterKnife.inject(this)` either from inside the `onFinishInflate()` method of the view (which is invoked in case your view is inflated via XML), or if you are creating new instances of this view programmatically, add it to the constructor which you're using.

**Comment by Taardal** [comment]
I tried what tomxor said, and now it works perfectly!

I was indeed using an old version of ButterKnife without knowing it, so I changed ``compile 'com.jakewharton:butterknife:5.1.2'`` to ``compile 'com.jakewharton:butterknife:6.1.0'`` in my ``build.gradle`` file.

I then called ``ButterKnife.inject(this)`` in my custom Button class from inside the ``onFinishInflate()`` method.

The code now roughly looks like this:

```language
public class FancyButton extends Button {

    public FancyButton(Context context) {
        super(context);
    }

    public FancyButton(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public FancyButton(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        ButterKnife.inject(this);
    }

    @OnClick
    public void onClick() {
        // Doing stuff...
    }
```

Thanks for the help!
