### ISSUE TITLE
Can ButterKnife help in reducing the size of apk?

### ISSUE THREAD

**Issue by bhuvneshvarma** [JakeWharton/butterknife#247]
Butter Knife help to have cleaner and more understandable code and reduce development time.But can ButterKnife  help in reducing the size of apk?

**Comment by JakeWharton** [comment]
No. The APK will be a tiny bit larger if you use ButterKnife because of the generated classes. That's the cost of reflection-free boilerplate reduction. If it was implemented using reflection the size would be about the same as normal `findViewById` and listener code.

**Comment by artem-zinnatullin** [comment]
BTW,  when Kotlin will support annotation processing it will be nice to use `[Inline] ` annotation for such generated code!
