### ISSUE TITLE
LICENSE.txt doesn't have the copyright owner

### ISSUE THREAD

**Issue by gfx** [JakeWharton/butterknife#249]
https://github.com/JakeWharton/butterknife/blob/master/LICENSE.txt

>  Copyright [yyyy] [name of copyright owner]

I'm happy if it has the correct name! ;)

**Comment by JakeWharton** [comment]
That is bthe template for applying the license which is part of the license itself.

**Comment by gfx** [comment]
Oh, really!? Thanks.
