### ISSUE TITLE
cannot add butterknife on separate android module

### ISSUE THREAD

**Issue by guamacherox** [JakeWharton/butterknife#251]
im separating my app in different modules in a same android project, i want to use butterknife in one of the modules, but it doesn`t recognize the command @InjectView(R.id.something), i can move everything to one module again and it works fine, but in a separate module it his own graddle and all the config setted up, it just not working, is like a conflict with the R object or something like that.

**Comment by JakeWharton** [comment]
Butter Knife does not support library projects because the `R.id` constants are not final. This is a limitation of Java's annotations and the Android SDK. Nothing we can do about it, sorry.

**Comment by ShreyashPromact** [comment]
@JakeWharton 
Are there any updates on this issue? What is the alternative?
