### ISSUE TITLE
Verb still @InjectView not @FindView

### ISSUE THREAD

**Issue by tunjos** [JakeWharton/butterknife#252]
compile 'com.jakewharton:butterknife:6.1.0'

**Comment by gabrieloshiro** [comment]
Was this issue solved? README.md uses @FindView. [Butterknife website](http://jakewharton.github.io/butterknife/) uses @InjectView

**Comment by JakeWharton** [comment]
The readme on master is for the code on master.

**Comment by tunjos** [comment]
Realized this..That's why I closed it.

**Comment by gabrieloshiro** [comment]
I just realized it... Came here to delete my comment... I wasn't fast enough. Sorry :-(
