### ISSUE TITLE
Problem with button listener

### ISSUE THREAD

**Issue by idanbar134** [JakeWharton/butterknife#254]
Hello,

    java.lang.IllegalStateException: Could not find a method Login(View) in the activity class com.nuro.Activities.MainActivity for onClick handler on view class android.widget.Button with id 'login_button'

How to solve this please,
Idan

**Comment by artem-zinnatullin** [comment]
Looks like you have `android:onClick="Login"` in your layout and such `Login()` method can not be found in your `MainActivity`, there is no problem with `ButterKnife`
