### ISSUE TITLE
ButterKnife @FindView throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by liuzheng9110** [JakeWharton/butterknife#255]
Used in my project you making up the latest code, FindView out of control to be empty.

textview.setText("xxx"); throws NullPointerException.

tks.

**Comment by fengdai** [comment]
Did you forget to call ```ButterKnife.bind()```?

**Comment by liuzheng9110** [comment]
Has been added, `ButterKnife.bind(this);` not, use  6.1.0 `ButterKnife.inject(this);` is ok.

**Comment by liuzheng9110** [comment]
When packing jar a file is missing.
`META-INF/services/java.javax.annotation.processing.Processor`
