### ISSUE TITLE
Does butterknife work with view that include merge-view.xml ?

### ISSUE THREAD

**Issue by ThanawatMas** [JakeWharton/butterknife#256]
Follow the question, I try to use and try using in many way  for use butterknife with merge view that include in main_layout file. I got a problem with these error :

======================  code
@InjectView(R.id.viewID)
View view;
....
//onCreate setContentLayout(main_layout.xml)
====================== merge_view.xml
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/viewID">
.....
</merge>
====================== runtime
java.lang.IllegalStateException: Required view 'viewID' with ID 2131296941 for field 'view' was not found. If this view is optional add '@Optional' annotation.
            at butterknife.ButterKnife$Finder.findRequiredView(ButterKnife.java:135)

**Comment by JakeWharton** [comment]
Yes. Butter Knife just calls `findViewById` under the hood so `viewID` was not present in the tree when you called `ButterKnife.inject`.

**Comment by ThanawatMas** [comment]
G thank sir, I got it.
