### ISSUE TITLE
no method named "bind()",only inject()

### ISSUE THREAD

**Issue by littletanker** [JakeWharton/butterknife#258]
i download the latest jar which the version is 6.1.0,but i can't find the method  ButterKnife.bind(this),only  have ButterKnife.inject(this), and it can not work,throw NPE.
Please help.
this is my code:

@InjectView(R.id.am_slde_drag_layout) SlideDragLayout slideDragLayout;

@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		ButterKnife.inject(this);
	}

slideDragLayout return null.

**Comment by JakeWharton** [comment]
If the variable was null that means the annotation processor did not run. See the website for details on how to configure it in your IDE.

The README is for the code on master which will be released soon. Inject is the right method to use for 6.1.0.

**Comment by owen19891030** [comment]
I have this problem, and use the latest jar , I have config in eclipse, also clean project,not work
![qq 20150512172029](https://cloud.githubusercontent.com/assets/2189145/7583817/5c2e3590-f8cb-11e4-9913-b2717d6b9352.png)

**Comment by JakeWharton** [comment]
Use @InjectView
