### ISSUE TITLE
Multiple ButterKnife.inject(target, View) causes references are reset

### ISSUE THREAD

**Issue by rmielnik** [JakeWharton/butterknife#259]
Hi,

I created ListView with some header and footer. My initialization is like:

```
{
	...
    final View header = inflater.inflate(R.layout.header, this, false);
    addHeaderView(header, null, false);
    ButterKnife.inject(this, header);
    (*)

    final View footer = inflater.inflate(R.layout.footer, this, false);
    addFooterView(footer, null, false);
    ButterKnife.inject(this, footer);
    (**)
	...
}
```
I used on click annotations and everything worked fine:
```
@Optional
@OnClick(R.id.some_view_from_header)
public void someWorkingFunction() {
	
}

@Optional
@OnClick(R.id.some_view_from_footer)
public void someOtherWorkingFunction() {
	
}
```

Then I needed to get references to those views. Tried with:
```
@Optional
@InjectView(R.id.some_view_from_header)
protected View viewFromHeader;

@Optional
@InjectView(R.id.some_view_from_footer)
protected View viewFromFooter;
```
What happens is at point (*) I have a properly set reference to viewFromHeader. At point (**) viewFromHeader is null and viewFromFooter is properly set.

Is this expected behavior?

**Comment by JakeWharton** [comment]
Calling `inject` will set a reference to every view, present or not. The fact that the click listeners continue to work is an accident–don't rely on that. The right way to do multiple injections is to use the view holder pattern for secondary injections.

```
static class HeaderViews {
  @InjectView(R.id.header_title) TextView title
}

final HeaderViews header = new HeaderViews();

// ...

ButterKnife.inject(header, headerView);
header.title.setText("HEADER!!!!!!");
```
