### ISSUE TITLE
The same id of view.

### ISSUE THREAD

**Issue by NorbertSzydlowski** [JakeWharton/butterknife#262]
I have got view with embed fragment that contains ViewPager layouts (the same).

Fragments (Pager) have the same BaseFragment that contains R.id.viewPager.

Second View Pager never works.

**Comment by JakeWharton** [comment]
Butter Knife uses `findViewById` which stops on the first instance it finds. If you have two views with the same id you will need to use a different root ViewGroup that allows it to find the two different ones. This is no different than you'd do with `findViewById` directly.
