### ISSUE TITLE
ViewInjector classes on Open File dialog

### ISSUE THREAD

**Issue by yarian** [JakeWharton/butterknife#263]
![screen shot 2015-05-07 at 2 23 27 pm](https://cloud.githubusercontent.com/assets/596223/7526244/e1bd7c4e-f4c4-11e4-8bd5-5f1dfb46210c.png)

Does anybody else get these autocomplete suggestions? Has anyone figured out a way to make them go away? I've done plenty of independent research but could not figure out a way.

**Comment by tomxor** [comment]
Your build path is declared as a source root for your project.

**Comment by JakeWharton** [comment]
This happens for most libraries that generate code (We see this with Dagger, etc.). Maybe it's time to request an IntelliJ feature to filter class names that match a regex. As an annotation processor, there's nothing Butter Knife can do about this, sorry.

**Comment by yarian** [comment]
No worries. Figured as much, thanks.
