### ISSUE TITLE
R.java not generated with Gradle on Library projects

### ISSUE THREAD

**Issue by gleenn** [JakeWharton/butterknife#264]
I've been fighting with this for a while but I think I've narrowed it down to Butterknife. It seems that switching from an Android app to library in your build.gradle file prevents the R.java file from being generated when doing a "gradle assembleRelease" which all gradle libraries are by default.

**Comment by JakeWharton** [comment]
Butter Knife does not work in library projects due to the fact that R values are non-final. Butter Knife has no effect on the generation of the R file, however, which is an unrelated task.

Unless you have some kind of sample or something, there's not really anything to go on from this anyway.
