### ISSUE TITLE
proguard error

### ISSUE THREAD

**Issue by mw258176257** [JakeWharton/butterknife#266]
in android studio The toast show always . the textView  is null ,please help me! thank you!

this is my code 
![image](https://cloud.githubusercontent.com/assets/3024900/7677009/48e3ab1e-fd7b-11e4-904b-2a822acdf686.png)

and this is my proguard-rules.rpo

-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontpreverify
-verbose
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*

-dontwarn

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class com.android.vending.licensing.ILicensingService

-keepclasseswithmembernames class * {
native <methods>;
}
-keepclasseswithmembers class * {
public <init>(android.content.Context, android.util.AttributeSet);
}
-keepclasseswithmembers class * {
public <init>(android.content.Context, android.util.AttributeSet, int);
}
-keepclassmembers class * extends android.app.Activity {
public void *(android.view.View);
}
-keepclassmembers enum * {
public static **[] values();
public static ** valueOf(java.lang.String);
}
-keep class * implements android.os.Parcelable {
public static final android.os.Parcelable$Creator *;
}

-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}

**Comment by mw258176257** [comment]
my studio version is 1.2.1.1

**Comment by mw258176257** [comment]
i use this below it work:

# Butterknife
-dontwarn butterknife.internal.**
-keep class butterknife.** { *; }
-keep class **$$ViewInjector { *; }

-keepclasseswithmembernames class * {
    @butterknife.InjectView <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.OnClick <methods>;
    @butterknife.OnEditorAction <methods>;
    @butterknife.OnItemClick <methods>;
    @butterknife.OnItemLongClick <methods>;
    @butterknife.OnLongClick <methods>;
}

**Comment by flyou** [comment]
in studio you can copy the java file and xml file (the file in libary )in you progect is ok

**Comment by mw258176257** [comment]
@flyou  you mean which one? can you tell me the file path?

**Comment by JakeWharton** [comment]
ProGuard problems are not specific to this library and fall under usage questions since ProGuard is a completely optional thing. I would ask on StackOverflow because you'll get _a lot_ more people who can deal with the situation and figure our what's wrong rather than just the few watching the project.
