### ISSUE TITLE
Allow multiple views to be debounced via @OnClick

### ISSUE THREAD

**Issue by elanas** [JakeWharton/butterknife#272]
The code below handles the debouncing of multiple view but each view is given a separate OnClickListener to handle the debounce. This solves of the problem of clicking the same view multiple times but does not solve of the problem of debouncing multiple clicks of multiple views.
```
@OnClick({ R.id.door1, R.id.door2, R.id.door3 })
public void pickDoor(DoorView door) {
  if (door.hasPrizeBehind()) {
    Toast.makeText(this, "You win!", LENGTH_SHORT).show();
  } else {
    Toast.makeText(this, "Try again", LENGTH_SHORT).show();
  }
}
```

This may exist already (though I didn't see it in the documentation), but it would be nice to have the functionality to debounce clicks to multiple views by handling all click events in a single DebouncingOnClickListener. Thoughts?

**Comment by JakeWharton** [comment]
The `DebouncingClickListener` uses a static for debouncing clicks which means that it should already be doing this.

**Comment by JakeWharton** [comment]
Per its Javadoc:
> A click on one button disables all buttons for that frame.

**Comment by elanas** [comment]
Thank you for the clarification. I misunderstood how the DebouncingClickListener operates.
