### ISSUE TITLE
@OnItemSelected doesn't appear to work in a ListFragment

### ISSUE THREAD

**Issue by djensen47** [JakeWharton/butterknife#273]
I tried to use `@OnItemSelected(android.R.id.list)` in a ListFragment but it didn't work. As is turns out ListFragment has a method `onListItemClick` that can be overridden to accomplish the same goal.

I'm wondering if I'm calling the injection in the proper location or not …

```Java
  @Override
  public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view = inflater.inflate(R.layout.fragment_items, container, false);

    ButterKnife.inject(this, view);

    return view;
  }

  @Override
  public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);

    ButterKnife.inject(this, view);

    adapter = new MyListAdapter(getActivity(), new List<Stuff>);
    setListAdapter(adapter);
  }


  //  @OnItemSelected(android.R.id.list)
  public void onItemSelected(int position) {
    Log.d(TAG, "position: " + position);
  }
```

My actual code does not invoke `ButterKnife.inject` twice. I just listed it this way to show that I tried changing the order and still ended up with the same, non-working, result.

**Comment by JakeWharton** [comment]
After `super.onViewCreated` is called the `ListFragment` should have initialized its own click listener. This means that calling Butter Knife should override the click listener with its own. That said, I would discourage Butter Knife's use inside of a `ListFragment`—at least to override the classes existing mechanism for callbacks. The implementation may change without warning and change the order of when these get executed leaving you with non-working code. Either use a normal `Fragment` to display your list (`ListFragment` doesn't give you much anyway) or just use the existing callback for list clicks.

**Comment by djensen47** [comment]
I thought it was weird that `ButterKnife.inject` didn't work after  `super.onViewCreated` but maybe I did something wrong when I tested it. Thanks for the advice on not mixing Butter Knife with `ListFragment`.

Thanks for the response!

**Comment by JakeWharton** [comment]
It should of you calk inject after calling the super method.
