### ISSUE TITLE
README.md out of date

### ISSUE THREAD

**Issue by ashrko619** [JakeWharton/butterknife#274]
Readme.md has <b>@FindView</b> Annotations instead of <b>@InjectView</b> annotations and injection is done using bind() method instead of inject() method

**Comment by ytRino** [comment]
v7.0 (currently snapshot) uses @FindView and bind().
So it is *newer* rather than *out of date*.
ref #258

**Comment by ashrko619** [comment]
Thanks :+1:

**Comment by JakeWharton** [comment]
Release will be this weekend. Sorry for delay.

**Comment by ytRino** [comment]
wow. Glad to hear that!

**Comment by ppamorim** [comment]
@JakeWharton 7.0.0 not working yet. Any news?

**Comment by JakeWharton** [comment]
What does "not working yet" mean? It's working fine here.

**Comment by ppamorim** [comment]
Sorry, now It's working... Bad connection

**Comment by JakeWharton** [comment]
:+1:

**Comment by ppamorim** [comment]
Now I'm ashamed :(
