### ISSUE TITLE
7.0.0 Changelog

### ISSUE THREAD

**Issue by Tolriq** [JakeWharton/butterknife#277]
Hi,

First thanks for the library since I never took time to do that :)

Changelog should mention the change of internal renaming of  $$ViewInjector to $$ViewBinder so that users think to check their proguard config. (Or add a line about needed proguard change)

As strangely not updating the proguard config will not trigger crash in Butterknife, it will just not bind the fields so not easy to think about that, first though is that annotation processor does not run.

Regards,
Tolriq

**Comment by JakeWharton** [comment]
Ah, yeah. Will add when I get to a computer.
