### ISSUE TITLE
View injection into subclasses from parent class is broken in 7.0

### ISSUE THREAD

**Issue by vpratfr** [JakeWharton/butterknife#281]
Hi,

I got a regression (feature?) when using 7.0 instead of 6.1: 

- I have a parent fragment class which basically does a `ButterKnife.inject / bind` in its `onCreateView` method.
- The child fragment classes do not have to worry about making that call, they just declare their `@Inject`/`@Bind` and their views get injected when the parent makes the ButterKnife injection/binding.

In 7.0 the views are all null in child classes
In 6.1 the views were properly bound.

Is that the intended behaviour? Did I skip something in the changelog?

**Comment by egor-n** [comment]
Works just fine for me. Are you sure your issue is not related to #277?

**Comment by vpratfr** [comment]
That was it. I indeed missed something in the changelog.

**Comment by ppamorim** [comment]
+1, we need a better documentation for this change.

**Comment by JakeWharton** [comment]
It's in the change log. If you don't read the change log when upgrading, no amount of documentation will save you from yourself.

**Comment by ppamorim** [comment]
@JakeWharton Ok jake, It was indifferent to me...
