### ISSUE TITLE
Bind resources in non view classes with context only.

### ISSUE THREAD

**Issue by gfred** [JakeWharton/butterknife#282]
In some cases there are classes which doesn't have an activity, view or dialog. But it would be nice to bind resources in classes with only have a context.

**Comment by lolkittens** [comment]
Where would butterknife find the views to inject without a source?

**Comment by gfred** [comment]
i am talking about resources (dimen, colors, string, int, drawable,...) which can now be bind with ButterKnife 7.0. (See changelogs). They don't require a view as source. Maybe use a context as source to bind?!

**Comment by JakeWharton** [comment]
When we switch to specialized view binder generation this will be possible.

**Comment by JakeWharton** [comment]
Blocked by #197.

**Comment by JakeWharton** [comment]
This is effectively done (in the next version) by referencing the generated view binding directly. When there are no view bindings the generated code will only require a `Context`.

e.g.,
```java
class Foo {
  @BindColor(R.color.foo) int foo;
}
```
bind with
```java
Foo foo = new Foo();
new Foo_ViewBinding(foo, context); // You don't need to retain this instance
```

The generated code API won't be API stable until 9.0, but this will be available in the next 8.x release to try out.
