### ISSUE TITLE
Why not Binding extras too ?

### ISSUE THREAD

**Issue by stephanenicolas** [JakeWharton/butterknife#283]
After swallowing the scope of [VitaminSaber](https://github.com/w2ji/VitaminSaber), it could be interesting to do the same with [Dart](https://github.com/f2prateek/dart).

@JakeWharton I have been a little surprised when I saw the 7.0.0 changelog. I remember when we talked about the scopes of a library and I agreed with you about the importance of sharpness over blunt scopes.

What motivated you here ?

**Comment by JakeWharton** [comment]
Never heard of VitaminSaber, but resources are used in code when
interacting with views and I got sick of calling into them. Extras are
for... fragments? Or activities? Either way, not related to views nor
accessible from a Context.

**Comment by stephanenicolas** [comment]
Thx, I get more the scope of ButterKnife.
