### ISSUE TITLE
Required bound views are null after calling ButterKnife.bind(this)

### ISSUE THREAD

**Issue by dkozel** [JakeWharton/butterknife#285]
I've just tried updating to the 7.0.0 release of Butter Knife from 6.1.0 and am encountering an immediate NPE. The only changes are updating the number in `build.gradle`, replacing `InjectView` with `Bind`, and `ButterKnife.inject` with `ButterKnife.bind`. Pausing with the debugger shows that none of the @Bind variables are being initialized, all are null.

In StartActivity (extends MyFragmentActivity)
```
...
@Bind(R.id.loginFormHints) LinearLayout loginFormHints;
...

@Override protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState, R.layout.activity_start);
  ButterKnife.bind(this);

  // Use loginFormHints
  Helpers.stripeLinearLayout(this, loginFormHints);
  ...
}
```

And the referenced super.onCreate in MyFragmentActivity (extends FragmentActivity)
```
protected void onCreate(Bundle savedInstanceState, int layout) {
	super.onCreate(savedInstanceState);

	this.requestWindowFeature(Window.FEATURE_NO_TITLE);
	setContentView(layout);
}
```

The, uninteresting, error log
```
E  Caused by: java.lang.NullPointerException
E      at com.myapp.helpers.Helpers.stripeLinearLayout(Helpers.java:102)
E      at com.myapp.helpers.Helpers.stripeLinearLayout(Helpers.java:133)
E      at com.myapp.activities.StartActivity.onCreate(StartActivity.java:84)
E      at android.app.Activity.performCreate(Activity.java:5431)
```

**Comment by JakeWharton** [comment]
Call `ButterKnife.setDebug(true)` and paste the logs.

**Comment by dkozel** [comment]
Very handy! Must remember it in the future.
```
D  Looking up view binder for com.myapp.activities.StartActivity
D  Not found. Trying superclass com.myapp.activities.MyFragmentActivity
D  Not found. Trying superclass android.support.v4.app.FragmentActivity
D  MISS: Reached framework class. Abandoning search.
```

**Comment by JakeWharton** [comment]
The generated class is missing. Are you using ProGuard? If so, the generated class name changed (see the change log file in the repo).

**Comment by dkozel** [comment]
Shame on me. Proguard.

I'm confirming now, but the issue is that I did not update the Proguard statements.
```
-  -keep class **$$ViewInjector { *; }
+ -keep class **$$ViewBinder { *; }
```

**Comment by dkozel** [comment]
That was indeed the issue.

Thanks for the help and for all of your helpful libraries, posts, and talks!

**Comment by JakeWharton** [comment]
:+1:

**Comment by sylversky** [comment]
I have null too. Im not turn on proguard
debug logs:

Looking up view binder for android.widget.RelativeLayout
MISS: Reached framework class. Abandoning search.

**Comment by dkozel** [comment]
Hello @sylversky, sounds like you are passing an incorrect object to `ButterKnife.bind(...)`. Can you start a StackOverflow question with the relevant source code for the fragment or activity and the tag 'butterknife'?

@JakeWharton I hope this is an appropriate recommendation.

**Comment by sylversky** [comment]
Oww sorry,

But thanks, ***I got the problem*** right now,

I wanna create Adapter, i'm use bind to inject TextView on my ViewHolder class, but my TextView still null.

Yes, I'm passing an incorrect object on my ViewHolder
```
...
 public ViewHolder(View view){
            ButterKnife.bind(view);
 }
...
```

It's supposed to be like this :  ***ButterKnife.bind(this, view);***

:+1:

**Comment by dkozel** [comment]
:+1: Glad you found it.

**Comment by xwei-handy** [comment]
:+1:

**Comment by beer44473** [comment]
NullPointerException i have this too in verios 7.0.1 
I Complie in api 21higher have work but in api 19 dont work is NullPointerException

**Comment by FelixForever** [comment]
I have the same problem while i use it  recyclerview.viewholder,i try to set ButterKnife.bind(this,view),but it throw the RuntimeEception:Unable to bind views for com.felix.dreamhome.Adp.DesignAdp$DesignVH.I don't know why.I use ButterKnife.bind(this,view) in the viewholder i create not the  recyclerview.viewholder and it work fine.And i also use ButterKnife.bind(view) in recyclerview.viewholder in the other project ,it work fine too.

**Comment by moka-a** [comment]
I have null too .. 

debug : 
03-31 14:05:05.448 3979-3979/com.moka.earylbird D/ButterKnife: Looking up view binder for com.moka.framework.toolbar.ToolbarLayout
03-31 14:05:05.448 3979-3979/com.moka.earylbird D/ButterKnife: Not found. Trying superclass android.widget.FrameLayout
03-31 14:05:05.448 3979-3979/com.moka.earylbird D/ButterKnife: MISS: Reached framework class. Abandoning search.
03-31 14:05:05.448 3979-3979/com.moka.earylbird D/ButterKnife: Looking up view binder for com.moka.earlybird.application.mvc.controller.main.MainActivity
03-31 14:05:05.449 3979-3979/com.moka.earylbird D/ButterKnife: Not found. Trying superclass com.moka.framework.controller.BaseActivity
03-31 14:05:05.449 3979-3979/com.moka.earylbird D/ButterKnife: Not found. Trying superclass android.support.v7.app.AppCompatActivity
03-31 14:05:05.449 3979-3979/com.moka.earylbird D/ButterKnife: MISS: Reached framework class. Abandoning search.


proguard-rule :
-keep @io.realm.annotations.RealmModule class *
-dontwarn javax.**
-dontwarn io.realm.**
-keep class **$$ViewBinder { *; }

please help

**Comment by blackadmin** [comment]
Updated to v8.0.1

Me too facing facing NPE, even tried turning off proguard.

Looking up view binder for myapp.FragmentControllerList
Not found. Trying superclass android.app.Fragment
MISS: Reached framework class. Abandoning search.

!!! Please HELP !!! :(

**Comment by serj-lotutovici** [comment]
@blackadmin see #536 or #526

**Comment by blackadmin** [comment]
@serj-lotutovici Great it solved the problem.

But had to add
```
packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
```

As there was file duplicate error while building.

Thankyou very much 👍

**Comment by JakeWharton** [comment]
That indicates you added the `butterknife-compiler` as a `compile` dependency, not `apt`.

**Comment by blackadmin** [comment]
Yes, I added the `butterknife-compiler` as `compile` dependency.

**Comment by JakeWharton** [comment]
That is incorrect, see the README.

**Comment by blackadmin** [comment]
Now, After enabling proguard, me getting warning, even after using the proguard config provided by you.

```
-keep public class * implements butterknife.internal.ViewBinder { public <init>(); }
-keep class butterknife.*
-keepclasseswithmembernames class * { @butterknife.* <methods>; }
-keepclasseswithmembernames class * { @butterknife.* <fields>; }
```

**Comment by blackadmin** [comment]
Sorry, I missed your comment, I go through ReadMe .

**Comment by blackadmin** [comment]
@JakeWharton Yes, I missed the new **ReadMe**, now everything is working fine, no duplicate file error and even proguard is working fine.

Thank you. :)

**Comment by JakeWharton** [comment]
Great!

**Comment by noomz** [comment]
Thx @dkozel ! Mine use this settings:

```
-keep class **$$ViewBinder { *; }
-keep class **$ViewHolder { *; }
-keep class butterknife.**$Finder { *; }
```

**Comment by peterbetos** [comment]
Also resolved another null pointer using annotationProcessor issue from my end.
 
It seems that declaring 
```
'com.jakewharton:butterknife:8.2.1' and 
'com.jakewharton:butterknife-compiler:8.2.1' 
```
as the first and foremost dependency is needed. 

Otherwise support libraries on a nested xml (especially if cannot already flatten the setup) returns NPE.

**Comment by renhuihhh** [comment]
I encountered the same problem days ago , and I found the code should write like this below:
`public class FollowersViewHolder extends RecyclerView.ViewHolder {
    @BindView(R.id.user_avatar)
    public ImageView userAvatar;
    @BindView(R.id.follower_login_name)
    public TextView  userLoginName;
    @BindView(R.id.follower_name)
    public TextView  userName;
    @BindView(R.id.user_bio)
    public TextView  userBio;
    @BindView(R.id.user_company_name)
    public TextView  userCompanyName;
    @BindView(R.id.user_location_name)
    public TextView  userLocationName;

    public FollowersViewHolder(View itemView) {
        super(itemView);
        **ButterKnife.bind(this, itemView);**//not this one->ButterKnife.bind(itemView)
    }
}`

And this problem appears in RecycleView scene

**Comment by ViliusKraujutis** [comment]
Had this issue too, just because I've added butterknife from Android Studio's Dependency management and not by copy-pasting gradle lines from Butterknife website.
So I had to add 
```
compile 'com.jakewharton:butterknife:8.5.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
```
instead of just
```
compile 'com.jakewharton:butterknife:8.5.1'
```

**Comment by carloxavier** [comment]
I'm experiencing null values on the bounded views.
For example on my fragment I have the call to unbinder.unbind() placed at the onDestroyView, 
but then by exiting and entering again the same view, the logs show `HIT: Cached in view binder map`, and at some later point I try to make visible a view getting a npe on it.
I would appreciate any hint on the issue, thnx

**Comment by cfxmys** [comment]
update the version 8.6.0
I meet the same problem,

I add 
compile 'com.jakewharton:butterknife:8.5.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'

into a library build.gradle file

and 
classpath 'com.jakewharton:butterknife-gradle-plugin:8.6.0'

into the buildscript

gradle version is 3.4.1
gradle plugin version is 2.4.0-alpha7

**Comment by 911shanky** [comment]
If none of the above solution is working for you try replacing:
`annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'`
with this line,
    `apt 'com.jakewharton:butterknife-compiler:8.7.0'`
 it worked for me while still using `R `instead of `R2`.

**Comment by travelgeezer** [comment]
Required bound views are null after calling ButterKnife.bind(this)，
Here's what I saw when I opened the debug mode：

D/ButterKnife: Looking up view binder for com.geezer.app.TODOActivity
D/ButterKnife: Not found. Trying superclass android.arch.lifecycle.LifecycleActivity
D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by travelgeezer** [comment]
Required bound views are null after calling ButterKnife.bind(this)，
Here's what I saw when I opened the debug mode：

D/ButterKnife: Looking up view binder for com.geezer.app.TODOActivity
D/ButterKnife: Not found. Trying superclass android.arch.lifecycle.LifecycleActivity
D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by VNAPNIC** [comment]
@Nullable
@BindView(R.id.item_timeline_username)
TextView userName;

**Comment by jeancsanchez** [comment]
@VNAPNIC  That worked for me. Thanks!!!

**Comment by AhmadullahSaikat** [comment]
👍  **### 10**
