### ISSUE TITLE
Error: cannot find symbol class InjectView

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/butterknife#286]
Hi,
I added `compile 'com.jakewharton:butterknife:7.0.0'` into my project.  However, I am getting these compilation errors:
> Error:(22, 19) error: cannot find symbol class InjectView

Please advise.

**Comment by JakeWharton** [comment]
See [the change log][1].

 [1]: https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-700-2015-06-27

**Comment by IgorGanapolsky** [comment]
Oh, I see.  So you're trying to implement/mimic the new Data Binding framework from Google?

**Comment by JakeWharton** [comment]
No. The changes here came before that was announced.
