### ISSUE TITLE
Finder.arrayOf(...) always returns Object[] if an optional view is null

### ISSUE THREAD

**Issue by hzsweers** [JakeWharton/butterknife#287]
If you bind an array of views and one is null/optional, `Finder.arrayOf(…)` returns an instance of `Object[]`, which results in a `ClassCastException` at runtime.

This worked fine before 7.0.0 when we used `@InjectViews`, I'm not sure what changed under the hood. It might be the case you shouldn't try to have nullable view in an array anyway, but just wanted to let you know in case this wasn't intentional.

### Example

```java
@Nullable
@Bind({R.id.textview0, R.id.textview1, R.id.textview2})
TextView[] textViews;
```

Results in this crash at runtime:

```
Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to android.widget.TextView[]
            at io.sweers.test.MainActivity$$ViewBinder.bind(MainActivity$$ViewBinder.java:11)
            at io.sweers.test.MainActivity$$ViewBinder.bind(MainActivity$$ViewBinder.java:8)
            at butterknife.ButterKnife.bind(ButterKnife.java:328)
            at butterknife.ButterKnife.bind(ButterKnife.java:246)
            at io.sweers.test.MainActivity.onCreate(MainActivity.java:23)
```

Full example here: https://github.com/hzsweers/Butterknife-test

**Comment by hzsweers** [comment]
Stepping through the debugger says the problem starts [here](https://github.com/JakeWharton/butterknife/blob/master/butterknife/src/main/java/butterknife/ButterKnife.java#L127). It seems the `T[]` cast doesn't take effect, because it still considers `newViews` an `Object[]` after.

Alternatively, it could do this to keep the correct casting, and also simplify the logic of `filterNull()` a little: https://gist.github.com/hzsweers/63a261d6fabe6e8a608e

**Comment by JakeWharton** [comment]
This was my bad. I should have been using `Array.newInstance` if I wanted to allocate. I took a similar approach inspired by you, but I made it a bit more simple at the expense of a few extra bytecode instructions: #288.

**Comment by JakeWharton** [comment]
Whoops. I screwed that up too...
