### ISSUE TITLE
Allow @OnClick with no ID on objects that are not subclass of View

### ISSUE THREAD

**Issue by grennis** [JakeWharton/butterknife#293]
When using RecyclerView it is very common to call setOnClickListener on the root item View. I usually do not put an ID on the root of the view, since it is not necessary. But then I can't bind using just @OnClick because I get compiler error "@OnClick annotation without an ID may only be used with an object of type "android.view.View" or an interface. "

Would it be possible to allow this and then @OnClick with no ID would bind to the root of the view?

**Comment by NOlivNeto** [comment]
Do you have a suggestion of how would this work?

**Comment by grennis** [comment]
I'm planning to send a PR but haven't been able to do this yet.
