### ISSUE TITLE
OnClick event delayed

### ISSUE THREAD

**Issue by ch11gz** [JakeWharton/butterknife#299]
I have a simply layout for my Fragment which looks broadly like this:
```
<LinearLayout android:orientation="vertical">

    <Toolbar/>

    <LinearLayout
        android:orientation="vertical">

        <FrameLayout
            android:id="@+id/button1"
            android:layout_height="0dp"
            android:layout_weight="0.5">

            <ImageView/>

            <LinearLayout android:orientation="vertical">
                <TextView/>
                <TextView/>
            </LinearLayout>

        </FrameLayout>

        <FrameLayout
            android:id="@+id/button2"
            android:layout_height="0dp"
            android:layout_weight="0.5">

            <ImageView/>

            <ImageView/>

            <LinearLayout android:orientation="vertical">
                <TextView/>
                <TextView/>
            </LinearLayout>
        </FrameLayout>
    </LinearLayout>
</LinearLayout>
```
If i use butterknife to bind the two FrameLayouts to an OnClick event I'm experiencing an issue where the event gets delayed. clicking button2 works fine. I can click and the event comes straight away.

However if I click button1 the event doesn't come through. If I subsequently press button2 then I get both events coming through at the same time.

If I manually add an OnClickListener and not use butterknife then everything works as expected. I have triple checked everything to make sure I'm not doing anything silly like giving both framelayouts the same id.

**Comment by mblcdr** [comment]
I experienced something similar to this. I have a button that shows an Activity as a dialog. Sometimes by being so quick I can tap it twice resulting in two dialogs to be shown instead of the second tap dismissing the dialog. Really odd!

I am also getting some crashes like this one:
```Java
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.x.w(FragmentManager.java:1377)
       at android.support.v4.app.x.c(FragmentManager.java:504)
       at android.support.v4.app.p.onBackPressed(FragmentActivity.java:178)
       at com.example.app.activity.PhotoActivity.back(PhotoActivity.java:225)
       at com.example.app.activity.bj.doClick(PhotoActivity$$ViewBinder.java:73)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
       at android.view.View.performClick(View.java:4209)
       at android.view.View$PerformClick.run(View.java:17457)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5341)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:929)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
Which indicates that the OnClick of a button is called after the ```onSaveInstanceState``` of an Activity!
@JakeWharton I appreciate if you could take a look at this. Thanks.

**Comment by JakeWharton** [comment]
There's nothing to look at. That stacktrace clearly indicates the View
initiated the click which passed into your user code whose actions
initiated the FragmentManager change.

**Comment by mblcdr** [comment]
Yes, I know. But is it possible for a normal click listener to be fired after onSaveInstanceState causing this? The code only calls OnBackPressed of an activity, also no fragment is in this activity!

 What about the dialog shown twice?

It is totally strange to me but these crashes start to appear when I upgraded to 7.0.1 from 6.1.0. I guess it is just a coincidence, because nothing changed in ButterKnife to reflect this.

**Comment by JakeWharton** [comment]
Yes, a normal click listener can be called in the same way. The trace indicates that the view is the origin of the event and it merely passes through our custom listener.

The two dialogs is a race condition in your code. The input events are queued and processed before the first dialog is every displayed.

**Comment by JakeWharton** [comment]
Cannot reproduce. If you can reproduce the behavior in a full sample I'll be happy to look.

**Comment by Malikkhoja** [comment]
Hi Jake,

I m trying to write onClick event of an button which belongs to an activity in an Fragment. I am not able to get the reference as ButterKnife takes **this**. Can you please help me?
