### ISSUE TITLE
Feature Request: Annotation for binding array resources

### ISSUE THREAD

**Issue by tpfaff** [JakeWharton/butterknife#300]
Would love to be able to bind array resources.

@BindString binds an R.string ID to a String field.

@BindArray binds an R.array ..........

**Comment by tomxor** [comment]
`@BindStringArray` was introduced in #297 and should probably be available on the next release. 

@JakeWharton there's also [getIntArray(int)](http://developer.android.com/reference/android/content/res/Resources.html#getIntArray(int)), [obtainTypedArray(int)](http://developer.android.com/reference/android/content/res/Resources.html#obtainTypedArray(int)) and [getTextArray(int)](http://developer.android.com/reference/android/content/res/Resources.html#getTextArray(int)) -- would you rather have multiple annotations (i.e. `@BindIntArray`, `@BindTypedArray`, `@BindTextArray`) - or switch to `@BindArray` and figure out which method to call according to the type of enclosing element?

**Comment by tpfaff** [comment]
Awesome!

**Comment by JakeWharton** [comment]
Oops. I thinking switching on `@BindArray` would be ideal provided there's no change of ambiguity.

**Comment by JakeWharton** [comment]
Although it prevents us from using the support-annotations in the future #144.

**Comment by tomxor** [comment]
Can't we use `@ArrayRes`?

**Comment by JakeWharton** [comment]
Oh it's not typed? I guess that makes sense (but is unfortunate). I'm not an array resources user (hence its omission and my lack of knowledge here). If that's true, then go for it!

**Comment by tomxor** [comment]
:+1:
