### ISSUE TITLE
Re-add @Optional for methods only.

### ISSUE THREAD

**Issue by IonAalbers** [JakeWharton/butterknife#306]
Not really an 'issue', just a notice.

The following code will give a lint warning on @Nullable:

**Primitive type members cannot be annotated**

```java
@Nullable
@OnClick(R.id.button1)
public void menuRowClicked(View v) {
    // ...
}
```

**Comment by JakeWharton** [comment]
Yeah I guess we didn't really think through the implications here for methods being annotated with nullable. Funny that it sees `void.class` as a "primitive". Something to consider for future versions for sure.

**Comment by hzsweers** [comment]
Could the `@OnClick` defer to the bound field's nullability instead? Currently it looks like it overrides it to be required again, even if the field is annotated with `@Nullable`. Would eliminate needing to worry about annotating methods since the fields have to be bound regardless.

**Comment by JakeWharton** [comment]
> Would eliminate needing to worry about annotating methods since the fields have to be bound regardless.

What do you mean here? Fields are not required for views on which listener annotations are used.

**Comment by hzsweers** [comment]
Oh my bad, I thought they were. In that case, I'm not sure what the best solution is other than supporting something like `@Optional` again for methods only. Could adding something in lint.xml maybe help out here? It doesn't avoid the weirdness of nullable primitives, but would at least address the IDE linting.

**Comment by JakeWharton** [comment]
Yeah, I think we'll re-add `@Optional` but only have it apply for listener bindings for methods and `@Nullable` will be for fields.

**Comment by hzsweers** [comment]
I agree. Open to a PR?

**Comment by JakeWharton** [comment]
Please!

**Comment by hzsweers** [comment]
Will do! Also should I target this as an 8.0 thing or a different branch
for 7.1? Not sure what difference it would make.

**Comment by JakeWharton** [comment]
I plan on releasing 8.0 on Monday.

**Comment by JakeWharton** [comment]
OMG did I just give an ETA? Don't quote me on that! It was a temporary
lapse of judgement!!

**Comment by hzsweers** [comment]
Inb4 someone posts this to /r/androiddev

I'll try to PR tonight
