### ISSUE TITLE
Generate code with JavaPoet

### ISSUE THREAD

**Issue by tomxor** [JakeWharton/butterknife#307]
Java code generating is currently performed using string builders. This in my opinion makes it hard on readability and maintainability. I would propose changing the code to use [Square's JavaPoet](https://github.com/square/javapoet). Could this be something of interest?

**Comment by JakeWharton** [comment]
Blocked by #192

**Comment by serj-lotutovici** [comment]
Will prepare a PR after #323 is merged.

**Comment by JakeWharton** [comment]
a300be0dbc543cedccad562fe0e0dcec5703f393
