### ISSUE TITLE
@BindDrawable generates deprecated code on API 22+

### ISSUE THREAD

**Issue by svenjacobs** [JakeWharton/butterknife#309]
When on API level 22+ the code generated by `@BindDrawable` provokes a deprecation warning because [Resource#getDrawable(int)](https://developer.android.com/reference/android/content/res/Resources.html#getDrawable(int)) should not be used on API 22+ anymore.

**Comment by JakeWharton** [comment]
This only matters if you use theme attributes in a drawable XML.

**Comment by JakeWharton** [comment]
A fix was merged.
