### ISSUE TITLE
@OnClick doesn't work with android-floating-action-button

### ISSUE THREAD

**Issue by carlyonmdsol** [JakeWharton/butterknife#310]
https://github.com/futuresimple/android-floating-action-button

For a FloatingActionsMenu the onClick looks like

    floatingActionsMenu.setOnFloatingActionsMenuUpdateListener(new FloatingActionsMenu.
                OnFloatingActionsMenuUpdateListener() {
            @Override
            public void onMenuExpanded() {

            }

            @Override
            public void onMenuCollapsed() {

            }
        });
 

This is not supported in ButterKnife with an @OnClick

Behavior like this breaks the purpose of the framework since I now have different locations for OnClicks depending on what is or is not supported by ButterKnife.

**Comment by JakeWharton** [comment]
There's far too many third-party libraries to bake in support in Butter Knife. The [design support library's FAB][1] uses `View.OnClickListener` which will work with `@OnClick`.

 [1]: https://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html

**Comment by carlyonmdsol** [comment]
Is there any way for third-party libraries to add support for ButterKnife?

**Comment by JakeWharton** [comment]
Not at this time. That's a complicated thing, but I plan to get to it
eventually.
