### ISSUE TITLE
@BindDimen doesn't work with custom float dimensions.

### ISSUE THREAD

**Issue by ewintory** [JakeWharton/butterknife#312]
Hi! I've just encountered the following problem, ButterKnife can't bind this dimension:
```xml
<item name="movie_item_image_aspect_ratio" format="float" type="dimen">0.5625</item>
```
```java 
@BindDimen(R.dimen.movie_item_image_aspect_ratio) float mImageAspectRatio;
```
Is it possible to bind such resources, or it's required to do some fixes in ButterKnife?

**Comment by JakeWharton** [comment]
What resources method would you load the value with without ButterKnife?

**Comment by ewintory** [comment]
Hi @JakeWharton , do you mean without? Without I'll do like that:
```java
TypedValue outValue = new TypedValue();
fragment.getResources().getValue(R.dimen.movie_item_image_aspect_ratio, outValue, true);
float aspectRatio = outValue.getFloat();
```

**Comment by JakeWharton** [comment]
Will fix for 7.1. No timeline on that though.

**Comment by JakeWharton** [comment]
The fix (if anyone wants to get fancy and try to contribute it) is going to be creating and re-using a `TypedValue` instance for all of the resource binding. This can either be done with a `ThreadLocal` on the `ButterKnife.Finder` or just once per injection in the generated code. I think I prefer the former since it keeps the generated code clean.

**Comment by ewintory** [comment]
@JakeWharton Okay, I'll try to fix it :)

**Comment by JakeWharton** [comment]
Does this throw an exception? Or just return 0?

**Comment by ewintory** [comment]
This just throws ```NotFoundException``` from ```Resources#getDimension(int)``` method:
```
public float getDimension(int id) throws NotFoundException {
        synchronized (mAccessLock) {
            TypedValue value = mTmpValue;
            if (value == null) {
                mTmpValue = value = new TypedValue();
            }
            getValue(id, value, true);
            if (value.type == TypedValue.TYPE_DIMENSION) {
                return TypedValue.complexToDimension(value.data, mMetrics);
            }
            throw new NotFoundException(
                    "Resource ID #0x" + Integer.toHexString(id) + " type #0x"
                    + Integer.toHexString(value.type) + " is not valid");
        }
    }
```
The reason is that custom float dimension's ```TypedValue.type``` equals to ``` TYPE_FLOAT```, not to ```TYPE_DIMENSION```.

**Comment by JakeWharton** [comment]
Interesting. So perhaps `@BindFloat` is more appropriate? I assume then that the value can be accessed using `Resources.getFloat` method?

**Comment by JakeWharton** [comment]
I spent an hour digging through the aapt tool, `Resources.java`, and the developer documentation looking for a more official specification on how resources are parsed and what dictates the "type".

**Comment by ewintory** [comment]
Now, I don't know how to organize such binding with ```FieldResourceBinding``` class...

**Comment by ewintory** [comment]
Hmm, maybe you are right, BindFloat will be more appropriate.

**Comment by ewintory** [comment]
@JakeWharton Strange, my IDE can't see```Resources#getFloat()``` method.

**Comment by JakeWharton** [comment]
Ah, it's not a public API (yet).

**Comment by ewintory** [comment]
@JakeWharton So, what should we do? Should we wait for getFloat approval, or make a workaround with TypedFalue?

**Comment by JakeWharton** [comment]
I'm focused on some (what I deem) more important changes in the library before I plan to get to this. I'd like to investigate how Android determines what type a resource declaration becomes. For example, this was marked as a float despite the clear dimension declaration in XML. Does replacing that with "float" yield the same result (is "float" even valid there?). What other formats alter the type?
