### ISSUE TITLE
7.0.x issue with ClassCastException

### ISSUE THREAD

**Issue by kalvish21** [JakeWharton/butterknife#313]
I get the following error updating to latest versions of butterknife (7.0.0 and 7.0.1):

Error:Execution failed for task ':myapp:compileDebugJava'.
> java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement
li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

Not quite sure, but when I downgrade to 6.1.0 all errors are gone.

**Comment by ewintory** [comment]
Hi, you should look at this: #303

**Comment by ewintory** [comment]
And read changelogs when upgrading.
