### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/butterknife#314]
I cannot use Butterknife 7. My app crashes with:
> NoSuchMethodError: No static method inject(Landroid/app/Activity;)V in class Lbutterknife/ButterKnife; or its super classes (declaration of 'butterknife.ButterKnife' appears in /data/app/com.chaione.healthhousecalls.drnow-1/base.apk)

What is going on??

**Comment by tomxor** [comment]
See the [change log](https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md).

**Comment by IgorGanapolsky** [comment]
@tomxor What am I looking at?

**Comment by tomxor** [comment]
> ButterKnife.bind and ButterKnife.unbind replaces ButterKnife.inject and ButterKnife.reset, respectively.

**Comment by IgorGanapolsky** [comment]
Makes no sense friend.  My activity which causes this stacktrace isn't
binding any views at all or calling Butterknife.

**Comment by IgorGanapolsky** [comment]
Actually, this error stems in another framework I am using - mosby - which
isn't compatible with Butterknife 7.

**Comment by JakeWharton** [comment]
So, no action to take here then?

**Comment by JakeWharton** [comment]
Looks like yes (read the original description).

**Comment by IgorGanapolsky** [comment]
Thanks for the help and this cool framework.  @changetip $1.
