### ISSUE TITLE
@BindBitmap(R.drawable.foo) Bitmap foo

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/butterknife#315]
```java
foo = BitmapFactory.decodeResource(res, R.drawable.foo);
```

**Comment by tomxor** [comment]
Is this going to replace `@BindDrawable`?

**Comment by JakeWharton** [comment]
No. Different use cases. Sometimes you need a raw Bitmap (notification
icon, task description icon, etc.).

**Comment by tomxor** [comment]
Should we actually clear the `Bitmap` reference in `unbind()`?

**Comment by JakeWharton** [comment]
I don't think so. Other resources do not behave this way and while there is a native component, the point of unbind it to prevent leaking activities from fragments when you can't really leak a Bitmap in the same fashion.

**Comment by vsay01** [comment]
I use ButterKnife 7.0.1 and I need to use the Bitmap resource, According to this thread @BindBitmap annotation was added, but when it is not found. Is it removed? Any other way to achieve this goal?

**Comment by JakeWharton** [comment]
It has not been released yet.
