### ISSUE TITLE
Binding listeners to provided root view if no ID is specified

### ISSUE THREAD

**Issue by radu-topor** [JakeWharton/butterknife#318]
Use case:

```java
class ViewHolder extends RecyclerView.ViewHolder {
    @Bind(R.id.some_text) TextView someText;

    ViewHolder(View view) {
        super(view);
        ButterKnife.bind(this, view);
    }

    // No child ID specified, so bind to root
    @OnClick void onItemClick() {
        Log.d("Item clicked. Position: ", getAdapterPosition());
    }
}
```

I've found other cases where this would be useful, but I believe this would be a more common one.

**Comment by tomxor** [comment]
IMO for for `RecyclerView.ViewHolder` this makes perfect sense. Can you elaborate on the other use cases?

**Comment by JakeWharton** [comment]
This feature already exists

**Comment by tomxor** [comment]
Only for view subclasses, no?

**Comment by JakeWharton** [comment]
I don't remember...

**Comment by tomxor** [comment]
https://github.com/JakeWharton/butterknife/blob/2d1f0ab204ee877a18d5eba2aab4d5c5b7cfb933/butterknife/src/main/java/butterknife/internal/ButterKnifeProcessor.java#L840-L848

**Comment by JakeWharton** [comment]
Dupe #293.
