### ISSUE TITLE
Is 7.0.1 workable

### ISSUE THREAD

**Issue by new-xd** [JakeWharton/butterknife#319]
I just download the latest JAR and try it with the sample project.
Then I get this:
07-17 14:26:34.320: D/ButterKnife(9794): Looking up view binder for com.example.butterknife.SimpleActivity
07-17 14:26:34.320: D/ButterKnife(9794): Not found. Trying superclass android.app.Activity
07-17 14:26:34.320: D/ButterKnife(9794): MISS: Reached framework class. Abandoning search.
.........
07-17 14:26:34.320: E/AndroidRuntime(9794): Caused by: java.lang.NullPointerException
07-17 14:26:34.320: E/AndroidRuntime(9794): 	at com.example.butterknife.SimpleActivity.onCreate(SimpleActivity.java:75)

Code :
line69		    super.onCreate(savedInstanceState);
line70		    setContentView(R.layout.simple_activity);
line71		    ButterKnife.setDebug(true);
line72		    ButterKnife.bind(this);

line74		// Contrived code to use the bound fields.
line75		    title.setText("Butter Knife");
line76		    subtitle.setText("Field and method binding for Android views.");
line77		    footer.setText("by Jake Wharton");
line78		    hello.setText("Say Hello");

title is null.

So, which version is workable?

**Comment by JakeWharton** [comment]
You code generation is not working or ProGuard is stripping the generated classes. See the README for ProGuard instructions or the website for help configuring your IDE for non-Gradle builds.

**Comment by JakeWharton** [comment]
Actually ProGuard is on the website too.

**Comment by new-xd** [comment]
Thank you
