### ISSUE TITLE
Could not find com.jakewharton:butterknife-compiler:7.0.1.

### ISSUE THREAD

**Issue by ersin-ertan** [JakeWharton/butterknife#324]
Grabbing butterknife with the apt for the compiler yields:

Error:Could not find com.jakewharton:butterknife-compiler:7.0.1.
Searched in the following locations:
    https://jcenter.bintray.com/com/jakewharton/butterknife-compiler/7.0.1/butterknife-compiler-7.0.1.pom
    https://jcenter.bintray.com/com/jakewharton/butterknife-compiler/7.0.1/butterknife-compiler-7.0.1.jar
  
P.S. The new README makes no mention of apply plugin: 'com.neenbedankt.android-apt'
The site docs will need a bump too, when apt is working.

**Comment by JakeWharton** [comment]
This hasn't been released yet. I'll update the readme

**Comment by JakeWharton** [comment]
aa4500587f7fdda5e6c249752c89deb4224083a8
