### ISSUE TITLE
Tint support on @BindDrawable

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/butterknife#326]
Usage:
```java
@BindDrawable(value = R.drawable.my_sweet_logo, tint = R.attr.accentColor)
Drawable mySweetLogo
```
Generates:
```java
TypedValue outValue = new TypeValue();
context.getTheme().resolveAttribute(annotation.tint(), outValue, true);
Resources res = context.getResources();
Drawable drawable = DrawableCompat.wrap(res.getDrawable(annotation.value()).mutate());
DrawableCompt.setTint(drawable, res.getColor(outValue.resourceId));
target.mySweetLogo = drawable;
```

**Comment by JakeWharton** [comment]
Check for the support-v4's `DrawableCompat` on the classpath as a prerequisite. This allow providing a friendly error message vs. just having the generated code fail to compile.

**Comment by mattprecious** [comment]
The single argument `getDrawable` was deprecated in API 22, so the generated code should do a version check and call the 2-arg version on 22+ and pass a null `Theme` .

**Comment by JakeWharton** [comment]
Ugh, yeah. That's being tracked by #309 because I didn't want to do it in generated code but as a static helper in one place (like the Context helpers we already have).

**Comment by lukaciko** [comment]
Do we really want the user to pass a color attribute instead of color resource ID? The above code would fail at runtime if the user accidentally passed a color resource ID (at `res.getColor()`).

**Comment by JakeWharton** [comment]
It would fail at compile-time with an `@AttrRes` annotation which it will have.

**Comment by JakeWharton** [comment]
Plus that same argument can be made for literally every `int` in this whole library.

**Comment by lukaciko** [comment]
Oh sure, support annotations to the rescue!

Still, don't you think color resources are more convenient in most cases?

**Comment by JakeWharton** [comment]
It's certainly easier to use, but i'm not sure it's more convenient. The
whole point of using a theme attribute is such that it allows the drawables
to change color when the view is inflated in multiple themes. For example,
we have a "green world" theme and a "white world" theme in our app and
views (with drawables) are used in both. We want to reference the same
drawable but have its color reflect the "primary" color of the theme.

**Comment by JakeWharton** [comment]
This was merged.
