### ISSUE TITLE
Proposal: Support vararg actions/setter/properties in apply()

### ISSUE THREAD

**Issue by hzsweers** [JakeWharton/butterknife#332]
Value prop: I've come across cases where I have a few modular actions that are sometimes used at the same time. For the sake of efficiency and convenience, it would be better to be able to apply a variable number of these in a single call and save the unnecessary repeated iterations that result from consecutive applications.

I can add some more concrete examples if necessary, let me know!

**Comment by hotchemi** [comment]
For example? May be you can use Dagger.

**Comment by hzsweers** [comment]
I think you mistunderstand, Dagger wouldn't help this at all.

Consider the following three actions:

```java
static final ButterKnife.Action<ImageView> DISABLE = new ButterKnife.Action<ImageView>() {
    @Override
    public void apply(ImageView tile, int index) {
        tile.setEnabled(false);
        safeTint(tile, R.color.disabled);
    }
};

static final ButterKnife.Action<ImageView> ENABLE = new ButterKnife.Action<ImageView>() {
    @Override
    public void apply(ImageView tile, int index) {
        tile.setEnabled(true);
        safeTint(tile, R.color.primary);
    }
};

static final ButterKnife.Action<ImageView> RESET_IMAGE = new ButterKnife.Action<ImageView>() {
    @Override
    public void apply(ImageView tile, int index) {
        tile.setImageDrawable(null);
    }
};
```

You can use them separately, and often will. But consider the situation where you have the following method:

```java
public void reset() {
    // Need to reenable everything and reset all images
    ButterKnife.apply(tiles, ENABLE);
    ButterKnife.apply(tiles, RESET_IMAGE);
}
```

This is slightly inefficient, as it will iterate over `tiles` twice. What I'm suggesting is to add support for doing this:

```java
public void reset() {
    // Need to reenable everything and reset all images
    ButterKnife.apply(tiles, ENABLE, RESET_IMAGE);
}
```

**Comment by hotchemi** [comment]
I see. Seems nice.

**Comment by SimonVT** [comment]
There's likely no difference in performance. You're comparing iterations over tiles twice versus iterating over tiles once and {ENABLE, RESET_IMAGE} tiles.size() times.
If you want performance (that you'll probably have a hard time measuring anyway), create an Action that wraps the two other actions. Then you'll save the extra loop.

There's probably a convenience argument to be made.

**Comment by hzsweers** [comment]
In hindsight, I was using "efficiency" as a placeholder for both performance and convenience, so I updated the original comment.

**Comment by JakeWharton** [comment]
Feel free to send a PR. Make it an overload, not just a change to the existing method, because I don't want to allocate the `Object[]` in the single (and common) case.

**Comment by hzsweers** [comment]
Will do. One question about implementation: Each method has a singular and plural view signature. Should there be vararg versions of both or just the plural?

For instance:

```java
apply(List<T>, Action);
apply(T, Action);
apply(List<T>, Setter, V);
apply(T, Setter, V);
apply(List<T>, Property<T, V>, V);
apply(T, Property<T, V>, V);

// Additions
apply(List<T>, Action...);
apply(T, Action...);
apply(List<T>, Setter..., V);
apply(T, Setter...);
apply(List<T>, Property<T, V>..., V);
apply(T, Property<T, V>..., V);
```

**Comment by JakeWharton** [comment]
Yes, all of them for completeness.

**Comment by hzsweers** [comment]
PR'd in #336.

Opted not to do this for properties and setters since it's unlikely that the same value would apply to multiple setters. Open to suggestions on it though
