### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by imyyq-star** [JakeWharton/butterknife#333]
Hello, in Fragment, if you call ButterKnife.unbind (this) in onDestroyView (), you can set the view resource to null. If you have not completed the network request at this time, and the network request will be used to view resources, then it will happen NullPointerException.
Forgive me for not good English

**Comment by artem-zinnatullin** [comment]
Add `if (someView != null)` checks or don't reset views via `ButterKnife.unbind(this)` or unsubscribe from async operations when fragment destroyed.

**Comment by JakeWharton** [comment]
This is a problem with your code, not the library. You need to account for the views having disappeared if you are making a network call inside the fragment

**Comment by yaoyao0719** [comment]
Hello，I want to know if I don't set ButterKnife.unbind(this) in activity and fragment ，that will hava what happen? Memory leaks will happen?
