### ISSUE TITLE
@BindDimen weird bug

### ISSUE THREAD

**Issue by c0nnector** [JakeWharton/butterknife#338]
Have this weird bug where lint will throw an exception about @BindDimen

I had this line and it worked fine till now
```java
@BindDimen(R.dimen.divider_margin)
int dividerMargin;
```

Now lint sometimes fails. Not sure if it's an issue with AS or with butterknife. Attaching lint result
<img width="840" alt="screen shot 2015-08-26 at 1 11 33 am" src="https://cloud.githubusercontent.com/assets/2115575/9481021/9398f544-4b8f-11e5-8905-f96f57ee1a01.png">

**Comment by JakeWharton** [comment]
I'll emit suppressions on the generated code. The next version will add `@DimenRes` to the `@BindDimen` (and other) annotations so it will be lint-impossible to pass the wrong value anyway and the check will happen at the right place.

**Comment by JakeWharton** [comment]
This is blocked by #330.

**Comment by c0nnector** [comment]
Any idea why it fails some of the times?

**Comment by JakeWharton** [comment]
Nope. No clue.

**Comment by c0nnector** [comment]
Closing the issue then. Maybe we'll find out in the next version

**Comment by gabrielittner** [comment]
@c0nnector do you use retrolambda and android-retrolambda-lombok? I just added those two to a project and had this error for the first time.

**Comment by c0nnector** [comment]
@gabrielittner Not using retrolamda

**Comment by tomxor** [comment]
Is it possible that the ID changes and the generated class does not get invalidated?

**Comment by JakeWharton** [comment]
Ah, probably. It's a shame we can't get the reference to the actual R
constant (without epic hacks).

**Comment by c0nnector** [comment]
I think it's an AS studio issue. Started after i updated to AS 1.4 preview 3

**Comment by emartynov** [comment]
Ok, got some clarification. Lint analyses sources as text files (maybe also class files). When I've tried to put in sources not constant reference but its value I got already error in AS:
<img width="722" alt="screenshot 2015-08-27 07 16 38" src="https://cloud.githubusercontent.com/assets/295424/9513120/ca189514-4c8b-11e5-8101-231bddb5c9b8.png">

**Comment by emartynov** [comment]
Created tools bug report https://code.google.com/p/android/issues/detail?id=183997&thanks=183997&ts=1440653372

**Comment by gpeal** [comment]
Would adding `//noinspection ResourceType` to the generated ViewBinder fix this? I'm seeing it as well.

**Comment by felipecsl** [comment]
For the time being I'd recommend adding this to your lint.xml

```
    <issue id="ResourceType">
        <!-- Remove this when this is fixed: https://github.com/JakeWharton/butterknife/issues/338 -->
        <ignore path="**/*$$ViewBinder.java" />
    </issue>
```

**Comment by marcio-granzotto-ckl** [comment]
Just to clarify, the lint.xml file should be on your-project-folder/app/lint.xml

**Comment by dimsuz** [comment]
Hmm. I started getting this error with `butterknife-8.2.1`. Using kapt (dunno if this is related).

Can this be a regression?

**Comment by dimsuz** [comment]
Though it's not `@BindDimen` as in original issue, but `@BindView`

**Comment by joshfriend** [comment]
Checking in to say that I get lint errors on 8.2.1 related to `@BindView` as well. @felipecsl's solution worked for me, but I had to change the path to `**/*_ViewBinding.java`:

```xml
<issue id="ResourceType">
    <!-- Remove this when this is fixed: https://github.com/JakeWharton/butterknife/issues/338 -->
    <ignore path="**/*_ViewBinding.java" />
</issue>
```

**Comment by AOrobator** [comment]
Currently experiencing this issue on 8.4.0 The following open source repository at this commit can reproduce the error 100% of the time: https://github.com/AOrobator/Konstellations/commit/6ff414762c20158e7dab3d383e05e6960d029fed
