### ISSUE TITLE
access ButterKnife Variable in Fragment from main Activity is null

### ISSUE THREAD

**Issue by amaydiam** [JakeWharton/butterknife#341]
Hello Guys i used ButterKnife in my project. Now I have Main Activity with 2 Tab Fragment ...

**MaiinActivity.Class**

 

       @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
        .....
        mPagerSlidingTabStrip = (PagerSlidingTabStrip) findViewById(R.id.tabs);
                mViewPager = (ViewPager) findViewById(R.id.pager);
                mPagerAdapter = new PagerAdapter(getSupportFragmentManager());
                mViewPager.setAdapter(mPagerAdapter);
               mPagerSlidingTabStrip.setViewPager(mViewPager);
            ........
            }
        
        public class PagerAdapter extends FragmentPagerAdapter { 
                private final String[] TITLES =
                        {"Tab 1", "Tab 2"};
                public PagerAdapter(FragmentManager fm) {
                    super(fm);
                }
                @Override
                public CharSequence getPageTitle(int position) {
                    return TITLES[position];
                }
        
                @Override
                public int getCount() {
                    return TITLES.length;
                }
                @Override
                public Fragment getItem(int position) {
             switch (position) {
                        case 0:
                            UserDetailFragment UserDetailFragment = new UserDetailFragment();
                            return UserDetailFragment;
        
                        case 1:
                            PhotoUserFragment PhotoUserFragment = new PhotoUserFragment();
                            return PhotoUserFragment;
                    }
                    return null;
                }
            }
    
    public void HandleSwipeRefresh (){
    
                        PhotoUserFragment puf = (PhotoUserFragment) 
                            puf.mSwipeRefreshLayout.setEnabled(false);
    }

**Fragment PhotoUserFragment.class**

    @Bind(R.id.swipe_container)
        public SwipeRefreshLayout mSwipeRefreshLayout;
    
           @Override
            public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                     Bundle savedInstanceState) {
        
                // "false");
                if (container == null) {
                    return null;
                }
                View rootView = inflater.inflate(R.layout.fragment_news_recyclerview, container, false);
                ButterKnife.bind(this, rootView);
           return rootView;
        
            }

In MainActivity.class `HandleSwipeRefresh()` to handle SwipeRefreshLayout in Fragment **PhotoUserFragment**. I getting force Close in line `puf.mSwipeRefreshLayout.setEnabled(false);`.  mSwipeRefreshLayout  is null, but mSwipeRefreshLayout  is exist in Layout. 
so how to access right mSwipeRefreshLayout on my MainActivity ?

**Comment by JakeWharton** [comment]
There is not enough code here to diagnose the problem, yet paradoxically there's already too much code here. Your problem is not with ButterKnife, but with how fragments, view pagers, and activities behave and relate to each other. ButterKnife is just a convenience for calling `findViewById` and creating listeners on views. It has no effect on the interactions of the larger components at hand which is where your problem lies. You could try StackOverflow, but you'll need to narrow down the scope of the problem. GitHub issues here are for explicit bugs or feature requests with the library which this is not.
