### ISSUE TITLE
[feature request] Detailed error message when ButterKnife is unable to bind views

### ISSUE THREAD

**Issue by pavel-mukhanov** [JakeWharton/butterknife#342]
It will be very useful if we know which view causes bind error. 
E/AndroidRuntime(18420): java.lang.RuntimeException: Unable to bind view [SimpleDraweeView] for

**Comment by JakeWharton** [comment]
Paste the entire stacktrace. I'm willing to bet there's a useful message in
the cause.

**Comment by pavel-mukhanov** [comment]
E/AndroidRuntime(19059): java.lang.RuntimeException: Unable to bind views for com.playdayteam.presentation.adapter.	RoomsAdapter$RoomHolder
	E/AndroidRuntime(19059): 	at butterknife.ButterKnife.bind(ButterKnife.java:322)
	E/AndroidRuntime(19059): 	at butterknife.ButterKnife.bind(ButterKnife.java:279)
	E/AndroidRuntime(19059): 	at com.playdayteam.presentation.adapter.RoomsAdapter$RoomHolder.<init>(RoomsAdapter.java:377)
	E/AndroidRuntime(19059): 	at com.playdayteam.presentation.adapter.RoomsAdapter.onCreateViewHolder(RoomsAdapter.java:103)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5062)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1947)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:434)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1322)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
	E/AndroidRuntime(19059): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1626)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1673)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1673)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1673)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
	E/AndroidRuntime(19059): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
	E/AndroidRuntime(19059): 	at android.view.View.layout(View.java:14891)
	E/AndroidRuntime(19059): 	at android.view.ViewGroup.layout(ViewGroup.java:4646)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	E/AndroidRuntime(19059): 	at android.widget.FrameLayout.onL

**Comment by JakeWharton** [comment]
The stacktrace is truncated because Android only allows 4000 chars. You can
call getCause() and log that explicitly to see the message.

**Comment by thesnitch123** [comment]
just doin muh job here: https://github.com/pavel-mukhanov/CuttingEdge/commit/125bf0e22ffaa7ec2306846d0c40559abd6e60e8#diff-7b5f80ea07746027e89cd983c64f2130R40

**Comment by pavel-mukhanov** [comment]
getCause helps, thank you.

**Comment by thesnitch123** [comment]
@JakeWharton did u see it tho, just b4 it was deleted?
