### ISSUE TITLE
Rejecting re-init on previously-failed class java.lang.Class<butterknife.internal.ButterKnifeProcessor>

### ISSUE THREAD

**Issue by angeloyxw** [JakeWharton/butterknife#345]
I find this log before start main activity.I can't resolve and hope tell me reason,thank you.
this is my log
I/art﹕ Late-enabling -Xcheck:jni
W/art﹕ Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widge
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<butterknife.internal.ButterKnifeProcessor>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<butterknife.internal.ButterKnifeProcessor>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<cn.sharesdk.sina.weibo.SinaActivity>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<cn.sharesdk.sina.weibo.SinaActivity>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.makeramen.RoundedTransformationBuilder$1>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.makeramen.RoundedTransformationBuilder$1>
D/ThemeValues﹕ customized theme has contain this value: miui/color/action_bar_tab_text_color_normal_light/#b3ffffff
D/ThemeValues﹕ customized theme has contain this value: miui/color/action_bar_tab_text_color_pressed_light/#ffffffff

**Comment by angeloyxw** [comment]
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<butterknife.internal.ButterKnifeProcessor>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<butterknife.internal.ButterKnifeProcessor>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<cn.sharesdk.sina.weibo.SinaActivity>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<cn.sharesdk.sina.weibo.SinaActivity>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.makeramen.RoundedTransformationBuilder$1>
I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.makeramen.RoundedTransformationBuilder$1>

**Comment by JakeWharton** [comment]
This has nothing to do with ButterKnife.
