### ISSUE TITLE
Resource binding fails in DialogFragment

### ISSUE THREAD

**Issue by psyren89** [JakeWharton/butterknife#346]
I have code that resembles the following:
```
public class Foo extends DialogFragment {
  @BindString(...)
  @BindString(...)

  @Bind(...)
  @Bind(...)

  @Override
  public Dialog onCreateDialog(...) {
    ...
    View view = View.inflate(...);
    ButterKnife.bind(this, view);
    ...
  }
}
```
After the call to `ButterKnife.bind()`, the views are bound properly, but the string resources are not. What do I need to do to fix this? Should I switch back to using `getString()` calls?

**Comment by JakeWharton** [comment]
As in, they're `null`?

**Comment by JakeWharton** [comment]
What do you see in the generated `Foo$$ViewBinder.java` class?

**Comment by psyren89** [comment]
> As in, they're `null`?

Correct.

> What do you see in the generated Foo$$ViewBinder.java class?

```
@Override public void bind(final Finder finder, final T target, Object source) {
  ...  
  target.idKey = res.getString(2131099675);
  target.colourKey = res.getString(2131099672);
  target.titleKey = res.getString(2131099680);
  target.modeKey = res.getString(2131099677);
  target.typeKey = res.getString(2131099681);
}
```

**Comment by JakeWharton** [comment]
Don't really know what to tell you. `null` is being returned from Android's `Resources` class. Doesn't really seem to have anything to do with ButterKnife.

Try loading the resources manually in the same place you're calling `ButterKnife.bind` and see if they come back `null` as well.

**Comment by psyren89** [comment]
Calls to `getString()` seem to work fine in the same place.
¯\_(ツ)_/¯

**Comment by prateek-patel** [comment]
I was also facing the same problem but then I release that I have not added annotation-processor in module build.gradle file. So add this line **compile 'com.jakewharton:butterknife-compiler:8.4.0'**

**Comment by atcharatip** [comment]
#841 @psyren89 

- [ ] 

- 

1.

**Comment by atcharatip** [comment]
#841
