### ISSUE TITLE
Multiple Bind (@Binds)

### ISSUE THREAD

**Issue by cemo** [JakeWharton/butterknife#349]
I am currently using as this:

```
   @Bind(R.id.tutorial_dot1)
   ImageView dot1;

   @Bind(R.id.tutorial_dot2)
   ImageView dot2;
 
   ...
   ...

   @Bind(R.id.tutorial_dot10)
   ImageView dot10;
```

Actually I am not interested in each element here. I just need an array and access them by index.

```
      @Binds(R.id.tutorial_dot1, R.id.tutorial_dot2, ... , R.id.tutorial_dot10)
      ImageView[] views;
```

Is it worth to add this feature?

**Comment by tomxor** [comment]
This feature already exists, you can pass an array of IDs to `@Bind`:

```java
@Bind({ R.id.one, R.id.two }) ImageView[] views;
```

**Comment by cemo** [comment]
I have just noticed bind takes multiple int. :(

**Comment by cemo** [comment]
what about BindDrawable? This does let me to bind multiple drawable. Is there any particular reason? @tomxor

**Comment by JakeWharton** [comment]
That is not supported. Why would that be useful to you?

**Comment by cemo** [comment]
Sorry, It was my fault.
