### ISSUE TITLE
Using Proguard and BindColor results in error

### ISSUE THREAD

**Issue by AndreasBackx** [JakeWharton/butterknife#350]
Trying to generate a signed APK with Proguard results in the following error:

```
Error: Expected resource of type color [ResourceType]
```

These are the bindings used in the Activity:
```java
@BindColor(R.color.darkRed) int darkRed;
@BindColor(android.R.color.white) int white;
```

This is what's generated and the error refers to the 2nd line:
```java
Resources res = finder.getContext(source).getResources();
target.darkRed = res.getColor(2131558428);
target.white = res.getColor(17170443);
```

These are the Proguard rules that I'm using for Butterknife as were mentioned on the website:
```
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}
```

Building the application without Proguard works just fine and the application works as it should. I'm also using Butterknife 7.0.1.

Could there be anything missing in the Proguard rules mentioned on the website?

**Comment by serj-lotutovici** [comment]
I think it's the same as #338.
