### ISSUE TITLE
Duplicate file with google app engine

### ISSUE THREAD

**Issue by joserocha3** [JakeWharton/butterknife#351]
I am getting this error when compiling and using both app engine and butterknife. It looks it has something to do with the annotations. Both butterknife and app engine use annotations. Is this something that you can fix on your end or would I have to not use gradle import instead as a lib to remove the redundant file? Thanks

Stack trace:

    * What went wrong:
    Execution failed for task ':app:packageDebug'.
    > Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor
    File 1: C:\Users\Pablo\.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife\7.0.1\d5d13ea991eab0252e3710e5df3d6a9d4b21d461\butterknife-7.0.1.jar
    File 2: C:\Users\Pablo\.gradle\caches\modules-2\files-2.1\com.google.appengine\appengine-api-1.0-sdk\1.9.21\f26748ef843330623b072572805337c8e6f586a3\appengine-api-1.0-sdk-1.9.21.jar

Gradle:

     compile 'com.google.appengine:appengine-api-1.0-sdk:1.9.21'
     compile 'com.jakewharton:butterknife:7.0.1'

**Comment by JakeWharton** [comment]
You can ignore this with:
```groovy
android {
  packagingOptions {
    exclude 'META-INF/services/javax.annotation.processing.Processo'
  }
}
```

**Comment by JakeWharton** [comment]
Since annotation processors run at the time of `javac`, this is a non-issue when packaging.

**Comment by joserocha3** [comment]
Great. Thanks!
