### ISSUE TITLE
Lint: Unused resource

### ISSUE THREAD

**Issue by Ph1b** [JakeWharton/butterknife#356]
My Android Studio 1.3.1 shows me that methods annotated with @OnClick are not used and thus can be deleted safely.
Is there a way to prevent this without adding a lint ignore for each method?

**Comment by lukaciko** [comment]
In Android Studio you can press alt/option+enter (intent actions) and then select Suppress for methods annotated by 'butterknife.OnClick'.

**Comment by JakeWharton** [comment]
If you use the [`android-apt` plugin][1] then Android Studio can see the generated code and the method will not show up as unused.

 [1]: https://bitbucket.org/hvisser/android-apt

**Comment by Ph1b** [comment]
Thats way more helpful than ignoring lint warnings. Because if I do so other lint checks will give false results. Thanks!
