### ISSUE TITLE
BindColor and BindDrawable should retrieve via ContextCompat instead of directly from Resources

### ISSUE THREAD

**Issue by wuman** [JakeWharton/butterknife#358]
Starting in M, the `ContextCompat` class provides the `getColor()`, `getColorStateList()` and the `getDrawable()` helper methods to retrieve colors and drawables.  The respective methods in the `Resources` class have been deprecated.

As such we should modify butterknife to accommodate these changes.  This would, however, require butterknife to depend on the support library.  I am happy to provide a patch for this, but I'm unsure whether @JakeWharton is okay with this new dependency.  Let me know!

**Comment by JakeWharton** [comment]
We don't need support-v4, as the ContextCompat methods are just glorified `if` statements that we can replicate in the runtime.

**Comment by JakeWharton** [comment]
This was fixed.

**Comment by jaredsburrows** [comment]
@JakeWharton @wuman What about the `getColor`?

I am seeing plenty of warnings:

```
warning: [deprecation] getColor(int) in Resources has been deprecated
    target.COLOR_PERCENT_CHANGE_RED = res.getColor(2131624030);
```

**Comment by JakeWharton** [comment]
The fix hasn't been released yet.

**Comment by jaredsburrows** [comment]
@JakeWharton Thanks for the quick reply. The date of the PR was merged at the end of September. When do you plan on releasing?

**Comment by JakeWharton** [comment]
I have no plan. Whenever all the things I want to put in 8.0 are done.
