### ISSUE TITLE
License still containing boilerplate notice

### ISSUE THREAD

**Issue by PLNech** [JakeWharton/butterknife#359]
Hi,

while integrating your project in a work of mine, I realised your license bears the following copyright notice:

`Copyright [yyyy] [name of copyright owner]`

Should you not, as explained in the appendix, "attach the following boilerplate notice, with the fields enclosed by brackets "[]" replaced with your own identifying information." ?

That being said, congratulations for your work on this awesome library !

**Comment by JakeWharton** [comment]
This is done at the bottom of the README.
