### ISSUE TITLE
NoSuchMethodError found on Android 2.2.x devices

### ISSUE THREAD

**Issue by dannysuen** [JakeWharton/butterknife#365]
In my production code I found following error occurs on Android 2.2.x devices:

java.lang.NoSuchMethodError: java.util.Arrays.copyOfRange
	at butterknife.ButterKnife$Finder.filterNull(ButterKnife.java:125)
	at butterknife.ButterKnife$Finder.listOf(ButterKnife.java:133)

Hope it's informative enough to help you locate the bug.

**Comment by JakeWharton** [comment]
Ugh. Yeah. That method is Java 6+ which is Android 2.3+.

**Comment by tbsandee** [comment]
See PR #367 for a starting point, if you like.
