### ISSUE TITLE
Jacoco (testCoverage) + butterknife 7.0.1 + android build tools (1.4.0-beta3) = exception

### ISSUE THREAD

**Issue by niekske** [JakeWharton/butterknife#377]
Hi, 

We use Butterknife 7.0.1 for our project, jacoco for code coverage and we are looking into to use Android Build Tools 1.4.0-beta3 (classpath 'com.android.tools.build:gradle:1.4.0-beta3') with SVG support. When we then run our application we get an exception in SomeFragment$$ViewBinder.java in jacoco.

See complete stacktrace: http://pastebin.com/9Q0Pb6Eh

A quick test: it does also fail with 1.4.0-beta2, but not with 1.4.0-beta1.

Regards,
Niek

**Comment by artem-zinnatullin** [comment]
Please repost this to Android Developers Tools team group https://groups.google.com/forum/#!forum/adt-dev

**Comment by niekske** [comment]
@artem-zinnatullin Done, post is not visible yet, because posts from new members are held for moderation.

**Comment by artem-zinnatullin** [comment]
:+1:, I believe it's a problem of tools, not ButterKnife

**Comment by niekske** [comment]
If it's really a tools issue I can file a bug to https://code.google.com/p/android/issues/list.

**Comment by artem-zinnatullin** [comment]
I am not 100% sure that it's a problem of Android Gradle Plugin, probably
it's a problem of Jacoco (which is separate tool), that's why I suggested
you contact ADT team, so they could give more information about this
problem :)

чт, 1 окт. 2015 г. в 15:07, niekske <notifications@github.com>:

> If it's really a tools issue I can file a bug to
> https://code.google.com/p/android/issues/list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JakeWharton/butterknife/issues/377#issuecomment-144707862>
> .
>
-- 

@artem_zin

**Comment by niekske** [comment]
Sample project: https://www.dropbox.com/s/rpbg9z64u8bxery/Jacoco_Butterknife_ADT.zip?dl=0

**Comment by niekske** [comment]
Xavier Ducrohet says: "Looks like butterknife dumps both the generated .java and .class in the compiler output folder which throws Jacoco off.

We changed how Jacoco is run to make it incremental, and this bypasses how Jacoco would normally exclude processing these files I suppose. It's an easy fix, thanks for the test project."

I guess this issue can be closed then? Or maybe here also some change is needed to prevent any other side effect from putting .java and .class files together?

**Comment by JakeWharton** [comment]
Yep. This has nothing to do with ButterKnife. All annotation processors behave that way because that's where javac points their output files.

Thanks for following up with the tools team about it though!
