### ISSUE TITLE
@Nullable doesn't work if Butterknife binds view from supersuperclass

### ISSUE THREAD

**Issue by tonyshkurenko** [JakeWharton/butterknife#389]
I have a super-superclass (class A) with a field:
```
@Bind(R.id.swipe_refresh)
@Nullable
protected SwipeRefreshLayout mRefreshLayout;
```

And when I call `ButterKnife.bind(this);` in the child-child class (class C extends B, which extends A) it provokes : 
```
E/AndroidRuntime:  Caused by: java.lang.IllegalStateException: Required view 'drawer_layout' with ID 2131624067 for field 'mDrawerLayout' was not found. If this view is optional add '@Nullable' annotation.
E/AndroidRuntime:     at butterknife.ButterKnife$Finder.findRequiredView(ButterKnife.java:140)
```

**Comment by JakeWharton** [comment]
Those are not the same views.

**Comment by tonyshkurenko** [comment]
Wow, Im deeply sorry!!! Just wanted to help and failed :(

**Comment by JakeWharton** [comment]
Happens to everyone :)

**Comment by cfxmys** [comment]
i met the same issue  in  8.6.0

here is the sample code

the base class
`public abstract class BaseFragment extends Fragment {
    @Override
    public final View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        if (rootView == null) {
            this.rootView = (ViewGroup) inflater.inflate(R.layout.fragment_base, container, false);

//            // init butterknife, has error
//            ButterKnife.bind(this, this.rootView);
 
        if (contentView == null) 
            contentView = gView(inflater, container, savedInstanceState);
           
        return rootView;
    }
	protected abstract View gView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState);
	
}`

the child class 
`public class TestFragment extends BaseFragment {

	@Override
    public View gView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		View content = inflater.inflate(R.layout.fragment_test, container, false);
		ButterKnife.bind(this, content); // worked well
	}
}`
