### ISSUE TITLE
@Unbinder usage in BaseFragment

### ISSUE THREAD

**Issue by mjurkus** [JakeWharton/butterknife#390]
Up until introduction of `@Unbinder` interface and annotation it was enough to add `Butterknife.unbind(this)` to your `BaseFragment` and all bindings.
From https://github.com/JakeWharton/butterknife/pull/378 it is no longer possible and requires to add
```
@Unbinder
ButterKnife.Unbinder unbinder;
```

to each fragment. Which IMO is not sexy.

```
public class BaseFragment$$ViewBinder<T extends BaseFragment> implements ViewBinder<T> {
  @Override
  public void bind(final Finder finder, final T target, Object source) {
    Unbinder unbinder = new Unbinder(target);
    target.unbinder = unbinder;
  }

  private static final class Unbinder implements butterknife.ButterKnife.Unbinder {
    private BaseFragment target;

    Unbinder(BaseFragment target) {
      this.target = target;
    }

    @Override
    public void unbind() {
      if (target == null) throw new IllegalStateException("Bindings already cleared.");
      target.unbinder = null;
      target = null;
    }
  }
}
```

**Comment by serj-lotutovici** [comment]
This was done, to give the unbinder a reference to all fragment views that have method bindings. See issue #211.  This way we can null out the listeners for the views, that where set via method bindings.

Since the parent fragment, doesn't really know about it's child's views, this approach was taken.

As an extension, of this, there may be a possibility to make it more generic by introducing `parent unbinder` handling, this way `ButterKnife.bind` will use the same field, but assign a different reference in the child. But not sure how this will work out.

**Comment by JakeWharton** [comment]
Sounds like we just need the hierarchy of the generated unbinder to match that of the viewbinder (and calling classes)

**Comment by serj-lotutovici** [comment]
@JakeWharton So basically during annotation processing check if there is a parent unbinder and make the actual unbinder inherit form that? 

But how then we handle the nulling of `target.binder` and `target.unbinder`?

**Comment by JakeWharton** [comment]
Sorry I wasn't thinking it through completely. This might be a bit tricky to get right.

**Comment by serj-lotutovici** [comment]
@JakeWharton I almost got it working... will submit a PR in a few minutes.

**Comment by JakeWharton** [comment]
Awesome!

**Comment by serj-lotutovici** [comment]
Ok, you're right... this is more tricky then I thought. If you're not in a hurry, will try to finish with this tomorrow...

**Comment by stephanenicolas** [comment]
Hi all, 

sorry to say this but yeah, the new API is less yummy than the old unbind. Wouldn't it be possible to associate a binder to all fragments performing a ButterKnife.bind call and keep the ButterKnife.unbind ? 
I got the feeling that a simple hashmap of week ref of fragments --> unbinder would make it completely transparent and ease migration to API 8.

**Comment by JakeWharton** [comment]
Can we just nuke inheritance of the generated view binders and instead make them responsible for the entire hierarchy?
