### ISSUE TITLE
Issue with inheritance

### ISSUE THREAD

**Issue by Ph1b** [JakeWharton/butterknife#391]
I have a `BaseActivity` which binds some views.

And I have several activities which extend this  `BaseActivity`. These extending classes add some views to a FrameLayout of their parent `BaseActivity`.

Both use `ButterKnife.bind(this)`.
But I get an exception that the views cannot be found. This is due to the `super.onCreate(...)` method of the extending classes call their parents `ButterKnife.bind(this)`through their `super.onCreate(...)`.

Is there a way to fix this without dropping ButterKnife?

**Comment by mjurkus** [comment]
Use `@Nullable` in `BaseActivity`

**Comment by Ph1b** [comment]
The problem are not the views of `BaseActivity`. The problems are the views of all activity which extend. So I would have to use `@Nullable`on all the views. This should work but this does not seem like a good solution as I would have to suppress tons of null-check warnings.

**Comment by JakeWharton** [comment]
This is just a cyclic dependency. You cannot bind a view, add views to it, and have those children bound after. You either need to do a normal `findViewById` for the frame to which you add views and then do a single bind after the fact, or use another object for binding the children which you can call `bind` on after adding them.

**Comment by Ph1b** [comment]
What do you mean by
> or use another object for binding the children which you can call bind on after adding them.

**Comment by JakeWharton** [comment]
```java
class Foo {
  @Bind(R.id.foo) TextView foo;
}
```
```
// parent class calls bind
// children are added, including 'foo'
Foo foo = new Foo();
ButterKnife.bind(foo, this);
```

**Comment by Ph1b** [comment]
Thanks. Isn't it possible that ButterKnife binds only views declared in Activity `A` when called from Activity `A`? And not from `B extends A`?

**Comment by anukools** [comment]
Same issue with the extended activities... Is there any better suggestions.

**Comment by artemisIrelia** [comment]
Coming from 2018. Is there any better solutions yet?
