### ISSUE TITLE
@Bind View in NavigationView is null when upgraded support-design lib to 23.1.0

### ISSUE THREAD

**Issue by tericky** [JakeWharton/butterknife#395]
Hi, after I upgraded the lib : com.android.support:design to version 23.1.0, the @Bind can't find View in NavigationView, there are any solution to bind it ?

PS. by google, I find out maybe is this problem : https://code.google.com/p/android/issues/detail?id=190226

**Comment by JakeWharton** [comment]
If `findViewById` doesn't work then Butter Knife can't work. You'll have to wait until they fix it or provide the getter method as the issue says.

**Comment by Deathangel908** [comment]
Mb we should leave this issue opened and mark this as a **FEATURE**. Is there a way to bind butterknife view in other way? For example:
`ButterKnife.bind(this, navigationView.getHeaderView(0));`
But also we also can't use few binds in a single view. I mean if I need Views from both **layout** and **navigation** `butterknife` wouldn't know which one to wire.
