### ISSUE TITLE
Bind view  in include crash

### ISSUE THREAD

**Issue by AndroFlo** [JakeWharton/butterknife#396]
Hello ,

When i use an include layout for my toolbar and then bind it in AppCompatActivity i have this message :
 Caused by: java.lang.IllegalStateException: Required view 'toolbar' with ID 2131558619 for field 'toolbar' was not found. If this view is optional add '@Nullable' annotation.

My layout toolbar
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.Toolbar
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/toolbar"
    android:layout_height="wrap_content"
    android:layout_width="match_parent"
    android:minHeight="?attr/actionBarSize"
    android:background="?attr/colorPrimary" >

<RelativeLayout
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">


    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/editText_title_toolbar"
        android:textColor="@android:color/white"
        android:text="@string/app_name"
        android:textStyle="bold" />
</RelativeLayout>


    </android.support.v7.widget.Toolbar>
```

```Java

 @Bind(R.id.toolbar)Toolbar toolbar ;
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_activity);

        ButterKnife.bind(this);
}
```

**Comment by JakeWharton** [comment]
That layout is not being included in main_activity. Otherwise it would have
worked.

**Comment by JakeWharton** [comment]
Butter Knife is just sugar on `findViewById`, and that's what is failing to find the view. As I said, make sure that layout is `<include>` in `main_activity` or ensure you put a Toolbar with that ID in `main_activity` layout.

If you can provide more information and prove that Butter Knife is at fault here then I'll re-open and investigate.

**Comment by AndroFlo** [comment]
Hello Jake,

I suppose it was a problem at compile time, because retrying it works this morning , 

sorry and thank you

**Comment by niiamon** [comment]
+1 can confirm this. As of version `7.0.1`, adding an ID to the include causes the view to not be found.

**Comment by bigggge** [comment]
I also have the problem , set an ID to the include causes the view not be found

**Comment by alexsimo** [comment]
Just stating the issue. Works if you remove the `@id` from your `<include/>`.
Try using layouts that don't need IDs.

**Comment by j2rong** [comment]
If you put an `android:id` attribute inside the `<include>`, the id will be overrided

**Comment by tranvnb** [comment]
Just wrap the include tag with a new View, and issue fixed

**Comment by cascal** [comment]
Any updates on this issue?

**Comment by JakeWharton** [comment]
Yes, it's closed as not an issue with the library.

**Comment by aqeeb421** [comment]
I did not get a proper answer!?
