### ISSUE TITLE
Why aren't proposed pull requests merged?

### ISSUE THREAD

**Issue by gnardini** [JakeWharton/butterknife#397]
Hi! Firstly, thank you very much for this library, I've found it incredibly useful and has helped me remove lots of boilerplate code on my apps.

That's exactly why I'm surprised it doesn't have more stuff. I just read some of the PRs and there are some very useful annotations there, such as https://github.com/JakeWharton/butterknife/pull/245 https://github.com/JakeWharton/butterknife/pull/229 https://github.com/JakeWharton/butterknife/pull/231 https://github.com/JakeWharton/butterknife/pull/201

They all look like they have useful aplications. In fact, I'm using two of them on an app I'm working with at the moment, but I'd be really nice if they already were integrated with the library, is there any reason they haven't been already? (some of them have been there for quite some time) I understand if you just want to keep this library as small as possible, but then maybe make a butterknife 2.0 or something with the extra stuff? Or is there another reason? Idk, just throwing ideas here :P

Anyways, just wondering, this still looks great, and thanks so much for all of your contributions to the Android community!

**Comment by ViliusKraujutis** [comment]
@gnardini why did you close this issue without any update? Still wondering why #231 was not merged.

**Comment by JakeWharton** [comment]
Because I don't want it in the core library. Custom listeners are the way
forward.
