### ISSUE TITLE
Bound views are null after calling ButterKnife.bind(this)

### ISSUE THREAD

**Issue by cp949** [JakeWharton/butterknife#399]
```java
public class LaunchActivity extends AppCompatActivity
{
    @Bind(R.id.toolbar)   Toolbar   mToolbar;

    @Override
    protected void onCreate (Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_launch);
        ButterKnife.setDebug(true);
        ButterKnife.bind(this);
        
        // mToolbar is null when using 7.0.2-SNAPSHOT or 8.0.0-SNAPSHOT
        // 7.0.1 good working
        // ...
    }
}
```
ButterKnife 7.0.1
It's ok!

ButterKnife 7.0.2-SNAPSHOT or 8.0.0-SNAPSHOT
Bound View(mToolbar) is null

Debug Message is
D/ButterKnife: Looking up view binder for kr.ohlab.rhyme.LaunchActivity
D/ButterKnife: Not found. Trying superclass android.support.v7.app.AppCompatActivity
D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by JakeWharton** [comment]
Is the generated code being created? There should be a file named `LaunchActivity$$ViewBinder.java` somewhere in the build directory.

**Comment by cp949** [comment]
ButterKnife 7.0.1
Yes. LaunchActivity$$ViewBinder.java file is created

ButterKnife 7.0.2-SNAPSHOT or 8.0.0-SNAPSHOT
The file is not created

**Comment by JakeWharton** [comment]
So the next version splits the compiler and the runtime. Please see the "For the SNAPSHOT" section under "Download" in the README: https://github.com/JakeWharton/butterknife#download and make sure you have both the compiler and runtime.

**Comment by cp949** [comment]
@JakeWharton  thank you!

**Comment by jhanay** [comment]
8.0.1 has the same problem.
And not found LaunchActivity$$ViewBinder.java in classes.jar

**Comment by jega4u** [comment]
I am getting same error on my fragments class  
Looking up view binder for android.widget.RelativeLayout
MISS: Reached framework class. Abandoning search.
Shutting down VM

**Comment by jhanay** [comment]
If your App has more modules,such as one of module is a framework lib. And you need config the apt plugin in application modules. em:
compile 'com.jakewharton:butterknife:8.0.1'   add in library module
apt 'com.jakewharton:butterknife-compiler:8.0.1'  add in application module.

**Comment by freetlab** [comment]
In build.gradle file of your app you need to add the apt command after compile butterknife command:
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'

**Comment by cuijianzhi** [comment]
maybe this line  mistaken:
`  annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'`
where is annotationProcessor nor compile.

**Comment by gooyuan** [comment]
@Jhanay It works for me. Thank you!

**Comment by spragucm** [comment]
I added the all of following and my problem was fixed:

// Butterknife requires Java 8.
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
dependencies {
    //View, resource, and object binding
    implementation 'com.jakewharton:butterknife:10.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.1.0'
}
```
NOTE: I was missing the annotationProcessor and the compileOptions. I added all requirements for a complete answer.
