### ISSUE TITLE
why not bind layout in class

### ISSUE THREAD

**Issue by motcwang** [JakeWharton/butterknife#401]
like this
"@BindLayout(R.layout.xxx)
public class XXX extend Activity {}

instead of "setContentView"

**Comment by JakeWharton** [comment]
This library is only concerned with binding views to fields and methods, and not actually inflating (or pretending to inflate) the views in an object. There are a few issues from long ago discussing this, but basically it boils down to the fact that while the Activity case is easy and seems obvious, it's less clear what to do for Fragments and Views, so we opt to just not do anything at all.
