### ISSUE TITLE
How do you build butterknife

### ISSUE THREAD

**Issue by bmeike** [JakeWharton/butterknife#403]
I've tried a couple targets and a couple build artifacts.  None seems to be the complete butterknife closed over dependencies.  What am I missing?

**Comment by JakeWharton** [comment]
`./gradlew build`?

**Comment by bmeike** [comment]
Right.  Thanks for the quick response.  So where is the lib, when the build is complete.  I ended up adding the compiler, the annotations, and still finding that I was missing 2 or 3 external deps.  If 'build' builds the distribution, which file is it?  Thanks!

**Comment by JakeWharton** [comment]
Ahhh, ok. There is no artifact that's usable standalone, you'd have to publish it to a repository so it had a `pom.xml` the declared its external dependencies. Either that or you'd have to follow the dependencies manually and grab all of their jars.

**Comment by bmeike** [comment]
Got it.

I believe I have used the maven plugin to publish to a �local repository�� A directory in the project root, I believe.

Would it be worth adding something like that to the project, so that it would be possible for contributors could test their builds?

You must have to build it, to release.  If it were automated it would be pretty handy.

-blake

**Comment by JakeWharton** [comment]
I usually just test with the sample app and unit tests in the repo itself.
I could add a plugin to build jar-with-dependencies versions of the
artifacts, but it seems like a rare case. The latest SNAPSHOT from master
is also automatically published to Sonatype's OSS snapshot repo so that you
can always pull in the latest version to experiment with.

What are you trying to accomplish?

**Comment by bmeike** [comment]
Verify that the changes that I submitted in a pull-request, yesterday, actually work!

… and, perhaps, use those changes in my project the main time

Will have a look at testing using the sample app.

-blake

**Comment by bmeike** [comment]
Thanks
