### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class XXXActivity

### ISSUE THREAD

**Issue by iyy** [JakeWharton/butterknife#405]
version:    
compile 'com.jakewharton:butterknife:8.0.0-SNAPSHOT'
apt 'com.jakewharton:butterknife-compiler:8.0.0-SNAPSHOT'

sdk version:
 compileSdkVersion 23
 buildToolsVersion "23.0.2"

I ran into a exception when i used 8.0.0-SNAPSHOT
the mainActivity.class can't be found in the dest APK
when I removed apt 'com.jakewharton:butterknife-compiler:8.0.0-SNAPSHOT'
everything is OK

The MainActiviy extends from AppCompatActivity

**Comment by JakeWharton** [comment]
This is unlikely ButterKnife's fault, but rather a problem with the appcompat dependency being included. If the base class is not found, the classloader will throw away the extending class which is `MyActivity` in this case.

Look higher up in the logs for VerifyError and see if it says something like AppCompatActivity not found.
