### ISSUE TITLE
Where can I see the ButterKnifeProcessor generated class file ?

### ISSUE THREAD

**Issue by xiaomeixw** [JakeWharton/butterknife#408]
Where can I see the ButterKnifeProcessor generated class file ? for examle: where to see the MyActivity$$ViewInjector.java  file?

**Comment by JakeWharton** [comment]
It depends on which Java compiler you are using and which build system you are using. It's completely transparent to ButterKnife, as it is to all annotation processors. For raw `javac` it's the same as the class output directory by default, and I think this is true of Maven-based projects. For Gradle it's usually also in the class output directory, although there are plugins which control the source output based on whether it's a Java or Android project, so if you're using one of those then it's up to the plugin. Not sure about other build systems or other Java compilers (like `ecj`).

Run a `find` command (or similar) on your project directory after a build and they'll surely turn up somewhere.

**Comment by xiaomeixw** [comment]
@JakeWharton Thanks, I found it in this path:   C:\AndroidStudio\opensource\butterknife-master\butterknife-sample\build\intermediates\classes\debug\com\example\butterknife\SimpleActivity$$ViewBinder.class. 
Wonderful...
