### ISSUE TITLE
Don't use nullable annotation to indicate optional listeners

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/butterknife#413]
Nullable annotations make sense for optional view bindings, but not so much for listener methods. If the listener method has no return value or primitive return value you are basically telling the compiler that you have a Nullable void or primitive and Android Studio gives you an inspection warning for it. If the listener did return a reference value (not sure if any do) you would be saying that the return value is nullable when in fact it may not be.

Should come up with a better alternative. That may be having things like @OptionalOnClick or add your own @Optional annotation to use in place of @Nullable

**Comment by SimonVT** [comment]
Resolved by #388.
