### ISSUE TITLE
Bind view that was inflated later in code

### ISSUE THREAD

**Issue by Tooroop** [JakeWharton/butterknife#414]
I have some views that I bind at the onViewCreated in the fragment that are @Nullable
Later in code and have to set up a few OnClickListeners on a view that I additionally inflate. I annotate those methods with the @OnClick annotation and @Nullable...

Later when I create the additional view I want to bind it to those methods, but when I do ButterKnife.bind(this, additionalView) the views that I bound in the onViewCreated are all set to NULL.

Is there any way I can additionally bind views that I inflate later in code?

**Comment by JakeWharton** [comment]
Use another object that corresponds to the views that are created later.
```java
class Whatever {
  @Bind(R.id.whatever) TextView whatever;
}
// ...
Whatever whatever = new Whatever();
ButterKnife.bind(whatever, newView);
```
