### ISSUE TITLE
help. some problem there with how to Correct use butterknife?

### ISSUE THREAD

**Issue by 1024iCloud** [JakeWharton/butterknife#415]
### but if i work with jrebel ,it's ok.
![one](http://7xovi2.com1.z0.glb.clouddn.com/FFFAC6B7-4A4E-4AFC-945A-B92A0D6EFAE3.png)
![two](http://7xovi2.com1.z0.glb.clouddn.com/F50BDE0B-E9B9-4B04-ACF0-E62263C7578C.png)
![three](http://7xovi2.com1.z0.glb.clouddn.com/188BFB21-7CEF-43D3-B4DF-746A4C059CA8.png)
![four](http://7xovi2.com1.z0.glb.clouddn.com/944AD289-E292-4885-833B-C9AE297EADAF.png)
![five](http://7xovi2.com1.z0.glb.clouddn.com/C74031C8-BDB5-4F2A-8402-A3A448CC089D.png)

**Comment by JakeWharton** [comment]
What version? Is ProGuard removing the classes? Can you see the generated sources in your build folder?

**Comment by chinume** [comment]
``` compile 'com.jakewharton:butterknife:7.0.1'
```

There is no ProGuard, and i set that   ``` minifyEnabled false```
ah,this is the debug environment not release and there is no open confusion.so...?
![Uploading 屏幕快照 2015-12-04 10.11.00.png…](http://7xovi2.com1.z0.glb.clouddn.com/屏幕快照%202015-12-04%2010.11.00.png)

**Comment by chinume** [comment]
@JakeWharton 
may u help me how to do that?When I run, it's throw NullPointerException

butterknife:7.0.1
android studio 1.41
java 8

**Comment by JakeWharton** [comment]
They would be under `intermediates`, not `generated`.
