### ISSUE TITLE
Feature : bind click / item selected on OptionMenu

### ISSUE THREAD

**Issue by okynk** [JakeWharton/butterknife#416]
I'm using `Toolbar` with `OptionMenu`, the usual way to do a "click action" on `OptionMenu` for example is 
```java
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        Intent intent;

        switch (item.getItemId()) {
            case R.id.action_settings:
                intent = new Intent(this, SettingsActivity.class);
                startActivity(intent);
                break;
        }

        return true;
    }
```
AFAIK butterknife didn't have feature to bind click this thing, so I think it will be great if butterknife could do `@OnOptionsItemSelected(R.id.action_settings)`

**Comment by JakeWharton** [comment]
This was proposed in #41 and rejected since it's not view-related. Even more specifically, it only works when the source is an activity or a fragment, and even in that case there's no way to hook into the callback without requiring the user to call back into ButterKnife.
