### ISSUE TITLE
ButterKnife fails to inject custom view

### ISSUE THREAD

**Issue by mirono** [JakeWharton/butterknife#417]
Layout:
<?xml version="1.0" encoding="utf-8"?>
<ScrollView ... 
    <FrameLayout ...
        <ImageView ...
        <LinearLayout ...
            <LinearLayout ...
                <TextView ...
                <sa.ui.widget.SearchView
                    android:id="@+id/search_view"
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginBottom="15dip"
                    android:layout_marginLeft="20dip"
                    android:layout_marginRight="20dip"
                    android:layout_marginTop="15dip">
                </sa.ui.widget.SearchView>
            </LinearLayout>
            <ImageView ...
            <TextView ...
...

The custom view is the SearchView (sa.ui.widget.SearchView)

Fragment:

	@InjectView(R.id.search_view) SearchView mSearchView;

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		super.onCreateView(inflater, container, savedInstanceState);
		View mRootView = inflater.inflate(R.layout.create_layout, container, false);
		ButterKnife.inject(mRootView);
		mSearchView = (SearchView) mRootView.findViewById(R.id.search_view);
....

After the line ButterKnife.inject(mRootView) is executed, mSearchView is null, but all other injected members/views are ok.
Executing the followin line (findViewById) will get the SearchView correctly.

The Butter Knife debug output show:
12-06 13:27:29.695 7402-7402/staging.com.seekingalpha.webwrapper D/ButterKnife: Looking up view injector for android.widget.ScrollView
12-06 13:27:29.695 7402-7402/staging.com.seekingalpha.webwrapper D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by mirono** [comment]
Update: It seems that all views are not injected properly.

**Comment by JakeWharton** [comment]
You are binding the view to itself and not to the 'this' in your example.
mSearchView will always be null.
