### ISSUE TITLE
Duplicate files copied in APK META-INF

### ISSUE THREAD

**Issue by crysan** [JakeWharton/butterknife#418]
Hi!
My error:
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor
	File1: C:\Users\Администратор\.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife\7.0.1\d5d13ea991eab0252e3710e5df3d6a9d4b21d461\butterknife-7.0.1.jar
	File2: C:\Users\Администратор\.gradle\caches\modules-2\files-2.1\io.realm\realm-android\0.86.0\e49a43bcbbc3d5e5491dd2f4d3799a504b618e6b\realm-android-0.86.0.jar

How can I fix it?

**Comment by crysan** [comment]
Ok!
packagingOptions {
    exclude 'META-INF/services/javax.annotation.processing.Processor'  // butterknife
}

**Comment by wilsilva** [comment]
nice!

**Comment by Androidized** [comment]
Life saver! Thanks!

**Comment by derohimat** [comment]
nice, fixed

**Comment by vinod1988** [comment]
Thanks @crysan

**Comment by Bajranghudda1** [comment]
@crysan 
I am still getting same issue

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.squareup.okhttp/okhttp/pom.properties
  	File1: /home/madhu/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp/okhttp/2.6.0/212387a39088ecd3daff8e3bfc3bdc4123e33c67/okhttp-2.6.0.jar
  	File2: /home/madhu/.gradle/caches/modules-2/files-2.1/com.crashlytics.android/crashlytics/1.1.13/e821eafa1bf489a26bdb71f95078c26785b37a1/crashlytics-1.1.13.jar

**Comment by crysan** [comment]
Here I am powerless.
Sorry.

**Comment by niemj6012** [comment]
nice
