### ISSUE TITLE
Butterknife 7.0.1 and Dagger 2.0.2   android studio duplicate file exception

### ISSUE THREAD

**Issue by gvsharma** [JakeWharton/butterknife#419]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor
	File1: C:\Users\Sharma\.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife\7.0.1\d5d13ea991eab0252e3710e5df3d6a9d4b21d461\butterknife-7.0.1.jar
	File2: C:\Users\Sharma\.gradle\caches\modules-2\files-2.1\com.google.dagger\dagger-compiler\2.0.2\1170f75c1ce293f80755bbc9fcd60e0765022bd0\dagger-compiler-2.0.2.jar

**Comment by artem-zinnatullin** [comment]
Please add `android { packagingOptions { exclude
'META-INF/services/javax.annotation.processing.Processor' }}`.

// I'm on mobile so please check Android Gradle Plugin documentation for
more information!

On Tue, Dec 15, 2015, 10:34 GVSharma <notifications@github.com> wrote:

> Error:Execution failed for task
> ':app:transformResourcesWithMergeJavaResForDebug'.
>
> com.android.build.api.transform.TransformException:
> com.android.builder.packaging.DuplicateFileException: Duplicate files
> copied in APK META-INF/services/javax.annotation.processing.Processor
> File1:
> C:\Users\Sharma.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife\7.0.1\d5d13ea991eab0252e3710e5df3d6a9d4b21d461\butterknife-7.0.1.jar
> File2:
> C:\Users\Sharma.gradle\caches\modules-2\files-2.1\com.google.dagger\dagger-compiler\2.0.2\1170f75c1ce293f80755bbc9fcd60e0765022bd0\dagger-compiler-2.0.2.jar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JakeWharton/butterknife/issues/419>.
>
-- 

@artem_zin

**Comment by gvsharma** [comment]
Thank artem_zin
