### ISSUE TITLE
Unable to access Immutable

### ISSUE THREAD

**Issue by gaowen** [JakeWharton/butterknife#420]
When I build project ，In compileDebugJavaWithJavac process。
The following problems occur：
Unable to access Immutable
Can not find javax.annotation.concurrent.Immutable class file
When I add compile 'com.google.code.findbugs: jsr305: 3.0.1' to dependencies  is OK。
why？

**Comment by JakeWharton** [comment]
That annotation is used nowhere in this project and none of the generated code uses it. Unless you can create a sample that reproduces this behavior with ButterKnife, I think your culprit lies somewhere else.
