### ISSUE TITLE
Fail to Bind Everything across modules

### ISSUE THREAD

**Issue by winlandiano** [JakeWharton/butterknife#426]
I'm using Android Studio2.0 and when I try to use @Bind in a library module, error of "Attribute must be constant" comes out. However it works fine when I'm working on application module. I'm sure it has nothing to do with the dependency, since the application module relies on that library module.

**Comment by JakeWharton** [comment]
Values on the `R` class are not `final` in library modules which makes this library unusable on those modules. This is a limitation of Java, and something this library has decided not to work around. See #2.
