### ISSUE TITLE
Passing additional parameters to onClick handler using Butterknife

### ISSUE THREAD

**Issue by kishorpawar** [JakeWharton/butterknife#427]
**This is actually not an issue, but could be new feature to the library. **

I want to handle onClick event for specific view, and pass some parameters to handler.  

Right now I have created a function and passing `View` and my params to that function and implementing onClick handler in that function as follows.  

    private void doSomething(View view, String... params)
    {
        view.setOnClickListener(new OnClickListener()
        {
            @Override
            public void onClick(View v) 
            {
                //  params is available here
            }
        });
    }

Can we have ButterKnife to allow such functionality?

**Comment by JakeWharton** [comment]
Butter Knife's callbacks are methods on a class so if you want additional parameters those would need to be fields on that class.

In your example, you could do:
```java
static class DoSomething {
  private final String[] params;

  DoSomething(String... params) {
    this.params = params;
  }

  @OnClick void onClick() {
    // params is available here
  }
}

private void doSomething(View view, String... params) {
  DoSomething ds = new DoSomething(params);
  ButterKnife.bind(view, ds);
}
```

Otherwise, for normal classes (like activities, fragments, and views) just use normal fields on those classes for accessing other data. There's no way to affect the generated code in a way to carry extra data.

**Comment by kishorpawar** [comment]
Hey thanks Jake.
This is really helpful.

**Comment by runrmrf** [comment]
Hi Jake, 

How do you declare the Button for the onClick in the above example? 

This is what I have but I couldn't get it to work:


```
public class EventMatchedFragment {

@BindView(R2.id.chat_btn)
Button chatBtn;

  public static EventMatchedFragment newInstance(MatchedEvent matchedEvent) {
  
    Bundle arguments = new Bundle();
    arguments.putParcelable("matchedEventDetails" matchedEvent);

    EventMatchedFragment eventMatchedFragment = new EventMatchedFragment();
    eventMatchedFragment.setArguments(arguments);
    return eventMatchedFragment;
  }

  class ChatButtonClass {

    private MatchedEvent mMatchedEvent;

    ChatButtonClass(MatchedEvent matchedEvent) {
        this.mMatchedEvent = matchedEvent;
    }

    @OnClick void onClick() {
        Intent intent = MessagesActivity.newInstance(getActivity(), mMatchedEvent);
        intent.putExtra("matchedEventDetails", mMatchedEvent);
        startActivity(intent);
    }
  }

  private void goToChat(final View view, final MatchedEvent matchedEvent) {
      chatBtn.setOnClickListener(new View.OnClickListener() {
          @Override
          public void onClick(View v) {
              ChatButtonClass chatButtonClass = new ChatButtonClass(matchedEvent);
              ButterKnife.bind(chatButtonClass, view);
          }
      });
    }
 }
```

When I clicked the button, it does nothing. 

If i then add `android:onClick="goToChat"` to the xml file, the app crashes with the error: 

> java.lang.IllegalStateException: Could not find method goToChat(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'chat_btn'

It would be greatly appreciated if you can take a look and advice. Thanks.

-R
