### ISSUE TITLE
problem on gradle 2.0.0-alpha6 (2016/1/15)

### ISSUE THREAD

**Issue by DJafari** [JakeWharton/butterknife#429]
hi
in latest version of gradle ( 2.0.0-alpha6 (2016/1/15) ) all views are null

**Comment by JakeWharton** [comment]
Butter Knife is an annotation processor and has nothing to do with the build system. If the views are null, then the annotation processor is not being run which is a problem with the build tool, not this library. Consider reporting this to http://b.android.com/ with much more info and reproduction steps.

**Comment by DJafari** [comment]
you say right, but in the `2.0.0-alpha3` gradle version everything is ok, but after upgrading to `2.0.0-alpha5` all views is null

i think must be relation

sorry for my bad english

**Comment by JakeWharton** [comment]
That is further evidence the problem is in the build system, not this
library.

**Comment by DJafari** [comment]
ok thanks

**Comment by NitroG42** [comment]
Just in case other people (like me) fall on this issue, here's the bug reported on android tracker : 
https://code.google.com/p/android/issues/detail?id=200043

And the workaround is to add android.incrementalJavaCompile=false to gradle.properties
