### ISSUE TITLE
RC 1 of BK 8

### ISSUE THREAD

**Issue by stephanenicolas** [JakeWharton/butterknife#430]
![image](https://cloud.githubusercontent.com/assets/1832925/12470382/7f014072-bfa8-11e5-88eb-70ded2c5bc28.png)

Can we get a stable RC artifact at least, just to be sure not to break a build when using a snapshot...
Or a beta... please :)

Thx for all this hard work !

**Comment by JakeWharton** [comment]
You can use JitPack to depend on stable artifacts based on SHAs for now or just use the old version. Releasing a beta would just be setting a bad precedent right now.
