### ISSUE TITLE
question about a way to avoid double click

### ISSUE THREAD

**Issue by mBigFlower** [JakeWharton/butterknife#432]
Hello ,
  I find a way to avoid double click, it implement the OnClickListener. However, I want to use the Butterknife's @OnClick(id){}. How can I do for it ?(the way I find is below)
========================================================================
    public abstract class ViewThrottleClickListener implements View.OnClickListener {
        private static final int THROTTLE_TIME_DEFAULT = 1000; // 1s
        public long lastClickTime = 0;

        public long getThrottleTime() {
            return THROTTLE_TIME_DEFAULT;
        }

        public abstract void throttleClick(View view);

        @Override
        public void onClick(View v) {
            long currentTime = Calendar.getInstance().getTimeInMillis();
            if (currentTime - lastClickTime > getThrottleTime()) {
                lastClickTime = currentTime;
                throttleClick(v);
            }
        }
    }

**Comment by JakeWharton** [comment]
There is no way to do this without copying that code everywhere you use `@OnClick`. The generated code cannot be controlled to change what listener it uses. Someday we'll support custom listeners and you'll be able to specify the callback class, but it's a long way away.
