### ISSUE TITLE
not support android 2.0 beta 4

### ISSUE THREAD

**Issue by reizamv** [JakeWharton/butterknife#442]
iam using android studio 2.0 beta 4 and when choose generate  butterknife didnt show...any help please

**Comment by tinybright** [comment]
I think it's problem of butterknife zelezny plugin.

**Comment by timqi** [comment]
if you are speaking "ButterKnifeZelezny" plugin in android studio, maybe you should have a look at project [avast/android-butterknife-zelezny](https://github.com/avast/android-butterknife-zelezny)
