### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by guoyibin27** [JakeWharton/butterknife#445]
There are two <Button> with the same id such as android:id="@+id/button"
and i have two method with the same name in different activity
 
@OnClick public void buttonClick(){//todo something....} 

only one method will be triggered

 butterknife version 7.0.1

**Comment by JakeWharton** [comment]
This will be solved by #394. No way to solve this right now beyond giving them different IDs.

**Comment by guoyibin27** [comment]
sorry,my mistake.
i have two button with the same id in different layout.
