### ISSUE TITLE
Throwing NPE in android M AOSP

### ISSUE THREAD

**Issue by binay37** [JakeWharton/butterknife#449]
Hi, I have integrated an app in android M AOSP and have used butterknife library 7.0.1. I have enabled proguard and have used the rules that is mentioned in the butterknife site. But still views are not getting initialized and on calling any method it throws NPE. The following is the proguard rules:
`-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }
-keepnames class * {
    @butterknife.Bind *;
}

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}
`

I have two classes.
```
public class ErrorLayoutViewHolder extends ViewHolder {

    @Bind(R.id.error_content_container)
    View errorContentLayout;
    @Bind(R.id.error_message)
    TextView errorMessage;
    @Bind(R.id.retry_button)
    View retryButton;

    public ErrorLayoutViewHolder(final View itemView, View.OnClickListener retryListener) {
        super(itemView);
        retryButton.setOnClickListener(retryListener);
        errorContentLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                return;
            }
        });
    }
}
```

```
public class ViewHolder {
    final public View itemView;

    public ViewHolder(View itemView) {
        this.itemView = itemView;
        itemView.setTag(this);
        ButterKnife.bind(this, itemView);
    }
}
```

The line  **retryButton.setOnClickListener(retryListener);** throws NPE.

Can anyone suggest me what I am doing wrong? It is not working only in android M AOSP.

**Comment by JakeWharton** [comment]
Can you debug what happens at runtime? ButterKnife will let you step into the generated code when it's doing binding.

**Comment by binay37** [comment]
Recently I found that Jack compiler is used and that is why it is not working. But I still haven't found the solution.

**Comment by binay37** [comment]
I have created a small app to test butterknife. I have enabled jack by using "useJack true" in gradle because in AOSP M, jack compiler is the default. The following are the logs:

    03-07 13:18:51.264 10277-10277/? D/ButterKnife: Looking up view binder for bktest.binay.com.butterknifetest.MainActivity
    03-07 13:18:51.265 10277-10277/? D/ButterKnife: Not found. Trying superclass android.app.Activity
    03-07 13:18:51.265 10277-10277/? D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by kirsting** [comment]
I tried Android N with Java8 recently and met NPE problem if Jack is enabled.

**Comment by JakeWharton** [comment]
Jack doesn't support annotation processors yet. Once it does the library will start working. You can't use Jack if you want to use this library.
