### ISSUE TITLE
Library project issue

### ISSUE THREAD

**Issue by larten** [JakeWharton/butterknife#45]
Hi,

I have 4 project.
common

model
service
view

view only see service, service only see model, all of these see common.
I put butterknife lib to common, set the annotations processing. In the view project i can use annotations, but eclipse say for @InjectView value: "The value for annotation attribute InjectView.value must be a constant expression"

@InjectView(R.id.toastviewcontainer)
    ToastContainerView toastContainerView;

The .aptgenerated folder created and contains this:
"public class MainActivity$$ViewInjector {
  public static void inject(Finder finder, hbogo.view.activity.MainActivity target, Object source) {
    View view;
    view = finder.findById(source, 0);
    target.toastContainerView = (hbogo.view.toast.ToastContainerView) view;
  }

  public static void reset(hbogo.view.activity.MainActivity target) {
    target.toastContainerView = null;
  }
}"

How can I correctly use butterknife in library projects?

Sry my bad english ;)

**Comment by jonneymendoza** [comment]
has this been resolved yet?

**Comment by JakeWharton** [comment]
No. And it probably never will be.

**Comment by TimB0** [comment]
It can now be used in a library....view the readme
