### ISSUE TITLE
Butter Knife 8 how to use it

### ISSUE THREAD

**Issue by CROSP** [JakeWharton/butterknife#450]
Hi, I have tried to find any documentation about Butter Knife 8, but haven't found any. 
How can I use it ? There is no such object available ButterKnife to call bind method. 

Is it working in a different way ?

**Comment by Nolanus** [comment]
Is there a reason for not releasing a new version that contains the features of "8.0" (including the `@Unbinder` annotation mentioned on the website) for nearly half a year now? I favor not to use SNAPSHOT dependencies to have stable builds.

**Comment by JakeWharton** [comment]
It's not done.
