### ISSUE TITLE
Question: How to use "butterknife" in RecyclerView?

### ISSUE THREAD

**Issue by vinod1988** [JakeWharton/butterknife#451]
Hi JakeWharton,

Sir how can i use "butterknife" in RecyclerView. Please give some code snippet.

**Comment by JakeWharton** [comment]
There are plenty of examples if you Google "butterknife recyclerview". Here's one example: https://teamtreehouse.com/community/using-butterknife-in-the-hourviewholder (except replace `@InjectView` with `@Bind`).
