### ISSUE TITLE
Can't find ButterKnife.unbind(this); in v8.0.0 snapshot

### ISSUE THREAD

**Issue by jemshit** [JakeWharton/butterknife#454]
On version 8.0.0 snapshot, compiler can't find `ButterKnife.unbind(this);` in `Fragment` , is it intentional ?

**Comment by egor-n** [comment]
See [new docs](https://github.com/JakeWharton/butterknife/blob/0a14312ae517bc8359a1f5146c72365305776a57/website/index.html#L164).

**Comment by jemshit** [comment]
Yeah, it does not exist on 8.0.0. Is it safe to use without unbind ?

**Comment by egor-n** [comment]
`ButterKnife@unbind# was removed in favor of `ViewUnbinder` interface. I linked to an example on how to use it.

**Comment by jemshit** [comment]
Got it, thanks :+1:
