### ISSUE TITLE
Proposal: switch from findViewById() for each view to one-time view hierarchy lookup

### ISSUE THREAD

**Issue by artem-zinnatullin** [JakeWharton/butterknife#462]
This should improve performance of views search in `ButterKnife.bind()` call.

---

Example: you have `n` views to bind and `m` views in the view hierarchy.

**Current cost of views search in ButterKnife.bind():** `n * m` because we need to go through all views in the hierarchy for each view we're binding (`findViewById()`).

**Cost of views search in ButterKnife.bind() with this proposal:** `m` because the idea is to go through all views in the hierarchy once and find all required views during this one-time loop.

---

Possible implementations: 

1) Easier to implement but requires `Map`.

Allocate a `Map<Integer, ? extends View>`(`SparseArray`), find views during one-time search loop through view hierarchy and put them to the map.

Then we can somehow reuse current `Finder` abstraction and retrieve views from the `Map`.

2) Harder to implement, but no `Map` required.

During one-time search loop, store all views that we need to bind both directly (`@Bind`) and indirectly (`@OnClick`/etc) as fields of generated class (we can reuse `$$ViewBinder` classes for that) and then work with fields directly without `Map` lookup.

3) Harder to implement, but no `Map` or additional fields required!

During one-time search loop, perform actual bindings for all required views, we can simply implement `MyClass$$ViewBinder.bind()` as 

``` java
for (int i = 0, count = viewGroup.getChildCount(); i < count; i++) {
  int currentViewId = viewGroup.getChildAt(i).getId();

  switch (currentViewId) { 
   case 123: ; // all bindings for view with id 123.
   case 124: ; // all bindings for view with id 124.
   // and so on.
  }
}
```

All solutions above require special case when root view is not `ViewGroup`. 3) will require some workaround to prevent binding views with same ids. 1) and 2) will require pretty cheap checks to store reference only to first found view with required id.

4) ??

---

// Idea comes from today's DataBinding discussion with @johnkil, he pointed me that DataBinding does efficient view lookup and I immediately wanted to do that in ButterKnife because I'm not a fan of DataBinding :smile: 

If proposal sounds ok and we'll decide which implementation is better, I can work on it iydm.

**Comment by egor-n** [comment]
> Cost of views search in ButterKnife.bind() with this proposal: `n`

Wouldn't that be `m`, because you go through all views in hierarchy and it contains `m` views?

**Comment by artem-zinnatullin** [comment]
@egor-n right, fixed, thanks! 

Though worth to mention that it's worse cost because we can stop search when all views will be found. Same applied to current cost of search because `findViewById()` will stop search asap too.

**Comment by JakeWharton** [comment]
I did this before in another (unreleased) project and it certainly works.
I'm only worried about the code size and complexity costs associated.

Feel free to explore after 8.0 is released. I don't want to burden an
already-large major release with more things.

**Comment by artem-zinnatullin** [comment]
ok, will wait for 8.0 then.

**Comment by JakeWharton** [comment]
This seems like far too much effort and machinery for little effort. Especially with ConstraintLayout now. Use data binding's view mapper types if you need this for performance.
