### ISSUE TITLE
All bind view are null

### ISSUE THREAD

**Issue by moka-a** [JakeWharton/butterknife#463]
```java
public class AccountFragment extends BaseFragment {

	@Bind( R.id.editText_email ) EditText editText_email;
	@Bind( R.id.editText_password ) EditText editText_password;
	@Bind( R.id.textView_contract ) TextView textView_contract;

	private Realm realm;

	@Override
	public View onCreateView( LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState ) {

		View rootView = inflater.inflate( R.layout.fragment_sign_in, container, false );
		setRootView( rootView );
		ButterKnife.bind( this, rootView );

		init();
		refresh();
		return rootView;
	}
        ...
}

```
in 
ButterKnife 8.0.0 snap shot
ButterKnife 7.0.1

editText_email / editText_password / textView_contract are null ,

my project in android studio
compileSdkVersion 23 ( tried v22 )
multiDexEnabled true
Application extended MultiDexApplication
turn off proguard 

and use rxAndroid, realm, kotlin 

plz Help 

error log :
```
D/ButterKnife: Looking up view binder for com.moka.earlybird.application.mvc.controller.account.AccountFragment
D/ButterKnife: Not found. Trying superclass com.moka.framework.controller.BaseFragment
D/ButterKnife: Not found. Trying superclass android.support.v4.app.Fragment
D/ButterKnife: MISS: Reached framework class. Abandoning search.
```

**Comment by JakeWharton** [comment]
Code generation isn't happened. Do you see the generated classes in your `build` folder? They should be named as `*$$ViewBinder.java`.

**Comment by moka-a** [comment]
I can't find generated classes which is named as *$$ViewBinder.java in my build folder

**Comment by JakeWharton** [comment]
That indicates you have misconfigured your build system. What version are
you using? How is it setup in your build.gradle?

**Comment by moka-a** [comment]
my project build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
ext.kotlin_version = '1.0.0'

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-rc1'
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
        classpath 'io.fabric.tools:gradle:1.21.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.0.0"
        classpath "io.realm:realm-gradle-plugin:0.88.2"
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "http://devrepo.kakao.com:8088/nexus/content/groups/public/" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```

and
app build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'io.fabric'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'realm-android'
apply plugin: 'com.neenbedankt.android-apt'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    mavenCentral()
}

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com.moka.earylbird"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 5
        versionName "0.0.5"
        multiDexEnabled true
    }
    productFlavors {
        dev {

            minSdkVersion 21
        }
        prod {

            minSdkVersion 14
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
//    lintOptions {
//        disable 'InvalidPackage'
//    }
//    packagingOptions {
//        exclude 'META-INF/services/javax.annotation.processing.Processor'
//    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
     compile 'com.jakewharton:butterknife:7.0.1'
}
```

**Comment by JakeWharton** [comment]
Is ProGuard removing them? You're sure they're not showing up in the build/ dir anywhere? Try running `find . -name '*$$ViewBinder.java'` in your project directory.

**Comment by moka-a** [comment]
there doesn't exist anywhere .. 

![2016-04-01 3 19 30](https://cloud.githubusercontent.com/assets/7301713/14199189/2b1b47fc-f81d-11e5-9af8-94a5b5c9a64b.png)

so, I try another project,  _*$$ViewBinder.java_ are exist.

**Comment by JakeWharton** [comment]
Are you trying to bind views in Kotlin code?

**Comment by moka-a** [comment]
No, I tried to bind views in java code. 

like this
```java
public class AccountFragment extends BaseFragment {

    @Bind( R.id.editText_email ) EditText editText_email;
    @Bind( R.id.editText_password ) EditText editText_password;
    @Bind( R.id.textView_contract ) TextView textView_contract;

    private Realm realm;

    @Override
    public View onCreateView( LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState ) {

        View rootView = inflater.inflate( R.layout.fragment_sign_in, container, false );
        setRootView( rootView );
        ButterKnife.bind( this, rootView );

        init();
        refresh();
        return rootView;
    }
        ...
}
```

**Comment by JakeWharton** [comment]
Not sure what to tell you then. If you can create a sample project which demonstrates the problem I'll have a look.

**Comment by moka-a** [comment]
First, thank you for your comment, but i can't find what is problem. so I change all java code to kotlin.
and i use koltin-extensions for view injection.

**Comment by JakeWharton** [comment]
Ok. Well if you think of anything I'd be curious to know what it was.

**Comment by oinegue** [comment]
Same issue here after a fresh installation of Android Studio 2.0. Solved after finding the link to [manual configuration](http://jakewharton.github.io/butterknife/ide-idea.html) to "Enable annotation processing".
Maybe should it be made clearer on the website?

Thanks for the great library.

**Comment by JakeWharton** [comment]
If you are using Gradle those instructions are not needed.

**Comment by croute** [comment]
I have same problem.

Realm version is 1.0.0 (plugin)
ButterKnife version is 8.0.0 
Trying to bind views in Java code. 
and other settings are similar.

**Comment by theGlenn** [comment]
Hey @JakeWharton I started having the exact same problem than @moka-a  a few minutes after I added Kotlin to my project. And I ended up turning my activities to kotlin too.

**Comment by theGlenn** [comment]
Alight I found the problem if you are using Kotlin+Java in your project but still want to use annotation processing in your Java classes replace `apt` with `kapt`.
Check this link: https://kotlinlang.org/docs/reference/using-gradle.html#annotation-processing

**Comment by moka-a** [comment]
I used kapt but didnt work
I will check your link
Thank you

**Comment by bean-liu** [comment]
You will need to add "apt 'com.jakewharton:butterknife-compiler:8.4.0'" to your app build.gradle

**Comment by thevoiceless** [comment]
Seconding @bean-liu, the [github page](https://github.com/JakeWharton/butterknife) says to use `annotationProcessor` but the [jakewharton.github.io page](https://jakewharton.github.io/butterknife/index.html) says to use `apt`. The former does not work for me, the latter does.

**Comment by LenaYan** [comment]
I met the same issue, after using apt instead of annotationProcessor it works fine.

**Comment by pinkApple** [comment]
@JakeWharton 
I met the same issue too , the realm causes this problem.
it's not kotlin's problem.
when I delete realm in my build.gradle, everything  work well.

butterknife can't work together with realm.

**Comment by lDuffy** [comment]
Getting the same issue using a mixed java/kotlin project with realm, dagger2 and butterknife. 
realm using kotlin doesn't generate schema when 'com.neenbedankt.android-apt' plugin is applied for some reason. I was getting the following error when trying to access realm objects "MyObject is not part of the schema for this realm". Removing the android-apt plugin, corrected this error but build was failing with dagger compelation errors.  
replacing  annotationProcessor 'com.google.dagger:dagger-compiler:2.6' with kapt 'com.google.dagger:dagger-compiler:2.6' fixed dagger compilation issue but now butterknife views are always null. I tried replacing annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0' with kapt 'com.jakewharton:butterknife-compiler:8.4.0' but was failing with the following error  error: cannot find symbol import butterknife.Unbinder;

**Comment by krokyze** [comment]
Didn't know why but at one moment the same problem appeared. Changing 
annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1' to kapt 'com.jakewharton:butterknife-compiler:8.5.1' solved the problem.

**Comment by ConorOD** [comment]
> apt 'com.jakewharton:butterknife-compiler:8.5.1'

Worked for me too. Using java.

**Comment by Fideas** [comment]
For mixed Java/Kotlin projects add the following lines to your module level `build.gradle`

```
apply plugin: 'kotlin-kapt'
...
dependencies {
    ....
    compile 'com.jakewharton:butterknife:8.5.1'
    kapt 'com.jakewharton:butterknife-compiler:8.5.1'
    ...
}
kapt {
    generateStubs = true
}
```

**Comment by Mathbl** [comment]
Am I the only one to notice that with kapt, it is often necessary to clean the project? Every now and then, after making changes to code (layout or activities, doesn't seem to matter), my app crashes with a null pointer because of a null view. A project cleaning always fixes it. Looks like it could be related to that: https://youtrack.jetbrains.com/issue/KT-10303 but it's supposed to be fixed.

**Comment by guuilp** [comment]
@Mathbl I face this issue. Did you find a workaround?

**Comment by Mathbl** [comment]
@guuilp Sadly no. I had to give up on the idea of gradually switch to Kotlin for now. There were some issues like this one that I was encountering and couldn't fix. Having to ship fast wasn't not compatible with build that fails randomly.

**Comment by guuilp** [comment]
@Mathbl that's sad to hear. Unfortunately, half of my project is already in Kotlin, so rollback is not an option. If you see any news about this issue, please refer it here. I'll do the same.

**Comment by guuilp** [comment]
@Mathbl see this comment: https://github.com/JakeWharton/butterknife/issues/966#issuecomment-310580310

I've been building the project for almost 5 hours and no clean project needed until now.

**Comment by 2hamed** [comment]
I have the same problem here with a mixed Java/Kotlin app. Strangely it's just one of my activities (MainActivity) that the ButterKnife classes are not generated for.
The rest of the app is ok.
Had to convert that one activity to kotlin to get it to work.

**Comment by itsmanoharkumar** [comment]
I simply removed the Kotlin from my project and it started working again.

**Comment by Kharlos** [comment]
ok so if I create a project java/kotlin butterknife doesn't work really?

**Comment by JakeWharton** [comment]
Works fine with kapt

**Comment by Kharlos** [comment]
I write 

implementation 'com.jakewharton:butterknife:9.0.0-rc1'
    kapt 'com.jakewharton:butterknife-compiler:9.0.0-rc1'

but it doesn't work, needs  other config?

**Comment by rohankandwal** [comment]
I am using java + Kotlin configuration since I am slowly migrating.

```
kapt {
  generateStubs = true
}

dependencies {
....
// View Injection
  implementation "com.jakewharton:butterknife:$rootProject.ext.butterKnifeVersion"
  kapt "com.jakewharton:butterknife-compiler:$rootProject.ext.butterKnifeVersion"
... }
```
Above code removed null issues after changing some adding Kotlin support to the JAVA project.
