### ISSUE TITLE
Cannot resolve symbol Unbinder

### ISSUE THREAD

**Issue by anjanibansal** [JakeWharton/butterknife#465]
I was just trying my hands on Butterknife. Got the 7.0.1 version using gradle.
In the docs, I found: 

> Fragments have a different view lifecycle than activities. When binding a fragment in onCreateView, set the views to null in onDestroyView. Butter Knife provides an ButterKnife.Unbinder interface which has an unbind method to do this automatically. Simply bind an unbinder with @Unbinder to the fragment.

When I tried doing that, I'm getting "cannot resolve symbol Unbinder". I did exactly how it's mentioned.
It is quite possible that I might be missing something. Searched everywhere but couldn't find anything. Could anyone please help me out with this?

**Comment by moka-a** [comment]
@Unbinder can be used in 8.0.0 SNAP_SHOT version, as I know

**Comment by JakeWharton** [comment]
Those docs weren't meant to be published. You can use `ButterKnife.unbind` for now.

**Comment by JakeWharton** [comment]
Fixed with 25656cb which reverted the site to the release version. Thanks for the heads up.

**Comment by anjanibansal** [comment]
Thanks for the info. :+1:
