### ISSUE TITLE
Attribute value must be constant

### ISSUE THREAD

**Issue by WenruiCui** [JakeWharton/butterknife#468]
When I use butterkinfe  in AS 2.1 preview 5 ,when i build my project,it tell me 

'Attribute value must be constant'

**Comment by JakeWharton** [comment]
You need to use an `R.id.` constant.

**Comment by WenruiCui** [comment]
I write like this
`@Bind(R.id.listview) private ListView mListView;`

and it tell me 
'Attribute value must be constant'

**Comment by JakeWharton** [comment]
ButterKnife can't be used in library projects.

**Comment by WenruiCui** [comment]
thank you

**Comment by amitav13** [comment]
Any workaround for this?

**Comment by carlosvictor** [comment]
See the following link:
https://github.com/JakeWharton/butterknife#library-projects

**Comment by yangxingbo** [comment]
When I use butterkinfe in AS 3.3  ,when i build my project,it tell me
'Attribute value must be constant'
