### ISSUE TITLE
Lint: unused declatations

### ISSUE THREAD

**Issue by frakc** [JakeWharton/butterknife#469]
Lint marks every single field injected with butterknife as unused
```java
@Bind(R.id.requestlist) ListView list; 
```
and every method with `@OnClick` annotation 
```java
@OnClick({ R.id.btn_deny, R.id.btn_confirm }) public void myClick(View v) {
    switch (v.getId()) {

      case R.id.btn_deny: {
  
      }
      break;
      case R.id.btn_confirm: {

      }
      break;
    }
  }
```
I did include androit-apt plugins as suggested here https://github.com/JakeWharton/butterknife/issues/356

**Comment by JakeWharton** [comment]
This is fixed in the forthcoming next version where the runtime and compiler are separate and the generated code will be visible to the static analysis.
