### ISSUE TITLE
onFocusChange after onDestroyView

### ISSUE THREAD

**Issue by chrjsorg** [JakeWharton/butterknife#470]
Hi,

I have the following code in a fragment:

```
    @Bind(R.id.login_edittext_email)
    EditText emailInput;

    @Bind(R.id.login_editText_password)
    EditText passwordInput;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_login, container, false);
        ButterKnife.bind(this, v);
        ...
    }
   
    @OnFocusChange({R.id.login_edittext_email, R.id.login_editText_password})
    void onFocusChange(View v, boolean hasFocus) {
    ...
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        ButterKnife.unbind(this);
    }
```
Unfortunately onFocusChange will be called again after onDestroyView resulting in a null pointer exception. 

`04-08 15:19:16.450 14517-14517/de.package.name.android D/LoginFragment: onDestroyView
04-08 15:19:16.451 14517-14517/de.package.name.android D/LoginFragment: onFocusChange
04-08 15:19:16.454 14517-14517/de.package.name.android D/AndroidRuntime: Shutting down VM
04-08 15:19:16.456 14517-14517/de.package.name.android E/AndroidRuntime: FATAL EXCEPTION: main`

I'm using v7.0.1. 
Do you have any idea how to fix this? (Except for the quick and dirty method, checking null for the view)

**Comment by JakeWharton** [comment]
This is already fixed in the forthcoming next version where the unbinding will clear listeners, not just `null` fields. Checking the field for `null` is a good workaround for the current version though.
