### ISSUE TITLE
AS2.0 @Bind() error 'Attribute value must be constant'

### ISSUE THREAD

**Issue by suweya** [JakeWharton/butterknife#471]
I'am update to AndroidStudio2.0 @Bind() error 'Attribute value must be constant'

**Comment by JakeWharton** [comment]
Sounds like an Android Studio bug then.

**Comment by fobid** [comment]
try check which R imported

**Comment by danding1207** [comment]
may not an Android Studio bug.in application Module is ok,but in library Module error 'Attribute value must be constant'

**Comment by kafji** [comment]
> ButterKnife can't be used in library projects.
- https://github.com/JakeWharton/butterknife/issues/468#issuecomment-206672480
