### ISSUE TITLE
setClickable(false) not work

### ISSUE THREAD

**Issue by leonard0629** [JakeWharton/butterknife#472]
i use @Bind to inject a click function on view, and enable/disable it by dynamic condition. but after view.setClickable(false) to disabled view, i found it still can be clicked.
how to avoid this and make setClickable work in right way?

**Comment by JakeWharton** [comment]
This isn't a problem related to Butter Knife which merely does `findViewById` and `setOnClickListener`. Please ask on StackOverflow or other related forums for general Android help.

**Comment by leonard0629** [comment]
but when i use setOnClickListener to bind a click function and view.setClickable works.
i change using setOnClickListener to using @Click annotation, view.setClickable not work.

**Comment by JakeWharton** [comment]
If you look at ButterKnife's generated code you'll see it just calls
setOnClickListener too.
