### ISSUE TITLE
@OnClick not working after orientation change (rotate)

### ISSUE THREAD

**Issue by black-snow** [JakeWharton/butterknife#474]
Hi there,

the `@OnClick` listeners ain't seem to be set up after orientation change.

```java
public class SomeFragment extends Fragment {
    ...

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.my_fragment, container, false);
        ButterKnife.bind(this, view);
        Log.d(TAG, "BIND");
        return view;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        ButterKnife.unbind(this);
        Log.d(TAG, "UNBIND");
    }

    @OnClick(R.id.button)
    public void onButtonClick() {
        Log.d(TAG, "clicked");
    }
}
```

I see bind and unbind get correctly called after activity recreation but the onclick just won't work. Seems like there's no solution to this yet. Found [this](http://stackoverflow.com/questions/32859764/onclick-doesnt-works-after-rotation-in-butterknife) on SO.

// edit
I added some more logging to my `onCreateView()`: I retrieve the current listener via reflection. Weirdly there seems to be a new listener set after orientation change:

    onclick: ...SomeFragment$$ViewBinder$1@422933b8
    onclick: ...SomeFragment$$ViewBinder$1@423c5c28

But somehow they do not fire.

// edit 2

This might not be a butterknife issue after all. Even when I get the view the classical way and set an onclick listener it doesn't fire after.

**Comment by JakeWharton** [comment]
Butter Knife doesn't participate in configuration changes in any way. After rotation `onCreateView` is called again, you call `ButterKnife.bind`, and it sets a click listener back to your method. Any failure to receive clicks is a disagreement between you and your view hierarchy or perhaps due to multiple fragments overlapping each other.
