### ISSUE TITLE
@OnItemSelected auto fired in Spinner

### ISSUE THREAD

**Issue by abhi007tyagi** [JakeWharton/butterknife#475]
In my spinner implementation, I am updating cursor adapter of spinner via cursor loader.
As soon as it gets loaded, OnItemSelected get fired with position equals to "0". Need to find way to stop it.

**Comment by JakeWharton** [comment]
This is not a behavior of Butter Knife, but of the normal item selection listener in Android.

**Comment by mustafababil** [comment]
It might be related to these topics:
http://stackoverflow.com/q/13397933
http://stackoverflow.com/q/2297601
http://stackoverflow.com/q/21747917
