### ISSUE TITLE
Travis's broken

### ISSUE THREAD

**Issue by stephanenicolas** [JakeWharton/butterknife#476]
https://travis-ci.org/JakeWharton/butterknife

(I got the same problem with a project and wanna get updated when it gets fixed.)

**Comment by stephanenicolas** [comment]
@jakewharton how did you know the licence was thé issue ?? I couldn't figure it out from the logs.

**Comment by JakeWharton** [comment]
If you expand the "Installing Android dependencies" part (which gets
auto-collapsed) you'll see it says "Not accepting license blahblahblah".
When you specify a license it only accepts those, when you specify no
license it accepts them all (or so I think).

**Comment by stephanenicolas** [comment]
Thx Jake. I am gonna check that out tomorrow.

By the way, why don't you ever use code coverage in any project of yours ?
I am not working for them but covetalls.io does a pretty good job..

Le mer. 13 avr. 2016 21:08, Jake Wharton <notifications@github.com> a
écrit :

**Comment by JakeWharton** [comment]
I run tests with code coverage to find missing branches in IntelliJ, but
otherwise don't care about the actual number as a metric.

**Comment by stephanenicolas** [comment]
Thx for sharing ;)

Le mer. 13 avr. 2016 21:14, Jake Wharton <notifications@github.com> a
écrit :
