### ISSUE TITLE
Include layout cannot bind views

### ISSUE THREAD

**Issue by franciscerio** [JakeWharton/butterknife#478]
I am using "include" layouts for my toolbar but i got NPE. 

I have a BaseToolbarActivity which is initializing Butterknife.bind(this) and other stuffs.
 - I bind my toolbar @Bind(R.id.toolbar) in BaseToobarActivity

In my SignupActivity extends BaseToolbarActivity, I need to set a toolbar title and other stuffs that is related to toolbar but here is the problem.

I always get NPE in toolbar. 

This is my signup_activity.xml
   
    <include
        android:id="@+id/toolbarContainer"
        layout="@layout/toolbar"></include>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/toolbarContainer"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:fillViewport="true"
        android:scrollbars="none">
    </ScrollView>

and this is my toolbar.xml

```
<android.support.v7.widget.Toolbar
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?android:attr/actionBarSize"
    android:background="@drawable/pager_bg"
    android:minHeight="?android:attr/actionBarSize"
    app:theme="@style/AppTheme"
    tools:ignore="MissingPrefix">
    
    <TextView
        android:id="@+id/tvToolbarTitle"
        fontPath="fonts/Roboto-Regular.ttf"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="left|center"
        android:text=""
        android:textAllCaps="true"
        android:textColor="@color/white"
        android:textSize="@dimen/text_font_size_toolbar_5"/>

</android.support.v7.widget.Toolbar>

```
I used this approach before but now i'm getting some errors. 

This is the Log: 
 D/ButterKnife: Looking up view binder for  com.do.de.ui.activity.SignupActivity
 D/ButterKnife: HIT: Loaded view binder class.

**Comment by JakeWharton** [comment]
Does it work for `findViewById`?

**Comment by andrey-shikhov** [comment]
The error is because in include tag id was redefined from toolbar to toolbarContainer so findViewById also will return null because no View with id="@id/toolbar" exists. So butterknife runs as designed.

**Comment by JakeWharton** [comment]
Good eyes 👀

**Comment by hemavathip** [comment]
even i have similar Include tag in my code like above . If i want  to declare toolbar using bindView in respective activity..which tool id should i need to specific

**Comment by roeiedri** [comment]
Hey, did you solve this error? im having trouble with the same thing
