### ISSUE TITLE
Please do not use apt

### ISSUE THREAD

**Issue by AlexAndriichenko** [JakeWharton/butterknife#479]
Apt increase compilation time of my project from 5 seconds to ~1 minute:(
And it deprecated in Java 7
http://docs.oracle.com/javase/7/docs/technotes/guides/apt/

It had try it when was using androidannotations https://github.com/excilys/androidannotations

**Comment by JakeWharton** [comment]
This project uses annotation processing built into the compiler (JSR 269), not the standalone apt tool.

Unless you can provide a project that demonstrates such a slowdown when ButterKnife is used, there's no action to take here.

**Comment by AlexAndriichenko** [comment]
it was com.neenbedankt.gradle.plugins:android-apt:1.4 plugin

this block was the problem for compilation:
configurations {
    apt
}

if it not need now, maybe all fine

I just see that you also use apt in 8.0.0 version https://github.com/JakeWharton/butterknife
