### ISSUE TITLE
Binding for Included layout and binding in inherited class not works

### ISSUE THREAD

**Issue by boyfox** [JakeWharton/butterknife#482]
1. Binding for Included layout : 
    I have MainActivity with following layout : 

    `<RelativeLayout>`
` <include layout="@layout/main_toolbar" />`
` <FrameLayout id="mainContainer">`
 `<include layout="@layout/transparent_progress_bar" />`
 `<include layout="@layout/common_offline_ui" />`
`</RelativeLayout>`

in transparent_progress_bar layout have a LinearLayout with id progress_bar_block and MainActivity inherited from BaseActivity: 

`public class MainActivity extends BaseActivity`

and BaseActivity :

```public class BaseActivity extends AppCompatActivity
    @Nullable
    @Bind(R.id.progress_bar_block)
    public View progressView; ```

But, when I try using progressView in fragments mainAct.progressView - this view always null

2. Binding in inherited class : 
    I use Butterknife with ViewHolder in my Adapter. ViewHolder class extends from BaseViewHolder:
   
 ```protected class ViewHolder extends RecyclerView.ViewHolder {
        @Bind(R.id.chatNewsTV)
        AppCompatTextView chatNewsTV;
        @Bind(R.id.chatDateTV)
        AppCompatTextView chatDateTV;
        @Bind(R.id.chatPhotoIV)
        CircleImageView chatPhotoIV;
        public ViewHolder(View v) {
            super(v);
            ButterKnife.bind(this, v);
        } 
    }```

and

```public abstract class BaseViewHolder extends RecyclerView.ViewHolder {
    @Nullable @Bind(R.id.titleTV)
    TextView titleTV;
    @Nullable @Bind(R.id.subTitleTV)
    TextView subTitleTV;
    @Nullable @Bind(R.id.leftIV)
    AppCompatImageView leftIV;
    @Nullable @Bind(R.id.rightIV)
    AppCompatImageView rightIV;
    @Nullable @Bind(R.id.sepLine)
    View sepLine;
    public BaseViewHolder(View itemView) {
        super(itemView);
        ButterKnife.bind(this, itemView);
    }
} 
```

when I using ViewHolder titleTV, ... always will be null. I using Android Studio 2.0 Release,
I added all configurations to proguard file:

```
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}
```

**Comment by demelvin** [comment]
I have this exact same issue.

**Comment by boyfox** [comment]
Thanks for suggestion @demelvin, I seen new version Butterknife and you recommendation.

**Comment by JakeWharton** [comment]
It looks like you might be calling `bind()` twice on a single instance? In that case some of your views will be overriden with `null`

**Comment by boyfox** [comment]
@JakeWharton you mean I can call to bind one time on activity onCreate if activity extends from BaseActivity? yes, you are right in this case, but when I use Butterknife in adapter to binding view holders with RecyclerView, I can use only BaseViewHolder and in this case I need call to bind in BaseViewHolder and in class who extends of BaseViewHolder, too. 
Have a any suggestion to this situation?

**Comment by JakeWharton** [comment]
Let the base class call bind and don't call it in the subclass. Both will
be bound with a single call.

**Comment by boyfox** [comment]
OK, thanks for helping and great useful library!

**Comment by Durgesh-1992** [comment]
@JakeWharton I have one activity and inside that activity I have one dialog so I need to two have separate view one for activity and one for dialog. So when I am binding view in oncreate method for activity its working but when I tried to do the same for dialog it ends up with crash "Caused by: java.lang.IllegalStateException: Required view 'mEtMac1' with ID 2131624703 for field 'mEtMac1' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.". Here mEtMac1 is TextView defined in dialog layout.

Have a any suggestion to this situation?
