### ISSUE TITLE
Null View

### ISSUE THREAD

**Issue by hanhmh1203** [JakeWharton/butterknife#492]
Hi friends,
I get problem.
In first time I call ButterKnife.bind(this); in onCreate activity, it ok.
after that, I finish activity and then I call it from other activity. and I get error null view child. I don't know why!.
Plz help me.

**Comment by ncapdevi** [comment]
I'm getting the same issue since switching over to 8.0.0.  Changed my @Bind to @BindView and now those Views are null

**Comment by supercairos** [comment]
Did you added the new apt dependency?

**Comment by ncapdevi** [comment]
I tried adding it, but I'm not sure if it's actually being included.  I get the same results whether it's there or not.

**Comment by dongweiq** [comment]
I have encountered this problem too.

**Comment by nomin0** [comment]
https://github.com/JakeWharton/butterknife#download 
read it
add apt...

**Comment by supercairos** [comment]
This will generate the Binding classes that will be called by reflexion by ButterKnife.bind(...)

**Comment by simpleton** [comment]
plz check below snippet in your `build.gradle`
```
dependencies {
  compile 'com.jakewharton:butterknife:8.0.0'
  apt 'com.jakewharton:butterknife-compiler:8.0.0'
}
```

**Comment by ravenet** [comment]
Hi,

Why we need apt here, any particular reasons?

**Comment by JakeWharton** [comment]
So that the generated code is created. The compiler is no longer embedded in the runtime.

**Comment by JakeWharton** [comment]
Look for `*$$ViewBinder.java` classes in the `build/` folder. If they're not there, code generation isn't happening. You can also call `ButterKnife.setLoggingEnabled(true)` to see whether it can find the generated classes or not.

**Comment by adi1133** [comment]
It would be nice if bind() caused an exception if the apt dependency is missing.

**Comment by supercairos** [comment]
Rtfm

**Comment by kubukoz** [comment]
Is there any option to use ButterKnife with Jack? AFAIK jack doesn't support apt, and I can't compile the project with the plugin :/

**Comment by JakeWharton** [comment]
No
