### ISSUE TITLE
Build fails with 8.0.0 "invalid format string: this.$1N = $1N" 

### ISSUE THREAD

**Issue by JulienDev** [JakeWharton/butterknife#506]
Hi @JakeWharton ,

Since I changed Buttkerknife version to 8.0.0, my project can't build anymore. It seems related to "createUnbinderConstructor". Unfortunately I can't provide the source code of my project...

Julien

> 0:43:55.996 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
> 10:43:55.997 [ERROR] [org.gradle.BuildExceptionReporter] 
> 10:43:55.997 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
> 10:43:55.997 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:compilePreprodNijiDebugJavaWithJavac'.
> 10:43:55.997 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.IllegalArgumentException: invalid format string: this.$1N = $1N
> 10:43:55.997 [ERROR] [org.gradle.BuildExceptionReporter] 
> 10:43:55.997 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
> 10:43:55.999 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compilePreprodNijiDebugJavaWithJavac'.
> 10:43:55.999 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
> 10:43:55.999 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
> 10:43:55.999 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
> 10:43:55.999 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
> 10:43:55.999 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
> 10:43:55.999 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
> 10:43:56.000 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
> 10:43:56.001 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
> 10:43:56.002 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
> 10:43:56.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: invalid format string: this.$1N = $1N
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.Main.compile(Main.java:553)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
> 10:43:56.004 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        ... 60 more
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: invalid format string: this.$1N = $1N
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:116)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at com.squareup.javapoet.CodeBlock$Builder.addStatement(CodeBlock.java:171)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at com.squareup.javapoet.MethodSpec$Builder.addStatement(MethodSpec.java:281)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at butterknife.compiler.BindingClass.createUnbinderConstructor(BindingClass.java:187)
> 10:43:56.005 [ERROR] [org.gradle.BuildExceptionReporter]        at butterknife.compiler.BindingClass.createUnbinderClass(BindingClass.java:171)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at butterknife.compiler.BindingClass.brewJava(BindingClass.java:146)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at butterknife.compiler.ButterKnifeProcessor.process(ButterKnifeProcessor.java:142)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.Main.compile(Main.java:523)
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter]        ... 80 more
> 10:43:56.006 [ERROR] [org.gradle.BuildExceptionReporter] 
> 10:43:56.006 [LIFECYCLE] [org.gradle.BuildResultLogger] 
> 10:43:56.007 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED

**Comment by JakeWharton** [comment]
Can you run `./gradlew dependencies` and see what version of JavaPoet is being used? Looks like you're getting an old version.

**Comment by JulienDev** [comment]
It seems to be using v1.6.1

https://pastebin.mozilla.org/8869294

**Comment by JulienDev** [comment]
If I add the following dependency it seems working: 

compile 'com.squareup:javapoet:1.7.0'

**Comment by JakeWharton** [comment]
You should be able to use 'apt' instead of 'compile' so your apk doesn't
bundle that dependency. I'm still surprised that's needed. I'll have to
look into it more later.

**Comment by JulienDev** [comment]
If it helps, I'm using:
- AS 2.1
- gradle-2.13-all.zip
- classpath 'com.android.tools.build:gradle:2.1.0'
- classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
- compileSdkVersion 23
- buildToolsVersion "23.0.3"
- minSdkVersion 15
- targetSdkVersion 23
- Java 7 compatibility
