### ISSUE TITLE
Handle uppercase package names.

### ISSUE THREAD

**Issue by DaRkRaGe** [JakeWharton/butterknife#507]
How to use BT 8 with multiple view holders in RecyclerAdapter? onCreateViewHolder method requires a generic object that extents Recycler.Viewholder. The error is: Error:Execution failed for task ':mobile:compileDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: couldn't make a guess for [my package].adapter.CouponsRecyclerAdapter.categoriesViewHolder

**Comment by JakeWharton** [comment]
Change your class name to CategoriesViewHolder

**Comment by DaRkRaGe** [comment]
Its not possible. Listen i have a parent viewholder that extends Recycler.Viewholder. I have 10 children viewholders that extends this parent. The method to select based on a template id what template the system should choose, can only get 1 class as a parameter and ofcourse output only one. After that you can cast the class you wan to the generic viewholder based again on the template id. This is how the RecyclerView works with multiple templates.

If you still dont understand what im talking about please let me know to paste actual code.

**Comment by JakeWharton** [comment]
It's not possible to rename your class?

**Comment by DaRkRaGe** [comment]
Wait the problem is the lower case letter?

**Comment by JakeWharton** [comment]
Yes. It can't guess which part is the package and which is the class name.

**Comment by DaRkRaGe** [comment]
LOL thank you man

**Comment by DaRkRaGe** [comment]
i will try it and let you know

**Comment by JakeWharton** [comment]
I think I can fix it for the next release regardless, though. We shouldn't need to enforce this.

**Comment by DaRkRaGe** [comment]
It's working. Thanks. I agree that you may need to fix it, because its not nice to enforce it

**Comment by KingdeJosh** [comment]
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: couldn't make a guess for com.example.akujobijoshua.StudentBuddy.todolis.MainActivity

i tried changing the name still doesnt work pls help

**Comment by joecizac** [comment]
> Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> 
> > java.lang.IllegalArgumentException: couldn't make a guess for com.example.akujobijoshua.StudentBuddy.todolis.MainActivity
> 
> i tried changing the name still doesnt work pls help

Try changing the package name to lower case.
So it must be com.example.akujobijoshua.**studentbuddy**.todolis.MainActivity

**Comment by KingdeJosh** [comment]
Yes it was

**Comment by nnarendra** [comment]
@KingdeJosh Can you please tell me which version of Android studio I need to use or any other tools versions
