### ISSUE TITLE
Built-in ProGuard rules (ver. 8.0.0) prevents all names from being obfuscated

### ISSUE THREAD

**Issue by pawel-marchewka** [JakeWharton/butterknife#509]
It looks like exactly the same problem as described in https://github.com/JakeWharton/butterknife/issues/104

Probably because you are using
`-keepnames class *`
instead of
`-keepclasseswithmembernames class *`

Bye.

**Comment by JakeWharton** [comment]
Send a PR?

**Comment by JakeWharton** [comment]
Just tried it, doesn't match correctly.

**Comment by shibenli** [comment]
ver. 8.0.0 ,has't it any Change Log ?

**Comment by shiraji** [comment]
Do you mind if I send a PR?
