### ISSUE TITLE
Lib cant Find adapter class

### ISSUE THREAD

**Issue by Xopoko** [JakeWharton/butterknife#511]
Error:(13, 98) error: package Adapters.FindTrackAdapter does not exist
![sdgfsdfgdgfs](https://cloud.githubusercontent.com/assets/6337061/14849827/e9f125a6-0c7d-11e6-83a7-7ef7b76d1dba.jpg)

**Comment by Xopoko** [comment]
I refactor name of package "Adapters" to "adapters" and project compilled! 0~0

**Comment by JakeWharton** [comment]
Yep. Dupe of #507. I'll fix soon.
