### ISSUE TITLE
Problem when mix com.android.tools.build:gradle-experimental:0.7.0-rc1

### ISSUE THREAD

**Issue by tuxkids** [JakeWharton/butterknife#517]
i have problem when using butterknife 8.0.1 in my ndk project

this is my configuration
<img width="542" alt="screen shot 2016-04-28 at 12 46 26 pm" src="https://cloud.githubusercontent.com/assets/1531684/14875663/71bdeb60-0d3f-11e6-88b7-4a7e49672ba8.png">
<img width="374" alt="screen shot 2016-04-28 at 12 47 15 pm" src="https://cloud.githubusercontent.com/assets/1531684/14875664/721222c0-0d3f-11e6-9276-9463a02d64b5.png">
<img width="332" alt="screen shot 2016-04-28 at 12 46 50 pm" src="https://cloud.githubusercontent.com/assets/1531684/14875665/72174070-0d3f-11e6-9387-781c8e7243ef.png">

and give me error like this 
<img width="548" alt="screen shot 2016-04-28 at 12 48 25 pm" src="https://cloud.githubusercontent.com/assets/1531684/14875675/88712e80-0d3f-11e6-94a2-d09c78f0ace5.png">

thanks in advance

**Comment by JakeWharton** [comment]
The android-apt plugin doesn't support the experimental plugin. Please file
an issue on that project for support.

**Comment by JakeWharton** [comment]
As a workaround you can specify the compiler as `provided` instead of `apt`

**Comment by auras** [comment]
Use this plugin for apt using gradle experimental https://bitbucket.org/pvoid/android-apt-experemental/overview
