### ISSUE TITLE
@BindView fields must not be private or static.

### ISSUE THREAD

**Issue by ut2014** [JakeWharton/butterknife#518]
@BindView fields must not be private or static.  i don't know,why??

**Comment by JakeWharton** [comment]
Because the generated code needs to be able to assign the values.

**Comment by ZakTaccardi** [comment]
I'm trying to bind a nullable (optional) view in kotlin (not using KotterKnife), and I'm getting this error.

What's the workaround?

Tried the below with no luck (same error)

`@field:[BindView(R.id.home_toolbar) Nullable] var toolbar: Toolbar? = null`

**Comment by VanDucit7** [comment]
Views are private then @BindView not allow.
@ut2014 you only delete private it will done

**Comment by apexkid** [comment]
@JakeWharton Can butterknife work with private variables that have setter? That seems to be a more robust way of doing things.

**Comment by JakeWharton** [comment]
No
