### ISSUE TITLE
8.0.1感觉有问题, 是我姿势不对吗?

### ISSUE THREAD

**Issue by ltd920678778** [JakeWharton/butterknife#523]
大神: 
我用8.0.1运行app后onClick()方法无法执行. 但是我使用7.0.1后是可以的.

在使用8.0.1我的代码如下

`
    public class MainActivity extends AppCompatActivity {

    @BindView(R.id.click_me)
    Button clickMeBN;
    @BindView(R.id.result)
    TextView resultTV;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);
    }

    @OnClick(R.id.click_me)
    public void onClick(){
        Log.d("HTTP", " http_response click");
        getMovie();
    }
}
`

**Comment by ataulm** [comment]
`onClick()` does not get called with Butterknife 8.0.1 or is there an error raised?

**Comment by JakeWharton** [comment]
Did you add the compiler to your build file?

**Comment by ltd920678778** [comment]
I'll check it over.
thank you！

发自我的 iPhone

在 2016年4月30日，04:45，Jake Wharton <notifications@github.com<mailto:notifications@github.com>> 写道：


Did you add the compiler to your build file?

―

**Comment by PoJo130111** [comment]
any solutions about this problem？

**Comment by ltd920678778** [comment]
it's work! thanks, 
我修改了Project和Module的build.gradle文件, 
是我的问题, 
不好意思, 各位.

**Comment by JakeWharton** [comment]
Great! Glad to hear it.

**Comment by ltd920678778** [comment]
Thanks for your help！

发自我的 iPhone

在 2016年4月30日，14:05，Jake Wharton <notifications@github.com<mailto:notifications@github.com>> 写道：


Great! Glad to hear it.

―
