### ISSUE TITLE
Version 8.01 doesn't work for my app. (Ver. 7 do)

### ISSUE THREAD

**Issue by rodzynek01** [JakeWharton/butterknife#524]
Hi,
I've a huge problem with applying new version to my app. I just simply replaced gradle libs from 7.0.1 to 8.0.1 and apps hasn't work. There aren't any error logs. I tested it on @OnClick annotation and it stopped working. As I said everyting were ok with 7.0.1. Should I do anything else except replacing a gradle lib?

**Comment by JakeWharton** [comment]
Did you add the compiler to your build file?

**Comment by rodzynek01** [comment]
Of course not. I added and it works. Thanks for help. Really, really great tool! :)

**Comment by JakeWharton** [comment]
Great! Glad it's working.
