### ISSUE TITLE
Using on android wear with BoxInsetLayout

### ISSUE THREAD

**Issue by sagits** [JakeWharton/butterknife#525]
Hi, im trying to use butterknife along with android wear. I use BoxInsetLayout as my parent layout but all my views are still null when i try to access them (i'm doing everything just like i would do in a normal activity).

 Im using the Butterknife.bind(Activity). Is there any issue related to wear? Thanks in advance.

**Comment by JakeWharton** [comment]
There should be no problems. Does `findViewById` work? Can you enable logging by calling `ButterKnife.setLoggingEnabled(true)` and paste what gets printed when you call `bind()`?

**Comment by sagits** [comment]
Hi Jake, thanks for answering. Im out of time now, but i have used a previous version of ButterKnife and it worked. It was not related to wear because it wasnt working on the mobile module too. 

I think the problem is that i was missing apt plugin/compiler. By the way, why this is needed now ?

**Comment by JakeWharton** [comment]
They used to be bundled into a single artifact which was convenient for consuming but challenging for development. By splitting them into two, the runtime can be a proper Android library and the compiler can be a proper Java project (and have its own dependencies).

This is a pretty standard pattern seen by other libraries which rely on code generation like Dagger.

But yep, that probably was it. Ensure you have both dependencies in the future. Thanks for reporting back.
