### ISSUE TITLE
why fragment is NullPointerException

### ISSUE THREAD

**Issue by poping888** [JakeWharton/butterknife#526]
![view is null](https://cloud.githubusercontent.com/assets/2569939/14933497/4c0bfb7a-0ec3-11e6-908a-69689adf84a9.png)
![nullpointerexception](https://cloud.githubusercontent.com/assets/2569939/14933499/5104e0ec-0ec3-11e6-983a-6e4184526694.png)
why? sos.....

**Comment by JakeWharton** [comment]
Do you have the compiler in your build file?

**Comment by poping888** [comment]
![build](https://cloud.githubusercontent.com/assets/2569939/14933524/ec0a649a-0ec3-11e6-9d0d-1d450df73c18.png)
this?

**Comment by JakeWharton** [comment]
No. You need to also include the compiler so that the generated code is actually generated. See the README or website for instructions

**Comment by poping888** [comment]
god,I see!!!!!!!!!!!
apt 'com.jakewharton:butterknife-compiler:8.0.1'
This is what to do? please

**Comment by JakeWharton** [comment]
Yes

**Comment by poping888** [comment]
thx..
