### ISSUE TITLE
Dealing with Capital Letter in Android Package

### ISSUE THREAD

**Issue by topeomot2** [JakeWharton/butterknife#528]
I am working on an App that already exist in the app Store with Package com.lorem.Example and I cannot change it. When I use Butterknife in the app, I get the following error when I try to build the project

C:\Users\Abayomi\AndroidStudioProjects\ExampleAndroidApp\app\build\generated\source\apt\debug\com\lorem\Example\HomeActivity$$ViewBinder.java
Error:(8, 22) error: cannot find symbol class Example
Error:(13, 58) error: package Example does not exist
Error:(37, 59) error: package Example does not exist
Error:(8, 22) error: cannot find symbol class Example
Error:(13, 58) error: package Example does not exist
Error:(37, 59) error: package Example does not exist

When I open HomeActivity$$ViewBinder.java, it shows the correct package name but it also imports com.lorem.Example

`
// Generated code from Butter Knife. Do not modify!
package com.lorem.Example;

import android.view.View;
import butterknife.Unbinder;
import butterknife.internal.Finder;
import butterknife.internal.ViewBinder;
import com.lorem.Example;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.Override;

public class HomeActivity$$ViewBinder<T extends Example.HomeActivity> implements ViewBinder<T> {
  @Override
  public Unbinder bind(final Finder finder, final T target, Object source) {
    InnerUnbinder unbinder = createUnbinder(target);
    View view;
    view = finder.findRequiredView(source, 2131689728, "field 'drawerLayout'");
    target.drawerLayout = finder.castView(view, 2131689728, "field 'drawerLayout'");
    view = finder.findRequiredView(source, 2131689730, "field 'view'");
    target.view = finder.castView(view, 2131689730, "field 'view'");
    view = finder.findRequiredView(source, 2131689841, "field 'registerBtn'");
    target.registerBtn = finder.castView(view, 2131689841, "field 'registerBtn'");
    view = finder.findRequiredView(source, 2131689840, "field 'loginBtn'");
    target.loginBtn = finder.castView(view, 2131689840, "field 'loginBtn'");
    view = finder.findRequiredView(source, 2131689681, "field 'progressBar'");
    target.progressBar = finder.castView(view, 2131689681, "field 'progressBar'");
    view = finder.findRequiredView(source, 2131689671, "field 'tb'");
    target.tb = finder.castView(view, 2131689671, "field 'tb'");
    return unbinder;
  }

  protected InnerUnbinder<T> createUnbinder(T target) {
    return new InnerUnbinder(target);
  }

  protected static class InnerUnbinder<T extends Example.HomeActivity> implements Unbinder {
    private T target;

    protected InnerUnbinder(T target) {
      this.target = target;
    }

    @Override
    public final void unbind() {
      if (target == null) throw new IllegalStateException("Bindings already cleared.");
      unbind(target);
      target = null;
    }

    protected void unbind(T target) {
      target.drawerLayout = null;
      target.view = null;
      target.registerBtn = null;
      target.loginBtn = null;
      target.progressBar = null;
      target.tb = null;
    }
  }
}
`

**Comment by JakeWharton** [comment]
This is already tracked by #507 and will be fixed soon.
