### ISSUE TITLE
Toolbar Binding is not working

### ISSUE THREAD

**Issue by androinove** [JakeWharton/butterknife#531]
public class MainActivity extends AppCompatActivity {

    @BindView(R.id.activityMainToolbar)
    Toolbar mToolbar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(MainActivity.this);
        setSupportActionBar(mToolbar);
    }

}

This always returns my mToolbar null!!!!!
What's wrong?

**Comment by JakeWharton** [comment]
What version? Did you include the compiler? Is the generated code present? What do the logs say when you enable them?

**Comment by androinove** [comment]
compile 'com.jakewharton:butterknife:8.0.1'

When I try to change the toolbar title, for example, using "mToolbar.setTitle("title");", it doesn't work.
Look:

"[...]Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setTitle(java.lang.CharSequence)' on a null object reference[...]"

When I use "mToolbar = (Toolbar) findViewById(R.id.activityMainToolbar);", and set a new title it works fine. :/

**Comment by JakeWharton** [comment]
You need to include `butterknife-compiler` in your `build.gradle` per the README otherwise the generated code will not be present.

**Comment by androinove** [comment]
Ok, then! I'll try it!

**Comment by androinove** [comment]
Hell yea! It works fine. I didn't read the new readme :(
Thanks!
