### ISSUE TITLE
8.0.1 does not work in library

### ISSUE THREAD

**Issue by opcc60** [JakeWharton/butterknife#532]
After putting dependency in a library's build.gradle, I can't import the ButterKnife object.(When I need to use 'ButterKnife.bind')
I used to use 7.0.1. It works well in library.

Is anything wrong with me? What should I do ?

Could you just put all to one jar?

THX.

**Comment by marcodebarbosa** [comment]
Seeing some code would be interesting. 
Are you sure you're inporting butterKnife library correctly to your activity/fragment?

**Comment by opcc60** [comment]
After I add dependency to my Project build.gradle and Module build.gradle like this, I find only one jar in my External Libraries(only butterknife-annotations-8.0.1) .There is no ButterKnife object in it.

apply plugin: 'com.android.library'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion '24.0.0 rc3'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 12
        versionName "1.2"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.jakewharton:butterknife:8.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.0.1'
}

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        // replace with the current version of the Android plugin
        classpath 'com.android.tools.build:gradle:2.1.0'
        // replace with the current version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by JakeWharton** [comment]
Why are you declaring both 7 and 8 of the butterknife dependency?

**Comment by opcc60** [comment]
Sorry, I just miss the //.

**Comment by opcc60** [comment]
I use Android Studio 2.1.0. And 8.0.1 works well in my app module. After sync gradle, I can find 2 jar about ButterKnife in my external libraries.
The problem was found just in library.

**Comment by JakeWharton** [comment]
ButterKnife won't work in a library because the R constants are not final
