### ISSUE TITLE
Resources are not being found throwing null pointer exception

### ISSUE THREAD

**Issue by marcodebarbosa** [JakeWharton/butterknife#533]
Hello guys,

I've been using ButterKnife 8.0.1, but since i made gradle libraries and gradle update, butterKnife stopped working in all the < 22 API's. This problem also happens using butterKnife 7.

I'm trying to run it in debug mode, so i am not using ProGuard.

If i use the variable as a field, it doesn't find the resource, but if i use as local variable, using this approach, it works:

`AutoCompleteTextView mEmail = ButterKnife.findById(this, R.id.edit_login_email);`

I got the log from the debug mode, and i got:

```
D/ButterKnife: Looking up view binder for com.shipnow.youship.activities.authenticator.LoginActivity
D/ButterKnife: Not found. Trying superclass com.shipnow.youship.activities.BaseActivity
D/ButterKnife: Not found. Trying superclass android.support.v7.app.AppCompatActivity
D/ButterKnife: MISS: Reached framework class. Abandoning search.
```

Does anyone has the same problem?

**Comment by JakeWharton** [comment]
The generated code is not in your APK. Is the compiler included in your build.gradle file?

**Comment by marcodebarbosa** [comment]
@JakeWharton I'm sorry, but what you mean by "compiler included in your buid.gradle file"? 

I have these four gradle dependencies, and they are out of date, and everything is working perfectly:

```
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.2.1'
    compile 'com.android.support:support-v4:23.1.1'
```

If i update them, for the next version (23.3.X) butterKnife stops working, as i described before.

**Comment by JakeWharton** [comment]
Where is your butterknife dependency then?

**Comment by marcodebarbosa** [comment]
I'm sorry, i haven't posted all because i thought it wouldn't be necessary.

```
    compile 'com.jakewharton:butterknife:8.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.0.1'
```

I just posted the ones which really created the problem.

**Comment by JakeWharton** [comment]
Do you see the generated classes in `build/generated/source/apt/`?

**Comment by marcodebarbosa** [comment]
Yes, all the generated classes are there.

**Comment by JakeWharton** [comment]
Well they're not ending up in the APK somehow. Are you using ProGuard?

**Comment by marcodebarbosa** [comment]
@JakeWharton as i said on the original post, my proguard is not being used.

**Comment by JakeWharton** [comment]
Then this is a packaging problem with your build system, not a problem with
Butter Knife so I don't know what to tell you.

**Comment by marcodebarbosa** [comment]
That's fine. I'll analyse my project and try to figure out what's wrong with it. Thank's @JakeWharton

**Comment by JIO6CTEPok** [comment]
Yep. I have the same problem with version 8.0.1. 
build/generated/source/apt/ generated.

**Comment by JakeWharton** [comment]
Closing since there's no action to take from the library side.
