### ISSUE TITLE
Included views don't get binded after updating from 7.0.1 to 8.0.1

### ISSUE THREAD

**Issue by jkwiecien** [JakeWharton/butterknife#536]
I have included view in my layout. It was working perfectly fine on 7.0.1

        `<include layout="@layout/view_white_progress" />`

This is just xml with progress view:

```
<?xml version="1.0" encoding="utf-8"?>
<com.victor.loading.rotate.RotateLoading xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/rotate_loading"
    android:layout_width="80dp"
    android:layout_height="80dp"
    android:layout_gravity="center"
    app:loading_width="5dp" />
```

But now after the bind my view is null as shown on the [screenshot](https://www.evernote.com/l/AWnJgB7jI4ZKq4wJPgJ1EooqS2a-o3FHLSU).

**Comment by serj-lotutovici** [comment]
Do you have the `butterknife-compiler` included in your build.gradle like here https://github.com/JakeWharton/butterknife#download?

**Comment by jkwiecien** [comment]
Yeah I think I skipped that part...
