### ISSUE TITLE
Can't bind View

### ISSUE THREAD

**Issue by maimuzo** [JakeWharton/butterknife#567]
I was using ButterKnife 7.0.1 yesterday.
following code is working.

but I update to ButterKnife 8.0.1,  and replace @Bind to @BindView, following code is NOT working.
mViewClickArea1 is null, because ButterKnife.bind() can not find view.
maybe, ButterKnife.bind() has bug.

in activity_top.xml:
        <View
            android:id="@+id/activity_top_group_area1"
            android:layout_width="@dimen/top_clickarea_width"
            android:layout_height="@dimen/top_clickarea_height"
            android:layout_alignParentRight="true"
            android:layout_alignParentTop="true"
            />

in activity:
public class TopActivity extends Activity {
    @BindView(R.id.activity_top_group_area1)
    protected View mViewClickArea1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_top);

        ButterKnife.bind(this);
        # do something... but mViewClickArea1 is null here.
    }
}

**Comment by avinz** [comment]
Hello,

Have you added the compiler to the project as described here: https://github.com/JakeWharton/butterknife#download ?

**Comment by maimuzo** [comment]
Hi avinz.
Thank you.

I fogat android-apt plugin and butterknife-compiler.
I setup these setting, and try again,,, this code is not working. =p

I'm checking ButterKnife's code by step-by-step debugging.
next code throws ClassNotFoundException
`Class<?> viewBindingClass = Class.forName(clsName + "$$ViewBinder");
`in ButterKnife.findViewBinderForClass()

and, I found these log:
D/ButterKnife: Looking up view binder for example.activity.TopActivity
D/ButterKnife: Not found. Trying superclass example.activity.BaseActivity
D/ButterKnife: Not found. Trying superclass android.app.Activity
D/ButterKnife: MISS: Reached framework class. Abandoning search.


```
public class TopActivity extends BaseActivity {
    @BindView(R.id.activity_top_group_area1)
    protected View mViewClickArea1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_top);

        ButterKnife.bind(this);
        # do something... but mViewClickArea1 is null here.
    }
}

public class BaseActivity extends Activity {
    # do something...
}
```

**Comment by maimuzo** [comment]
Sorry, I resolved this problem.

I setup android-apt plugin and butterknife-compiler, but this code is not working in this timing.
next, I tried something,,, this code works fine.
I don't understand this cause.
clean & rebuild? (but I tried sometimes...)

thank you for help.

**Comment by JakeWharton** [comment]
Sounds like Gradle didn't sync right away. It shouldn't happen again. Glad it's working now for you though

**Comment by eugenybaldovsky** [comment]
I have the same issue. Tried to use ButterKnife in activities and fragments. All views are null.

**Comment by JakeWharton** [comment]
Read the readme

**Comment by smer4ik** [comment]
I had the same issue, It doesnt want to work with android-apt. When I deleted this line, it works like a cahrm. Thank you.

**Comment by paringer** [comment]
I have same issue, resolved, by,
renaming "annotationProcessor" back to "apt" in app.gradle and adding line 
apply plugin: 'com.neenbedankt.android-apt'
in app.gradle 
and adding
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        mavenCentral()
    }
}
in myproject.gradle.
Another solution is upgrade gradle and remove line apply plugin: 'com.neenbedankt.android-apt'

**Comment by Ramstein** [comment]
Very easy to solve. Create a copy of the layout you are applying on the window and use this copied layout from now on, solved.
