### ISSUE TITLE
Does not support JDK8

### ISSUE THREAD

**Issue by yuzhongxingke** [JakeWharton/butterknife#571]
When the JDK 1.8, configure the build. GradleDefaultConfig 
defaultConfig {
jackOptions {
            enabled true
        }
}

 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

Compile error:

"Error: Could not find the property 'options' on the task' : app: compileDebugJavaWithJack '."

**Comment by gabrielittner** [comment]
The android gradle plugin currently doesn't support annotation processing when using jack https://code.google.com/p/android/issues/detail?id=204065

**Comment by IgorGanapolsky** [comment]
Is this still the case with final Android N apis today?  I thought Google would've fixed annotation processing support...

**Comment by JakeWharton** [comment]
They have. Consult the Jack documentation for how to use annotation
processors.

**Comment by JakeWharton** [comment]
Also it doesn't have anything to do with N since it's a build system
feature.

**Comment by IgorGanapolsky** [comment]
@JakeWharton Thanks.  But here is specifically says: 
> Android N Preview SDK, which includes the required Jack toolchain 
https://developer.android.com/preview/j8-jack.html

So it has something to do with N.

**Comment by JakeWharton** [comment]
That is for using Java 8 language features which isn't related to
annotation processing. The version of Jack in the preview was the only one
which supported those.
