### ISSUE TITLE
AppCompatActivity butterknife:8.0.1

### ISSUE THREAD

**Issue by calber** [JakeWharton/butterknife#572]
it seems butterknife doesn't handle properly AppCompatActivity (support lib),
the Finder class doesn't match AppCompatActivity as valid target hence no binding are set (crashing the app)...
This issue does not exist with butterknife:7

**edit**: I dig it more and it seems it's not AppCompatActivity which make the binder fails
I've got an exception java.lang.ClassNotFoundException: org.calber.xxx.Main$$ViewBinder
(which inherit from AppCompatActivity) the superclass search fail (but is correct as it is framework class)

the problem seems: my app is multi apk, the package name is set in gradle with applicationId, while the manifest has a different (more generic) name, the package name used for the search is the manifest one (org.calber.xxx) ...
(The issue can be closed for me, with a more appropriate naming the issue disappear. I leave this to you in case you see possible improvements)

**Comment by JakeWharton** [comment]
Even if you use multi-apk the package name for your classes doesn't change. I don't understand what the actual problem was.

**Comment by calber** [comment]
sorry to have mentioned "multi apk" it was misleading, point is: Manifest declare package name xxx, build.gradle declare applicationId yyy. Finder try to match yyy.AppCompatActivity and fail. No Exception is thrown, the bind remain null.
It may be considered a wrong configuration, at least in my case it was not intentional, but it's possible and you can build app (and publish on the market) configured that way.
In theory the Finder should be able to manage the situation, not sure if it's worth the change...

**Comment by maelfosso** [comment]
I think I have the same problem
All the variable which I apply BindView on, are null

**Comment by fusion44** [comment]
Same problem here. This is my ViewHolder:
``` java 
public class SectionViewHolder extends RecyclerView.ViewHolder {
        public final View view;
        @BindView(R.id.forumSectionHeaderTextView)
        public TextView sectionTextView;
        public Forum item;

        public SectionViewHolder(View view) {
            super(view);
            this.view = view;
            ButterKnife.bind(this, view);
        }

        @Override
        public String toString() {
            return super.toString() + "HeaderViewHolder " + item.forumTitle;
        }
    }
```

findViewBinderForClass(Class<?> cls) in ButterKnife.java won't find a ViewBinder for this class and fails silently so the view will be null. Looking through the most recent source code in the repository it looks like there has been some code added to throw exceptions in this case. 

I'm not sure what Class.forName(clsName + "$$ViewBinder") is supposed to find so currently I'm out of info :) If you need more please let me know.

Thanks!

**Comment by JakeWharton** [comment]
I suspect this is that you are missing the compiler artifact in your build. See the README for how to properly set up BK 8.

If you are convinced this is not the case, I need a sample project that demonstrates the problem.
