### ISSUE TITLE
nullpointerexception

### ISSUE THREAD

**Issue by zuoguodang** [JakeWharton/butterknife#575]
i have use butterknife 8.0.1 in my project,but the variable of view is null.7.0.1 is ok

**Comment by fusion44** [comment]
Please take a look at #572 This looks like a duplicate.

**Comment by JakeWharton** [comment]
See the README for how to add the compiler to your build.

**Comment by zuoguodang** [comment]
@fusion44 @JakeWharton Thanks!This problem have been solved.
