### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by MrThiago** [JakeWharton/butterknife#577]
Using compile 'com.jakewharton:butterknife:8.0.1'

I keep getting this error:

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

my code:

@BindView(R.id.app_version) TextView app_version;

...onCreate(....
setContentView(R.layout.activity_landing);
ButterKnife.bind(this);

**Comment by serj-lotutovici** [comment]
You need to include the `butterknife-compiler` as a dependency. See https://github.com/JakeWharton/butterknife#download
