### ISSUE TITLE
Java Compiler Lint: Avoid warnings?

### ISSUE THREAD

**Issue by rfgamaral** [JakeWharton/butterknife#579]
> :app:compileFlavorDebugJavaWithJavac
> Note: C:\Workspace\Project\app\build\generated\source\apt\flavor\debug\com\company\appname\ui\debug\DebugActivity$$ViewBinder.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.

Anyway to disable these Lint checks **just** for generated files (inside the `build` folder only) or at least for ButterKnife?

**Comment by JakeWharton** [comment]
We can generate suppressions. What's the offending code look like?

**Comment by rfgamaral** [comment]
This is the generated class:

```
import android.view.View;
import butterknife.Unbinder;
import butterknife.internal.Finder;
import butterknife.internal.ViewBinder;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.Override;

public class DebugActivity$$ViewBinder<T extends DebugActivity> implements ViewBinder<T> {
  @Override
  public Unbinder bind(final Finder finder, final T target, Object source) {
    InnerUnbinder unbinder = createUnbinder(target);
    View view;
    view = finder.findRequiredView(source, 2131624041, "field 'mDrawerLayout'");
    target.mDrawerLayout = finder.castView(view, 2131624041, "field 'mDrawerLayout'");
    return unbinder;
  }

  protected InnerUnbinder<T> createUnbinder(T target) {
    return new InnerUnbinder(target);
  }

  protected static class InnerUnbinder<T extends DebugActivity> implements Unbinder {
    private T target;

    protected InnerUnbinder(T target) {
      this.target = target;
    }

    @Override
    public final void unbind() {
      if (target == null) throw new IllegalStateException("Bindings already cleared.");
      unbind(target);
      target = null;
    }

    protected void unbind(T target) {
      target.mDrawerLayout = null;
    }
  }
}
```

And these are the full lint errors:
> \app\build\generated\source\apt\variant\debug\com\package\ui\debug\DebugActivity$$ViewBinder.java:23: warning: [unchecked] unchecked call to InnerUnbinder(T) as a member of the raw type InnerUnbinder
>     return new InnerUnbinder(target);
>            ^
>   where T is a type-variable:
>     T extends DebugActivity declared in class InnerUnbinder
> \app\build\generated\source\apt\variant\debug\com\package\ui\debug\DebugActivity$$ViewBinder.java:23: warning: [unchecked] unchecked conversion
>     return new InnerUnbinder(target);
>            ^
>   required: InnerUnbinder<T>
>   found:    InnerUnbinder
>   where T is a type-variable:
>     T extends DebugActivity declared in class DebugActivity$$ViewBinder
> 2 warnings

And my class is something like this:

```
public class DebugActivity extends WrapperActivity {
    @BindView(R.id.layout_drawer)
    protected DrawerLayout mDrawerLayout;
}
```

**Comment by jaredsburrows** [comment]
@rfgamaral It looks like you are making "warnings" as "errors"?

I am simply temporarily disabling mine until this is fixed.
```
tasks.withType(JavaCompile) {
    configure(options) {
        // TODO
        compilerArgs << "-Xlint:-unchecked"
        compilerArgs << "-Xlint:-rawtypes"
    }
}
```

**Comment by ChristianBecker** [comment]
#582 addresses this warnings, too

**Comment by jaredsburrows** [comment]
@ChristianBecker Yeah, I just saw that :)
