### ISSUE TITLE
Unable to Build in release mode with proguard enabled

### ISSUE THREAD

**Issue by lkishor** [JakeWharton/butterknife#581]
Got this warning with build failed message.

with Butterknife v 8.0.1

`Warning:butterknife.internal.Utils: can't find referenced method 'android.content.res.ColorStateList getColorStateList(int,android.content.res.Resources$Theme)' in library class android.content.res.Resources
Warning:butterknife.internal.Utils: can't find referenced method 'int getColor(int,android.content.res.Resources$Theme)' in library class android.content.res.Resources`

this is mostly due to:
`compileSdkVersion 22
targetSdkVersion 22`

Upgrading these to 23 is not an option for me for now.

this if condition:
(Build.VERSION.SDK_INT < Build.VERSION_CODES.M) fails maybe.

Please suggest a workaround if any.

**Comment by JakeWharton** [comment]
You can safely ignore these warnings. Those methods will only be called when available at runtime.
