### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by vfaSonnt** [JakeWharton/butterknife#583]
When I try to build a release version with proguard, it fail to build with the error from ViewBinder generated code.
Have anyone seen this problem before? 

![screen shot 2016-05-19 at 2 35 57 pm](https://cloud.githubusercontent.com/assets/12553442/15386092/00739a80-1dd0-11e6-846b-0dc669ccd237.png)

**Comment by lkishor** [comment]
there is a chance that your package
`ListViewHolder` is causing the problem, trying keeping it small case

**Comment by vfaSonnt** [comment]
I don't think so. Because the error occur on every classes used with butterknife. I just screenshot those lines for example. But this error only occur with version 8.x, I changed to 7.x and it 've worked.

**Comment by JakeWharton** [comment]
Use lowercase package names or switch to the 8.1.0-SNAPSHOT for now. This will be fixed in the next release. Dupe of #507.
