### ISSUE TITLE
build in lib module  will cause NullPointerException

### ISSUE THREAD

**Issue by ZhoujunAndroid** [JakeWharton/butterknife#584]
when I  build in lib module like this 
![562d4596-f8a1-4648-a307-42889cf2b143](https://cloud.githubusercontent.com/assets/5690180/15427434/b3891d14-1ec7-11e6-89e5-b5e9df5a3226.png)
 
then cause NullPointerException

Then I change to build in app module ,That‘s OK

**Comment by JakeWharton** [comment]
Library modules are not supported.
