### ISSUE TITLE
What is the corrent way to unbind views in onDestroyView()

### ISSUE THREAD

**Issue by meNESS** [JakeWharton/butterknife#585]
Hi,

Previously I was using `unbind()` method but now in v8 of ButterKnife, there's no such method and just the binding method returns an `Unbinder` which will help with that. But the question, what is the correct way to do that? Is it recommended in fragments?

**Comment by lkishor** [comment]
Create a field in your fragment as
`Unbinder unbinder;`
in onCreateView you call

`unbinder = Butterknife.bind(this, root);`

and in onDestroyView you need to call

`unbinder.unbind();`

thats it you're done.

**Comment by meNESS** [comment]
@lkishor Thanks man. Is it recommended to unbind?

**Comment by lkishor** [comment]
Yes it is, It will set your bindings to null, freeing up memory...take a look at 
**BINDING RESET** at
http://jakewharton.github.io/butterknife/

**Comment by meNESS** [comment]
@lkishor Thanks so much man.

**Comment by alejandro-pnz** [comment]
What about an inheritance? For example, I have an BaseFragment with some binded views. Also, I have an ExtendedBaseFragment, which also has his own binded views. It is correct to unbind only in parent class (BaseFragment) or not?

**Comment by aimanbaharum** [comment]
Sorry to ask this, but why the change from the simple `Butterknife.unbind()`?

Warm regards,
_A user who just upgraded from previous version_

**Comment by JakeWharton** [comment]
So listeners can be cleared

**Comment by semaphore3000** [comment]
Is it really necessary that Butterknife throws an exception when the target object is null while unbinding (throw new IllegalStateException("Bindings already cleared."))? Could it not just do nothing? With the exception thrown I have to catch it always preventively and cannot do anything about it anyway.

**Comment by GokhanArik** [comment]
I agree with @semaphore3000 . Is there a better way to handle this @JakeWharton
