### ISSUE TITLE
Problem with nullpointer exception with butterknife 8.0.1

### ISSUE THREAD

**Issue by darius1706** [JakeWharton/butterknife#588]
Hello,
I have decided to switch version from 7.0.1 to 8.0.1 in my app.
My dependencies in build.gradle are:

`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'de.greenrobot:eventbus:2.4.1'
}`

But after switch I got nullpointer exception (I have changed Bind to BindView):

`@BindView(R.id.offers) ListView offers;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        setContentView(R.layout.activity_offers);
        EventBus.getDefault().registerSticky(this);
        ButterKnife.bind(this);

        offers.requestFocus(); // Here I got NullPointerException

        offer_row_adapter = new Offer_Row_Adapter(offers.getContext(), offerModels);
        offers.setAdapter(offer_row_adapter);
    }
`

With version 7.0.1 without problems.

Thank you
Radek

**Comment by JakeWharton** [comment]
Please see the readme for correct build configuration.
