### ISSUE TITLE
Feature request: Bind Resources like plurals?

### ISSUE THREAD

**Issue by cpeppas** [JakeWharton/butterknife#589]
Is there any support at the moment for things like binding plurals strings
i.e. @BindPlural ?

It would be nice to have.

**Comment by SimonVT** [comment]
How would quantities be passed to the bind method?

**Comment by italankin** [comment]
ButterKnife is a compile-time library. If at compile-time you know exact amount of items - you don't need plurals. In other case it doesn't make sense.

**Comment by cpeppas** [comment]
opsss that's correct guys
Closing as it doesn't make sense..
