### ISSUE TITLE
Is it some kinda misspelling in v8.1.0-SNAPSHOT?

### ISSUE THREAD

**Issue by brainail** [JakeWharton/butterknife#595]
Hi,

I was looking through the source code and IMO the code is incorrect a little bit:

```
public static Unbinder bind(@NonNull Object target, @NonNull Activity source) {
    return getViewBinder(target).bind(Finder.VIEW, target, source);
}
```

I think that the correct **Finder** is **ACTIVITY** here, isn't it?
Because later you will try to cast a **source** to the **Finder's type** (in this case you will try to cast a passed **Activity** to the **View** class and it's impossible of course).

**Comment by JakeWharton** [comment]
Looks like copy/paste. Want to submit a PR?

**Comment by brainail** [comment]
Yeah, sure. I will send it soon.

**Comment by JakeWharton** [comment]
Thanks!
