### ISSUE TITLE
Butterknife doesn't work with Java 8

### ISSUE THREAD

**Issue by juergenzimmermann** [JakeWharton/butterknife#602]
When I change app/build.gradle to use Java 8 the compilation of the project doesn't work anymore. I attach a testcase as a zip file whose content can be placed in a new project in the app subdirectory. I also attach a screenshot to illustrate the compilation error.
![screenshot](https://cloud.githubusercontent.com/assets/734334/15709367/a1b79d5e-2804-11e6-859d-035ff19b2480.png)
[testcase-butterfly.zip](https://github.com/JakeWharton/butterknife/files/293363/testcase-butterfly.zip)

**Comment by serj-lotutovici** [comment]
Butterknife doesn't have anything to do with this... it's the new jack compiler, apt 1.8 doesn't work with it. You need to add the `butterknife-compiler` in you dependencies with `annotationProcessor` instead of `apt`. See http://tools.android.com/tech-docs/jackandjill#TOC-Repackaging-support

**Comment by JakeWharton** [comment]
What he said!

**Comment by guness** [comment]
Here is an example usage:

https://github.com/nickwph/annotation-processor-with-java8-jack-and-jill-android#sample-dependencies
