### ISSUE TITLE
@Nullable not seen with version 8.0.1

### ISSUE THREAD

**Issue by theyann** [JakeWharton/butterknife#604]
Hey guys,

Just had a weird regression issue today. I've updated to 8.0.1 a few days ago and this just came up.

So my code that has not changed --> 
```
// declaration
 @Nullable
 @BindView(R.id.tvErasePhoneNumber)
 TextView tvErasePhoneNumber;

...

  // binding in onViewCreated (yes this is a fragment)
  ButterKnife.bind(this, view); // storing the unbinder in a local variable, omitting that code for clarity

```
The error (just the last interesting bit, I can put the full error stack if you want) -->
> 06-02 13:41:54.470 20354-20354/com.portima.mybroker.beta.debug E/RegistrationPhoneNumberFragment: Caused by: java.lang.IllegalStateException: Required view 'tvErasePhoneNumber' with ID 2131820921 for method 'erasePhoneNumberClicked' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
06-02 13:41:54.470 20354-20354/com.portima.mybroker.beta.debug E/RegistrationPhoneNumberFragment:     at butterknife.internal.Finder.findRequiredView(Finder.java:51)
06-02 13:41:54.470 20354-20354/com.portima.mybroker.beta.debug E/RegistrationPhoneNumberFragment:     at com.portima.mybroker.ui.fragments.registration.RegistrationPhoneNumberFragment$$ViewBinder.bind(RegistrationPhoneNumberFragment$$ViewBinder.java:20)
06-02 13:41:54.470 20354-20354/com.portima.mybroker.beta.debug E/RegistrationPhoneNumberFragment:     at com.portima.mybroker.ui.fragments.registration.RegistrationPhoneNumberFragment$$ViewBinder.bind(RegistrationPhoneNumberFragment$$ViewBinder.java:13)
06-02 13:41:54.470 20354-20354/com.portima.mybroker.beta.debug E/RegistrationPhoneNumberFragment:     at butterknife.ButterKnife.bind(ButterKnife.java:187)

So my problem: @Nullable is there, Butterknife doesn't seem to agree with me on that regard, we've been fighting a lot lately, it must be because it's spring or something.
No matter, could you guys check this out? Or maybe tell me what I did wrong? I checked the documentation, there was no obvious changes on that front.

Thanks a bunch in advance.

**Comment by serj-lotutovici** [comment]
It's not the field... you have a method `erasePhoneNumberClicked()` which is probably annotated with `@OnClick`. Annotate the method with `@Nullable` or `@Optional`, and you should be fine.

**Comment by theyann** [comment]
Thank you @serj-lotutovici, my head is not screwed up right.
Indeed it was the method, and it had a @Nullable instead of @Optional. Thanks a lot for this :)
