### ISSUE TITLE
the new version is always return null

### ISSUE THREAD

**Issue by androidmcriny** [JakeWharton/butterknife#610]
@BindView can not work well ,the view always is null
but the version 7.0.1 use @bind is good to work

**Comment by binhbt** [comment]
I got issue too. When i use 8.1.0 @BindView and @OnClick don't work. It always return null @@

**Comment by serj-lotutovici** [comment]
You need to include the `butterknife-compiler` in your dependencies. See https://github.com/JakeWharton/butterknife#download
