### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setHint(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by jega4u** [JakeWharton/butterknife#612]
I am getting same error on my fragment class. 

compile 'com.jakewharton:butterknife:8.0.1'
apt 'com.jakewharton:butterknife-compiler:8.0.1'

Looking up view binder for android.widget.RelativeLayout
MISS: Reached framework class. Abandoning search.
Shutting down VM

**Comment by JakeWharton** [comment]
Please provide a full example that demonstrates the problem.

**Comment by JanithaR** [comment]
Same issue here so I will provide my source.

```
public class AboutFragment extends BaseFragment {

    @BindView(R.id.appVersion)
    TextView appVersionTxt;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        final View view = inflater.inflate(R.layout.activity_about, container, false);

        ButterKnife.setDebug(true);
        ButterKnife.bind(this, view);

        appVersionTxt.setText(FacilitApplicationContext.getFacilitApplicationContext().getAppVersion());

        return view;
    }
}
```

The text view is there in the activity_about layout.
`<TextView
                android:id="@+id/appVersion"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:layout_below="@+id/appName"
                android:layout_marginTop="5dp"
                android:gravity="center_horizontal"
                android:textColor="@color/black"
                android:textSize="14sp" />`

But when the application is run.

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
>                                          at facilit.net.mobile.fragments.AboutFragment.onCreateView(AboutFragment.java:54)

From the logcat.

> 06-09 18:32:39.892 D/ButterKnife: Looking up view binder for facilit.net.mobile.fragments.AboutFragment
> 06-09 18:32:39.894 D/ButterKnife: Not found. Trying superclass facilit.net.mobile.fragments.BaseFragment
> 06-09 18:32:39.901 D/ButterKnife: Not found. Trying superclass android.support.v4.app.Fragment
> 06-09 18:32:39.901 D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by serj-lotutovici** [comment]
@JanithaR seams that the `butterknife-compiler` is not added to you build file.

Can you share your post your `build.gradle`?

**Comment by JanithaR** [comment]
Pasting both.

```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile 'com.google.android.gms:play-services-gcm:9.0.2'
    compile 'com.google.android.gms:play-services-analytics:9.0.2'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.pushwoosh:pushwoosh:3.4.3'
    compile 'com.jakewharton:butterknife:8.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.0.1'
}
```

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by serj-lotutovici** [comment]
@JanithaR  Checked on a project with the same setup.... and it works for me. 

Do you see the generated files? they should be located in `app/build/generated/source/<yourBuildVariant>/facilit/net/mobile/fragments/`.

**Comment by JanithaR** [comment]
@serj-lotutovici Nope, no such generated files.

**Comment by JakeWharton** [comment]
Are you using Jack?

**Comment by JakeWharton** [comment]
ProGuard?

**Comment by serj-lotutovici** [comment]
@JanithaR / @jega4u can one of you guys create a github project, that reproduces this issue... I will have some time this evening and can take a look...

**Comment by JanithaR** [comment]
@JakeWharton I don't even know what Jack is so nope not using it and ProGuard is not enabled for the debug version of the app.

@serj-lotutovici I just create a new project and checked the usage on both inside an Activity and a Fragment and it works fine. At this point I'm guessing this is something to do with my project configuration. In brief the project I'm working on,

- was ported from Eclipse few years back
- has a core module which is a library that is included in the app module. That library module includes the following.

`apply plugin: 'android-apt'`

```
dependencies {
    ...
    compile 'com.jakewharton:butterknife:8.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.0.1'
}
```

... So as I was writing this just for the sake of checking I moved both the above mentioned lines to the actual app module's build.gradle file and it works.

**Comment by JakeWharton** [comment]
Great! So we can close this?

**Comment by JanithaR** [comment]
Maybe, for two reasons... 
1) I guess if butterknife can't be used by including it in a library module you guys should verify that.
2) My issue is sorted but the OP's situation might be different.

**Comment by JakeWharton** [comment]
It can't be used in a library module.

**Comment by jega4u** [comment]
`package com.jega.kanthukadai.ui;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.text.TextUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;

import com.jega.android.commons.logger.Logger;
import com.jega.kanthukadai.R;

import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnClick;
import butterknife.Unbinder;

/**
 * Created by jega on 29/05/16.
 */
public class OTPRequestFragment extends BaseFragment {


    @BindView(R.id.otpEditTextMdn) EditText editTextPhoneNumber;

    private Unbinder unbinder;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        //return super.onCreateView(inflater, container, savedInstanceState);
        View view = inflater.inflate(R.layout.otprequestfragment, container,false);
        ButterKnife.setDebug(true);
        ButterKnife.bind(view);
        editTextPhoneNumber.setHint("Null Pointer");

        return view;
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);


    }

    @OnClick({R.id.otpButtonRequest})
    public void sendOTPRequest() {
        // Send OTP Request to server and register the SMS Listener
        if (Logger.IS_DEBUG_ENABLED) {
            Logger.debug(getClass(), "sendOTPRequest()");
        }
        String mdn = editTextPhoneNumber.getText().toString();
        if (TextUtils.isEmpty(mdn)) {
            editTextPhoneNumber.setError(getString(R.string.otp_please_enter_ur_mobile_no));
        } else {
            // start the OTP Verification fragment and intercept the PIN
        }
    }


    @Override
    public void onDestroyView() {
        if(unbinder!=null) {
            unbinder.unbind();
        }
        super.onDestroyView();
    }
}
`

Build.gradle 
`
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'android-apt'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}


android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.jega.kanthukadai"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile project(':logger')
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile('com.crashlytics.sdk.android:answers:1.3.6@aar') {
        transitive = true;
    }
    // Circular ImageView
    compile project(':database')
    compile project(':android-common')

    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'io.reactivex:rxandroid:1.2.0'
    compile 'io.reactivex:rxjava:1.1.5'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.android.support:support-v4:23.4.0'

    compile 'com.jakewharton:butterknife:8.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.0.1'

}
`
**BaseActivity** 

/**
 * Created by jega on 14/05/16.
 */
public abstract class BaseActivity extends AppCompatActivity {


    private BaseFragment currentFragment;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        if (Logger.IS_DEBUG_ENABLED) {
            Logger.debug(getClass(), "onCreate() ");
        }
        super.onCreate(savedInstanceState);
    }


//    @Override
//    protected void onStart() {
//        if (Logger.IS_DEBUG_ENABLED) {
//            Logger.debug(getClass(), "onStart() ");
//        }
//        super.onStart();
//    }

    @Override
    protected void onStop() {
        if (Logger.IS_DEBUG_ENABLED) {
            Logger.debug(getClass(), "onStop() ");
        }
        super.onStop();
    }


    @Override
    protected void onDestroy() {
        if (Logger.IS_DEBUG_ENABLED) {
            Logger.debug(getClass(), "onDestroy() ");
        }
        super.onDestroy();
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        if (Logger.IS_DEBUG_ENABLED) {
            Logger.debug(getClass(), "onConfigurationChanged() " + newConfig);
        }
        super.onConfigurationChanged(newConfig);
    }

    /**
     * @param fragments
     */
    public void show(Fragments fragments) {
        show(fragments, null);
    }

    /**
     * @param fragments
     * @param extra
     */
    public abstract void show(Fragments fragments, Bundle extra);

    /**
     * @param container
     * @param screen
     * @param extra
     */
    protected void attach(int container, BaseFragment screen, Bundle extra) {

        final String tag = screen.getCustomTag();
        Fragment old = getSupportFragmentManager().findFragmentByTag(tag);
        if (Logger.IS_DEBUG_ENABLED) {
            Logger.debug(getClass(), "old=" + old);
            Logger.debug(getClass(), "showFragment :: " + screen.getClass().getSimpleName());
        }
        if (!getSupportFragmentManager().popBackStackImmediate(tag, 0)) {
            FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
            ft.replace(container, screen, tag);
            if (screen.isAddToBackStackAllowed()) {
                ft.addToBackStack(tag);
            }
            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN);
            ft.commit();
            if (Logger.IS_DEBUG_ENABLED) {
                Logger.debug(getClass(), "popBack failed=" + tag);
            }
            currentFragment = screen;
        } else {
            if (Logger.IS_DEBUG_ENABLED) {
                Logger.debug(getClass(), "popBack success=" + tag);
            }
        }
    }

}
`
`

**Comment by jega4u** [comment]
No sure what happen , suddenly it is started working after upgrading the gradle to 2.1.2

**Comment by jega4u** [comment]
please close the ticket

**Comment by 1756211858** [comment]
你检查自己的setContentView(your Layout);

**Comment by sirmagid** [comment]
why dagger 2  @Inject cannot update TextView ?

	public String selectDay_STR(String v) {
		shamsiDate = (TextView) rootView.findViewById(R.id.shamsi_date);
		return v;
	}

i use 
@BindView(R.id.shamsi_date)
	TextView shamsi_inject;
its not work why?

**Comment by Caticatt** [comment]
Still doenst work

**Comment by sundharsk** [comment]
View rootView = inflater.inflate(R.layout.fragment_mlap, container, false);
  Spinner spinner =rootView. findViewById(R.id.spinner);
  ArrayAdapter<CharSequence> ad = ArrayAdapter.createFromResource(getActivity(), R.array.clock, android.R.layout.simple_spinner_item);
        ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner.setAdapter(ad);

I also had the Nullpointerexception saying that  :java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Spinner.setAdapter(android.widget.SpinnerAdapter)' on a null object reference
