### ISSUE TITLE
Code completion doesn't work of Studio after using ButterKnife Plugin.

### ISSUE THREAD

**Issue by HenryBrightChao** [JakeWharton/butterknife#614]
after clicking 'Genarate ButterKnife Injections', the ButterKnife Dialog pops up.But it would hide then..
causing the code completion doesn't work.
(Studio 2.1.2    ButterKnife7.0.1)
Thx first.

**Comment by JakeWharton** [comment]
This is a third-party plugin. Not from Butter Knife. Report to the plugin
directly.
