### ISSUE TITLE
8.1.0 compile error with dagger and eventbus

### ISSUE THREAD

**Issue by hamberluo** [JakeWharton/butterknife#617]
```
cannot find symbol class DaggerAppComponent
cannot find symbol class EventBusIndex
```

**Comment by JakeWharton** [comment]
There is not enough information to make this report actionable.

**Comment by hamberluo** [comment]
@JakeWharton add stacktrace.

**Comment by JakeWharton** [comment]
You probably use Dagger 2 which broke the use of JavaPoet in other annotation processors. Try upgrading to 2.4 otherwise declare JavaPoet 1.7.0 as an `apt` dependency *first*.

**Comment by hamberluo** [comment]
yes i update dagger2 to 2.5 and fix it.
very thanks.

**Comment by JakeWharton** [comment]
Great!

**Comment by GokhanArik** [comment]
For future references, I had a similar problem with **Dagger 2.2** and **ButterKnife 8.2.0** and upgrading Dagger to 2.5 solved the problem. Thanks @JakeWharton

The error message I got was this

`Note: Creating DefaultRealmModule error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider butterknife.compiler.ButterKnifeProcessor could not be instantiated: java.lang.NoSuchMethodError: com.squareup.javapoet.CodeBlock.of(Ljava/lang/String;[Ljava/lang/Object;)Lcom/squareup/javapoet/CodeBlock;`

**Comment by weixuefeng** [comment]
惊为天人

**Comment by luziming** [comment]
很牛逼的样子
