### ISSUE TITLE
How to use butterknife injection in a subclass view

### ISSUE THREAD

**Issue by yuzhongxingke** [JakeWharton/butterknife#618]
Hello, when injected into the view and found a problem:
BaseFragment (parent) :

`public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) { 
    activity = getActivity(); 
    view = inflater.inflate(getFragmentResId(),null); 
    ButterKnife.bind(context, view);
   return view; 
}`

And then realized in subclasses getFragmentResId () abstract methods, and the subclass injection control

`@BindView(R.id.fl_header_view)
FrameLayout mFlHeaderView;
@BindView(R.id.recycler_view)
RecyclerView mRecyclerView;
@BindView(R.id.springview)
SpringView mSpringview;
@BindView(R.id.fl_footer_view)
FrameLayout mFlFooterView;

@Override
protected int getFragmentResId() {
    return R.layout.layout_fragment_base_recyclerview;
}`
But such views are null, seems to be no injection of success, if so, please realize how to do?

**Comment by JakeWharton** [comment]
What version?

**Comment by andersonblough** [comment]
I'm seeing the same issue. Version 8.1.0

**Comment by jaredsburrows** [comment]
@yuzhongxingke 

1. Make sure to use `8.1.0`.

2. Instead of `inflater.inflate(getFragmentResId(),null)` please use `inflater.inflate(getFragmentResId(), container, false);`

3. In your `BaseFragment`, make sure you have `protected Unbinder mUnbinder` references to call `unbind` on later.

4. Call `this.mUnbinder = ButterKnife.bind(context, view);` in your actual subclasses of `BaseFragment`.

**Comment by GuyDavis90** [comment]
Is the issue the object you are trying to bind to?
What is the context you have as the first parameter of ButterKnife.bind?
If that is the BaseFragment you are trying to bind to then perhaps it should be 'this' and not 'context'?

**Comment by rchampa** [comment]
@GuyDavis90 try this.getActivity()

**Comment by GuyDavis90** [comment]
@rchampa From my understanding, it's not expecting a context for that first argument. It's expecting the object that you wish to bind. (The one with all the @BindView annotations) So in @yuzhongxingke example that would be 'this'.

**Comment by JakeWharton** [comment]
What @GuyDavis90 said. Use `this` for the first param.
