### ISSUE TITLE
Website does not match butterknife/website/index.html

### ISSUE THREAD

**Issue by RyanRamchandar** [JakeWharton/butterknife#622]
http://jakewharton.github.io/butterknife/ gives:
`Annotate fields with @Bind and a view ID...`

https://github.com/JakeWharton/butterknife/blob/master/website/index.html has:
`<p>Annotate fields with <code>@BindView</code> and a view ID for..`

Notice `@Bind` vs `@BindView`. Something is out of sync.

**Comment by JakeWharton** [comment]
Deployed the website. Thanks.
