### ISSUE TITLE
Feature Request: Native support on annotationProcessor Gradle Task

### ISSUE THREAD

**Issue by peterbetos** [JakeWharton/butterknife#624]
Hi Jake - If you can have this compatible with annotationProcessor as well aside from the apt plugin, it can reduce the dependency on additional 3rd party plugin for the annotation processing natively supported on Android N. 

Here's the setup to validate the support:
parent build.gradle should be using 
`classpath 'com.android.tools.build:gradle:2.2.0-alpha1'`

The following line is removed on the application build.gradle
`apply plugin: 'com.neenbedankt.android-apt'`

Thanks.

**Comment by JakeWharton** [comment]
This is already supported. Use `annotationProcessor` instead of `apt`.

**Comment by peterbetos** [comment]
Hi Jake - I tried using the tag but it crashes since the @BindView instances are null when using annotationProcessor

**Comment by JakeWharton** [comment]
Can you see the generated sources?

**Comment by peterbetos** [comment]
I switched to 
`classpath 'com.android.tools.build:gradle:2.2.0-alpha3'`
and it worked. Thanks.

**Comment by peterbetos** [comment]
peterbetos@gmail.com
sent you some files

‘You can refer to the link below for the sources’

Download:

https://www.wetransfer.com/downloads/e5f1e4111ab828750b49b6b4536265cd20160619073309/30974dbd6270b97c49dbde7c5ab1eff920160619073309/5e3d22

Files (233 KB total)
source.zip

Will be deleted on
26 June, 2016


Get more out of WeTransfer, get Plus
https://www.wetransfer.com/plus?trk=email-recipient_download


About WeTransfer: https://www.wetransfer.com/about
Contact: https://www.wetransfer.com/contact
Legal: https://www.wetransfer.com/legal

To make sure you can receive our emails, please add noreply@wetransfer.com to your [trusted contacts](http://we.tl/trustedcontacts)

**Comment by peterbetos** [comment]
The new 'com.android.tools.build:gradle:2.2.0-alpha6' works with Butterknife. We can already close this. Thanks.

**Comment by vanniktech** [comment]
@peterbetos then close the issue yourself?
