### ISSUE TITLE
Not found in butterknife:8.1.0

### ISSUE THREAD

**Issue by billytb** [JakeWharton/butterknife#643]
I integrated butterknife:8.1.0 to my library in project
I use like butterknife-sample-lib but android studio report not found @RClass(R2.class) and @BindView error "Attribute value must be constant"

This is gradle : 

```
apply plugin: 'com.android.library'
apply plugin: 'android-apt'

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'

    compile 'com.jakewharton:butterknife:8.1.0'
    apt 'com.jakewharton:butterknife-compiler:8.1.0'
}

**Comment by billytb** [comment]
i added classpath "${GROUP}:butterknife-gradle-plugin:${VERSION_NAME}" to gradle 
but have Error:Could not find com.jakewharton:butterknife-gradle-plugin:8.2.0-SNAPSHOT

**Comment by JakeWharton** [comment]
Support for this is on `master` is not yet released and so you cannot use any of this functionality yet. Wait for 8.2.0 to be released before you try all this, or you can use the 8.2.0-SNAPSHOT for now.
