### ISSUE TITLE
butterknife & RecyclerView & SwipeLayout: swipelayout item will have no animation

### ISSUE THREAD

**Issue by lawlietxxl** [JakeWharton/butterknife#652]
compile 'com.daimajia.swipelayout:library:1.2.0'
compile 'com.jakewharton:butterknife:8.1.0'
compile 'com.android.support:recyclerview-v7:23.0.0'

before I bind the recyclerview(which holds some swipelayout items) everything is fine. after I use butterknife to bind the view, the item's animation is disabled.

**Comment by JakeWharton** [comment]
There's not enough information to make this report actionable, and I can't see how Butter Knife would be the cause since it merely does `findViewById` and sets listeners. Without a full reproducible project that demonstrates Butter Knife is the cause I don't see any action to take here.
