### ISSUE TITLE
Cannot bind the click event

### ISSUE THREAD

**Issue by ziyeyouhu** [JakeWharton/butterknife#660]
Cannot bind the click event

**Comment by JakeWharton** [comment]
There is not enough information to make this bug report actionable.

**Comment by ziyeyouhu** [comment]
`public class MainActivity extends BaseActivity {


    @BindView(R.id.tv_name)
    TextView mTvName;
    @BindView(R.id.button)
    Button mButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

        CheckUpdate.getInstance().startCheck(MainActivity.this);
        
    }


    @OnClick(R.id.button)
    public void onClick() {
    //        It is not performing

    }
}`

**Comment by JakeWharton** [comment]
Doesn't tell me your build system configuration, or whether you can see
generated code, or whether you're using ProGuard, etc...

**Comment by ziyeyouhu** [comment]
`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.jakewharton:butterknife:8.1.0'
    compile 'com.android.support:recyclerview-v7:23.3.0'
    compile 'com.android.support:cardview-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-annotations:23.3.0'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.j256.ormlite:ormlite-android:4.48'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.github.bumptech.glide:glide:3.7.0'

}`

I didn't use  ProGuard

**Comment by JakeWharton** [comment]
See the readme. Your build isn't fully configured with the compiler.

**Comment by ziyeyouhu** [comment]
dependencies {
  compile 'com.jakewharton:butterknife:8.1.0'
  apt 'com.jakewharton:butterknife-compiler:8.1.0'
}

This is the right position?

**Comment by ziyeyouhu** [comment]
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
