### ISSUE TITLE
Can ButterKnife  used in this way?： find id after  ViewGroup.addView(new View())?

### ISSUE THREAD

**Issue by CodingForAndroid** [JakeWharton/butterknife#662]
`public class Main2Activity extends Activity {
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout view = (LinearLayout) View.inflate(this, R.layout.activity_main2, null);
        setContentView(view);
        view.addView(View.inflate(this, R.layout.activity, null));
        ButterKnife.bind(this,view);
        iconBackTop.setVisibility(View.VISIBLE);
    }
}`

R.layout.activity_main2:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:orientation="vertical"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin">

    <TextView
        android:id="@+id/tv_01_02"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!" />
    <TextView
        android:id="@+id/tv02"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!" />
    <TextView
        android:id="@+id/tv03"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!" />
</LinearLayout>`

R.layout.activity:
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:background="@color/bg"
    android:orientation="vertical" >

  
    <Button
        android:id="@+id/icon_back_top"
        android:layout_width="42dip"
        android:layout_height="42dip"

        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_marginBottom="10dip"
        android:layout_marginRight="14dip"
        android:layout_marginLeft="14dip"
        android:background="@drawable/icon_back_top"
        android:visibility="gone" />

    
</RelativeLayout>`

if  i want  find id for (Button  icon_back_top   ) from the child layout:  R.layout.activity ,in the MainActivity， can  butterknife do this ?

**Comment by JakeWharton** [comment]
Yes. ButterKnife just calls `findViewById` so as long as the views end up in the view tree ButterKnife doesn't care how they got there.

**Comment by CodingForAndroid** [comment]
got it  tks @JakeWharton
