### ISSUE TITLE
How can i make a jar with the Source Code?

### ISSUE THREAD

**Issue by GuoFeilong** [JakeWharton/butterknife#663]
I modify the class of "DebouncingOnClickListener"
I add  a method to resolve the fast click,
`  private synchronized static boolean isFastClick() {
        long time = System.currentTimeMillis();
        if (time - lastClickTime < 600) {
            return true;
        }
        lastClickTime = time;
        return false;
    }`

the i modify the onClick

`@Override
    public final void onClick(View v) {
        if (enabled) {
            enabled = false;
            v.post(ENABLE_AGAIN);
            if (isFastClick()) {
                return;
            }
            doClick(v);
        }
    }`

now it can work ,but i can not make a jar !
thanks!

**Comment by JakeWharton** [comment]
ButterKnife is an aar, not a jar. You can build by running `./gradlew assemble` and the aar will be in `butterknife/build/outputs/`.

**Comment by GuoFeilong** [comment]
Hi Jake I have run the aar command ，the i copy the release arr into a new project ，but it can not work

all butterknife-annotations can not work
such as @Bind(ID)  @OnClick @OnItemClick
in activity  only `Butterkinfe.bind(this)` is OK?

**Comment by JakeWharton** [comment]
The aar has a dependency on the butterknife-annotations jar which is where
all the annotations are kept. If you are including a local file you either
need to depend on butterknife-annotations or copy its jar as well.
