### ISSUE TITLE
Version 8.2.0 not working

### ISSUE THREAD

**Issue by optisamit** [JakeWharton/butterknife#668]
It seems that the library is generating classes with `_ViewBinder` suffix but looks for `$$ViewBinder` during binding process

**Comment by JakeWharton** [comment]
It definitely looks for `_ViewBinder`: https://github.com/JakeWharton/butterknife/blob/065fca9221e79effef6a32788907c3bc302287dc/butterknife/src/main/java/butterknife/ButterKnife.java#L207

Are you sure you are using the right versions of every artifact?

**Comment by optisamit** [comment]
Oh, stupid me... Sorry, I've forgotten that I need to change the version twice
