### ISSUE TITLE
8.2.0 Lint issue - SuspiciousImport

### ISSUE THREAD

**Issue by jaredsburrows** [JakeWharton/butterknife#669]
In `8.0.0` we also had a lint issue. Here is `8.2.0` lint issue:

```
    <>/Activity_ViewBinding.java:4: Error: Don't include android.R here; use a fully qualified name for each usage instead [SuspiciousImport]
    import android.R;
    ~~~~~~~~~~~~~~~~~

       Explanation for issues of type "SuspiciousImport":
       Importing android.R is usually not intentional; it sometimes happens when
       you use an IDE and ask it to automatically add imports at a time when your
       project's R class it not present.

       Once the import is there you might get a lot of "confusing" error messages
       because of course the fields available on android.R are not the ones you'd
       expect from just looking at your own R class.

    1 errors, 0 warnings
    Wrote HTML report to file:///<>/build/outputs/lint-results-debug.html
    Wrote XML report to file:///<>/build/outputs/lint-results-debug.xml
    :lintDebug FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':lintDebug'.
            > Lint found errors in the project; aborting build.

            Fix the issues identified by lint, or add the following to your build script to proceed with errors:
    ...
    android {
        lintOptions {
            abortOnError false
        }
    }
    ...

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

            BUILD FAILED
```

**Comment by JakeWharton** [comment]
This is already fixed by #665. I didn't realize it was a lint error though. That's really dumb. I guess I'll make a point release for it.

**Comment by jaredsburrows** [comment]
@JakeWharton Thanks for the quick response! I'll stick with `8.1.0` for now. Do you mind if I make a pull request for test app with lint turned on in order to capture these?

**Comment by JakeWharton** [comment]
The sample is decoupled from the code on master because it now depends on
the Gradle plugin, so it can't help catch problems anymore.

**Comment by jaredsburrows** [comment]
SuspiciousImport is actually a lint warning. I just force them as errors to ensure there is no issues on releases.

Here is the lint configuration I use:
```
    lintOptions {
        textReport true
        textOutput "stdout"
        checkAllWarnings true
        warningsAsErrors true
    }
```

Here is your test app: https://github.com/JakeWharton/butterknife/blob/master/sample/app/build.gradle#L22.

Just turn the warnings on full blast and break the build to ensure the warnings are all fixed. We can use this block in your `sample` app.

**Comment by JakeWharton** [comment]
Ah, got it. Then a release isn't as urgent.

Adding that to the sample app won't catch failures until after a release so
it won't help prevent this case in the future.

**Comment by jaredsburrows** [comment]
@JakeWharton Do you mind if make `appSource` version folder and move the `app` to `appBinary` and turn on `lint` to catch these before release?

**Comment by JakeWharton** [comment]
I don't want to make the sample any more confusing. I'd rather a new module
which also moved the tests from the app.

**Comment by jaredsburrows** [comment]
@JakeWharton So is this ok?

Modules:
```
|-- butterknife-annotations
|-- butterknife-compiler
|-- butterknife-gradle-plugin
|-- butterknife-lint
|-- butterknife
|-- sample
|-- butterknife-lint-test        <-- example with lint turned on
```

**Comment by JakeWharton** [comment]
The scope seems larger than just testing lint. How about
'butterknife-integration-test' instead?

**Comment by jaredsburrows** [comment]
@JakeWharton Please see https://github.com/JakeWharton/butterknife/pull/682.
