### ISSUE TITLE
View.callOnClick() does not call the bound onClick method

### ISSUE THREAD

**Issue by sorousharghavan** [JakeWharton/butterknife#674]
When a method is assigned as the onClick routine for a view using the OnClick(R.id.view) annotation, the method will not get called if callOnClick is performed on the view. The method has to be invoked manually instead.

**Comment by JakeWharton** [comment]
`@OnClick` works by just setting `View.setOnClickListener`, so that's not ButterKnife-specific behavior.

**Comment by dumbfingers** [comment]
@sorousharghavan Just FYI: I have a project which using Butterknife v6.0.0 and the `callOnClick` method will trigger butterknife's OnClick annotation.
