### ISSUE TITLE
Hi, jake! version 8.2.1, How to use library project? R2.class not found?

### ISSUE THREAD

**Issue by zhangluya** [JakeWharton/butterknife#675]
version 8.2.1, How to use library project? R2.class not found?

**Comment by zhangluya** [comment]
Error:Could not find com.jakewharton:butterknife-gradle-plugin:8.2.0.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/jakewharton/butterknife-gradle-plugin/8.2.0/butterknife-gradle-plugin-8.2.0.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/jakewharton/butterknife-gradle-plugin/8.2.0/butterknife-gradle-plugin-8.2.0.jar
Required by:
    bestpayClient:bestpayclient-cashier:unspecified

**Comment by JakeWharton** [comment]
Looks like you need to add `mavenCentral()` as a `repository` entry in your `buildscript`. There's an example in the README but under the normal usage. I'll copy/paste it to the library section.

**Comment by zhangluya** [comment]
Thank you very much for your answer. This is my library project configuration, Would you please help me to have a look at where there are problems. 

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.2.0'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'com.neenbedankt.android-apt'

dependencies {
    compile 'com.jakewharton:butterknife:8.2.0'
    apt 'com.jakewharton:butterknife-compiler:8.2.0'
}
