### ISSUE TITLE
Question about butterknife configuration

### ISSUE THREAD

**Issue by TYZRPVX** [JakeWharton/butterknife#677]
It is easy to import butterknife previous version, I can add `compile 'com.jakewharton:butterknife:7.1.1'` to dependencies and everything works well. But the latest version need more complex configuration in Gradle, and I failed to config butterknife due to some strange problems, such as sync time-out, etc. 

So, could you tell me why butterknife prefer to a more complex configuration ?

**Comment by JakeWharton** [comment]
The code generator was split from the runtime so that the runtime could contain lint checks and proguard rules and dependencies on things like the support library.
