### ISSUE TITLE
8.2.1 how to  judge  more than one  id  in a onclick  

### ISSUE THREAD

**Issue by Leifzhang** [JakeWharton/butterknife#681]
i don't know how to  solve  view.getId() is different from R2.id.item;
How to user switch in moudle

**Comment by JakeWharton** [comment]
For runtime code (which is what you're writing inside that method) you can use the normal `R.id.item`. The `R2` is only needed for inside the annotations.

**Comment by Leifzhang** [comment]
thank you . in moudle i may just use if else instead of switch
