### ISSUE TITLE
Resources are not getting bind with version 8.2.1

### ISSUE THREAD

**Issue by rushabh1191** [JakeWharton/butterknife#683]
Hi,
I am seeing that view injector files are not getting generated while using butterknife.

Here is my gradle file : 
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.0'
    compile 'com.google.firebase:firebase-core:9.2.1'
    compile 'com.google.firebase:firebase-storage:9.2.1'
    compile 'com.google.firebase:firebase-config:9.2.1'
    compile 'com.google.firebase:firebase-auth:9.2.1'
    compile 'com.google.firebase:firebase-database:9.2.1'
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
```

And this is project level build.gradle

```

buildscript {
    ext.kotlin_version = '1.0.3'
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

I have been using butterknife for a while,but getting this issue for the first time.

**Comment by janswist** [comment]
Same here

**Comment by xuguobiao** [comment]
I got NullPointerException too when using @BindView(R2.id.***) in my library module.

**Comment by guidi** [comment]
Same problem here.

**Comment by kageiit** [comment]
> ext.kotlin_version = '1.0.3'

If you use kotlin, we do not have the ability to generate code with R2 correctly see #670 so it may not work for you if you are using kotlin in a library project. It would be helpful if you could provide a sample project so we can make sure that is the case

**Comment by LiuJQ** [comment]
I got NullPointerException too when using @BindView(R.id.***) in my app module.

**Comment by VladimirVinageras** [comment]
LiuJQ: If you are using 8.2.1 just try using 7.0.1! It works 4 me! )

**Comment by LiuJQ** [comment]
@VladimirVinageras Thx, I have no choice =.=

**Comment by xuguobiao** [comment]
@LiuJQ try using 8.2.0, it works.

**Comment by jaredsburrows** [comment]
@JakeWharton We can close this since @rushabh1191 has not replied. The latest is now `8.4.0`.

**Comment by rushabh1191** [comment]
Two days back I updated the version, It started working. Thank you.
