### ISSUE TITLE
butterknife 8.2.1 with dagger 2 error

### ISSUE THREAD

**Issue by anasanasanas** [JakeWharton/butterknife#686]
after update to butterknife 8.2.1 start getting this error when build the project 

cannot find symbol class DaggerActivityComponent
and 
cannot find symbol class DaggerApplicationComponent

> Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider butterknife.compiler.ButterKnifeProcessor could not be instantiated: java.lang.NoSuchMethodError: com.squareup.javapoet.CodeBlock.of(Ljava/lang/String;[Ljava/lang/Object;)Lcom/squareup/javapoet/CodeBlock;

**Comment by JakeWharton** [comment]
Use Dagger 2.5. Old versions bundled JavaPoet incorrectly.

**Comment by anasanasanas** [comment]
thanks you.

**Comment by Sugarya** [comment]
it works, thanks

**Comment by peng0398** [comment]
It works , thanks.
