### ISSUE TITLE
The issues about ButterKnife with Glide.....

### ISSUE THREAD

**Issue by WhatWeCan** [JakeWharton/butterknife#687]
Ignore that I just know a little English.
When i use ButterKnife 8.2.1 ,I use Glide to load one image,and there is one error,
## java.lang.IllegalArgumentException: You must pass in a non null View
compile:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.jakewharton:butterknife:8.2.1'
}
error codes:
`@BindView(R.id.tv_hello)
    TextView tvHello;
    @BindView(R.id.iv_glide)
    ImageView ivGlide;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

        Glide.with(this)
                .load(R.mipmap.ic_launcher)
                .into(ivGlide);
    }`
When I use findViewById to get the ivGlide ,the application can run.
I surf the internet to find the solution,but i didn't find it.  Could you tell me what this about?

**Comment by JakeWharton** [comment]
Your build is not configured correctly. Please see the README for instructions on setting up the missing 'butterknife-compiler' artifact.

**Comment by WhatWeCan** [comment]
ok, Thank you
