### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by a491392040** [JakeWharton/butterknife#688]
throw NullPointException  when run art enviroment,Butterknife don't surpport Android 5.0 and later?

**Comment by JakeWharton** [comment]
There's not enough information to make this report actionable. Without information on your build setup and usage it's impossivle to tell what the problem is.

**Comment by a491392040** [comment]
My project set targetVersion 23,build-tools 23.0.3,My device is Nexus 5p,System is Android6.0,When i run app on the Android4.4,It is right,Run on Android 6.0,It throw exception,Log show don't find class *_ViewBinder.I think, If because of MulitDex ?

**Comment by JakeWharton** [comment]
What's your build configuration of the library look like?

**Comment by a491392040** [comment]
this root cfg:
![1](https://cloud.githubusercontent.com/assets/7316390/17352767/13026122-596c-11e6-8b52-c2e7ea3965d5.png)
this module build  cfg:
![2](https://cloud.githubusercontent.com/assets/7316390/17352774/282bed02-596c-11e6-8c25-7051f9e41e0d.png)
