### ISSUE TITLE
8.2.1 can not compile with jack

### ISSUE THREAD

**Issue by yunair** [JakeWharton/butterknife#693]
#### this is stacktrace when I build

>  Error:14:53:34.377 [ERROR] [org.gradle.BuildExceptionReporter] 
14:53:34.377 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:53:34.378 [ERROR] [org.gradle.BuildExceptionReporter] 
14:53:34.378 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:53:34.378 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:transformJackWithJackForDebug'.
14:53:34.390 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.AssertionError: java.lang.IllegalArgumentException
14:53:34.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.frontend.java.JackBatchCompiler.performCompilation(JackBatchCompiler.java:226)
14:53:34.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1712)
14:53:34.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.frontend.java.JackBatchCompiler.compile(JackBatchCompiler.java:188)
14:53:34.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.Jack.buildSession(Jack.java:977)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.Jack.run(Jack.java:496)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:102)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	... 85 more
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.source.util.Trees.instance(Trees.java:76)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at butterknife.compiler.ButterKnifeProcessor.init(ButterKnifeProcessor.java:123)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.BatchAnnotationProcessorManager.discoverNextProcessor(BatchAnnotationProcessorManager.java:157)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:116)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:909)
14:53:34.391 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
14:53:34.392 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.jack.frontend.java.JackBatchCompiler.performCompilation(JackBatchCompiler.java:223)
14:53:34.392 [ERROR] [org.gradle.BuildExceptionReporter] 	... 90 more
14:53:34.392 [ERROR] [org.gradle.BuildExceptionReporter] 

the `build.config` file content is 

> compile 'com.jakewharton:butterknife:8.2.1'
    annotationProcessor  'com.jakewharton:butterknife-compiler:8.2.1'

what wrong did I do?

**Comment by yunair** [comment]
same as #673

**Comment by yunair** [comment]
I think I find the problem,
compare  `ButterKnifeProcessor.java` source code `8.2.1` with `8.1.0`, the different of `init()` method is `8.2.1` version code has one extra line code 
~~~ java
 trees = Trees.instance(processingEnv);
~~~

but, in `init()` method, there is nothing params named processingEnv, It is should using params env instead?

#### before
~~~ java
@Override public synchronized void init(ProcessingEnvironment env) {
    super.init(env);

    elementUtils = env.getElementUtils();
    typeUtils = env.getTypeUtils();
    filer = env.getFiler();
    trees = Trees.instance(processingEnv);
  }
~~~


#### after
~~~ java
@Override public synchronized void init(ProcessingEnvironment env) {
    super.init(env);

    elementUtils = env.getElementUtils();
    typeUtils = env.getTypeUtils();
    filer = env.getFiler();
    trees = Trees.instance(env);
  }
~~~

**Comment by yunair** [comment]
at the version 8.2.1, the butterknife-compiler source code has using library in `com.sun.*`, but in android new build toolchain `jack & jill`, there is not exist this library, especially `javac`, so we can not use butterknife-8.2.1 with jack compiler. 

In future release, Is there a plan to not use `com.sun.*` library?

**Comment by yunair** [comment]
the code at `ButterKnifeProcessor.java`,  `init()` method, `Trees.instance()`.

**Comment by JakeWharton** [comment]
This is already tracked by #673

**Comment by kageiit** [comment]
> at the version 8.2.1, the butterknife-compiler source code has using library in com.sun.*, but in android new build toolchain jack & jill, there is not exist this library, especially javac

com.sun is not related to javac. it is part of the `tools.jar` that should still be usable in jack. Filed an issue with jack https://code.google.com/p/android/issues/detail?id=218017
