### ISSUE TITLE
How to Use ButterKnife.bind() in a non activity class

### ISSUE THREAD

**Issue by kaustav07** [JakeWharton/butterknife#694]
I am using a class that implements TextWatcher to validate my fields in Sign up page and i want to use butterknife to bind views. How can i do it. I have passed the instance of my Activity class to my TextWatcher implementation but after that also it doesn't bind the views..What can i do?

![butterknife](https://cloud.githubusercontent.com/assets/11479382/17270892/1a81b8be-568b-11e6-9655-c3aa35f5154d.PNG)

And the call from Activity

![butterknife2](https://cloud.githubusercontent.com/assets/11479382/17270908/6a65686c-568b-11e6-92c0-e38f560ea007.PNG)

**Comment by JakeWharton** [comment]
Use the two argument version which separates the instance being bound (`this`) from the source of the views (`activity`).

**Comment by kaustav07** [comment]
In my code how to do that?Can you guide please?

**Comment by egor-n** [comment]
Call `ButterKnife.bind(this, this.activity)` instead of `ButterKnife.bind(this.activity)` in the `SignUpValidation`. The first argument is the target for your bindings, the second argument is the source of the bindings.

**Comment by kaustav07** [comment]
It worked fine..Thank you very much..

**Comment by eddieberklee** [comment]
Sorry for resurfacing this old thread, but in the new version of ButterKnife, there is now the ability to bind resources, such as with @BindColor() - is this possible to do in a custom view as long as I have a context object. I know I can pass along my activity reference, but I'd just rather not add an unnecessary extra parameter.

**Comment by JakeWharton** [comment]
Yes. Reference the generated class directly and it has a constructor that
accepts only a Context.

**Comment by eddieberklee** [comment]
Hi @JakeWharton thanks for the quick reply. I'm not sure what you mean by the generated class. Which class should I be looking at because ButterKnife.bind doesn't have a signature that accepts only a Context:

![screenshot 2017-02-22 20 27 05](https://cloud.githubusercontent.com/assets/1836653/23244923/6ddb8b48-f93d-11e6-963e-68242aadf5ef.png)

**Comment by JakeWharton** [comment]
SideScroller_ViewBinder

**Comment by eddieberklee** [comment]
Oh shit. Thanks for making this library and helping me make my code a little cleaner.
