### ISSUE TITLE
lint.jar cannot be deleted when i clean the project

### ISSUE THREAD

**Issue by JeffZane** [JakeWharton/butterknife#695]
Error:Execution failed for task ':app:clean'.
> Unable to delete file: ...\app\build\intermediates\explodedaar\com.jakewharton\butterknife\8.2.1\jars\lint.jar

**Comment by JakeWharton** [comment]
This is similar to https://github.com/JakeWharton/timber/issues/100, and it's a bug in Android Studio and not this library. If you are not using the latest Studio and plugin version (2.1.0 or newer) then report a new bug on http://b.android.com/.
