### ISSUE TITLE
java.lang.NoSuchFieldError in library using 8.2.1

### ISSUE THREAD

**Issue by GISirFive** [JakeWharton/butterknife#696]
Excuse me @JakeWharton 
I'm trying to use ButterKnife 8.2.1 in my library module, but throwing Exception below when start:
`FATAL EXCEPTION: `
`java.lang.NoSuchFieldError: test.zbzbx.com.mylibrary.R$id.mButton`
`at test.zbzbx.com.mylibrary.TestActivity_ViewBinding.<init>(TestActivity_ViewBinding.java:22)`
`at test.zbzbx.com.mylibrary.TestActivity_ViewBinder.bind(TestActivity_ViewBinder.java:13)`
`at test.zbzbx.com.mylibrary.TestActivity_ViewBinder.bind(TestActivity_ViewBinder.java:10)`
`at butterknife.ButterKnife.bind(ButterKnife.java:125)`
`at test.zbzbx.com.mylibrary.TestActivity.onCreate(TestActivity.java:25)`

**following is my module config:**

**project-level  build.gradle**

    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }

**library-level  build.gradle**

`buildscript {`
`    dependencies {`
`         classpath 'com.jakewharton:butterknife-gradle-plugin:8.2.1'`
`    }`
`}`
`apply plugin: 'com.android.library'`
`apply plugin: 'com.neenbedankt.android-apt'`
`apply plugin: 'com.jakewharton.butterknife'`

`dependencies {`
`    compile 'com.jakewharton:butterknife:8.2.1'  `
`   apt 'com.jakewharton:butterknife-compiler:8.2.1'  `
`}  `

**TestActivity in library**

`public class TestActivity extends AppCompatActivity {

    @BindView(R2.id.mButton)
    Button mButton;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test);
        ButterKnife.bind(this);

    }

    @OnClick(R2.id.mButton)
    public void onClick() {
        Toast.makeText(TestActivity.this, "Test" + mButton.getText(), Toast.LENGTH_SHORT).show();
    }
}`

**Comment by JakeWharton** [comment]
Are you using ProGuard on the library?

**Comment by ffelini** [comment]
@JakeWharton  I have a different issue.... class Butterknife not found... it's not loaded as dependency, only the annotation interfaces are loaded for some reason

**Comment by GISirFive** [comment]
Not using ProGuard on the library, the **proguard-rules.pro** is empty, so does the main module.
I'm using Android Studio 2.1.2, and the project tree is below:
**MyApplication**
\>.gradle
\>.idea
\>**app**
\>build
\>gradle
\>**mylibrary**
.gitignore
build.gradle
gradle.properties
gradlew
gradlew.bat
local.properties
MyApplication.iml
settings.gradle

**note:** app directory is main module, mylibrary is library module

**Comment by waitinghc** [comment]
@JakeWharton I have a the same as issue, the onClick don`t working on the library 
![image](https://cloud.githubusercontent.com/assets/9429308/17474010/491f90b8-5d86-11e6-8535-5acfb4987fbd.png)

**Comment by JakeWharton** [comment]
Use R.id in the switch.

**Comment by waitinghc** [comment]
@JakeWharton thanks

**Comment by jaredsburrows** [comment]
@GISirFive Can you please update to the latest, `8.4.0` and try again?

**Comment by GISirFive** [comment]
@jaredsburrows Ok, I'll response you after try it.

**Comment by GISirFive** [comment]
@jaredsburrows @JakeWharton 
It's Ok my friends! This problem has disappeared in **8.4.0**, Thanks a lot!

**Comment by jaredsburrows** [comment]
@GISirFive Close this.

**Comment by urvish91** [comment]
Still not working in my code. i have done same like your sample. please help me.
