### ISSUE TITLE
Error on Module Library using multidex.

### ISSUE THREAD

**Issue by epool** [JakeWharton/butterknife#697]
I am getting the following error when I try to run my project, I am using butterknife in a library module and I have enabled multidex in the main app module.
```
Error:Execution failed for task ':appMDLive:transformClassesWithJarMergingForProductionDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: butterknife/BuildConfig.class
```

**Comment by JakeWharton** [comment]
This seems very clearly to be a build system problem. Does a clean build fix it?

**Comment by epool** [comment]
No, it doesn't.

**Comment by epool** [comment]
I found my mistake, previously we were using butterfork and I forgot to update the other modules that were using butterfork. Sorry, my bad.
