### ISSUE TITLE
@BindView(R2.id xx ) in lib not work

### ISSUE THREAD

**Issue by guider** [JakeWharton/butterknife#698]
@BindView(R2.id.textview)
    TextView textview;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.act);
        ButterKnife.bind(this);
        Log.e("zjw", "   title   " + textview);

    }

print   title   null  
 click textview nouse

**Comment by JakeWharton** [comment]
There's no enough information here to make this report actionable. Please include information such as how you're configuring your build, whether the generated code is present in the `build/` folder, if you're using ProGuard, etc.

**Comment by guider** [comment]
just a demo no ProBuard  
---------------------------------------------------------------------------------------------
project build.gradle 

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
---------------------------------------------------------------------------------------------

app build.gralde
apply plugin: 'com.android.application'
apply plugin: 'android-apt'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

    defaultConfig {
        applicationId "com.yanyuanquan.android.butterknifedemo"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'
    compile project(':helper')
}
---------------------------------------------------------------------------------------------
lib build.gradle

apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'com.neenbedankt.android-apt'
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.2.1'
    }
}
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.jakewharton:butterknife:8.2.1'
}
-----------------------------------

THIS All
 Please Help me   Thank you !

**Comment by JakeWharton** [comment]
If you turn on ButterKnife logging in the application what do the logs show when attempting to bind that class?

**Comment by guider** [comment]
I create  a demo  
https://github.com/guider/ButterknifeDemo
maybe you can check out and check where I have error 3Q

**Comment by guider** [comment]
@JakeWharton  

 I create a demo
https://github.com/guider/ButterknifeDemo
maybe you can check out and check where I have error 3Q

**Comment by guider** [comment]
yeah  !  I have solve  THx

**Comment by JakeWharton** [comment]
What was the problem?

**Comment by hy9be** [comment]
@guider How did you solve the problem?

**Comment by ytzys** [comment]
This is a solution http://blog.csdn.net/ytzys/article/details/53243438

**Comment by aiquantong** [comment]
@guider How did you solve the problem?
