### ISSUE TITLE
Whether or not to cancel the unbind () method after 8.0

### ISSUE THREAD

**Issue by robin12210325** [JakeWharton/butterknife#699]
Whether or not to cancel the unbind () method after 8.0, i can not find unbind method

**Comment by JakeWharton** [comment]
Details are in the [change log][1] which should always be consulted when upgrading. `bind` returns an interface which contains the `unbind` method.

 [1]: https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md
