### ISSUE TITLE
Older versions documentation

### ISSUE THREAD

**Issue by luiseduardobrito** [JakeWharton/butterknife#700]
Is there any section in the documentation where I can find information from older versions of the project, such as the Javadocs?

**Comment by JakeWharton** [comment]
The website is checked into the repo so you can download an old tag and browse the `website/` directory. For Javadoc you can either download the jars (aka zips) from Maven central at http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.jakewharton%22%20AND%20a%3A%22butterknife%22 or browse online using http://javadoc.io/doc/com.jakewharton/butterknife/8.2.1 (and the version dropdown).

**Comment by luiseduardobrito** [comment]
Thank you for the amazingly fast response, I'll check those resources!
