### ISSUE TITLE
Unable to unbind view for RecyclerView's View Holder

### ISSUE THREAD

**Issue by harry-nguyen-88** [JakeWharton/butterknife#701]
Hi Jake, I wonder how we can unbind view for recycler's view holder ? I cannot find any destructor method for view holder so It can lead to memory leak issue in future!

P/S: You wrote a very awesome plugin. I believe that it helped million android devs around the world to save time for UI binding stuff :+1:

**Comment by JakeWharton** [comment]
You do not need to unbind view holders. Fragments are the _only_ case where you need to actually unbind things. Activities, dialogs, custom views, and view holders are all bind and then forget!

**Comment by WinterRunner** [comment]
Why? ===>Activities, dialogs, custom views, and view holders are all bind and then forget!
