### ISSUE TITLE
RadioGroup not supported

### ISSUE THREAD

**Issue by Kevin-Stark** [JakeWharton/butterknife#703]
when I write the codes like these,
 @BindView(R.id.gender)
 RadioGroup group;
the app is crashed.
because RadioGroup cannot be cast to android.widget.CompoundButton.

**Comment by JakeWharton** [comment]
What is `gender` in your XML?

**Comment by Kevin-Stark** [comment]
is a RadioGroup. @JakeWharton

**Comment by JakeWharton** [comment]
That seems unlikely.

**Comment by Kevin-Stark** [comment]
sorry,it's my fault,my usage is not right,thanks a lot.
