### ISSUE TITLE
Bindings fail after file changes using jack compiler and java 8

### ISSUE THREAD

**Issue by bennmapes** [JakeWharton/butterknife#704]
Using Android Studio 2.2 Beta running on Mac OSX 10.10.5
and butterknife 8.1.0 (I couldn't get the latest build to work due to issue #673)

I opened this issue on https://code.google.com/p/android/issues/detail?id=219768 but I'm unsure if this is something going on with Android Studio or something going on with this library, maybe you can point me in the right direction.

Steps to Reproduce bug:
1. open and build the project https://github.com/bennmapes/android_bug
2. deploy it to device
3. change the string in the RandomClass
4. deploy to device again
5. should get null pointer when binding fails
6. to fix this rebuild the whole project and it should work again

**Comment by hnvn** [comment]
I confirm this problem. I'm crazy about it. I spent a lot of time for rebuild my project again and again.

**Comment by bennmapes** [comment]
I know exactly what you mean about having to wait ages for things to rebuild. It's driving me crazy as well.

**Comment by hnvn** [comment]
So sad, nobody reply. I think this problem come from Android Studio and Jack compiler, because generated files of ButterKnife annotations already existed, but something was wrong while building them to APK file.

**Comment by peterbetos** [comment]
Already has an issue on this:
https://code.google.com/p/android/issues/detail?id=218017

**Comment by hnvn** [comment]
It's not this issue. Your issue only happen in v2.8.1 and it cause build processing end with a exception. My problem only appear at runtime, because the Butterknife Annotation not working, it make a NullPointerException at runtime when I try to access a View.

**Comment by peterbetos** [comment]
But the issue seems to be the cause during runtime as well. My existing issue is the same as yours actually and it's only happening when it's not using APT. Probably a lot of com.sun.* Exceptions are just being bypassed and are just realized when the app is actually running.

**Comment by hnvn** [comment]
My problem do not appear when I update my AndroidStudio to v2.2 Beta 2 (until now, I still haven't encounter it yet). Maybe, this problem come from build tool.

**Comment by marcosrocha85** [comment]
hnvn, had that problem yesterday and it worked by adding the butterknife-compiler key on dependencies section of my gradle module's project.
I realized that issue appears when you are using other annotation packages like Realm, Retrofit and so on.

**Comment by hnvn** [comment]
marco, you mean like: 

`compile 'com.jakewharton:butterknife:'                          + butterknifeVersionCode`
` annotationProcessor 'com.jakewharton:butterknife-compiler:'     + butterknifeVersionCode`

Of course, you must add the butterknife-compiler when use customized annotations

**Comment by marcosrocha85** [comment]
Yes, but in my case my dependencies came:
```
    compile 'com.jakewharton:butterknife:8.2.1'
    compile 'com.jakewharton:butterknife-compiler:8.2.1'
```

Just check your package options adding the path to processor like:
```
android {
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}
```

**Comment by peterbetos** [comment]
@marcosrocha85 Your workaround seems to fix our issue as well. 👍

**Comment by duckinferno** [comment]
@marcosrocha85 You should be using `annotationProcessor` for your compiler, not `compile`

    compile 'com.jakewharton:butterknife:8.3.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.3.0'

**Comment by bennmapes** [comment]
I can confirm as well that I haven't seen this issue after updating to Android Studio 2.2 **Beta 2**

The issue must have been with Android Studio 2.2 Preview and Beta 1 only.

**Comment by DreaminginCodeZH** [comment]
@hnvn I'm encoutering the same issue as you mentioned with Android Studio 2.2.2 (Stable channel), and I had to rebuild on approximately every build. Did you encounter it again? How did you solve it?

**Comment by rmtmckenzie** [comment]
I'm seeing the same issue as well @DreaminginCodeZH with build tools and studio 2.2.2. Definitely seems to be a build issue rather than butterknife though as it affects other annoations as well. Pretty sure it's caused by the new packaging tool introduced with this version.

Adding `android.useOldPackaging=true` to my gradle.properties file seems to be working as a temporary workaround.

**Comment by hnvn** [comment]
In my opinion, the best practice of using Lambda expression in Android is using RetroLamda. Jack toolchain is not good enough now. Buiding time of Jack is larger than JIT

Get Outlook for iOS




On Thu, Nov 10, 2016 at 12:08 AM +0700, "Morgan" <notifications@github.com> wrote:












I'm seeing the same issue as well @DreaminginCodeZH with build tools and studio 2.2.2. Definitely seems to be a build issue rather than butterknife though as it affects other annoations as well. Pretty sure it's caused by the new packaging tool introduced with this version.



Adding android.useOldPackaging=true to my gradle.properties file seems to be working as a temporary workaround.

**Comment by purebel** [comment]
Facing the same issue with AS 2.2.3 and ButterKnife 8.4.0, with Jack enabled & Java 8.

Hope anyone can share the final solution if any.
