### ISSUE TITLE
App crash when use <fragment ... />view inside XML

### ISSUE THREAD

**Issue by geekroot** [JakeWharton/butterknife#706]
Using Android Studio 2.2 Beta and ButterKnife 8.2.1

I have a MainActivity file which contain a <fragment ... /> in its layout file. This <fragment ... /> load a Fragment but when i use ButterKnife.bind() in its onCreateView method i always got this error

`android.view.InflateException: Binary XML file line #81: Error inflating class fragment`

In case i used the rootView.findViewById method everything is ok.

**Comment by JakeWharton** [comment]
Paste the full exception

**Comment by geekroot** [comment]
The full exception is [here ](http://pastebin.com/D3dVt0Yh)

**Comment by JakeWharton** [comment]
What makes you think Butter Knife is at fault here?

**Comment by JakeWharton** [comment]
> Caused by: java.lang.ClassCastException: android.support.v7.widget.RecyclerView cannot be cast to android.widget.AdapterView

You're trying to bind a RecyclerView to an AdapterView.

**Comment by geekroot** [comment]
When i remove ButterKnife.bind and use the normal findViewById the app run perfectly.

**Comment by geekroot** [comment]
Just for future reference.

> Caused by: java.lang.ClassCastException: android.support.v7.widget.RecyclerView cannot be cast to android.widget.AdapterView

That exception is triggered when you use the notation @OnItemSelected(R.id.recycler_view_tip_records) using a RecyclerView. The notation need an AdapterView object (ListView).

```
@OnItemSelected(R.id.recycler_view_tip_records)
public void onItemClick(int position){
        Toast.makeText(getActivity().getApplicationContext(), "Item selected at position " + position, Toast.LENGTH_SHORT).show();
    }
```

**Comment by DmitryMelnyk** [comment]
Or  @OnItemClick
