### ISSUE TITLE
@BindView in an Activity gets me a NullPointerException

### ISSUE THREAD

**Issue by monicalabbao-rogomi** [JakeWharton/butterknife#720]
Hi team! I had the following code for my activity

    private Unbinder mUnbinder;
    @BindView(R.id.sp_category)
        Spinner mSpCategory;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sample_spinner);
        mUnbinder = ButterKnife.bind(this);
        initActionBar();
        initSpinners();
    }

When i try setting up my spinner with an Adapter I get an exception that the spinner `mSpCategory` is null:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Spinner.setAdapter(android.widget.SpinnerAdapter)' on a null object reference`

It also happens when I try @BindView on TextView then binding it into the activity, like so:

    @BindView
    TextView mSampleTextView;

Can you please tell me what is going on with the new BindView please? Thanks!

**Comment by JakeWharton** [comment]
Did you include the compiler in your build?

**Comment by monicalabbao-rogomi** [comment]
Hello @JakeWharton , this one?

compile 'com.jakewharton:butterknife:8.2.1'

**Comment by JakeWharton** [comment]
You need two dependencies. Have a look at the README for instructions.

**Comment by monicalabbao-rogomi** [comment]
@JakeWharton thank you, my problem is solved now!

**Comment by JakeWharton** [comment]
Great!
