### ISSUE TITLE
please help me ,how to use in java8? thinks eveyboby.

### ISSUE THREAD

**Issue by hyr0318** [JakeWharton/butterknife#734]
`Error:Could not find property 'options' on task ':app:compileDebugJavaWithJack'.`

**Comment by GISirFive** [comment]
@hyr0318  Thinking that It is not a **butterknife issue**. I'm using JDK 8 for a long time, and not encounter this problem. Check your gradle.build at first.

**Comment by hyr0318** [comment]
@GISirFive  when i add this in gradle.build it will  NullPointerException  and use butterknife:7.0.1'
 defaultConfig {

        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        jackOptions {
            enabled true
        }
    }
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
dependencies {
    compile 'com.jakewharton:butterknife:7.0.1'
}
and don't add this in gradle.build  it will be worked .

but when i use butterknife 8.4.0  in java8  
Error:Could not find property 'options' on task ':app:compileDebugJavaWithJack'.

how can i solve this problem ？ think you .

**Comment by GISirFive** [comment]
`jackOptions {
        enabled true
 }`
It is not an essential code I thought, remove it and try again

**Comment by hyr0318** [comment]
@GISirFive  if i change to false  it will 
Error:Jack is required to support java 8 language features. Either enable Jack or remove sourceCompatibility JavaVersion.VERSION_1_8.

**Comment by GISirFive** [comment]
Sorry cannot help it, It's beyond my scope of knowledge....

**Comment by hyr0318** [comment]
@GISirFive  in your gradle.build  `jackOptions { enabled true }` it will worked ?

**Comment by GISirFive** [comment]
`jackOptions { enabled true }`
I'v never add this before

**Comment by hyr0318** [comment]
@GISirFive .....if you don't add jackOptions { enabled true } you don't hava this :
`Error:Jack is required to support java 8 language features. Either enable Jack or remove sourceCompatibility JavaVersion.VERSION_1_8.` ?

**Comment by GISirFive** [comment]
yeah, and I always use jdk 8

**Comment by hyr0318** [comment]
@GISirFive  in you build.gradle  do you hava this ` compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }` ?

**Comment by GISirFive** [comment]
yes

**Comment by JakeWharton** [comment]
You do not need to apply the 'android-apt' plugin when using Jack. Please see the "Note" under "Download" in the README. All you need to do is use the `annotationProcessor` configuration with the compiler artifact.
