### ISSUE TITLE
How to apply different values to different views?

### ISSUE THREAD

**Issue by lion4ik** [JakeWharton/butterknife#737]
Hi Jake! Please explain how I can apply different value for each view ? 
It seems like I need 

```java
void apply(List<T> list, Property<? super T, V> setter,  List<V> value)
```
which will apply value.get(i) for list.get(i). Can you you suggest me best solution using ButterKnife?

**Comment by JakeWharton** [comment]
Use the `Setter` variant which provides an index to the callback.
