### ISSUE TITLE
ButterKnife prevents obfuscation

### ISSUE THREAD

**Issue by emartynov** [JakeWharton/butterknife#746]
ButterKnife keeps small portion of reflection because of generic `bind()` method. Would be nice to allow obfuscation for these classes as well. Maybe by generating some static map corresponded binders to classes?

Does anyone think it is a valueable?

**Comment by JakeWharton** [comment]
You can reference the generated classes directly if you want to enable complete obfuscation. Details are in the CHANGELOG under v8.3.0 and support for this is experimental until v9.0 is released.

I don't think the generated map adds any value since it also needs looked up reflectively and thus suffers the same problem of itself being obfuscated.

**Comment by emartynov** [comment]
The problematic place is:
`Class<?> viewBindingClass = Class.forName(clsName + "_ViewBinder");`

The rest is not using reflection if I'm not mistaking.
So if we generate something like:
```
Map<Class, Class> targetClassToBinderClass;
...
targetClassToBinderClass.put(MainActivity.class, MainActivity_ViewBinder.class);
```
Then proguard/dexguard should correctly obfuscate this code as well.

**Comment by JakeWharton** [comment]
Right, except in order to access that map you have to do reflection to look up the generated class.

**Comment by emartynov** [comment]
Ah, yes, we can not modify existing files.

So it should generate class and its name should be kept out from obfuscation.

I don't know if it smaller evil than keeping all activities and fragment.

**Comment by JakeWharton** [comment]
You can also just reference the generated code directly like I said. Replace `ButterKnife.bind(this)` with `new Whatever_ViewBinder(this)` and you're done.

**Comment by emartynov** [comment]
Ok, thanks!
And closing the issue.

**Comment by emartynov** [comment]
The last question, @JakeWharton do you know how to suppress the proguard configuration from the library?

**Comment by JakeWharton** [comment]
I don't think that you can. There's an Android bug filed for that.

**Comment by emartynov** [comment]
So, it means if I even use generated code directly I still need to find a way how to turn off the proguard rule from ButterKnife library.

**Comment by JakeWharton** [comment]
Yes. The ProGuard rules will be separated in 9.0 when using the generated
code API becomes stable.

**Comment by jolsondc** [comment]
Replacing ButterKnife.bind(this) with new Whatever_ViewBinder(this) and use them in my code. which does work and Proguard obfuscate my classes. but only problem here is i have to copy them from Debug folder to my package from getting changed/deleted. and update it every time i add/remove views

**Comment by emartynov** [comment]
You should not copy them. It is generated code and should be available for the compilation reference without copying.

**Comment by jolsondc** [comment]
Yes. but until i remove all imports of Butterknife from class, proguard dont work on it. 

That is i have to get rid of all the Annotation which in turns deletes all the generated class from debug folder.

**Comment by pearlmaknun** [comment]
Whatever_ViewBinder(this) turns red, why?

**Comment by jolsondc** [comment]
Whatever_ViewBinde(this) class is generated in debug folder. you need to manually copy that file in your package.

**Comment by JakeWharton** [comment]
Do not copy the generated types.
