### ISSUE TITLE
ButterKnife breaks CoordinatorLayout anchoring

### ISSUE THREAD

**Issue by athornz** [JakeWharton/butterknife#747]
I'm unsure if this is a bug in ButterKnife, or the support library, but when ButterKnife is used in conjunction with a CoordinatorLayout inside a RecyclerView, the call to ButterKnife.bind() causes the CoordinatorLayout anchoring to break.

Uncommenting the call to bind() results in everything working as expected.

I've filed a bug report with Google also, where you can find a sample project: 
https://code.google.com/p/android/issues/detail?id=222802&thanks=222802&ts=1474246332

**Comment by JakeWharton** [comment]
This is not caused by Butter Knife since its generated code only calls
findViewById which seems to be side-effecting in this case.
