### ISSUE TITLE
ButterKnife 8.4.0 Not Working, Not Anonotation

### ISSUE THREAD

**Issue by nextkaki** [JakeWharton/butterknife#750]
I Using Android Studio 2.2

No Using Annotation
@BindView <- Not Found.
Etc. All Annotaion Not Found

*******Project.Build.gradle
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        **classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'**
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}

*******app.build.gradle
apply plugin: 'com.android.application'
apply plugin: 'android-apt'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        applicationId "**********"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha8'
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'
}

**Comment by aliusa** [comment]
You're using 8.2.1 is what I see.

`compile 'com.jakewharton:butterknife:8.2.1'`

**Comment by nextkaki** [comment]
dear aliusa.

I Use 8.4.0 -> Error. therefore 8.2.1 downgrade

**Comment by JakeWharton** [comment]
This seems like a studio problem. If you can't use the annotation then
you're not even using the library.

**Comment by nextkaki** [comment]
Thank You. JakeWharton

I Found Solution.

App:Module -> Gradle
apply plugin: 'com.neenbedankt.android-apt' <- Top Position

dependencies {
 compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
}


Project:Module -> Gradle
 repositories {
        jcenter()
    }
 dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
}

Studio Restart.

Solution Ok!
