### ISSUE TITLE
Butterknife v8.2.0+ breaks lint with android gradle plugin 2.2.0

### ISSUE THREAD

**Issue by mik9** [JakeWharton/butterknife#751]
Logs with v8.4.0: https://gist.github.com/mik9/73b62458be405ad322dd096e24d7ecef
Logs with v8.1.0: https://gist.github.com/mik9/6f84925acb104420e4e1193d073a5053

Sample project to reproduce: https://www.dropbox.com/s/qej8tqaevm7rd8z/ButterknifeLintFail.zip?dl=0

Run `./gradlew lintDebug` to see problem.

**Comment by jaredsburrows** [comment]
@mik9 I am not seeing this at all. Can you upload your project to Gtihub? I have no lint issues with `8.4.0` here: https://github.com/jaredsburrows/android-gif-example.

**Comment by JakeWharton** [comment]
This happens when you're using Retrolambda without the special lombok fork that adds lambda support. Until ButterKnife's lint checks are updated to the JetBrain's PSI model instead of Lombok this error will continue to happen (unless you apply the lombok fix for Retrolambda).
