### ISSUE TITLE
the new Jack compiler with version 2.2.0

### ISSUE THREAD

**Issue by aloe20** [JakeWharton/butterknife#760]
I am using Android Studio2.2.When I use the new Jack and I instead replace 'apt' with 'annotationProcessor'. 
classpath 'com.neenbedankt.gradle.plugins:android-annotationProcessor:1.8'.
I gradle my project refresh failed.

https://jcenter.bintray.com/com/neenbedankt/gradle/plugins/android-annotationProcessor/1.8/android-annotationProcessor-1.8.pom
    https://jcenter.bintray.com/com/neenbedankt/gradle/plugins/android-annotationProcessor/1.8/android-annotationProcessor-1.8.jar
    https://repo1.maven.org/maven2/com/neenbedankt/gradle/plugins/android-annotationProcessor/1.8/android-annotationProcessor-1.8.pom
    https://repo1.maven.org/maven2/com/neenbedankt/gradle/plugins/android-annotationProcessor/1.8/android-annotationProcessor-1.8.jar

these urls is 404 not found.What can I do?

**Comment by serj-lotutovici** [comment]
there is no ` 'com.neenbedankt.gradle.plugins:android-annotationProcessor:1.8'.`, you can delete that line completely. Just replace your `apt 'com.jakewharton:butterknife:8.4.0` with `annotationProcessor 'com.jakewharton:butterknife:8.4.0` in your dependency block
