### ISSUE TITLE
conflict with android-apt plugin

### ISSUE THREAD

**Issue by strongmanb** [JakeWharton/butterknife#764]
hello  @JakeWharton 
I used butterknife version 7.0.1 before and it work well, but when I update to the verion of 8.4.1, it cant work.
> you said: Note: If you are using the new Jack compiler with version 2.2.0 or newer you do not need the 'android-apt' plugin and can instead replace apt with annotationProcessor when declaring the compiler dependency.

I remove the "android-apt" plugin and replace apt with annotationProcessor, everything is good.But actually I need the "android-apt" plugin, because my project used dagger2(It need apt). So the trouble is that if I add the apt plugin then butterknife can't work, or if I remove the apt plugin then dagger2 can't work.

I don't know how to fix this issue.Count you give me some advice? I am crazy now./(ㄒoㄒ)/~~

**Comment by JakeWharton** [comment]
You can use `annotationProcessor` with Dagger. This is a build system configuration and has nothing to do with BK or Dagger. You either use android-apt or the built-in support for _any_ annotatoin processor dependency.
