### ISSUE TITLE
ButterKnife 和 NavigationView actionLayout 使用问题

### ISSUE THREAD

**Issue by VernonLee** [JakeWharton/butterknife#765]
Hello JakeWharton ，我最近正在使用ButterKnife的过程中遇到ButterKnife和NavigationView中actionLayout结合使用的场景，从现有的功能基础上，调用ButterKnife.bind(actionLayout)以及重写诸如onCheckedChanged等事件时，会和Activity的事件发生冲突，请问，如何对actionLayout使用ButterKnife呢？非常谢谢！

**Comment by xxxzhi** [comment]
How to conflict with the Activity Event? For Example?

**Comment by VernonLee** [comment]
多谢回复。那我举个例子吧

我的ActionView如下：

View view = MenuItemCompat.getActionView(dayNightMenuItem);
ButterKnife.bind(view);

绑定好之后，

在成员变量中声明控件，比如 
@BindView(R.id.switch)
Switch mSwitch; 

* 它这里会报找不到对象错误。

还有 我要监听switch变化事件：

@OnCheckedChanged void xxx() {
 
}

* 方法中捕捉不到响应

基于上面两种情况，所以我猜测是和activity事件冲突或者是其他原因导致的。

**Comment by xxxzhi** [comment]
@VernonLee Do you bind many views who has child view with id R.id.switch or has no view with id R.id.switch?  Or are there more than one view which id is R.id.switch? Try to remove butterknife and use custom OnCheckedChanged setting, checkout the result.

**Comment by xxxzhi** [comment]
Btw, try to use the English bar, or estimated jake can not help you.

**Comment by xxxzhi** [comment]
Btw, try to use the English bar, or estimated Jake can't help you.

**Comment by VernonLee** [comment]
@xxxzhi 只有在actionLayout中用到R.id.switch，其他地方没有用到。出现这种情况我猜测是受ButterKnife自身处理view绑定机制影响，NavigationView中actionLayout才出来没多久，所以可能是还没有做适配或者增加这方面的功能。

我英语不太好，发到这里最主要目的还是让碰到同类问题的国人朋友们看到，然后一起讨论。

**Comment by JakeWharton** [comment]
I can't help here, sorry!
