### ISSUE TITLE
Support identifiers

### ISSUE THREAD

**Issue by TeodorKolev** [JakeWharton/butterknife#767]
Is there support for next code:
`Drawable message = (Drawable) getResources().getDrawable(getResources().getIdentifier(myText, "drawable", MainActivity.PACKAGE_NAME));`

**Comment by JakeWharton** [comment]
No, there's no point. The only reason to use that syntax is to do dynamic loading at runtime and Butter Knife resolves everything at compile time. Stick to what you already have.
