### ISSUE TITLE
Resources not bound after upgrading from 7.0.1 to 8.1.0 -> 8.4.0

### ISSUE THREAD

**Issue by fxhereng** [JakeWharton/butterknife#768]
Hi,

Like says the title, when tyring to upgrade from 7.0.1 to 8.X, I wasn't able to bind views properly, always getting NullPointerException. Gradle project had been cleant and rebuilt.

It was only working using ButterKnife.findById(...).

I ended up going back to old version. 

For information, my proguard:
```
#Butterknife
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}
```
sdk version:
```
 compileSdkVersion 23
 buildToolsVersion "23.0.1"
```

Thanks

**Comment by joseluisametller** [comment]
When on declaration, instead of using:

@Bind(R.id.recycler_view)
RecyclerView recyclerView;

use

@BindView(R.id.recycler_view)
RecyclerView recyclerView;

**Comment by fxhereng** [comment]
Yes, I changed every @Bind annotations to @BindView, otherwise it doesn't compile

**Comment by JakeWharton** [comment]
Did you follow the instructions in the README and CHANGELOG? Show your build.gradle.

**Comment by fxhereng** [comment]
Sorry I didn't notice there was a changelog, I only followed on http://jakewharton.github.io/butterknife/. I will have a look thanks!
