### ISSUE TITLE
Annotation compiler error in lib project

### ISSUE THREAD

**Issue by amansinghal** [JakeWharton/butterknife#769]
Hi Jack,

I am trying to integrate butterknife into my lib project but I am having following problem while compiling annotation in my gradle file. 

Error:Could not find com.android.support:support-annotations:24.1.0.
Searched in the following locations:
    file:/C:/Program Files/Android/android-studio/gradle/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.pom
    file:/C:/Program Files/Android/android-studio/gradle/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.jar
    https://jcenter.bintray.com/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.pom
    https://jcenter.bintray.com/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.jar
    file:/E:/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/sdk/extras/android/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.pom
    file:/E:/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/sdk/extras/android/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.jar
    file:/E:/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/sdk/extras/google/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.pom
    file:/E:/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/sdk/extras/google/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.jar
    file:/E:/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/sdk/extras/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.pom
    file:/E:/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/adt-bundle-windows-x86-20140321/sdk/extras/m2repository/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.jar
Required by:
    toppr:aman-core:unspecified

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**build.gradle**

apply plugin: 'com.android.library'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'com.jakewharton.butterknife'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE'
    }
}

buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:24.+'
    testCompile 'junit:junit:4.12'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'org.parceler:parceler-api:1.0.4'
    compile 'com.jakewharton:butterknife:7.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    compile('io.nlopez.smartadapters:library:1.2.3') {
        transitive = false
    }
    compile 'com.android.support:recyclerview-v7:24.+'
    compile 'com.android.support:appcompat-v7:24.+'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile "com.squareup.picasso:picasso:2.5.2"
    compile 'com.android.support:design:24.+'
    compile 'com.android.support:cardview-v7:24.+'
    compile 'com.android.support:support-annotations:24.+'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.google.firebase:firebase-database:9.4.0'
    compile 'com.google.firebase:firebase-storage:9.4.0'
    compile 'com.google.firebase:firebase-config:9.4.0'
    compile 'com.google.firebase:firebase-crash:9.0.2'
}

**Comment by iNoles** [comment]
This is not a butterknife issue. 

Could not find com.android.support:support-annotations:24.1.0.

**Comment by amansinghal** [comment]
May be not but while I am trying to build the project without **apt 'com.jakewharton:butterknife-compiler:8.4.0'** then I am not catching any error but now I am not able to access @Bind  & ect. annotations in my main project which is inheriting the library project.

**Comment by JakeWharton** [comment]
Your "Android repository" in SDK manager needs updated. If you use the Android Gradle 2.2.0 plugin or Android Studio 2.2 or newer it will automatically update this when you use a newer dependency.

**Comment by voghDev** [comment]
By the way, you are trying to import various versions of `ButterKnife` at the same time. If you use 7.0.1 (It seems it is included in your dependencies list), then you don't need the compiler 8.4.0, and if you use 8.4.0, then remove the 7.0.1 dependency
