### ISSUE TITLE
Help! What's the function of scanForRClasses ?

### ISSUE THREAD

**Issue by Dear-zhen** [JakeWharton/butterknife#770]
Hi ,Jake Wharton. In your butterknife, A probleam I've thought long time. That is ,what's the function of the scanForRClasses ? And inside, I don't know the function of the class Trees also. I've sought much on google, but found nothing useful, although I found the doc of Trees  on Oracle. It is a pity that there are no description about this class on it. So I hope you can give me some help ! Thank you very much !

**Comment by JakeWharton** [comment]
It reads the source code to map the IDs the processor sees back to the resource names for the generated code.
