### ISSUE TITLE
Apply @SuppressLint attribute to generated handler methods when necessary

### ISSUE THREAD

**Issue by jasonwyatt** [JakeWharton/butterknife#772]
I have my `lint.xml` set up so that `ClickableViewAccessibility` raises an `error`. 

The `@OnTouch` binding does not have a way to suppress that warning when I am making sure to call `performClick` when necessary in my annotated method.

I recommend either picking up `@SupressLint` annotations on bound methods and applying them to the generated listener, or adding an optional string parameter to the `@On[Event]` annotations themselves for this situation.

**Comment by andreas-** [comment]
+1

**Comment by Bkrickl** [comment]
+1
