### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by daiwj** [JakeWharton/butterknife#773]
Error:Could not find support-annotations.jar (com.android.support:support-annotations:24.1.0).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.jar

i don't know how to fix this problem..., i'm sure the network is available and i had installed all of the support repositories.

**Comment by JakeWharton** [comment]
The support-annotations artifact comes from the "android repository" in your SDK. Ensure that the "android repository" is up-to-date in your SDK manager.
