### ISSUE TITLE
No include option

### ISSUE THREAD

**Issue by TeodorKolev** [JakeWharton/butterknife#774]
There is no tutorial or any clue that include option is possible in Butterknife.
```
  <include
        layout="@layout/some_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/my_id"/>
```
Nither this works:
```
@BindView(R.id.my_id)
    View myId;
```
Neither binding of included inner text views. Is that even possible?

**Comment by JakeWharton** [comment]
`<include>` tags are inlined by the layout inflater such that the views in the included XML replace the tag. Since Butter Knife just calls `findViewById`, any view inside the include is available to be bound.

**Comment by TeodorKolev** [comment]
What about calling layout that it is not included? Do I have to create addition class where I inflate it and call inner views from that class?
