### ISSUE TITLE
使用ButterKnife后 在加载完网络数据之后在使用view 会报java.lang.NullPointerException

### ISSUE THREAD

**Issue by huoshulei** [JakeWharton/butterknife#775]
使用ButterKnife后 
在加载完网络数据之后在使用view 
经常会报view 为空
打印log日志view==null 结果为ture

**Comment by snowf07** [comment]
> 使用ButterKnife后
> 在加载完网络数据之后在使用view
> 经常会报view 为空
> 打印log日志view==null 结果为ture

谁看懂你的中文啊...
