### ISSUE TITLE
BindString binds the String to a dimen value after adding non-English locale Strings

### ISSUE THREAD

**Issue by hy9be** [JakeWharton/butterknife#776]
You can see my String variables becomes the something like "16.0sp".

![image](https://cloud.githubusercontent.com/assets/3392907/19401543/e21b51d0-9229-11e6-9de6-312c32e3ba87.png)

I checked the ViewBinder class, it looks the variables were bind to some dimen variables.

![image](https://cloud.githubusercontent.com/assets/3392907/19401606/33a0d85e-922a-11e6-9cf7-47c921011f0d.png)

**Comment by hy9be** [comment]
@JakeWharton Any idea why this is happening. I may be able to help to submit a fix. Thanks!

**Comment by hy9be** [comment]
It works well in English (default) locale. But runs into this problem in non-English locales.

**Comment by hy9be** [comment]
The dimen variables are defined in the lib project.

**Comment by JakeWharton** [comment]
Does it happen on clean builds? Might have to tear out the mapping of IDs to real `R.*` references in v9...

**Comment by hy9be** [comment]
Yes it occurs on clean builds as well. But the problem is gone after I upgrade my build-tool from 23 to 24. Very weird.

Thanks anyways. I am closing this ticket.
