### ISSUE TITLE
how can i user this in  <include  android:id="@+id/layout1" layout="@layout/simple_layout"/> and  <include  android:id="@+id/layout2" layout="@layout/simple_layout"/>in the same layout,@BindView cant bind the same widget but they are different Object;

### ISSUE THREAD

**Issue by HPLY** [JakeWharton/butterknife#777]
how can i user this in  <include  android:id="@+id/layout1" layout="@layout/simple_layout"/> and  <include  android:id="@+id/layout2" layout="@layout/simple_layout"/>in the same layout,@BindView cant bind the same widget but they are different Object;

**Comment by JakeWharton** [comment]
This is currently not supported but tracked by #394.
