### ISSUE TITLE
Unexpected error during visit: com.android.jack.ir.ast.JMethodCall at "Unknown source info"

### ISSUE THREAD

**Issue by xybCoder** [JakeWharton/butterknife#780]
Error:Execution failed for task ':app:transformJackWithJackForQqRelease'.

> com.android.sched.scheduler.RunnerProcessException: Error during 'ShrinkAndMainDexTracer' runner on 'public class com.xxx.app.ui.activity.MainActivity_ViewBinding (D:\project\xxx-android\xxx\app\build\generated\source\apt\qq\release\com\xxx\app\ui\activity\MainActivity_ViewBinding.java:14.14-14.37)': Unexpected error during visit: com.android.jack.ir.ast.JMethodCall at "Unknown source info"

  i am using ButterKnife 8.4.0.

**Comment by JakeWharton** [comment]
This is a bug with Jack and should be reported to b.android.com.

**Comment by Xy-joe** [comment]
I'm currently facing this issue trying to generate a signed apk. How do i go about it. I'm using Butterknife 8.6.0, buildtoolversion 27.0.2
