### ISSUE TITLE
@OnTextChanged crashes on string

### ISSUE THREAD

**Issue by pyricau** [JakeWharton/butterknife#782]
```
@OnTextChanged(R.id.foo) void onTextChanged(String bar) {
}
```

This crashes when the generated code attempts to cast the CharSequence to a String, but the CharSequence isn't actually a String.

Either Butterknife should complain about String as a type here, or it should call toString() on the CharSequence.

**Comment by JakeWharton** [comment]
The casting behavior exists so that you can match `BindView` behavior:
```java
@BindView(R.id.foo) TextView fooView;
@OnClick(R.id.foo) void onClick(TextView fooView) { /* .. */ }
```
Either fails at runtime. The behavior probably works for _any_ argument which is why this was allowed. We should just force it to only work for `View` types.

**Comment by JakeWharton** [comment]
PR welcome if anyone out there wants to try this. I'm busy for at least two weeks.
