### ISSUE TITLE
Help! Error when bind view in android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by stdupanda** [JakeWharton/butterknife#784]
hello,master Jake! I came across one question when i tried to bind view in Fragment,code like :

        public class ClockFragment extends android.support.v4.app.Fragment{
        @BindView(R.id.tvSwitch)
        TextView tvSwitch;
        @Nullable
        @Override
        public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
                                 @Nullable Bundle savedInstanceState) {
            View view = inflater.inflate(R.layout.frg_clock, container, false);
            ButterKnife.bind(this, view);
            return view;
        }
        @Override
        public void onActivityCreated(@Nullable Bundle savedInstanceState) {
            super.onActivityCreated(savedInstanceState);
    
            //tvSwitch = (TextView) getActivity().findViewById(R.id.tvSwitch);//without butterknife,this works fine
            Log.i("tag"">>>>>>>>>>>>>>>>>>>" + tvSwitch.getText());//this will cause java.lang.NullPointerException
        }
    } 

version 8.4.0, ide: Android Studio
can you tell me how to bind view in android.support.v4.app.Fragment ？

**Comment by jimitpatel** [comment]
Why you need to re-initialize tvSwitch when it has already been initialized using @BindView?
Also tell, is tvSwitch part of your Activity or Fragment??

**Comment by stdupanda** [comment]
@jimitpatel i don't mean to re-initialize tvSwitch, it just turned out to be null when i used it:
Log.i("123","tag" + tvSwitch.getText());//this will cause java.lang.NullPointerException which means @BindView didn't have initialized tvSwitch

**Comment by JakeWharton** [comment]
Butter Knife only binds views inside `R.layout.frg_clock` and in this case you're reaching outside the fragment scope into the activity. Either retain your old `findViewById` code or remove your fragment's dependency on a view that is outside of its scope.

**Comment by lokeshhemrajani** [comment]
Cant I bind TextViews outside Activity like in helper class? What would be another option to get access to textview outside activity other than findViewById?
