### ISSUE TITLE
BindViews into individual references

### ISSUE THREAD

**Issue by mehmet6parmak** [JakeWharton/butterknife#789]
Would not it be nice to support such a syntax, (in addition to `List<T>`)

```
@BindViews({R.id.btn_butterknife, R.id.btn_glide})
Button btnButterKnife, btnGlide; 
```

**Comment by JakeWharton** [comment]
Those are two fields defined separately with an annotation only on the first one. I would strongly discourage defining fields like that, but regardless there's no way for Butter Knife to figure out which fields are "grouped" in the source in that way. As far as the compiler and Butter Knife are concerned those are two completely separate, unrelated fields.
