### ISSUE TITLE
the  bind  and  unbind  in the Fragment

### ISSUE THREAD

**Issue by Knight-xiaolu** [JakeWharton/butterknife#791]
i want  to know  whether need to  unbind  the view in Fragment ,sometimes, get the http result after onDestoryView,if i unbind the view will happen null exception,

**Comment by JakeWharton** [comment]
Yes. Unbind in `onDestroyView`. Otherwise you are leaking those objects. If a request response is delivered after this callback you need to ignore it or persist it somewhere for use when the view comes back.
