### ISSUE TITLE
Confused by the way to import this library

### ISSUE THREAD

**Issue by CoXier** [JakeWharton/butterknife#792]
As Jack Wharton saied:

> Note: If you are using the new Jack compiler with version 2.2.0 or newer you do not need the 'android-apt' plugin and can instead replace apt with annotationProcessor when declaring the compiler dependency.

I don't know the version of Jack compiler.Is there a way to find the version?

My builde.gradle(app level):

```gradle
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
}
````

**Comment by aaronhe42** [comment]
> version 2.2.0

I think it's referring to android gradle plugin version.

**Comment by aaronhe42** [comment]
And, the `annotationProcessor` from android gradle plugin 2.2.0+ actually would work without Jack compiler.

**Comment by JakeWharton** [comment]
I updated the README. Make sure you are using version 2.2.0 or newer of the Android Gradle plugin and then just use `annotationProcessor`, as has been said.
