### ISSUE TITLE
Butterknife suddenly stop workink

### ISSUE THREAD

**Issue by Balthair94** [JakeWharton/butterknife#793]
Hi good day.
I was working using butterknife 8.0.1. But suddenly it stopped working. It send me the same message. Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference. I already checked the objects and everybody are correct, there is no object missing or null.
I even changed the butterknife version but it does not work. I don't know what else to do. This is my gradle.

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
//apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    packagingOptions {
        exclude 'META-INF/NOTICE' // will not include NOTICE file
        exclude 'META-INF/LICENSE' // will not include LICENSE file
        // as noted by @Vishnuvathsan you may also need to include
        // variations on the file name. It depends on your dependencies.
        // Some other common variations on notice and license file names
        exclude 'META-INF/notice'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license'
        exclude 'META-INF/license.txt'
    }

    defaultConfig {
        applicationId "hauspa.cliente"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    dexOptions {
        preDexLibraries = false
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }
}

buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://zendesk.artifactoryonline.com/zendesk/repo' }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.7@aar') {
        transitive = true;
    }
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.google.android.gms:play-services-location:9.4.0'
    compile 'com.google.android.gms:play-services-maps:9.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}

**Comment by anthonymonori** [comment]
It sounds like a problem with your code and not with the library in specific. If you want us to help you out, please start by posting the exact LogCat output your are facing and parts of the code where it points to. You could also maybe try posting it to StackOverflow and tag it with ButterKnife.

Have a great day!

**Comment by JakeWharton** [comment]
Without a failing test case or sample we have no way of knowing what the actual problem is. Your list is null and something is causing it to be null.
