### ISSUE TITLE
Add project-level build.gradle setup to http://jakewharton.github.io/butterknife/

### ISSUE THREAD

**Issue by mateusgrb** [JakeWharton/butterknife#794]
As many people get to this library through http://jakewharton.github.io/butterknife/, it would be nice to have the 'android-apt' plugin setup there too, like it does in this github page's README. This way, we would skip [this error](http://stackoverflow.com/questions/36876158/gradle-dsl-method-not-found-apt).

**Comment by JakeWharton** [comment]
Using the 'android-apt' plugin is no longer required with the Android Gradle plugin 2.2.0 or newer so all that's left is the individual project configuration. As such, I don't think we need to add anything.
