### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ljf1172361058** [JakeWharton/butterknife#801]
```

1. @BindView(R.id.email_sign_in_button)
2. Button emailSignInButton;
3. 
4. @Override
5. protected void onCreate(Bundle savedInstanceState) {
6.         super.onCreate(savedInstanceState);
7.         setContentView(R.layout.activity_login);
8. 
9.         ButterKnife.bind(this);
10. 
11.         // @OnClick()点击事件失效,所以采用该方式测试
12.         // @OnClick() Click event failure, so the test using this way
13.         emailSignInButton.setOnClickListener(new View.OnClickListener() {
14.             @Override
15.             public void onClick(View view) {
16.                 ToastUtils.showShort(LoginActivity.this, "Can help me? thanks.");
17.             }
18.       });
19. }
20.
21.@OnClick(R.id.email_sign_in_button)
22.public void onClick() {
23.        ToastUtils.showLong(this, "output");
24.}

```

## Module gradle:

```
dependencies {
    // 编译ButterKnife注解框架(Compile ButterKnife annotation framework)
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}
```

## 是我的配置出错了么？(**Is my configuration error?**)

**Comment by cnexcelee** [comment]
me too

**Comment by NikoYuwono** [comment]
@ljf1172361058 Please paste the whole stacktrace

**Comment by ljf1172361058** [comment]
@NikoYuwono ok.

**Comment by cnexcelee** [comment]
@NikoYuwono  hello ,i had this error ,too.
my log:
11-11 17:23:01.032 10507-10507/com.diycode.lynn D/ButterKnife: Looking up binding for com.diycode.lynn.LoginActivity
11-11 17:23:01.032 10507-10507/com.diycode.lynn D/ButterKnife: Not found. Trying superclass com.diycode.lynn.TestBaseActivity
11-11 17:23:01.032 10507-10507/com.diycode.lynn D/ButterKnife: Not found. Trying superclass android.app.Activity
11-11 17:23:01.032 10507-10507/com.diycode.lynn D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by NikoYuwono** [comment]
@cnexcelee Post your code

**Comment by caiyoufei** [comment]
@ljf1172361058  我测试发现如果使用apply plugin: 'com.neenbedankt.android-apt'会造成空指针

**Comment by LeifDong** [comment]
@NikoYuwono  I have the same problem，my gradle code:
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
=================================================
#library build.gradle
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    compile 'com.android.support:design:24.2.1'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.github.chrisbanes.photoview:library:1.2.4'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'in.srain.cube:ultra-ptr:1.0.11'
    compile "com.wefika:flowlayout:0.4.1"
}

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'
    useLibrary 'org.apache.http.legacy'
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }
}
Hope for your help.

**Comment by caiyoufei** [comment]
@LeifDong  
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
这三个是使用本地库的时候需要的
compile 'com.jakewharton:butterknife:8.4.0'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
这两个是使用gradle库需要的

分开使用，别一起用

**Comment by LeifDong** [comment]
@caiyoufei 你好，这是我修改之后的配置,但是依然是java.lang.NullPointerException，我发现编译之后，没有生成XXActivity_ViewBinding.java文件。请问你知道怎么处理吗？
apply plugin: 'com.android.library'

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    compile 'com.android.support:design:24.2.1'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.github.chrisbanes.photoview:library:1.2.4'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'in.srain.cube:ultra-ptr:1.0.11'
    compile "com.wefika:flowlayout:0.4.1"
}

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'
    useLibrary 'org.apache.http.legacy'
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }
}

**Comment by LeifDong** [comment]
dependencies {
  compile 'com.jakewharton:butterknife:8.4.0'
  annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}

我发现添加以上代码到 app‘s build.gradle 是正确的。
但是添加到library’s build.gradle 就会java.lang.NullPointerException.

**Comment by taruntak** [comment]
Any solution??

**Comment by qindachang** [comment]
So, I just use old version to solution this proplem:
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'

**Comment by qindachang** [comment]
In my above everyone whos like me beacuse i am every biger and longer and handsome, look at this !!!
replace the 'annotationProcessor '  with 'apt'. 
sample:
dependencies {
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
}

i am your brother.

**Comment by ljf1172361058** [comment]
@LeifDong 
我试了下,真的是这样才有用,目前也只能加载app's build.gradle中用了。
但不知为何只有加在app's build.gradle才有效,而加在library's build.gradle却无效

**Comment by fvaryu** [comment]
@ljf1172361058 @LeifDong 
Library projects

To use Butter Knife in a library, add the plugin to your buildscript:

buildscript {
  repositories {
    mavenCentral()
   }
  dependencies {
    classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
  }
}
and then apply it in your module:

apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
Now make sure you use R2 instead of R inside all Butter Knife annotations.

class ExampleActivity extends Activity {
  @BindView(R2.id.user) EditText username;
  @BindView(R2.id.pass) EditText password;
...
}

Library 用法不同 根据你的代码 你那是在library中使用么？

**Comment by gmyboy** [comment]
use
`classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8 ` 
in your root build.gradle dependencies, add 
`apply plugin: 'android-apt'` 
in your app.gradle, Then use 
`compile 'com.jakewharton:butterknife:8.4.0'
 apt  'com.jakewharton:butterknife-compiler:8.4.0'`
as the app.gradle dependencies.
Get it!

**Comment by ljf1172361058** [comment]
@fvaryu 是的 我的就是在 library 中使用导致的 NullPointerException

**Comment by maoruibin** [comment]
If use Butter Knife in a library, you should check this introduce  [butterknife#library-projects](https://github.com/JakeWharton/butterknife#library-projects) by J.W

**Comment by maoxiandemeng** [comment]
@ljf1172361058   我也出现这个问题，最后怎么解决的呢

**Comment by ljf1172361058** [comment]
@maoxiandemeng 
改你主  Module 中的 build.gradle 和项目中的 build.gradle

1.在你主 Module 下 build.gradle 中的 apply plugin: 'com.android.application' 的下面加入
```
apply plugin: 'android-apt'
...
```
2. 在你主 Module 下 build.gradle 中的 dependencies 里加入
```
compile 'com.jakewharton:butterknife:8.4.0'
apt 'com.jakewharton:butterknife-compiler:8.4.0'
```
3.在你项目下的 build.gradle 中的 dependencies 里加入
`classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'`

**Comment by maoxiandemeng** [comment]
@ljf1172361058  意思是不用library 形式引入

**Comment by MrSimpleX** [comment]
@ljf1172361058 那就是在每个Library中都依赖一下
`compile 'com.jakewharton:butterknife:8.4.0'`
`apt 'com.jakewharton:butterknife-compiler:8.4.0'`
这两个库吗？我是在项目组件化的时候碰到的这个问题，抽取基础组件的时候在Library里导入butterknife，主工程依赖基础组件，请问你是每个module里都引入了一遍吗

**Comment by ljf1172361058** [comment]
@MrSimpleX  我只在 Library 中依赖了 butterknife，主项目依赖该 Library。(PS:我的项目只有主 Moudule 和 Library )

**Comment by ltigers** [comment]
使用butterknife和rxjava
java.lang.IllegalStateException:Fatal Exception thrown on Scheduler.Worker thread.
2 rx.android.schedulers.LooperScheduler$ScheduledAction.run(SourceFile:114)
3 ......
4 java.lang.NullPointerException:Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
5 im.pica.pica.ui.TemplateActivity$3.onError(SourceFile:162)
6 rx.observers.SafeSubscriber._onError(SourceFile:153)
7 rx.observers.SafeSubscriber.onError(SourceFile:115)
8 rx.exceptions.Exceptions.throwOrReport(SourceFile:216)
9 rx.observers.SafeSubscriber.onNext(SourceFile:139)
10 rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(SourceFile:224)
11 rx.android.schedulers.LooperScheduler$ScheduledAction.run(SourceFile:107)
12 android.os.Handler.handleCallback(Handler.java:756)
13 android.os.Handler.dispatchMessage(Handler.java:95)
14 android.os.Looper.loop(Looper.java:135)
15 android.app.ActivityThread.main(ActivityThread.java:5263)
16 java.lang.reflect.Method.invoke(Native Method)
17 java.lang.reflect.Method.invoke(Method.java:372)
18 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ltigers** [comment]
Sometimes normal, something wrong。
I do'nt know why has this issue

**Comment by ltigers** [comment]
when activity is destory, i use unbinder.unbind(); Is this causes this error when the network request has not finish

**Comment by ltigers** [comment]
空指针部分机型会出现：华为 GRA-CL00

**Comment by rch0903** [comment]
I got this problem too,and i use it in app's build like this:
compile 'com.jakewharton:butterknife:8.5.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1';
My solution is delete 'apt' in project's build and app's build,I think the 'apt' is conflicted with 'annotationProcessor',only one can be retained.

**Comment by dongjielitianjiao** [comment]
@ljf1172361058  我用的rxbinding  一直报空指针，解决不了呢

**Comment by JakeWharton** [comment]
It's not clear what the problem is here, but it seems like code isn't being generated or packaged into the APK. Ensure proper build configuration, that the generated classes are in `build/`, and that they end up in the final APK with APK inspector.

**Comment by ChasonChen** [comment]
在多module开发中，如果当前项目butterknife依赖来自于其他module，则会导致当前项目使用时空指针。确保项目当前目录下的build.gradle文件中加入butterknife依赖，才能保证当前项目中使用时不会空指针。

**Comment by ljf1172361058** [comment]
是的,所以我现在把 butterknife 依赖都放在我的主 module 中

**Comment by MoMuBai** [comment]
butterknife8.0以下的时候，正常使用 `compile 'com.jakewharton:butterknife:7.0.1'`就可以，但是在butterknife8.0以上，使用`implementation 'com.jakewharton:butterknife:8.5.1'`(AndroidStudio3.0)一直报NullPointerException，后来又继续添加了`annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'`才避免了NullPointerException

**Comment by GreenPepperForPotato** [comment]
第一阶段：下面配置可以正常工作，生成对应的xxxActivity_ViewBinding
dependencies{
    implementation 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'
}

第二阶段：新项目添加了kotlin环境，在app.gradle中添加了下面的代码，就不能编译自动生成xxxActivity_ViewBinding了，到了指定界面就报NullPointerException

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'   // 经过排查是这段代码产生了影响

解决办法有两种：
1、apply plugin: 'kotlin-kapt'   这行代码注释，（不推荐）
2、把annotationProcessor这一块改成kapt。就可以了。kapt 也能够处理Java 文件，所以不需要再保留 annotationProcessor 的依赖
dependencies{
    implementation 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
    kapt 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'
}
