### ISSUE TITLE
ButterKnife8.4.0  and Dagger2 plugin conflict

### ISSUE THREAD

**Issue by caiyoufei** [JakeWharton/butterknife#803]
Because dagger2 need use apply plugin: 'com.neenbedankt.android-apt',so butterknife8.4.0 is always NullPointException

**Comment by caiyoufei** [comment]
经测试，使用com.neenbedankt.android-apt这个插件必然导致 butterknife8.4.0空指针；
可以使用低版本的butterknife避免这个问题，但是如果使用了dagger2.2可能会出现编译问题

**Comment by manjunathc23** [comment]
+1

**Comment by vzeitler** [comment]
do you have "apt 'com.jakewharton:butterknife-compiler:8.4.0'" in your dependencies ?

**Comment by J1aDong** [comment]
@vzeitler  @caiyoufei   +1,经测试，在引用android-apt的情况下，将com.jakewharton:butterknife-compiler:8.4.0的annotationProcessor前缀改为apt可以正常工作

**Comment by jp1017** [comment]
Neither apt nor annotationProcessor works well. :disappointed:

**Comment by jp1017** [comment]
@caiyoufei see thie blog: 

http://www.jianshu.com/p/268c14130bea

We all see, the two libs recommand using `annotationProcessor`

**Comment by CaoyangLee** [comment]
dependencies {
  compile 'com.jakewharton:butterknife:8.4.0'
  annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}

use apt replace of annotationProcessor!
use apt replace of annotationProcessor!
use apt replace of annotationProcessor!

**Comment by ceduliocezar** [comment]
Replacing annotationProcessor for apt as @CaoyangLee  mentioned  worked for my project.

**Comment by Emeritus-DarranKelinske** [comment]
This is how I got both to work together:

    // Butter Knife
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    // Dagger 2
    apt 'com.google.dagger:dagger-compiler:2.8'
    compile 'com.google.dagger:dagger:2.8'
    provided 'javax.annotation:jsr250-api:1.0'

**Comment by Davids89** [comment]
Thanks @Emeritus-DarranKelinske

**Comment by renhuihhh** [comment]
@caiyoufei dagger2 都2.8了  我用的2.8没发现有这个问题哦

**Comment by TonyTangAndroid** [comment]
@renhuihhh   参考 Emeritus-DarranKelinske  给出的答案

**Comment by hoombar** [comment]
The option that @Emeritus-DarranKelinske provided doesn't see to work when you are using ButterKnife inside a library by applying the plugin
```
apply plugin: 'com.jakewharton.butterknife'
```
