### ISSUE TITLE
InjectView to BindView Conversation

### ISSUE THREAD

**Issue by s9iper1** [JakeWharton/butterknife#804]
i am working in a fragment and i have inflated class with viewpager and binded it 

` @BindView(R.id.walk_through_dialog_vp_pager)
    protected ViewPager mViewPager;`

in OnviewCreated method i am working further with the pageView 

` @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        ButterKnife.bind(getActivity(), view);
        unbinder = ButterKnife.bind(getActivity(), view);
        ButterKnife.setDebug(true);
        Log.e("TAG", "Pager "+ String.valueOf(mViewPager == null));
        mViewPager.setAdapter(new WalkThroughPagerAdapter());
}`

mViewPager is null here. 
i have done update in the project it was working fine before i just change to BindView from InjectView
i have also done changes in proguard.cfg 

`# Butterknife
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }`

i have also enabled debugger but got nothing in the log.
dependencies 
`compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'`

**Comment by iNoles** [comment]
I think Fragment has own bind methods

**Comment by JakeWharton** [comment]
Bind takes the target object and the source. You are passing the activity
and view and should instead switch to using the view and 'this'.

**Comment by s9iper1** [comment]
thanks @JakeWharton  solved it, :)
