### ISSUE TITLE
Question: About new ContentView annotation

### ISSUE THREAD

**Issue by rusmichal** [JakeWharton/butterknife#810]
Hello,

I use Butterknife in all my project, that is great helpful library. I have question about new improvements. I wonder to add new annotation e.g. ContentView for Activity and Fragments.

When we create new activity, We have to almost always override `onCreate()` where we have to provide content view. I like to separate code because methods should do only one thing. so I have created my own abstract `BaseActivity` where I have two important method. `onActivityCreate()` and `getContentView()`. New extended Activity from BaseActivity have to implement these methods and I get separated `onCreate()` into two different methods. It looks like that:

```
public abstract class BaseActivity extends AppCompatActivity {
    protected abstract int getContentView();

    protected abstract void onActivityCreate(Bundle savedInstanceState);

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(getContentView());

        onActivityCreate(savedInstanceState);
    }
}
```
Subclasses looks like that:

```
public class TestActivity extends BaseActivity {
    @Override
    protected int getContentView() {
          return R.layout.activity_test;
    }

    @Override
    protected void onActivityCreate(Bundle savedInstanceState) {
          //...call methods
    }
}
```
I think it looks clear. So I have question. Is it good idea to create new annotation @ContentView which help you and provide content resource to `setContentView()` method? What do you think?

**Comment by JakeWharton** [comment]
See #8. I prefer the current behavior of being ignorant as to where the views originate.
