### ISSUE TITLE
Unable to bind after change in screen orientation.

### ISSUE THREAD

**Issue by shashwatsgsits** [JakeWharton/butterknife#813]
When I am changing the screen orientation, I am getting the following error. 
Caused by: java.lang.IllegalStateException: Required view 'drawer' with ID 2131689716 for field 'drawerLayout' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

I am binding a DrawerLayout. 
In onCreateView, the fragment is getting inflated. Binding is done in onViewCreated. DrawerLayout is a parent element in the fragment.
ID is defined for the DrawerLayout after the orientation change but findViewById gives Null.
drawerLayout = (DrawerLayout) view.findViewById(R.id.drawer); (**Null**).

In ondestroy method, I am unbinding the view.

Please refer to the code snippet below.

`    @BindView(R.id.drawer)
    DrawerLayout drawerLayout;
`

` @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.main_fragment, container, false);
        return view;
    }`

`@Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onSaveInstanceState(savedInstanceState);
        drawerLayout = (DrawerLayout) view.findViewById(R.id.drawer);
        unbinder = ButterKnife.bind(this, view);
   `}

`@Override
    public void onDestroyView() {
        super.onDestroyView();
        unbinder.unbind();
    }`

`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:layout_width="match_parent" android:id="@+id/fragment"
        android:layout_height="match_parent">

    </FrameLayout>
    <android.support.design.widget.NavigationView
        android:id="@+id/navigation_view"
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        android:background="#80000000"

        android:layout_marginLeft="-64dp"
        android:layout_gravity="start">

        <fragment
            android:layout_width="match_parent"
            android:orientation="vertical"
            android:layout_height="match_parent"
            android:id="@+id/navigationFragment"
            class="com.xyz.fragment.MenuFragment" />
    </android.support.design.widget.NavigationView>

</android.support.v4.widget.DrawerLayout>
`

**Comment by JakeWharton** [comment]
Butter Knife just calls `findViewById` so if there's an orientation change you're inflating a new XML tree and you need to re-bind your objects and Butter Knife is just trying to call `findViewById`. My guess would be the the fragment is re-creating its view in a detached hierarchy before the parent activity XML is set, but I'm really not sure. What I can say with confidence, however, is that there's nothing special going on in this library that's causing the problem.
