### ISSUE TITLE
cannot work with Lambda of Java8

### ISSUE THREAD

**Issue by Hhh3S** [JakeWharton/butterknife#815]
### if  I add
jackOptions{
            enabled true
}
### and
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}
### to my app's builed.gradle , then will cause NullPointException
# why?
我蹩脚的英语....

**Comment by edsky** [comment]
我用java8就没有问题,但是遇上了另外的一个[问题](https://github.com/JakeWharton/butterknife/issues/818)  
你是一直有问题么?我是**修改了下文件使其能被编译**,这样才会生成代码.

然后,我还发现一个问题就是开启了java8后会莫名其妙出现编码问题,改一下又好了(ansi-gbk)。

**Comment by JakeWharton** [comment]
This is a problem of the Jack compiler and not Butter Knife. It's likely that Jack doesn't support all (or any) annotation processors currently and so Butter Knife never runs as part of the build.
