### ISSUE TITLE
Is it possible to add proxy for @OnClick?

### ISSUE THREAD

**Issue by Muyangmin** [JakeWharton/butterknife#816]
I have an app using butterknife `8.4.0` and most click events were bind by @OnClick annotation. Now I want to add **a global feature for all click events**, such as a sound, or a vibrate/haptic feedback. A proxy class for `DebouncingOnClickListener` seems to be a solution, but I didn't find such API in library. Is that available now? 

Thanks.

**Comment by JakeWharton** [comment]
No, not without forking the library. Once #497 is added you'll be able to create your own annotations that delegate to any class you want.
