### ISSUE TITLE
Sometimes null-pointer exception, sometimes not

### ISSUE THREAD

**Issue by edsky** [JakeWharton/butterknife#818]
I found that if the file isn't change,that butterknife also not generate the binding code.so its can't found the binding.like this:
`Looking up binding for *.*.ListViewAdapter$ViewHolder`
`Not found. Trying superclass java.lang.Object`

maybe this issues is only on me.

In my solution:
- force to change the file contains binding code, its so .. not good.
- Build > Clean Project  ,it's more trouble
- maybe change the compile options,but I don't know how to do.

Compiler Environment
- java 8 is on
- rxbinding is on
- rxandroid is on
- butterknife is on

Test only one file change ,and another(use ViewHolder) not.
That's all.

**Comment by JakeWharton** [comment]
Are you using instant run?

**Comment by yamabu** [comment]
Same to me.
Only jack and java8 is on.
No instant run.

**Comment by xanscale** [comment]
jack hate annotation :D

**Comment by edsky** [comment]
as your said,I test it in **java8 off**,
**all right**.
