### ISSUE TITLE
@Bindview is not applicable to type 'TextInputLayout'

### ISSUE THREAD

**Issue by omamapk** [JakeWharton/butterknife#819]
Hi,

I have sync these two dependencies in my gradle file:
` compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'`

Does this version support binding material design components?

**Comment by JakeWharton** [comment]
Yes. This works fine for me. Can you provide a sample that demonstrates the problem?

**Comment by omamapk** [comment]
it just worked now, don't know why it was a issue before.
