### ISSUE TITLE
android-apt:1.8 unable to sync behind proxy network

### ISSUE THREAD

**Issue by sandeeptengale** [JakeWharton/butterknife#821]
I am trying to use 
`com.neenbedankt.gradle.plugins:android-apt:1.8` for butterknief, but android-apt:1.8 is not getting sync with my project. But android-apt:1.7 is working fine for me.

I am using `com.android.tools.build:gradle:2.2.2` which is latest I guess. Please let me know why 1.8 of android-apt is not working for me..

**Comment by sandeeptengale** [comment]
Sorry its my proxy related issue got resolved, will close the ticket

**Comment by JakeWharton** [comment]
You no longer need to use that plugin with the latest Android Gradle
plugin. See the README.
