### ISSUE TITLE
R2 can't be found , are there any solution for this issue

### ISSUE THREAD

**Issue by ZhouKanZ** [JakeWharton/butterknife#822]
ButterKnife version : 8.4.0
 Ev : Window 10
 As : 2.1.2

Frist i use ButterKnife in main project there aren't any problem , then I want make this project as a moudle , Unfortunately all bindview(R.id.xx) occurred  "元素值必须为常量表达式" --'means elements must be constant expression', I have try to use R2 replace R , R2 cann't be found . 

Moudle  Build.gradle :
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'

Project build.gradle : 
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

are there any solution for this.

**Comment by Thewhitelight** [comment]
你好 你解决这个问题了吗 
我的问题是 R2可以生成 但是用的时候控件NPE

**Comment by ZhouKanZ** [comment]
我解决了，但是还会遇到新的问题，NPE不懂什么意思，但最好别再库里面用UI，我最后这些问题全都解决了，库是不能引用主工程的任何东西的，最后我还是放弃了库的形式，直接导入的，不好意思，这些天一直没用自己的电脑，没看到

**Comment by Joycechidi** [comment]
I still have issues with my code after following the steps. Please look through and see what I am doing wrong.

MAIN ACTIVITY (I get the error message "cannot resolve symbol R2")
public class MainActivity extends AppCompatActivity {
    public static final String TAG = MainActivity.class.getSimpleName();

    private CurrentWeather CurrentWeather;
    
    @BindView(R2.id.timeLabel) TextView TimeLabel;
    @BindView(R2.id.temperatureLabel) TextView TemperatureLabel;
    @BindView(R2.id.humidityValue) TextView HumidityValue;
    @BindView(R2.id.precipValue) TextView PrecipValue;
    @BindView(R2.id.summaryLabel) TextView SummaryLabel;
    @BindView(R2.id.iconImageView) TextView iconImageView;


    private GoogleApiClient client2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

**XML FILE**
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="joycechidiadi.com.weatherappy.MainActivity"
    android:background="#ffbb33">

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:srcCompat="@drawable/degree"
        android:layout_alignTop="@+id/temperatureLabel"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_marginRight="61dp"
        android:layout_marginEnd="61dp"
        android:layout_marginTop="25dp"
        android:id="@+id/degreeimageView"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:inputType="textPersonName"
        android:text="   100"
        android:ems="10"
        android:id="@+id/temperatureLabel"
        android:textColor="@android:color/white"
        android:textSize="100sp"
        android:layout_centerVertical="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:inputType="textPersonName"
        android:text="At 5:00PM, it will be"
        android:ems="10"
        android:layout_above="@+id/degreeimageView"
        android:layout_centerHorizontal="true"
        android:id="@+id/timeLabel"
        android:textColor="#80ffffff"
        android:textSize="18sp"/>

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:srcCompat="@drawable/cloudy_night"
        android:layout_alignBottom="@+id/locationLabel"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:id="@+id/iconImageView"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:inputType="textPersonName"
        android:text="   Calgary AB, Canada"
        android:ems="10"
        android:id="@+id/locationLabel"
        android:textColor="@android:color/white"
        android:textSize="24sp"
        android:layout_marginBottom="77dp"
        android:layout_above="@+id/timeLabel"
        android:layout_toRightOf="@+id/iconImageView"
        android:layout_toEndOf="@+id/iconImageView"/>

    <LinearLayout
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/temperatureLabel"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_marginTop="10dp">

        <LinearLayout
            android:orientation="vertical"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_toRightOf="@+id/humidityLabel">

            <TextView
                android:text="HUMIDITY"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/humidityLabel"
                android:textColor="#80ffffff"/>

            <TextView
                android:text="0.88"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/humidityValue"
                android:textColor="@android:color/white"
                android:textSize="24sp"/>
        </LinearLayout>
    </LinearLayout>

    <TextView
        android:text="RAIN/SNOW?"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/temperatureLabel"
        android:layout_toEndOf="@+id/locationLabel"
        android:id="@+id/precipLabel"
        android:layout_alignWithParentIfMissing="false"
        android:textColor="#80ffffff"
        android:layout_alignBottom="@+id/linearLayout3"
        android:textSize="10sp"
        android:layout_alignLeft="@+id/precipValue"
        android:layout_alignStart="@+id/precipValue"
        android:layout_toRightOf="@+id/locationLabel"/>

    <TextView
        android:text="100%"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/precipLabel"
        android:id="@+id/precipValue"
        android:textColor="@android:color/white"
        android:textSize="24sp"
        android:gravity="center_horizontal|fill_horizontal"
        android:layout_toRightOf="@+id/timeLabel"
        android:layout_toEndOf="@+id/timeLabel"/>

    <TextView
        android:text="Rainy with a chance of hailstone"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="77dp"
        android:id="@+id/summaryLabel"
        android:textSize="18sp"
        android:textColor="@android:color/white"
        android:gravity="center_horizontal"/>

</RelativeLayout>


**BUILD.GRADLE (APP)**
apply plugin: 'com.android.application'
apply plugin: 'com.jakewharton.butterknife'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "joycechidiadi.com.weatherappy"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'


    testCompile 'junit:junit:4.12'
    compile 'com.google.android.gms:play-services-appindexing:8.4.0'
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
}

**Comment by ZhouKanZ** [comment]
Sorry I almost ignore the notification,If I dont forget this issue, you should change the 'apply plugin: 'com.android.application' to 'apply plugin: 'com.android.library' in file BUILD.GRADLE (APP)  , then R2 can be resolved . Hope  it work for you.

**Comment by Joycechidi** [comment]
Hi ZhouKanZ,

I have made the changes you suggested, rather I get this error message;
Error:Library projects cannot set applicationId. applicationId is set to 'joycechidiadi.com.weatherappy' in default config.

Here is my Gradle buildscript:
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "joycechidiadi.com.weatherappy"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
    testCompile 'junit:junit:4.12'
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
}

**Comment by ZhouKanZ** [comment]
remove this line which contain 'applicationId',I guess you are fresh developer of android . >.<  try it again ! You'd better read log carefully.

**Comment by Joycechidi** [comment]
I added the 'applicationId' again then copied and pasted this build script:

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
}

The R2 was not working and I changed back to R. Voila! It worked.


Thank you so much.

**Comment by wirteEable** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.lds.chat.t01/cn.ld.oamodule.MainActivity}: java.lang.IllegalStateException: Required view 'title_text' with ID 2131624792 for field 'titleText' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.   

Moudle Build.gradle :
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife' 
apply plugin: 'android-apt'

Project build.gradle :
buildscript {
repositories {
jcenter()
mavenCentral()
}
dependencies {
classpath 'com.android.tools.build:gradle:2.1.0'
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
classpath 'com.jakewharton:butterknife-gradle-plugin:8.5.1'
}
}

what can i do?

**Comment by JakeWharton** [comment]
Add a view with that ID or remove the field that wants to bind to it.

**Comment by Joycechidi** [comment]
Thank you. I have solved the issue.

**Comment by ZhouKanZ** [comment]
It's my pealsure that  can help you , Sorry I'm so late to reply. Sadly github don't have function of sending emoj  ><!

**Comment by Joycechidi** [comment]
Thank you for the help. I appreciate.

**Comment by Jafar396** [comment]
@Joycechidi @ZhouKanZ @JakeWharton 
I try to merge two project and when I convert the second project to library module the @BindView(R.id.xxx) in library is tell me (attribute value must be a constant) and when I research I add in my library module:
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
and:
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
and:
implementation 'com.jakewharton:butterknife:10.2.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.1'
and I add in my project:
dependencies {
classpath 'com.android.tools.build:gradle:3.6.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.1'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
my gradle is 5.6.4
but when I replace R to R2 , The R2 is not found
please help me

**Comment by ritwikshanker** [comment]
> @Joycechidi @ZhouKanZ @JakeWharton
> I try to merge two project and when I convert the second project to library module the @BindView(R.id.xxx) in library is tell me (attribute value must be a constant) and when I research I add in my library module:
> apply plugin: 'com.android.library'
> apply plugin: 'com.jakewharton.butterknife'
> and:
> compileOptions {
> sourceCompatibility JavaVersion.VERSION_1_8
> targetCompatibility JavaVersion.VERSION_1_8
> }
> and:
> implementation 'com.jakewharton:butterknife:10.2.1'
> annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.1'
> and I add in my project:
> dependencies {
> classpath 'com.android.tools.build:gradle:3.6.1'
> classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.1'
> 
> ```
> // NOTE: Do not place your application dependencies here; they belong
> // in the individual module build.gradle files
> ```
> 
> }
> my gradle is 5.6.4
> but when I replace R to R2 , The R2 is not found
> please help me

Where you able to fix this @Jafar396 ?

**Comment by aiquantong** [comment]
Where you able to fix this @Jafar396 ?
