### ISSUE TITLE
BindColor annotation returns 0

### ISSUE THREAD

**Issue by lawloretienne** [JakeWharton/butterknife#823]
I tried to set up an annotation like 
`@BindColor(R.color.grey_300) int grey300;`
but the value of grey300 is 0 after the 
`ButterKnife.bind(this);`
statement.

**Comment by JakeWharton** [comment]
What does the generated code look like?

**Comment by lawloretienne** [comment]
So I also have @BindView annotation in my MainActivity class, and when i look at the MainActivity_ViewBinding.java and MainActivity$$ViewBinder.java generated code i can see the views in here but not any color resources.

**Comment by JakeWharton** [comment]
Are you using instant run?

**Comment by lawloretienne** [comment]
I turned off Instant Run because it has caused all sorts of problems for me.  So no i don't use instant run.

**Comment by JakeWharton** [comment]
Does it happen on clean builds?

**Comment by JakeWharton** [comment]
Are you using Jack?

**Comment by lawloretienne** [comment]
It happens on clean builds, and no im not using Jack.

**Comment by lawloretienne** [comment]
Here are my proguard rules for butterknife

#ButterKnife
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}

**Comment by lawloretienne** [comment]
So I tried changing from
annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
to
apt 'com.jakewharton:butterknife-compiler:8.4.0'

and now I can see the color resources in the generated code in MainActivity_ViewBinding.java

So then it all starts to work.  I am just curious why this is the case.

**Comment by JakeWharton** [comment]
You're either using an old version of the Android Gradle plugin (update to
2.2.3) or you're using an old version of Realm's Gradle plugin (update to
whatever latest is).
