### ISSUE TITLE
D/ButterKnife: MISS: Reached framework class. Abandoning search.

### ISSUE THREAD

**Issue by marcoalmeidap** [JakeWharton/butterknife#826]
Hi, 

Im trying to use Butter Knife, but I got the following errors:

D/ButterKnife: Looking up binding for *.*.*.MainActivity
D/ButterKnife: Not found. Trying superclass android.support.v7.app.AppCompatActivity
D/ButterKnife: MISS: Reached framework class. Abandoning search.

Can you help me pls ?

**Comment by JakeWharton** [comment]
You haven't provided any information and this isn't a support forum. Is your build configured per the README? What does the generated code look like? What versions are you using of the library, of Gradle, of the Android Gradle plugin?
