### ISSUE TITLE
No work with listview headview and footview bind

### ISSUE THREAD

**Issue by bigmanLau** [JakeWharton/butterknife#827]
hi,jake,I have  a problem list below.  I dont know how to bind a  multiView when listview have  a  footview and headview ,and i want  setOnclick to some of the view that from footview or headview.Can u  show  me a Way to solve?
Code:
 View rootView = inflater.inflate(R.layout.fragment_fabao_detail_with_fabao_nav, null);
        ButterKnife.bind(this, rootView);
        footerView = inflater.inflate(
                R.layout.fragment_fabao_detail_with_fabao_footerview, swipeTarget,
                false);

        headView = inflater.inflate(
                R.layout.fragment_fabao_detail_with_fabao_headview, null);
        ButterKnife.bind(this, headView);
Cause:
 java.lang.IllegalStateException: Required view 'iv_back' with ID 2131493026 for field 'ivBack' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation,

**Comment by bigmanLau** [comment]
i have solve this kind of problem ,solve method from #147 
  static class HeadViewHolder {
        @BindView(R.id.tv_project_name)
        TextView tvProjectName;
       
        HeadViewHolder(View view) {
            ButterKnife.bind(this, view);
        }
}
just user like use in a  adapter

**Comment by JakeWharton** [comment]
Using a view holder object specific to the layout you are inflating is the correct approach.
