### ISSUE TITLE
NullPointerException with Jack Optons enabled

### ISSUE THREAD

**Issue by wlTrunks** [JakeWharton/butterknife#830]
Sometime after compilation binding return NullPointerException on Recyclerview Viewholder
gradle
 jackOptions {
            enabled true
        }
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
 compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'

`public class ItemViewHolder extends RecyclerView.ViewHolder {

    @BindView(R.id.title)
    TextView title;
    @BindView(R.id.image)
    ImageView image;

    public ItemViewHolder(View view) {
        super(view);
        ButterKnife.bind(this, view);
    }
}`

 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                     at ru.altarix.nature.gui.mainwindow.viewdata.MainListAdapter.onBindViewHolder(MainListAdapter.java:35)
                                                                     at ru.altarix.nature.gui.mainwindow.viewdata.MainListAdapter.onBindViewHolder(MainListAdapter.java:32)

`    @Override
    public void onBindViewHolder(ItemViewHolder customViewHolder, int i) {
        MainListItem item = itemList.get(i);
        customViewHolder.title.setText(item.getTitle());  //here nullpointer
        customViewHolder.image.setImageResource(item.getRes());
        customViewHolder.image.setOnClickListener(view -> mListener.click(item.getId()));
    }
`

**Comment by xanscale** [comment]
jack hate annotationProcessor :)

**Comment by JakeWharton** [comment]
Jack's annotation processor support is the problem here, not Butter Knife.
