### ISSUE TITLE
Bind String resourse

### ISSUE THREAD

**Issue by andromedcodes** [JakeWharton/butterknife#833]
Android ActionBarDrawerToggle require 2 parameters in the end which are type int and should be a string resource from R.string resource file as described on the ActionBarDrawerToggle constructor.

`public ActionBarDrawerToggle(Activity activity, DrawerLayout drawerLayout,
            Toolbar toolbar, @StringRes int openDrawerContentDescRes,
            @StringRes int closeDrawerContentDescRes)`

However when using butter knife, i used @BindString() annotation but the debugger is rising an issue : 

> Error:(31, 65) error: @BindString field type must be 'String'. (com.crispbrain.goestream.ui.activities.HomeActivity.navBarOpen)

I also tried with @BindInt() annotation but Butter knife complains that the resource should be of type int.

please advise.
thnx

**Comment by JakeWharton** [comment]
Just pass the R.string constants directly to that method.

**Comment by andromedcodes** [comment]
Thanks for the reply. That's what i did actually but it would be great if
butter knife would support this feature in the next releases.
Best luck.

**Comment by andromedcodes** [comment]
Sure. Thanks for the sharp clarification.
All best luck.
