### ISSUE TITLE
Could not find method annotationProcessor() for arguments [com.jakewharton:butterknife-compiler:8.4.0] 

### ISSUE THREAD

**Issue by isanwenyu** [JakeWharton/butterknife#834]
I upgrade the version to 8.4.0 like this:

```
dependencies {
  compile 'com.jakewharton:butterknife:8.4.0'
  annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}
```
```
Could not find method annotationProcessor() for arguments [com.jakewharton:butterknife-compiler:8.4.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
But I got the error as the above , what's the problem?

**Comment by JakeWharton** [comment]
Are you using version 2.2.0 or newer of the Android Gradle plugin?

**Comment by wuhuaqing** [comment]
I am satisfied with the same contingency issue  
           Error:Gradle DSL method not found: 'annotationProcessor()'

**Comment by isanwenyu** [comment]
It's my fault！
After upgraded the version of gradle plugin to 2.2.3, my project build successfully. Thks.
I check it out, 'annotationProcessor()' was added in  version 2.2.0 or newer of the Android Gradle plugin.

**Comment by JakeWharton** [comment]
Great. Thanks for replying.
