### ISSUE TITLE
how to use butterknife in the library and the app module at the same time

### ISSUE THREAD

**Issue by sicmu** [JakeWharton/butterknife#835]
When I use butterknife in the library and the app module at the same time, I got this problem.
-------------------------------------------------------------------
Project:Module -> Gradle
buildscript {
    repositories {
        //jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
}
allprojects {
    repositories {
        mavenCentral()
    }
}

-----------------------------------
the library -> gradle
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.fresco:fresco:0.12.0'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}
------------------------------------------------
app module -> Gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {
        applicationId "com.sicmu.lovefate"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 3
        versionName "1.0.2"

    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    repositories {
        flatDir {
            dirs 'libs'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/upload_1.1.3.300_4200.jar')
    compile files('libs/wup-1.0.0-SNAPSHOT.jar')
    compile files('libs/MobTools.jar')
    compile files('libs/MobCommons.jar')
    compile name: 'SMSSDK-2.0.1', ext: 'aar'
    compile project(':im')
    compile 'com.tencent.bugly:crashreport_upgrade:latest.release'
    compile 'com.tencent.bugly:nativecrashreport:latest.release'
    compile files('libs/AMap_Location_V3.2.0_20161205.jar')
    compile files('libs/AMap_Search_V3.6.1_20161122.jar')
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}
--------------------------------------------------------------
in the library, i define a class:
public abstract class BaseFragment extends Fragment {
    private Unbinder unbinder;

    /**
     * 主界面容器
     */
    private ViewGroup mLayoutContent;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View layout = inflater.inflate(R.layout.fragment_layout, container, false);
        mLayoutContent = (ViewGroup) layout.findViewById(R.id.layout_content);
        int res = obtainCreateView();
        if (res != -1) {
            inflater.inflate(res, mLayoutContent, true);
        }
        ButterKnife.setDebug(true);
        unbinder = ButterKnife.bind(this, layout);
        componentInit(layout);
        return layout;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        unbinder.unbind();
    }

    /**
     * 获取布局资源
     *
     * @return
     */
    protected int obtainCreateView() {
        return -1;
    }
}
-------------------------------------------
and in the library, i define another class
public class BaseListFragment extends BaseFragment implements
        SwipeRefreshLayout.OnRefreshListener,
        BaseAdapter.OnItemClickListener,
        BaseAdapter.OnItemLongClickListener {

    /**
     * 下拉刷新组件
     */
    @BindView(R2.id.swipe)
    protected SwipeRefreshLayout swipe;

    /**
     * 列表组件
     */
    @BindView(R2.id.list)
    protected RecyclerView recycler;

    /**
     * 设置Fragment的布局
     *
     * @return 返回布局id
     */
    protected int obtainCreateView() {
        return R.layout.fragment_base_list_layout;
    }

    @Override
    public void componentInit(View view) {
        super.componentInit(view);
        // 设置布局管理器
        recycler.setLayoutManager(obtainLayoutManager());
        // 设置divider
        RecyclerView.ItemDecoration decoration = obtainDecoration();
        if (decoration != null) {
            recycler.addItemDecoration(decoration);
        }
        // 设置适配器
        mAdapter = obtainAdapter();
        recycler.setAdapter(mAdapter);
    }
.....
}
---------------------------------
and the problem is : 
when i define a class HomeFragment in the app model, and extends BaseListFragment,
recycler defined in BaseFragment is null ,and throw the NullPointerException.

**Comment by JakeWharton** [comment]
This is not a support forum, and you posted the exact same thing in an existing issue. If you have a question please use StackOverflow with the 'butterknife' tag. If you think you have a bug then please provide a sample project which _fully_ and clearly reproduces the issue.

**Comment by sicmu** [comment]
When i modify the app module gradle file, annotate the butterknife defines:
    //compile 'com.jakewharton:butterknife:8.4.0'
    //annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'

the problem above can be resolved. but i find another problem, butterknife can not be used in the app module.

the modify app module gradle file:
------------------------------------------- 
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {
        applicationId "com.sicmu.lovefate"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 3
        versionName "1.0.2"


    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    repositories {
        flatDir {
            dirs 'libs'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/upload_1.1.3.300_4200.jar')
    compile files('libs/wup-1.0.0-SNAPSHOT.jar')
    compile files('libs/MobTools.jar')
    compile files('libs/MobCommons.jar')
    compile name: 'SMSSDK-2.0.1', ext: 'aar'
    compile project(':im')
    compile 'com.tencent.bugly:crashreport_upgrade:latest.release'
    compile 'com.tencent.bugly:nativecrashreport:latest.release'
    compile files('libs/AMap_Location_V3.2.0_20161205.jar')
    compile files('libs/AMap_Search_V3.6.1_20161122.jar')
    //compile 'com.jakewharton:butterknife:8.4.0'
    //annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}

**Comment by sicmu** [comment]
@JakeWharton OK.
