### ISSUE TITLE
Butterknife in BaseActivty 

### ISSUE THREAD

**Issue by zy1301529626** [JakeWharton/butterknife#836]
public class BaseActivity extends ActionBarActivity{
 @Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		super.onCreate(savedInstanceState);
		App.getInstance().mActivityStack.addActivity(this);
		initContentView();
		ButterKnife.bind(this);
		attachUI();
		initView();
		initEvents();
	}
}  
-----------------------------------------------------------------------------------------------------
public class BaseRegisterActivity extends BaseActivity:

public abstract class BaseRegisterActivity extends BaseActivity{
	
	@Bind(R.id.edit_user_phone)
	protected EditText editUserPhone;
}
---------------------------------------------------------------------------------------------------
public class ShiMingRegisterActivity extends BaseRegisterActivity implements ShiMingRegisterContract.View {

	
	@Bind(R.id.edit_user_idcard)
	EditText editUserIdCard;
	private ShiMingRegisterContract.Presenter mRegisterPresenter;

     private void commitRegister() {
		// TODO Auto-generated method stub
		String phoneNumber = editUserPhone.getText().toString();
    }
}

when i click a button ,  log nullpointException in the method commitRegister(), editUserPhone is null

**Comment by JakeWharton** [comment]
There's not enough information here to figure out the problem. Can you provide a minimally reproducing sample?

**Comment by zy1301529626** [comment]
* BaseActivity

		public abstract class BaseActivity extends ActionBarActivity {
	
		@Override
		protected void onCreate(Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		super.onCreate(savedInstanceState);
		setContentView(getLayout());
		ButterKnife.bind(this);
		}
	
	
		public  abstract int getLayout();
		}

* BaseMainActivity

		public abstract class BaseMainActivity extends BaseActivity {
	
		@Bind(R.id.edit_query)
		protected EditText editQuery;
	
		}

* MainActivity

  		public class MainActivity extends BaseMainActivity {
	
		private static final String TAG = "MainActivity";

		@Override
		public int getLayout() {
		// TODO Auto-generated method stub
		return R.layout.activity_main;
		}
	
		@OnClick(R.id.bt_test)
		void onBtclick(){
		Log.i(TAG, "editQuery="+editQuery.getText().toString());
		}	
		}


* include_bt.xml

		<?xml version="1.0" encoding="utf-8"?>
		<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    	android:layout_width="match_parent"
    	android:layout_height="wrap_content"
    	android:orientation="vertical" >

    
    	<EditText
        android:id="@+id/edit_query"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
    

		</LinearLayout>


* activity_main

		<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    		xmlns:tools="http://schemas.android.com/tools"
    		android:layout_width="match_parent"
    		android:layout_height="match_parent"
    		android:orientation="vertical"
    		tools:context="com.example.butterknifer.MainActivity" >

    		<include layout="@layout/include_bt"/>
    
    		<Button
        		android:id="@+id/bt_test"
        		android:layout_width="match_parent"
        		android:layout_height="wrap_content"
        		android:text="test" />

		</LinearLayout>


> include_bt.xml is a common xml ,so i want inject editQuery this view in the BaseMainActivity. when i click 
  bt_test ,the editQuery is null in the MainActivity

**Comment by zy1301529626** [comment]
you get editQuery is not null from BaseMainActivity , the ButterKnife version is v7.0.0 

why  i get editQuery is null  in the ButterKnife  v7.0.1

**Comment by danielw93** [comment]
Tried with 7.0.1 as well, still can't reproduce unfortunately.
Do you have a stack trace? 
Or some more code from the 2 actual Activities that seem to cause the problem?

**Comment by zy1301529626** [comment]
if do not have BaseMainActivity , this is useful

**Comment by zy1301529626** [comment]
can you give me you test project?
you can share you project in the github

**Comment by zy1301529626** [comment]
i use butterknifr v8.4.0 , this is useful . why not useful int the butterknife v7.0.1

**Comment by danielw93** [comment]
I have posted a test repository here: https://github.com/danielw93/butterknife-issue-836
It uses the exact code you posted above, only alternating the butterknife versions.

There are 3 branches: master uses butterknife v.8.4.0, and a branch for 7.0.0 and 7.0.1 each.
Again I can not reproduce your problem and I don't seem to completely understand your responses.

Just to clarify, could you answer the following points?

1. version 8.4.0 works for you in your production code (yes/no)?
2. version 8.4.0 works for you in my example code (yes/no)?
3. version 7.0.1 works for you in your production code (yes/no)?
4. version 7.0.1 works for you in my example code (yes/no)?
5. version 7.0.0 works for you in your example code (yes/no)?
6. version 7.0.0 works for you in my example code (yes/no)?

I still have the suspicion that your problem lies in your production code and can not be reliably reproduced by the minimal example you have posted here.

Again, maybe a stack trace from the error happening in your code or some more actual code would help. Is your code on GitHub?

**Comment by zy1301529626** [comment]
thanks

**Comment by danielw93** [comment]
@zy1301529626 sooo...was this helpful? Have you resolved the problem? Or is this still an issue for you?
Otherwise @JakeWharton this can probably be closed

**Comment by JakeWharton** [comment]
Thanks!
