### ISSUE TITLE
NullPointException with java8???

### ISSUE THREAD

**Issue by ClareChen** [JakeWharton/butterknife#841]
I found that when using java8 with jack compiler(InstantRun is off), sometimes when 'rerun' app, NullPointException will occur(not every time).Then 'clean project' or 'rebuild project' can fix that.
Stop using java8 can fix that too.

My gradle file:

`apply plugin: 'com.android.application'

android {
  compileSdkVersion 25
  buildToolsVersion "25.0.1"
  defaultConfig {
    applicationId ""
    minSdkVersion 19
    targetSdkVersion 25
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    jackOptions {
      enabled true
    }
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  compile fileTree(include: ['*.jar'], dir: 'libs')
//...
  // ButterKnife
  compile 'com.jakewharton:butterknife:8.4.0'
  annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
//...
}
`

**Comment by JakeWharton** [comment]
Sounds like it might be a Jack bug then. Are the generated sources present when you get the NPE?

**Comment by ClareChen** [comment]
@JakeWharton No, when I got the NPE I didn't find the generated sources like 'xxActivity_ViewBind' class.
So, Jack's bad then?

**Comment by JakeWharton** [comment]
Yes. That indicates Jack isn't running the ButterKnife compiler when it
should have. You should report this to http://b.android.com/

**Comment by ClareChen** [comment]
Thanks.
#815 
#830

**Comment by ClareChen** [comment]
@JakeWharton With Gradle plugin 2.3.0-beta2 and Gradle Wrapper 3.3, it works well now.

**Comment by FlyMantou** [comment]
在Project的build.gradle中这样写：
 dependencies {
classpath 'com.jakewharton:butterknife-gradle-plugin:8.5.1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8' // 添加的部分
}

app的builder.gradle中这样写：
apply plugin: 'android-apt'
dependencies {
apt 'com.jakewharton:butterknife-compiler:8.5.1'
}
library中这样写：
apply plugin: 'com.jakewharton.butterknife'
dependencies {
 compile 'com.jakewharton:butterknife:8.5.1'
}

另外注意：使用retrolambda的时候要引用三方库 ，不要开启jack
以上，我的空指针问题就是这样解决的
