### ISSUE TITLE
Bug in Butterknife 8.4.0 R2 id is not equals with xml write id in Library

### ISSUE THREAD

**Issue by MrSimpleX** [JakeWharton/butterknife#844]
Hello,thanks write this
I think i find a Bug in Butterknife 8.4.0,in my project, i use it both in project and Library
in Library, when i user like this:
```java
@OnClick({R2.id.tv_lai_home, R2.id.tv_lai_same})
	public void onClick(View view) {
		switch (view.getId()) {
			case R2.id.tv_lai_home:
				Routers.open(ModuleActivity.this,"aidaiRouter://base_login");
				break;
			case R2.id.tv_lai_same:
				Routers.open(ModuleActivity.this,"aidaiRouter://base_login");
				break;
		}
	}
}
```
i click id is tv_lai_home in window,the code
`Routers.open(ModuleActivity.this,"aidaiRouter://base_login");`
is not run,i debug and find `view.getId()` is not equals with `R2.id.tv_lai_home`, So i am confused

Sorry about my poor english

**Comment by JakeWharton** [comment]
You need to use `R.id.*` for the runtime code. Only use `R2` in annotations.

**Comment by MrSimpleX** [comment]
Ugh..I know,thank you

**Comment by duongnv1996** [comment]
R not work for me. I have changed from R2 - > R in switch case . Then AS build log that : 

> error: constant expression required

**Comment by MrSimpleX** [comment]
you may try **Clean** or **reBuild**

**Comment by duongnv1996** [comment]
Clean or rebuild not work for me. Thank sir

**Comment by dhaslkfha** [comment]
> Clean or rebuild not work for me. Thank sir

change switch to if else.

**Comment by EesiLife** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法回复您的邮件。我将尽快给您回复。
