### ISSUE TITLE
DebouncingOnClickListener Quick click issues

### ISSUE THREAD

**Issue by Ahuangshang** [JakeWharton/butterknife#845]
DebouncingOnClickListener clss have a method onClick, in this method you had code 
"v.post(ENABLE_AGAIN);",why don't used "  v.postDelayed(ENABLE_AGAIN, 500);"
this can solve the quick click issues. I wan't to change it ,but how can I do?

**Comment by JakeWharton** [comment]
Because it only disables clicks for a single frame.

**Comment by Ahuangshang** [comment]
If I wan't to do that, how can I do? I can't change the code.

**Comment by JakeWharton** [comment]
There is currently no way for custom behavior.
