### ISSUE TITLE
Could not find class 'butterknife.ButterKnife$1', referenced from method butterknife.ButterKnife.<clinit>

### ISSUE THREAD

**Issue by themass** [JakeWharton/butterknife#846]
error  at  android 4.x ,but  ok at 5.x and 6.x

Could not find class 'butterknife.ButterKnife$1', referenced from method butterknife.ButterKnife.<clinit>
Could not find class 'butterknife.ButterKnife$ViewBinder', referenced from method butterknife.ButterKnife.findViewBinderForClass

my  environment

butterknife 7.0.1
ext.global_compileSdkVersion = 23
ext.global_buildToolsVersion = "22.0.1"
ext.global_minSdkVersion = 15
ext.global_targetSdkVersion = 22
gradle 2.10  and  gradle plugin 2.0.0

**Comment by JakeWharton** [comment]
Sounds like you're using ProGuard or something that is messing with the classes. This isn't a problem with the Butter Knife library, though.
