### ISSUE TITLE
plugin 'com.jakewharton.butterknife' causes gradle's processDebugResources to fail on Lexical error

### ISSUE THREAD

**Issue by aziza4** [JakeWharton/butterknife#848]
Hi,

I worked and enjoyed butterknife very much, until now that I need to convert my app to library.
Following jake's instructions on github, I had to use butterknife plugin. However this plugin prevents my library to compile with the following error:

        Error:Execution failed for task ':mfcpdb:processDebugResources'.
        > Lexical error at line 4604, column 27.  Encountered: "\u05f3" (1523), after : ""

for 2 days I've googled to find a solution to this with no success. Sadly, i had to go over all my code and remove butterknife allover.

Can anyone help me with this?

Thanks, Yossi.

[A] system info:
===============
 - Windows 10 64 bit
 - Android studio 2.2.3
 - Java version 1.8.73

[B] my build .gradle (project):
=================

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

subprojects {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

[C] my build.gradle (library):
==================

apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'android-apt'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    dexOptions {
        maxProcessCount 2
        javaMaxHeapSize "2g"
    }
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 3
        versionName "3.2"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.9.3@aar') {
        transitive = true
    }
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:design:25.1.0'
    compile 'com.android.support:recyclerview-v7:25.1.0'
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.android.support:cardview-v7:25.1.0'

    compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.google.firebase:firebase-crash:10.0.1'
    compile 'com.google.firebase:firebase-messaging:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-places:10.0.1'
    compile 'com.google.code.gson:gson:2.4'

    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2'

    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'

    compile 'joda-time:joda-time:2.9.4'
    compile 'com.fatboyindustrial.gson-jodatime-serialisers:gson-jodatime-serialisers:1.3.0'

    compile 'com.makeramen:roundedimageview:2.2.1'

    compile 'com.github.hotchemi:permissionsdispatcher:2.3.1'
    apt 'com.github.hotchemi:permissionsdispatcher-processor:2.3.1'

    compile 'com.jaredrummler:android-device-names:1.1.2'
}

apply plugin: 'com.google.gms.google-services'

**Comment by TheNattyDread** [comment]
Did you find a solution? Suddenly my app is unusable and I've narrowed it down to Butterknife. I'm getting logs related to GMS leaking SQL connections but I'm not sure they are related. I've removed Butterknife on a few activities and used it the old way and it's working. Maybe it's time to switch to view binding....

**Comment by aziza4** [comment]
Unfortunately no. I removed butterknife for the time being...
