### ISSUE TITLE
New experimental direct use of view binding class needs overloaded constructors

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/butterknife#849]
I like the idea of the new feature to call the constructor of the view binding directly, but the problem is that it requires passing in the view which makes it a pain to use.

The generated view binding for MyActivity should have an overloaded constructor to allow just passing the activity without the view as in:

```
  @UiThread
  public MyActivity_ViewBinding(final T target) {
    this(target, target.getWindow().getDecorView());
  }

```
So I can say:

    new MyActivity_ViewBinding<>(this);

instead of:

    new MyActivity_ViewBinding<>(this, getWindow().getDecorView());

**Comment by JakeWharton** [comment]
I suppose this is doable only for subclasses of Activity and View.
