### ISSUE TITLE
R2.id.xxx and R.id.xxx is not equals

### ISSUE THREAD

**Issue by yjfnypeu** [JakeWharton/butterknife#850]
I used BF with the version of 7.0.1。And this time I have occurred a strange problem with R2.When I called ButterKnife.bind to bind view.BF find an incorrect view with R2.id.xxx. and also caused by class cast exception. so I had debugged and see. the generated value of R2.id.xxx was not equaled with source value R.id.xxx。is that because the plugin is not compact with versions of 7.x。or it's a bug?

**Comment by JakeWharton** [comment]
R2 does not exist in v7, only v8, and yes the values intentionally do not match. R2 is only for use inside annotations in library projects but all runtime code should still be using the normal R.
