### ISSUE TITLE
[Question] Where to define butterknife.minSdk?

### ISSUE THREAD

**Issue by PiotrWpl** [JakeWharton/butterknife#855]
Hello,

In Butterknife 8.5.0 we can find:

> Based on the minimum SDK version (as specified by butterknife.minSdk until http://b.android.com/187527 is released) the generated code now changes to use newer APIs when available.

But I can't find out where I should define this minSdk. Could You help me?

Thanks!

**Comment by ChristianBecker** [comment]
You can pass the `butterknife.minSdk` via [`javaCompileOptions.annotationProcessorOptions`](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.AnnotationProcessorOptions.html) DSL to the Annotation Processor:

```
android {
  …
  defaultConfig {
    …
    javaCompileOptions {
      annotationProcessorOptions {
        arguments = [ 'butterknife.minSdk' : '16' ]
      }
    }
  }
}
```

**Comment by PiotrWpl** [comment]
That was all I need. Thx!

**Comment by andromedcodes** [comment]
Is there any way to setup these args using a gradle task written in `Kotlin`? I have tried this but it doesn't seem to work:
```
variants.all { variant ->
            variant.javaCompileOptions.annotationProcessorOptions.apply {
                arguments.put("navigator.package.name", "my.package.name")
            }
        }
```
