### ISSUE TITLE
Resource binding in methods

### ISSUE THREAD

**Issue by UMFsimke** [JakeWharton/butterknife#858]
Although ButterKnife is great library, I face often with quite large number of variables for resources in my activities/fragments/adapter or custom views. Since I do want to have consistent code and I'm using quite a lot `@BindString`, `@BindColor`, `@BindDimen`, `@BindDrawable` annotations. But usually I don't need to have all those variables in memory all the time but only in specific cases I need to have their values. Since ButterKnife already supports `ButterKnife.findById(View, int)` has there been any thought of adding:
`ButterKnife.findStringById(int)`, `ButterKnife.findDrawableById(int)` etc? I believe it would be useful in order to save memory while not storing all pieces and to have more cleaner code.

**Comment by JakeWharton** [comment]
`findById` exists for abusing generics to automatically cast the `View` to the desired type. I don't see how your proposed methods would be any different than those that are already on the `Resources` object.
