### ISSUE TITLE
NullPointerException Due to possibly incorrect install instructions in Readme

### ISSUE THREAD

**Issue by vpotvin** [JakeWharton/butterknife#859]
Hello,

I was updating a project from version 7.0.0 to current version 8.5.1. I used instructions from the readme and the website which stated to add gradle dependences:

```
compile 'com.jakewharton:butterknife:8.5.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
```

Using this configuration butterknife did not properly locate and bind views, leading to nullpointerexceptions. I believe the code was not being generated.

I fixed the problem by changing the configuration to 

```
compile 'com.jakewharton:butterknife:8.5.1'
apt 'com.jakewharton:butterknife-compiler:8.5.1'
```
I am not sure why this happened but it may be useful to document the problem in the readme so that other users may find a solution. All similar solutions I was able to find are from slightly older versions so for a time I assumed they did not apply to this version.

**Comment by JakeWharton** [comment]
The information in the README is correct for the current versions of the Gradle plugin. The `apt` dependency scope comes from the 'android-apt' plugin which is now deprecated. It's likely that you're relying on something else that erroneously pulls it in (Realm?).

You can find details for direction migration here: https://bitbucket.org/hvisser/android-apt/wiki/Migration and there's a general blogpost about the topic here: http://www.littlerobots.nl/blog/Whats-next-for-android-apt/.
