### ISSUE TITLE
Can't find enclosing method void onClick when enabling Proguard

### ISSUE THREAD

**Issue by lawgimenez** [JakeWharton/butterknife#862]
Hi, I was trying to assembleRelease in Gradle and I get the following error 

`can't find enclosing method 'void onClick(android.content.DialogInterface,int)' in program class`

and we are using version **apt 'com.jakewharton:butterknife-compiler:8.4.0'**

**Comment by JakeWharton** [comment]
What makes you think this is related to Butter Knife?

**Comment by lawgimenez** [comment]
Because it is annotated in **@OnClick(R.id.button_delete)**

**Comment by lawgimenez** [comment]
Nevermind, it seems I need to rebuild project first before generating a release. Thanks! Apologize!
