### ISSUE TITLE
Use of private scope for variables and methods

### ISSUE THREAD

**Issue by nikolastankovic** [JakeWharton/butterknife#866]
Hi :) ... I just wonder if it's possible to use the private scope for variables and methods with Butterknife. 

I wanna do something like this:
``` java
@BindView(R.id.my_button)
private Button mMyButton;
```
Why I've to make this to public or default, which is protected, when I wanna use private? I wonder why this isn't supported.

Thanks for your answer in advance :) Cheers, Nikola

**Comment by serj-lotutovici** [comment]
The generated code, doesn't use reflection. That's why the fields and methods, should be accessible from the same package.

**Comment by nikolastankovic** [comment]
Yeah I thought that could be the reason. Is it possible to request this as feature?

**Comment by JakeWharton** [comment]
No. It is not possible to accomplish
