### ISSUE TITLE
Version 8.5.1 -> Mutiple Dex File exception for support library in Wear Project

### ISSUE THREAD

**Issue by ricard-v** [JakeWharton/butterknife#867]
Hi !

I recently updated my project to use the latest of the latest :
- SDK 25
- Build Tools 25.0.2

And for my Wear Project, my buid.gradle look like :

```
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.jakewharton:butterknife:8.5.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    compile 'com.google.android.support:wearable:2.0.0-beta2'
```

Gradle sync work, but compiling does not.
The error is as follow :

> Error:Execution failed for task ':wear:transformClassesWithDexForDebug'. com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

So I had to revert by to `8.4.0`.

How can I fix this issue ? Thanks !

**Comment by JakeWharton** [comment]
This occurs when you have two copies of the support library being bundled and is a build system issue, not a ButterKnife issue. You can run `./gradlew :app:dependencies` to see your dependency graph to make sure you are getting only one support library and also ensure that you don't have a jar of it in your `libs/` directory. I would also try a clean build if you haven't already done that.

**Comment by gyqGitHub** [comment]
Threre's a way to solve1
 compile ('com.jakewharton:butterknife:8.5.1'){
        exclude module: 'support-compat'
    }
