### ISSUE TITLE
can not bind a custom view(Butterknife8.4.0)

### ISSUE THREAD

**Issue by xuwab** [JakeWharton/butterknife#869]
**   I have a problems with the binding of my custom view that do not work but other codes work well when I upgrade it from 7.0.1 to 8.4.0.

Here is my similar codes:**
--------------------------------------------------------------------------------------------------
public class MyContainerView extends ViewPager {

	public MyContainerView(Context context) {
		init(context);
	}

	private void init(Context context){

		//...

		removeAllViews();

		View A = new View();
		new ViewHolderA(A);
		addView(A, 0);

	}

	class ViewHolderA {

		@BindView(R.id.bt_a) Button btA;

		public ViewHolderA(View view){
			ButterKnife.bind(MyContainerView.this, view);
		}

		@OnClick(R.id.bt_a) void onClick(){
			System.out.println("----- A ------");
		}
	}

}

--------------------------------------------------------------------------------------------
	

**         When I initialize the binding in init（）using “ButterKnife.bind(this)”,it cannot not work. I delete it and use "ButterKnife.bind(this,view);" in viewholder ,it also not work. So I bind in  viewholder using "ButterKnife.bind(A.this,view);". Then, the view A which i add can be displayed but the click event can not work.  
         When I click it ,it can not work but the widgets on the back fragment work. So，the view likes transparent that it is visible but not working.
	The problem is not found when i use the version of 7.0.1.**

**Comment by ygnessin** [comment]
Using `ButterKnife.bind(this, itemView);` works for me in a view holder, as shown below. You should be binding to the view holder, not to its container object.

```java
    class MyViewHolder extends ViewHolder {
        MyViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);
        }
    }
```

**Comment by xuwab** [comment]
Thank you for your attention to this problem.I had tried your method but it did't work ,so I binding to its container object. Then the view  was visible but the click event can not work.

**Comment by JakeWharton** [comment]
What @ygnessin said is correct. If you can provide a full failing example we can take a look. Otherwise your problem is that you're not binding to the right object.
