### ISSUE TITLE
Allow layout resources in R2

### ISSUE THREAD

**Issue by elihart** [JakeWharton/butterknife#871]
Currently the gradle plugin skips layout types when generating R2 (https://github.com/JakeWharton/butterknife/blob/master/butterknife-gradle-plugin/src/main/java/butterknife/plugin/FinalRClassBuilder.java#L28)

Butterknife does not use these, but I have a feature in [Epoxy](https://github.com/airbnb/epoxy) where a layout resource is a value in an annotation. I would love to support library projects, without having to duplicate the plugin just to add support for layout.

I know it's strange to request this from Butterknife, since it isn't related to the library, but the gradle plugin Butterknife provides is potentially useful to many other libraries. It could be its own generic library.

Would it be possible to have the plugin take parameters in our gradle files to specify which resource types it should allow?

@kageiit R2 actually does include layout files when building with Buck. I'm wondering if you did something different with buck to allow all resources?

**Comment by kageiit** [comment]
Buck has its own way of generating the R2 class. It does not rely on the gradle plugin, but it mimics closely.

It should be possible to add support for supported types as an option to the plugin's extension

**Comment by kageiit** [comment]
Alternatively, we can have the gradle plugin generate R2 entries for all resource types. I am in favor of this approach as `R2` is a throwaway class anyway and it is less confusing to use and configure based on different libraries' usecases. I have opened #872 to do the same.

@JakeWharton let me know your thoughts

**Comment by elihart** [comment]
Sounds great, thanks for putting up the change so fast. Looking forward to hearing Jake's thoughts.

**Comment by elihart** [comment]
@JakeWharton Have any time to chime in on this?
