### ISSUE TITLE
Generated singned apk occur DexException

### ISSUE THREAD

**Issue by EdisonLiao** [JakeWharton/butterknife#875]
my project's build gradle as follow:
`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.jakewharton:butterknife:8.5.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    testCompile 'junit:junit:4.12'
}`

and when I Generated singned apk occur DexException as follow:
`Error:Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;`

I just created a new project in AS,and add butternife dependency, I cannot fix it ........

**Comment by JakeWharton** [comment]
This is not an issue with Butter Knife but instead in your build configuration. You are somehow pulling in two versions of the support-v4 dependency. Check the output of `./gradlew :app:dependencies`.
