### ISSUE TITLE
Lint raise error when using @BindView with R instead of R2

### ISSUE THREAD

**Issue by vanniktech** [JakeWharton/butterknife#876]
Given I am in an Android app where I have the Gradle Plugin applied to use the generated R2 class, I would like to get warned by Lint when I'm using `@BindView(R.id.my_id)` as I should use R2 instead.

Usecase: Having an app that is using okbuck and hence will be compiled as a library.

What do you think?

**Comment by JakeWharton** [comment]
If it's disabled by default, then sure.

**Comment by vanniktech** [comment]
No longer interested in this since I've moved away from Buck / Library ButterKnife mode.
