### ISSUE TITLE
Butterknife 8.5.1 bind with view holder

### ISSUE THREAD

**Issue by elriczhan** [JakeWharton/butterknife#879]
Hi, 
    I have a question.
    Butterknife 8.5.1 we bind a view then return an Unbinder. in the RecyclerView, how do we unbind the ViewHolder?

**Comment by JakeWharton** [comment]
You don't need to. Only fragments need to in onDestroyView.

**Comment by timusus** [comment]
@JakeWharton are you able to elaborate on why this is unnecessary for ViewHolders? 

If not here, then perhaps on this [Stackoverflow Question](http://stackoverflow.com/questions/38015412/where-should-i-unbind-butterknife-8-x-x-in-a-viewholder/43656611#43656611)

**Comment by JakeWharton** [comment]
They don't outlive the associated view. A fragment does.

**Comment by timusus** [comment]
OK, gotcha. Thanks.

**Comment by yoavgray** [comment]
Is this the case for custom views as well? If I create a custom view that has views inside it, and I bind them in the constructor, do I not need to unbind them?
