### ISSUE TITLE
Can't use Kotlin's List for @BindViews

### ISSUE THREAD

**Issue by ZakTaccardi** [JakeWharton/butterknife#880]
```
@BindViews(
            R.id.keypadview_0,
            R.id.keypadview_1,
            R.id.keypadview_2,
            R.id.keypadview_3,
            R.id.keypadview_4,
            R.id.keypadview_5,
            R.id.keypadview_6,
            R.id.keypadview_7,
            R.id.keypadview_8,
            R.id.keypadview_9
    )
    lateinit var numberButtons: List<TextView>
```

Butterknife throws exception `@BindViews List or array type must extend from View or be an interface.` Workaround is to use kotlin's `MutableList` or `Array`."

This is trivial (especially since immutable array works), but it would be nice to support an immutable list in kotlin.

**Comment by grandstaish** [comment]
Could you try it with `lateinit var numberButtons: List<@JvmSuppressWildcards TextView>` and see if that works? My guess is that wildcards are the issue here as they can't be used for arrays or mutable lists.

**Comment by ZakTaccardi** [comment]
`List<@JvmSuppressWildcards TextView>` works!

**Comment by arekolek** [comment]
Just wondering, is `@BindViews(...) lateinit var foo: List<View>` better for some reason than `@BindViews(...) lateinit var foo: Array<View>`?

**Comment by JakeWharton** [comment]
No
