### ISSUE TITLE
Any problem with Using Old version ?

### ISSUE THREAD

**Issue by myinnos** [JakeWharton/butterknife#881]
In one of my Android project am using old version([butterknife-parent-7.0.1](https://github.com/JakeWharton/butterknife/releases/tag/butterknife-parent-7.0.1)) of Butter Knife  

But the latest version is [8.5.1](https://github.com/JakeWharton/butterknife/releases/tag/8.5.1), dint find any description in [releases](https://github.com/JakeWharton/butterknife/releases) to check differences/bugs between this two version

Where i have to check all the details of versions or let me know any issues with [this](https://github.com/JakeWharton/butterknife/releases/tag/butterknife-parent-7.0.1) old version ?

**Comment by JakeWharton** [comment]
The change log can be found here https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md which details the differences between those two versions.
