### ISSUE TITLE
Error:Execution failed for task ':mobile:compileDebugJavaWithJavac'. > java.lang.NoSuchMethodError: butterknife.internal.ListenerClass.remover()Ljava/lang/String;

### ISSUE THREAD

**Issue by ettleramesh** [JakeWharton/butterknife#882]
Error:Execution failed for task ':mobile:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: butterknife.internal.ListenerClass.remover()Ljava/lang/String;  what this i got i not possible to fix

**Comment by JakeWharton** [comment]
You are using different versions for the 'butterknife' and 'butterknife-compiler' artifacts. These are only guaranteed to work with the same version.
