### ISSUE TITLE
8.0以上控件名不同xml里面的不能重复？

### ISSUE THREAD

**Issue by a85454597** [JakeWharton/butterknife#883]
If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.   要加特殊标识？

**Comment by JakeWharton** [comment]
I'm not sure what you're asking, but that error is shown when a view ID that you have used in `@BindView` is not present in the view hierarchy.

**Comment by macleo** [comment]
lol.His problem is English mixed with Chinese.LOL
