### ISSUE TITLE
Required view "tvBalance" with ID 2131493005 for field "tvBalance" was not found. If this view is optional add "@Nullable"(fields) or "@Optional"(methods) annotation

### ISSUE THREAD

**Issue by a85454597** [JakeWharton/butterknife#886]
I hava many views id is tvBalance.    for example  I have a view’s id is "tvBalance"  in xml A, and  I have another view’s id is "tvBalance" in xml B too. and  I have another view’s id is "tvBalance" in xml C too......  this error what should i do?

**Comment by JakeWharton** [comment]
The error indicates that the view is not present in the view hierarchy when you are binding. You either need to mark it as nullable if the view is optional, bind at a later time when the view is present, or remove the field altogether if it's not in the layout you are binding with.

**Comment by a85454597** [comment]
I'm sure it exists this xml,but it also exists another xml in the same id is ‘tvBalance’.

**Comment by jdaros** [comment]
Got the same issue, have you found the solution ?

**Comment by tanseerpasha** [comment]
Got the same issue,  I was trying to inflate wrong XML file. I fixed that and now it works fine.

**Comment by mipicdev** [comment]
I had also this issue, but the corresponding view was commented out in the XML file.

**Comment by lemonteazhang** [comment]
Got the same issue, I was trying to inflate a custom scrollview in my XML file. Changed the custom scrollview to original scrollview and I fixed that and now it works fine.

**Comment by Axxxtosh** [comment]
you are probably binding before setContentView(R.layout.your_layout_name);

**Comment by FaridaMenisy** [comment]
you should add @nullable annotation , that will fix it

**Comment by Prakash172** [comment]
got issue inside the fragment, just removed the unused binded view and it works.

**Comment by peterchaula** [comment]
Yeah! :-( it wasn't because I accidentally took out the call to setContentView()

**Comment by qingchen1016** [comment]
It took me a long time to find out that the layout was wrong，setContentView（）It's wrong

**Comment by pratyooshp3** [comment]
Build > Clean Project fixed it for me.
