### ISSUE TITLE
Can i use like  this？

### ISSUE THREAD

**Issue by a85454597** [JakeWharton/butterknife#887]
in a activity  i have two views   
can i use like this?
ButterKnife.bind(this,view1);
ButterKnife.bind(this,view2);

**Comment by a85454597** [comment]
![image](https://cloud.githubusercontent.com/assets/12132140/23308487/4105cdae-fae6-11e6-8db7-97283e791386.png)

**Comment by JakeWharton** [comment]
No. You need to bind different view hierarchies to different objects otherwise it will try to find every view in both.

Please ask future general questions on StackOverflow with the 'butterknife' tag. Issues are for feature requests and bug reports.

**Comment by a85454597** [comment]
sorry  and thanks a lot
