### ISSUE TITLE
Is Butterknife aware of Gradle 3.4's incremental compilation?

### ISSUE THREAD

**Issue by EduardDopler** [JakeWharton/butterknife#888]
This is no real issue but having read [Gradle's new feature](https://blog.gradle.org/incremental-compiler-avoidance) which speeds up compilation by many times but only if annotations are implemented a special a way, I was wondering whether Butterknife allows Gradle doing those optimizations or whether it leads to recompiling every file where Butterknife annotations are present.

**Comment by JakeWharton** [comment]
ButterKnife is a JSR 269 standard annotation processor and doesn't know anything about build systems. So your concern is how Gradle implements invoking the Java compiler and it's support as this library has no means to effect Gradle.

**Comment by BarryFruitman** [comment]
It is now: https://github.com/JakeWharton/butterknife/commit/2acac62c7354fee46a5201d50a4712732f6dd1ed
