### ISSUE TITLE
View Cast

### ISSUE THREAD

**Issue by Xy-joe** [JakeWharton/butterknife#890]
Really enjoying butterknife but I'm working with buterknife 8.4.0 and  I noticed that it doesn't indicate or show an error if the wrong view type is being cast into the id of another view type. for example 
`<EditText
                android:layout_width="match_parent"
                android:layout_height="40dp"
                android:inputType="text"
                android:ems="10"
                android:layout_gravity="center"
                android:background="@drawable/edit_text"
                android:hint=""
                android:layout_marginTop="1dp"
                android:id="@+id/editText" />
 <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="Username"
                android:textColor="@color/white"
                android:textStyle="normal"
                android:textSize="15dp"
                android:layout_gravity="end"
                android:layout_marginTop="25dp"
                android:id="@+id/text_view"/>` 
Now these are two different views but i can cast the id of the text view into the Edit text and there will be no errors until you run the code and get  an error. 
Check this out

`@BindView(R.id.text_view)
 EditText textview;
 @BindView(R.id.editText)
   Textview editiew;` 

Please i would like to know if there is something I'm missing  thanks

**Comment by JakeWharton** [comment]
As ButterKnife only has access to Java files and not layout XML files it has no way of validating the declared type. You can use Android's databinding to generate bindings based on the layout XML if something like that is a requirement.

**Comment by JakeWharton** [comment]
This could be solved with a Gradle plugin, but at this time I don't want to require the use of a Gradle plugin.

**Comment by Xy-joe** [comment]
Ok nice got it
