### ISSUE TITLE
is  can support Android 2.1 ????

### ISSUE THREAD

**Issue by whao189** [JakeWharton/butterknife#892]
oh,  @JakeWharton , about butter knife  , my device is android-7 (Android 2.1  Eclair ), but butter knife compile is error .

error message :  --> 

 Manifest merger failed : uses-sdk:minSdkVersion 7 cannot be smaller than version 9 declared in library [com.jakewharton:butterknife:8.5.1]    

------<

so , is  can support Android2.1 ???

**Comment by whao189** [comment]
the butter knife's "builde.gradle", it is  

ext {
  minSdkVersion = 9
  targetSdkVersion = 25
  compileSdkVersion = 25
  buildToolsVersion = '25.0.2'
  sourceCompatibilityVersion = JavaVersion.VERSION_1_7
  targetCompatibilityVersion = JavaVersion.VERSION_1_7
}

minSdkVersion = 9 .......

is there any limits ??

**Comment by JakeWharton** [comment]
The support libraries we use only support 9+ so we have no choice but to do that same.
