### ISSUE TITLE
lead to conflict，How to deal with it？

### ISSUE THREAD

**Issue by hwra2008** [JakeWharton/butterknife#895]
In module.gradle,add "compile 'com.jakewharton:butterknife:8.5.1" lead to  to conflict:
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/hardware/display/DisplayManagerCompat$JellybeanMr1Impl.class

**Comment by JakeWharton** [comment]
That class isn't from ButterKnife. Your build system is doing something
wrong and including two copies of the same library. Try running the
dependencyInsight task.

**Comment by SolveBugs** [comment]
I meet this problem too,when i add "compile('com.jakewharton:butterknife:8.6.0') {
        exclude module: 'support-compat'
    }" in my dependencies like this ,the problem solved。

**Comment by guixin567** [comment]
i meet too,when i add "compile('com.jakewharton:butterknife:8.6.0') {
exclude module: 'support-compat' in my dependencies ,it has a other problem Could not find method compile for arguments com.jakewharton:butterknife:8.6.0,
