### ISSUE TITLE
I am using the latest Android Studio 2.2.3 and i have added the proguard-rules.pro also, i got the following errors.

### ISSUE THREAD

**Issue by srinivasgoud** [JakeWharton/butterknife#896]
Warning:butterknife.compiler.ButterKnifeProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor
Warning:butterknife.compiler.ButterKnifeProcessor$IdScanner: can't find superclass or interface com.sun.tools.javac.tree.TreeScanner
Warning:butterknife.compiler.ButterKnifeProcessor$RClassScanner: can't find superclass or interface com.sun.tools.javac.tree.TreeScanner
Warning:butterknife.compiler.ButterKnifeProcessor$VarScanner: can't find superclass or interface com.sun.tools.javac.tree.TreeScanner
Warning:com.google.auto.common.AnnotationValues$1$1: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.google.auto.common.AnnotationValues$1$1$1: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.google.auto.common.AnnotationValues$1$1$2: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.google.auto.common.AnnotationValues$1$1$3: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.google.auto.common.AnnotationValues$1$1$4: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.google.auto.common.AnnotationValues$1$2: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.google.auto.common.BasicAnnotationProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor
Warning:com.google.auto.common.BasicAnnotationProcessor$2: can't find superclass or interface javax.lang.model.util.SimpleElementVisitor6
Warning:com.google.auto.common.MoreElements$1: can't find superclass or interface javax.lang.model.util.SimpleElementVisitor6
Warning:com.google.auto.common.MoreElements$2: can't find superclass or interface javax.lang.model.util.SimpleElementVisitor6
Warning:com.google.auto.common.MoreElements$3: can't find superclass or interface javax.lang.model.util.SimpleElementVisitor6
Warning:com.google.auto.common.MoreElements$4: can't find superclass or interface javax.lang.model.util.SimpleElementVisitor6
Warning:com.google.auto.common.MoreTypes$15: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.MoreTypes$16: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.MoreTypes$2: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.MoreTypes$3: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.MoreTypes$4: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.MoreTypes$5: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.MoreTypes$CastingTypeVisitor: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.SuperficialValidation$1: can't find superclass or interface javax.lang.model.util.AbstractElementVisitor6
Warning:com.google.auto.common.SuperficialValidation$2: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor6
Warning:com.google.auto.common.SuperficialValidation$3: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.google.auto.service.processor.AutoServiceProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor
Warning:com.squareup.javapoet.AnnotationSpec$Visitor: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor7
Warning:com.squareup.javapoet.JavaFile$2: can't find superclass or interface javax.tools.SimpleJavaFileObject
Warning:com.squareup.javapoet.TypeName$1: can't find superclass or interface javax.lang.model.util.SimpleTypeVisitor7
Warning:butterknife.compiler.BindingClass: can't find referenced class javax.lang.model.element.Modifier
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.AbstractProcessor
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.ProcessingEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced field 'javax.annotation.processing.ProcessingEnvironment processingEnv' in program class butterknife.compiler.ButterKnifeProcessor
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.source.util.Trees
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Modifier
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ElementKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeVariable
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.ArrayType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.DeclaredType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Types
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ExecutableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ElementKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ExecutableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.VariableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.DeclaredType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ElementKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Modifier
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.SourceVersion
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.tools.Diagnostic$Kind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.ProcessingEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.Messager
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Elements
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.PackageElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.AnnotationMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ExecutableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.source.util.Trees
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.tools.javac.tree.JCTree
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Elements
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.MirroredTypeException
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Types
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.source.util.Trees
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.VariableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.AbstractProcessor
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.DeclaredType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.ArrayType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ExecutableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.VariableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.tools.Diagnostic$Kind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.MirroredTypeException
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.tools.javac.tree.JCTree
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.ProcessingEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.source.util.Trees
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Modifier
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ElementKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeKind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Types
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.SourceVersion
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.Messager
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Elements
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.PackageElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.tools.Diagnostic
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.tools.javac.tree.JCTree$Visitor
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Elements
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.util.Types
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.Filer
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.source.util.Trees
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.ProcessingEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Modifier
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeVariable
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.ArrayType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.DeclaredType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeVariable
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.ArrayType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeVariable
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.VariableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ExecutableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.VariableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.DeclaredType
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.TypeMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.SourceVersion
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.tools.Diagnostic$Kind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.tools.Diagnostic$Kind
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.AnnotationMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.ExecutableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.AnnotationMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.AnnotationMirror
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.tools.javac.tree.JCTree
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.type.MirroredTypeException
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class com.sun.tools.javac.tree.JCTree
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.TypeElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.VariableElement
Warning:butterknife.compiler.ButterKnifeProcessor: can't find referenced class javax.lang.model.element.Element

**Comment by JakeWharton** [comment]
Your dependency isn't set up correctly. Please see the README for instructions on what your build.gradle should look like.
