### ISSUE TITLE
Cannot add extension with name 'android'

### ISSUE THREAD

**Issue by aelmahdaoui** [JakeWharton/butterknife#900]
The readme says to add the following in the module:

```
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
```

But if I add it to the already present plugins,  i have:

```
apply plugin: 'com.android.application'
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
```

This however gives me the following error:

> Cannot add extension with name 'android', as there is an extension already registered with that name.

**Comment by JakeWharton** [comment]
```groovy
apply plugin: 'com.android.application'
apply plugin: 'com.android.library'
```
add one of these two, not both.

**Comment by aelmahdaoui** [comment]
Only the one with "application" works, if I try to add only the library, it gives the error:

> Error:Library projects cannot set applicationId. applicationId is set to XXX in default config.

**Comment by gau4sar** [comment]
@JakeWharton I think the README.MD needs to be updated

**Comment by franksight** [comment]
@JakeWharton I think the README.MD needs to be updated

apply plugin: 'com.android.application'
apply plugin: 'com.android.library'
BECAUSE NOBODY KNOWS add one of these two, not both.
