### ISSUE TITLE
Unbinder and Utils class not found

### ISSUE THREAD

**Issue by aelmahdaoui** [JakeWharton/butterknife#901]
Following the readme file, I tried to use BindView. I imported the class:
`import butterknife.BindView;`
I then tried it:
`@BindView(R2.id.someEditText) EditText someEditText;`
and it imports the library fine so it seems(it gives me the proper suggestions). If I try to run it I get the following errors after it opens the MainActivity_ViewBinding.java file:

> Error:(8, 19) error: cannot find symbol class Unbinder
Error:(9, 28) error: cannot find symbol class Utils

in that java file. Also, if I check that file I see that these two lines are not recognized:
`import butterknife.Unbinder;
import butterknife.internal.Utils;`

In addition, if I try to write:
` ButterKnife.bind(this);`

It is also not recognized

**Comment by aelmahdaoui** [comment]
DebouncingOnClickListener and ButterKnife have the same issue

**Comment by JakeWharton** [comment]
This is a problem with your build configuration, not this library. Ensure you are using the same version for the plugin and each dependency. If you can reproduce the problem in a sample project I'll take a look. Otherwise there's really nothing we can do here.
