### ISSUE TITLE
(Object) with ID XXX for field was of the wrong type issue with different flavors in Android Studio 2.3

### ISSUE THREAD

**Issue by rwmorey71** [JakeWharton/butterknife#902]
I'm not sure if this is an Android Studio bug or a ButterKnife issue.

However, I have a project with different flavors. Most of the code is shared between flavors but there is one layout and fragment that are customized for each flavor.

In that case I am getting the "wrong type" error. I tried to fix the issue by changing the name of the control in both the custom XML and the Java code but the error continued.

Finally, I tried renaming the XML file but the error continued to happen.

I can't rename the Fragment itself because that would break the code.

I can provide files if you let me know what files to provide.

**Comment by rwmorey71** [comment]
Hi -
This is not a ButterKnife issue. I changed the code to the standard FindViewById and I am getting the same ClassCastException.

Rich

**Comment by JakeWharton** [comment]
Yes, multiple layouts with the same ID either need to use a common supertype or use different IDs for the views in different resource qualifier directories such that only one gets bound depending on the configuration of the device.
