### ISSUE TITLE
how can i unbind widget listener?

### ISSUE THREAD

**Issue by macleo** [JakeWharton/butterknife#904]
At first Thanks JakeWharton support this project for us.

my problem is :
button bind OnClickListener can using like this :  btn_agree.setOnClickListener(this);
cancel bind this listener can using like this: btn_agree.setOnClickListener(null);

ok,then how can i unbind some widget listener using ButterKnife?
thanks author and everyone.

**Comment by JakeWharton** [comment]
Calling `bind()` returns an `Unbinder` which you should hold on to and then call its `unbind()` method to clear any listeners.

See http://jakewharton.github.io/butterknife/#reset

**Comment by macleo** [comment]
Thank u my god, i found method apply can help you reach my dest.Thank u.
