### ISSUE TITLE
Can auto fillup method parameters?

### ISSUE THREAD

**Issue by macarthor** [JakeWharton/butterknife#905]
if I write a method like setItemClick, can butterknife auto fillup the necessary parameters? I don't expect to remember all those parameters.
I know I can use `int position` as the parameter, but what if there are two int parameters.

**Comment by JakeWharton** [comment]
It matches left to right. So if there are two int params you'll match the first two corresponding int parameters of the backing listener method, assuming there are at least two. To my knowledge there aren't any occurrences of this. The closest is the int and long parameters of a list click which correspond to the position and ID, respectively.

**Comment by macarthor** [comment]
@JakeWharton thx for the explanation.
another question is whether butterknife can automatically fillup the parameters of the method? for example, i typed: `@OnItemClick void onI`, can it auto shows completion like `onItemClick()`, and auto fillup the 4 parameters of method?

**Comment by JakeWharton** [comment]
No. It can't do that. That would require an IDE plugin which I'm not going
to develop, but someone is free to do so as a third-party extension.

**Comment by macarthor** [comment]
@JakeWharton got it. many thx.
