### ISSUE TITLE
About Unbind 

### ISSUE THREAD

**Issue by TieUper** [JakeWharton/butterknife#906]
In Activity or Fragment, Whether it will lead to memory leaks if i don't use unbind method.  i use unbind method on activity destory, then a delay response will cause the NullPointerException when i use the bindView such as Textview.setText()

**Comment by JakeWharton** [comment]
The leak is your response callback retaining the ability to callback the activity or fragment after it was destroyed. Cancel your requests when the UI is leaving or detach your requests from being able to interact directly with your UI.

This is not a Butter Knife-specific problem.
