### ISSUE TITLE
android studio 2.4 does not suppot annotationProcessor?

### ISSUE THREAD

**Issue by freecsdn** [JakeWharton/butterknife#908]
Error:Execution failed for task ':member:javaPreCompileRelease'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
  - butterknife-7.0.1.jar
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

**Comment by JakeWharton** [comment]
Use the latest version of the library to solve this problem. Instructions are in the README.

**Comment by BoxResin** [comment]
Edit `build.gradle` file like this:
![image](https://cloud.githubusercontent.com/assets/13031505/25555642/0475e45a-2d27-11e7-8d9a-0ed9e0e753d8.png)

**Comment by JakeWharton** [comment]
That is not needed

**Comment by Devnagi** [comment]
Use this - annotationProcessor 'com.jakewharton:butterknife:7.0.1'
compile 'com.jakewharton:butterknife:7.0.1'

**Comment by brinkkemper** [comment]
@BoxResin What developer posts code as an image! Who does that!

**Comment by BoxResin** [comment]
@brinkkemper I'm sorry.
```gradle
javaCompileOptions {
    annotationProcessorOptions {
        includeCompileClasspath = true
    }
}
```

**Comment by medchado** [comment]
tyso u save my life bro

**Comment by hemant00007** [comment]
![na](https://user-images.githubusercontent.com/23187346/37524260-54bd7278-294f-11e8-85d0-9120879b4e17.jpg)

**Comment by ParkHanUl** [comment]
hey friend good thank you for your help ㅠ_ㅠ

**Comment by softmarshmallow** [comment]
> @BoxResin What developer posts code as an image! Who does that!

i do
