### ISSUE TITLE
TransformException: java.util.zip.ZipException: duplicate entry

### ISSUE THREAD

**Issue by courysky** [JakeWharton/butterknife#909]
I met this error:
`Execution failed for task ':app:transformClassesWithJarMergingForStagingDebug'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/graphics/drawable/DrawableCompatBase.class`
How to solve it ?Thx

**Comment by NazuButters** [comment]
compile ('com.jakewharton:butterknife:8.5.1'){
        exclude module: 'support-compat'
    }

this maybe be would help you

**Comment by JakeWharton** [comment]
This is a build system problem, not a Butter Knife problem. See my comment here: https://github.com/JakeWharton/butterknife/issues/903#issuecomment-287264156
