### ISSUE TITLE
dialog injection fail

### ISSUE THREAD

**Issue by oqq5518** [JakeWharton/butterknife#912]
`    View view = getActivity().getLayoutInflater().inflate(R.layout.dialog_jieguo_chaxun, null);
        dialog = new AlertDialog.Builder(getActivity()).setView(view).show();
        ButterKnife.bind(this, view);`

it can't find the element..why?

**Comment by JakeWharton** [comment]
It's not in the layout you inflated.

**Comment by oqq5518** [comment]
can you explain more?i don't understand.

**Comment by JakeWharton** [comment]
The generated code just calls `findViewById` so if it can't find a view then that view is not in the layout you inflated. If you ran a manual `findViewById` with the same ID on `view` it would return null.

**Comment by oqq5518** [comment]
``` java
View view = getActivity().getLayoutInflater().inflate(R.layout.dialog_jieguo_chaxun, null);
 dialog = new AlertDialog.Builder(getActivity()).setView(view).show(); 
ButterKnife.bind(this, view);
```
but i have declared ButterKnife.bind(this, view)...

**Comment by oqq5518** [comment]
onCreate() in Activity,i write `ButterKnife.bind(this, view);`
and i also write `ButterKnife.bind(this, view);` in an dialog code.
