### ISSUE TITLE
Support for multiple binding of view 

### ISSUE THREAD

**Issue by PrathameshKesarkar** [JakeWharton/butterknife#913]
can we have support to something like this .
`@BindViews({R.id.loginView,R.id.signUpView})
View loginView, signUpView;`
This can help to reduce the boilerplate code. I know Butterknife support multiple binding with the help of List<View> 
But I guess this would give us more control over naming view rather than relying on List.

**Comment by JakeWharton** [comment]
No. That is syntactically equivalent to
```
@BindViews({R.id.loginView,R.id.signUpView}) View loginView;
View signUpView;
```
