### ISSUE TITLE
When i import butterknife, build failed

### ISSUE THREAD

**Issue by doubliekill** [JakeWharton/butterknife#916]
Warning: Exception while processing task java.io.IOException: Can't write [/home/travis/build/********/app/build/intermediates/transforms/proguard/default/release/jars/3/1f/main.jar] (Can't read [/home/travis/.android/build-cache/79a91b5bb1902cd6f19507b785d99e0f479b6d88/output/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [android/support/v4/os/b.class == classes.jar:android/support/v4/os/AsyncTaskCompatHoneycomb.class]))
:app:transformClassesAndResourcesWithProguardForDefaultRelease FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForDefaultRelease'.
> Job failed, see logs for details

**Comment by doubliekill** [comment]
@JakeWharton

**Comment by JakeWharton** [comment]
This is a build system problem, not a Butter Knife problem. See my comment here: https://github.com/JakeWharton/butterknife/issues/903#issuecomment-287264156
