### ISSUE TITLE
RESOURCE BINDING in adapter

### ISSUE THREAD

**Issue by nAkhmedov** [JakeWharton/butterknife#917]
Awesome lib 👍  How to bind resources in adapter, i created as a filed but all of them null.
<img width="625" alt="screen shot 2017-03-30 at 6 27 15 pm" src="https://cloud.githubusercontent.com/assets/8067423/24506363/aac0e580-1576-11e7-8e2f-7f15658702ce.png">

Thanks in advance!

**Comment by JakeWharton** [comment]
Call `new ViewBinder_MainMenuAdapter(context)`.

**Comment by nAkhmedov** [comment]
``` public MainMenuAdapter(Context context) {
        this.mContext = context;
        new MainMenuAdapter_ViewBinding(MainMenuAdapter.this, context);
    }```

**Comment by nAkhmedov** [comment]
Thank you for yr reply, It doesn't help. did i call it wrong place?

**Comment by nAkhmedov** [comment]
Such ViewBinder_MainMenuAdapter class doesn't exist

**Comment by JakeWharton** [comment]
It's generated by Butter Knife when you compile.

**Comment by nAkhmedov** [comment]
Yes, but ButterKnife is generating MainMenuAdapter_ViewBinding class only. ViewBinder_MainMenuAdapter is not exist. Could you help me to solve this issue?
