### ISSUE TITLE
 Could not find method annotationProcessor

### ISSUE THREAD

**Issue by manoj-android** [JakeWharton/butterknife#920]
Hey Jake,
 While compiling the code I see  below error:

Could not find method annotationProcessor() for arguments [com.jakewharton:butterknife-compiler:8.5.
4]

My gradle plugin version is 3.4.1
Android Studio is 2.3

Any thoughts on why we could not find method ? 

More logs:

11:22:54.590 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 8473034752, Free: 2758103040}
11:22:54.590 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 586153984}
11:22:54.808 [INFO] [org.gradle.api.Project] SDK initialized in 18564 ms
11:22:54.808 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :app - Registering model element 'tasks.sonarqube' (hidden = false)
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file 'C:\GitWorkspace\OhCurrent\mobile_android\app\build.gradle' line: 180
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating project ':app'.
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not find method annotationProcessor() for arguments [com.jakewharton:butterknife-compiler:8.5.
4] on DefaultExternalModuleDependency{group='com.jakewharton', name='butterknife', version='8.5.4', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.
DefaultExternalModuleDependency.
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
11:22:54.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
11:22:54.824 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]

**Comment by JakeWharton** [comment]
You need to use the Android Gradle plugin version 2.2 or newer which is when `annotationProcessor` was introduced. The is usually define in the root `build.gradle` file.

**Comment by znwabudike** [comment]
Hi Jake, I am having this same issue with Android Gradle plugin 2.3.1

10:41 AM	Gradle sync failed: Could not find method annotationProcessor() for arguments [com.jakewharton:butterknife-compiler:8.5.1] on DefaultExternalModuleDependency{group='com.jakewharton', name='butterknife', version='8.5.1', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
				Consult IDE log for more details (Help | Show Log)
