### ISSUE TITLE
Hello! Question about bintrayUpload

### ISSUE THREAD

**Issue by Ayvytr** [JakeWharton/butterknife#924]
I use bintrayUpload command to publish a library on bintray website, and added to jcenter, then I added dependence in my project, and opened my library classes, It doesn't have annotate/note. How could I add annotate on my published library? And on jcenter website project files, exists .asc files. What does it do?

**Comment by JakeWharton** [comment]
I don't quite understand how this is related to Butter Knife. Are you asking if you can use Butter Knife in your library?
