### ISSUE TITLE
Suspicious incrementor in an inner loop

### ISSUE THREAD

**Issue by lifove** [JakeWharton/butterknife#925]
Hi

In a recent snapshot, I've found the following suspicious code at butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java

```
1041       for (int i = 0; i < methodParameters.size(); i++) {
1042         VariableElement methodParameter = methodParameters.get(i);
1043         TypeMirror methodParameterType = methodParameter.asType();
...
1071           for (int j = 0; j < parameters.length; j++) {
1072             Parameter parameter = parameters[j];
1073             builder.append("\n\n  Parameter #")
1074                 .append(j + 1)
1075                 .append(": ")
1076                 .append(methodParameters.get(j).asType().toString())
1077                 .append("\n    ");
1078             if (parameter == null) {
1079               builder.append("did not match any listener parameters");
1080             } else {
1081               builder.append("matched listener parameter #")
1082                   .append(parameter.getListenerPosition() + 1)
1083                   .append(": ")
1084                   .append(parameter.getType());
1085             }
1086           }
```
In Line 1076, should the indexer j of methodParameters.get(j) be i as of the outer for loop iterating with methodParameters.size(). Since parameters.lengh is same as methodParameters.size(), so this might not be an issue. But I wanted to report just in case. Thanks!

**Comment by JakeWharton** [comment]
I think it's fine as-is, but I'll admit to the code being _very_ unclear. It took me a few reads to understand this giant code block.

This code path is an error reporting case where we're re-looping over all the params. The loop uses `parameters.length` which is initialized to `methodParameters.size()` size and then uses `j` to index into _both_ the `parameters` and `methodParameters` collections.

So there's no actual bug, but it's a gnarly bit of code. Thanks for potentially identifying it though. I'd love to see this gigantic block cleaned up in the future to be more clear.
