### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource "com.bt.sample.id:drawable/banner_placeholder" (7f02005b) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f02005b a=-1 r=0x7f02005b}

### ISSUE THREAD

**Issue by mukesh4u** [JakeWharton/butterknife#926]
The  drawable banner_placeholder is there in all 4 drawable folder but sometimes I am facing the above issue.Please help me.

**Comment by JakeWharton** [comment]
This is not an issue with Butter Knife itself. The generated code is just calling `getDrawable()` with the `R.drawable` reference that you provide. Try StackOverlfow?
