### ISSUE TITLE
Binding several views to a Listener with multiple methods in Butterknife

### ISSUE THREAD

**Issue by nicozimmermann94** [JakeWharton/butterknife#927]
Hey, it seems like it was once possible to bind a method to multiple views at once. Like I have three EditViews and each one should listen on text change events. It looks like it is not possible to determine which EditView was changed.
A good example is this issue: http://stackoverflow.com/questions/40963739/binding-several-views-to-a-listener-with-multiple-methods-in-butterknife

**Comment by JakeWharton** [comment]
There's a test for this: https://github.com/JakeWharton/butterknife/blob/fc10f1674a08162ad7cf8c762c11a748c20c25d8/butterknife/src/test/java/butterknife/OnClickTest.java#L118. If you think it's broken please provide a failing test case or full sample.
