### ISSUE TITLE
Aboute  R2 some problem

### ISSUE THREAD

**Issue by myxfeng** [JakeWharton/butterknife#931]
Error:Could not find com.android.tools.build:gradle:2.2.0.
Error:Could not find com.android.tools.build:gradle:2.2.0.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
Required by:
    XiZangDaily:usercentermodule:unspecified > com.jakewharton:butterknife-gradle-plugin:8.5.1
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
Required by:
    XiZangDaily:usercentermodule:unspecified > com.jakewharton:butterknife-gradle-plugin:8.5.1

the com.jakewharton:butterknife-gradle-plugin:8.5.1  use  Low version gradle  and maVen don't have   gradle 2.2.0
https://repo1.maven.org/maven2/com/android/tools/build/gradle/

**Comment by JakeWharton** [comment]
Newer versions of the Android Gradle plugin are only available in jcenter.
Add it to your buildscript repositories.
