### ISSUE TITLE
Warning:unknown enum constant Scope.LIBRARY_GROUP

### ISSUE THREAD

**Issue by proyectox123** [JakeWharton/butterknife#933]
With these imports:

import android.support.annotation.CallSuper;
import android.support.annotation.UiThread;

Log shows:

Error:(4, 34) error: package android.support.annotation does not exist

library version: 8.5.1
gradle: 2.2.3

**Comment by JakeWharton** [comment]
ButterKnife [depends on `support-annotation`][1] version [25.1.0][2] which has this. Your build system is likely forcing it to use an older version.

 [1]: https://github.com/JakeWharton/butterknife/blob/master/butterknife/build.gradle#L24
 [2]: https://github.com/JakeWharton/butterknife/blob/master/build.gradle#L56
