### ISSUE TITLE
Why you not use javaassist or asm to slove inject problem

### ISSUE THREAD

**Issue by InLook** [JakeWharton/butterknife#935]
> ## Now i dev function about route in android with apt, i find many work  about apt to solve inject problem with reflect.Perhaps this will affect the performance, and use proguard.

**For example,In ButterKnife**
![image](https://cloud.githubusercontent.com/assets/4536178/25389472/5342685a-2a03-11e7-9fa6-1f7df66b6189.png)
![image](https://cloud.githubusercontent.com/assets/4536178/25389489/60474ea8-2a03-11e7-86f8-ef7d3d631fac.png)

**I Use javaassist in route link this,**
![image](https://cloud.githubusercontent.com/assets/4536178/25389758/0988af8e-2a04-11e7-8120-12cfa92d4665.png)
Many People not use this,Maybe there is a reason，Please tell me
PS：Sorry，Forgive my poor English，My opinion may be  clear

**Comment by JakeWharton** [comment]
Annotation processors cannot modify existing class files. That requires a Gradle plugin which I don't want to build.

There's an even easier zero-reflection mechanism for using Butter Knife: reference the generated code directly via `new YourClass_ViewBinding(..)`.

**Comment by InLook** [comment]
I search about java reflection performance with google http://stackoverflow.com/questions/435553/java-reflection-performance
**so only one object  instantiate，just more than 3ms，so it's  zero-reflection mechanism.**
By the way, can  I use java assist  gradle plugin to solve this problem：

> apt generate A class manager every sub module generate class in main module.

It bring other problems？or solve in other way?
Waiting for your Help,Thank Yout
