### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by jarvan11** [JakeWharton/butterknife#936]
Error:Could not find com.android.tools.build:gradle:2.2.0.
Searched in the following locations:
    file:/C:/MyWork/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    file:/C:/MyWork/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
Required by:
    project :life > com.jakewharton:butterknife-gradle-plugin:8.5.1

**Comment by JakeWharton** [comment]
The Android Gradle plugin is available on JCenter only now. Add `jcenter()` to your buildscript repositories.

**Comment by yperess** [comment]
@JakeWharton could you update the README on the front page to reflect the requirement for `jcenter()`? Specifically for when using this in a library.
