### ISSUE TITLE
how does butterKnife bind multiple views in an activity

### ISSUE THREAD

**Issue by ozy20** [JakeWharton/butterknife#937]
before this, my activity has been tied once, and now I need to add a header view, how to bind the header

**Comment by egor-n** [comment]
You can't bind the same object (activity in your case) twice to two different view hierarchies. You should create a separate class to hold references of your header. Take a look at [this comment](https://github.com/JakeWharton/butterknife/issues/889#issuecomment-283975386) or [this comment](https://github.com/JakeWharton/butterknife/issues/259#issuecomment-97813388), for example.

**Comment by JakeWharton** [comment]
Thanks @egor-n!
