### ISSUE TITLE
Class constructor.newInstance() InvocationTargetException Error

### ISSUE THREAD

**Issue by JunsuLime** [JakeWharton/butterknife#938]
```java
ItemHolder viewHolder = holder.holderClazz
.getConstructor(ABS_PARAM)
.newInstance(mContext, itemView, holder.handler);
```

I make newInstance using Class.getConstructor().newInstance()

and I got error  java.lang.reflect.InvocationTargetException, when i bind my viewholder with Butter.knife

```java
public LoadingViewHolder(Context context, View itemView, Object handler) {
        super(context, itemView, handler);
        ButterKnife.bind(this, itemView)
    }
```

and I solve this problem with basic view binding (findViewByid)

```java
public LoadingViewHolder(Context context, View itemView, Object handler) {
        super(context, itemView, handler);
        loadingText = (TextView) itemView.findViewById(R.id.loading_text);
        loadingProgress = (ProgressBar) itemView.findViewById(R.id.loading_progress);
    }
```

I can bind view by findViewById but I want to use Butter knife at all case.

This error does not occur at every case.

In some case, this error InvocationTargetException occurs.

I appreciate your help!!  :) Thank you 👍

**Comment by JakeWharton** [comment]
Without a full stacktrace or a sample project demonstrating the issue it's impossible to know what's going on.
