### ISSUE TITLE
Passing additional parameters to onClick handler using Butterknife

### ISSUE THREAD

**Issue by runrmrf** [JakeWharton/butterknife#941]
Hi Jake,

This is an extension of: https://github.com/JakeWharton/butterknife/issues/427#issuecomment-173011104.

How do you declare the Button for the onClick from the example you provided in the above case?

This is what I have but I couldn't get it to work:

```
public class EventMatchedFragment {

@BindView(R2.id.chat_btn)
Button chatBtn;

  public static EventMatchedFragment newInstance(MatchedEvent matchedEvent) {
  
    Bundle arguments = new Bundle();
    arguments.putParcelable("matchedEventDetails" matchedEvent);

    EventMatchedFragment eventMatchedFragment = new EventMatchedFragment();
    eventMatchedFragment.setArguments(arguments);
    return eventMatchedFragment;
  }

  class ChatButtonClass {

    private MatchedEvent mMatchedEvent;

    ChatButtonClass(MatchedEvent matchedEvent) {
        this.mMatchedEvent = matchedEvent;
    }

    @OnClick void onClick() {
        Intent intent = MessagesActivity.newInstance(getActivity(), mMatchedEvent);
        intent.putExtra("matchedEventDetails", mMatchedEvent);
        startActivity(intent);
    }
  }

  private void goToChat(final View view, final MatchedEvent matchedEvent) {
      chatBtn.setOnClickListener(new View.OnClickListener() {
          @Override
          public void onClick(View v) {
              ChatButtonClass chatButtonClass = new ChatButtonClass(matchedEvent);
              ButterKnife.bind(chatButtonClass, view);
          }
      });
    }
 }

```

When I clicked the button, it does nothing.

If i then add android:onClick="goToChat" to the xml file, the app crashes with the error:

> java.lang.IllegalStateException: Could not find method goToChat(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'chat_btn'

It would be greatly appreciated if you can take a look and advice. Thanks.

-R

**Comment by JakeWharton** [comment]
You don't need a separate type. Put the click method on the fragment, bind in `onCreateView`, and pull the object from the fragment arguments inside the method.

**Comment by runrmrf** [comment]
Hi Jake,

Thanks for the quick response. This is what I have` onCreateView`

```
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup
            container, @Nullable Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_event_matched_details, container, false);
        mUnbinder = ButterKnife.bind(this, rootView);

        return rootView;
    }

```
and i created the method below in the fragment but I'm not too sure how to pull the object from the fragment arguments inside the method:

```
    @OnClick(R2.id.event_matched_details_event_chat_btn)
    public void setChatBtn() {

        

    }

```

I'm very new to Android development and also to using Butterknife. Could you please advise?

**Comment by JakeWharton** [comment]
They're available by calling getArguments(). Use the same key you stored
the object with in your static factory method.

**Comment by runrmrf** [comment]
However, MatchedEvent is a class, how do you put that in a Bundle?

**Comment by runrmrf** [comment]
This is what I have:

```
    @OnClick(R2.id.event_matched_details_event_chat_btn)
    public void setChatBtn(MatchedEvent matchedEvent) {

        Intent intent = MessagesActivity.newInstance(getActivity(), matchedEvent);
        intent.putExtra("matchedEventDetails", matchedEvent);
        startActivity(intent);

    }
```

Got this error:

>   Methods may have up to 1 parameter(s):

**Comment by JakeWharton** [comment]
You're already putting it in a bundle. Now you need to retrieve it using
the same key on the Bundle returned from getArguments()

**Comment by runrmrf** [comment]
I got it. I had the getArguments() in the onCreate method and just had to make that a global variable. Thanks for the hint.
