### ISSUE TITLE
The latest version is not depended on the latest com.android.support

### ISSUE THREAD

**Issue by yuanhcn** [JakeWharton/butterknife#943]
+--- com.jakewharton:butterknife:8.5.1
|    +--- com.jakewharton:butterknife-annotations:8.5.1
|    |    \--- com.android.support:support-annotations:25.1.0 -> 25.3.1
|    +--- com.android.support:support-annotations:25.1.0 -> 25.3.1
|    \--- com.android.support:support-compat:25.1.0 -> 25.3.1 (*)

**Comment by JakeWharton** [comment]
This is fine. They're binary compatible and Gradle takes care of choosing the newer version as you can see. You're welcome to send a PR to update them but I'm not making a release just to track dependency updates.
