### ISSUE TITLE
How to use this method :ButterKnife.bind(View target)

### ISSUE THREAD

**Issue by lucky9322** [JakeWharton/butterknife#946]
Hello,
        I want to konw the use of the scene about ButterKnife.bind(View target).
So is there an example? 
      thanks.

**Comment by JakeWharton** [comment]
From the website:

> Bind a view's children into fields using `ButterKnife.bind(this)`. If you use `<merge>` tags in a layout and inflate in a custom view constructor you can call this immediately after. Alternatively, custom view types inflated from XML can use it in the `onFinishInflate()` callback.

This method binds a view to its own children.

**Comment by lucky9322** [comment]
Thanks .
According to your introduction I have verified this result.
