### ISSUE TITLE
update Android studio error 

### ISSUE THREAD

**Issue by Geekince** [JakeWharton/butterknife#956]
Error:Could not find com.android.tools.build:gradle:2.2.0.
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
Required by:
    project :base-layer > com.jakewharton:butterknife-gradle-plugin:8.5.1

**Comment by JakeWharton** [comment]
Dupe #936.
