### ISSUE TITLE
App crashes almost every code change until Rebuild performed

### ISSUE THREAD

**Issue by galaxi76** [JakeWharton/butterknife#957]
My issue is similar to this SO post, except it happens to me sporadically (but often) when I change any code, not only views.
http://stackoverflow.com/questions/42447941/androidstudio-sporadically-stops-generating-butterknife-bindings-until-rebuild

**Comment by SimonVT** [comment]
Try disabling jack. Not sure it ever worked properly with annotation processors, and it's deprecated anyway.

**Comment by JakeWharton** [comment]
Try without Jack for sure. But otherwise this is a tools problem in failing to run the processor and there's nothing ButterKnife can do to fix it. If you can create a reproducible sample file it on b.android.com.

**Comment by galaxi76** [comment]
@SimonTV I would love to disable jack (I miss Instant Run!) and have been waiting for it to be official since the announcement in March re the depreciation,  so thanks so much for bringing it to my attention!
@JakeWharton You're right, this seems to be a tools issue.  Even when trying to disable jack, I got an error about java 8. Then tried updating gradle plugin and version to a preview as hinted by the docs, other errors. Will post on SO and update here when solved.
