### ISSUE TITLE
Proguard minifyEnabled true + butterknife = error

### ISSUE THREAD

**Issue by Delphian2015** [JakeWharton/butterknife#959]
Hello. I have Android Studio 2.3.2.  

When I start my app I have a lot of warnings and error:

> Information:Gradle tasks [:app:assembleDebug] Warning:butterknife.compiler.ButterKnifeProcessor$IdScanner: can't find superclass or interface com.sun.tools.javac.tree.TreeScanner Warning:butterknife.compiler.ButterKnifeProcessor$RClassScanner: can't find superclass or interface com.sun.tools.javac.tree.TreeScanner Warning:butterknife.compiler.ButterKnifeProcessor$VarScanner: can't find superclass or interface com.sun.tools.javac.tree.TreeScanner Warning:org.apache.poi.hssf.usermodel.DummyGraphics2d: can't find superclass or interface java.awt.Graphics2D Warning:org.apache.poi.hssf.usermodel.EscherGraphics: can't find superclass or interface java.awt.Graphics Warning:org.apache.poi.hssf.usermodel.EscherGraphics2d: can't find superclass or interface java.awt.Graphics2D Warning:org.apache.poi.poifs.crypt.dsig.SignatureMarshalListener: can't find superclass or interface org.w3c.dom.events.EventListener Warning:org.apache.poi.xslf.usermodel.XSLFRenderingHint: can't find superclass or interface java.awt.RenderingHints$Key .... Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebug'. Job failed, see logs for details

My progard-rules is:

```
-dontobfuscate
-dontoptimize
-optimizations !code/allocation/variable
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}
-keepattributes *Annotation*,EnclosingMethod,Signature
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keep class org.parceler.Parceler$$Parcels
-keep public class org.apache.poi.** {*;}
-keep public class * implements butterknife.internal.ViewBinder   
{ public<init>();}
-keep class butterknife.*
-keepclasseswithmembernames class * { @butterknife.* <methods>; }
-keepclasseswithmembernames class * { @butterknife.* <fields>; }
```

My gradle:

```
buildTypes { release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        } }
```
if i change minifyEnabled false. There are no errors. I am using multidex mode. How can I solve the problem?

**Comment by JakeWharton** [comment]
Looks like your build isn't configured correctly. You have the compiler on the `compile` configuration instead of on `annotationProcessor`. See the README and ensure your setup matches its recommendation.

**Comment by Delphian2015** [comment]
Jake, thank you. I solved the problem.

**Comment by ghost** [comment]
Cause: superclass access check failed: class butterknife.compiler.ButterKnifeProcessor$RScanner (in unnamed module @0x4f220a2e) cannot access class com.sun.tools.javac.tree.TreeScanner (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x4f220a2e


HELP PLEASE

**Comment by Kola-Chao** [comment]
> Cause: superclass access check failed: class butterknife.compiler.ButterKnifeProcessor$RScanner (in unnamed module @0x4f220a2e) cannot access class com.sun.tools.javac.tree.TreeScanner (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x4f220a2e
> 
> HELP PLEASE

I have the same problem, can you tell me how you solved it?

**Comment by technicalyarana** [comment]
Cause: superclass access check failed: class butterknife.compiler.ButterKnifeProcessor$RScanner (in unnamed module @0x34a5ef24) cannot access class com.sun.tools.javac.tree.TreeScanner (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x34a5ef24


i got this problem can anyone solve please

**Comment by umar-aftab-qureshi** [comment]
I have also faced the same issue can anyone help me with this?

**Comment by bhaskarjha514** [comment]
@umar7860 found any solution??

**Comment by bhaskarjha514** [comment]
> I have also faced the same issue can anyone help me with this?

Change JDK version to 11 in Android Studio

Ref - https://www.youtube.com/watch?v=CIAeWm7ywEQ

**Comment by umar-aftab-qureshi** [comment]
@bhaskarjha514  it works... Thank you :)

**Comment by Fajeeer** [comment]
> > I have also faced the same issue can anyone help me with this?
> 
> Change JDK version to 11 in Android Studio
> 
> Ref - https://www.youtube.com/watch?v=CIAeWm7ywEQ

I have updated to jdk11 and checked it but I still get the same error. Why do I still get it?

**Comment by RakeshYadav010** [comment]
thank Jake it work for me
