### ISSUE TITLE
@BindColor fields must not be private or static (Kotlin)

### ISSUE THREAD

**Issue by Jawnnypoo** [JakeWharton/butterknife#960]
Hey there,

This is an issue that I see when using butterknife with Kotlin. It occurs with the following:

```
//These are broken, I believe so is @BindFloat
@BindInt(R.integer.some_int) var someInt: Int = 0
@BindDimen(R.dimen.some_dimen) var someDimen: Int = 0
@BindColor(R.color.colorPrimary) var colorPrimary: Int = 0
@BindBool(R.bool.some_bool) var someBool: Boolean = false
``` 

<img width="753" alt="screen shot 2017-05-17 at 10 34 29 pm" src="https://cloud.githubusercontent.com/assets/1459320/26185598/98cca26e-3b51-11e7-9bdf-55e06ef8d33e.png">

Here is a project that produces these errors
https://github.com/Jawnnypoo/ButterknifeBindFailure

**Comment by diegomontoya** [comment]
We are also having this issue.  With latest Android Studio 3.0 preview and latest butterknife release

**Comment by Jawnnypoo** [comment]
Good to know. Just to confirm, I tested this with a few ButterKnife versions including 8.0.0 and still had the error, so I think this is independent of the version of ButterKnife (past 8.0.0 when this feature was added) and Android Studio.

**Comment by Ilya-Gh** [comment]
The issue is the same as described [here](https://github.com/JakeWharton/butterknife/issues/783#issuecomment-254959414). 

> That's a property whose backing field is private. Add `@JvmField` to generate a public field instead.

**Comment by Jawnnypoo** [comment]
Ahhh good stuff @Ilya-Gh thanks. Hopefully others will find this issue when they run into this then! 😄

**Comment by pedrovarela86** [comment]
I defined my with lateinit and they work..

**Comment by erikhuizinga** [comment]
Either `@JvmField` or `lateinit` work for me, but YMMV if the property must no be nullable.

**Comment by theapache64** [comment]
I replaced `internal var (\w+): (\w+)(\? = null)` with `lateinit var $1: $2` and it worked xD

**Comment by SwishHoopDev** [comment]
```
@BindView(R.id.myView)
@JvmField
var myView: View? = null
```
or 
```
@BindView(R.id.myView)
lateinit var myView: View
```
