### ISSUE TITLE
lib 8.6.0 -> Execution failed for task kotlin.text.StringsKt__StringsJVMKt.replace, parameter $receiver

### ISSUE THREAD

**Issue by MrThiago** [JakeWharton/butterknife#961]
lib 8.6.0
Error:Execution failed for task ':app:processArmeabiDebugResources'.
> Parameter specified as non-null is null: method kotlin.text.StringsKt__StringsJVMKt.replace, parameter $receiver

**Comment by sapphirejade** [comment]
The same issue happens to me when I try to solve https://github.com/JakeWharton/butterknife/issues/842 .
So maybe you can refer to my solution to fix it.
Hope it will be helpful.

**Comment by Gaket** [comment]
Run into the same problem

**Comment by JakeWharton** [comment]
Not clear why you think this library is the problem. Provide a sample to reproduce.
