### ISSUE TITLE
[Suggestion] Declear this works with kotlin.

### ISSUE THREAD

**Issue by XieEDeHeiShou** [JakeWharton/butterknife#966]
I'm learning kotlin recently, then I tried to use ButterKnife with Kotlin directly, of course, nothing happened. Then I searched it, asked for help, and read the [Kotlin's refrences-Kapt](http://kotlinlang.org/docs/reference/kapt.html#using-kotlin-annotation-processing-tool) again to get an answer: use kapt and ButterKnife will work.
So my suggestion is add:
>If you are using Kotlin
>```gradle
>apply plugin: 'kotlin-kapt'
>```
>and this:
>```diff
>- annotationProcessor 'com.jakewharton:butterknife-compiler:8.6.0'
>+ kapt 'com.jakewharton:butterknife-compiler:8.6.0'
>```
to [ButterKnife-Download](https://github.com/JakeWharton/butterknife#download) to tell others this works with Kotlin, maybe someone is looking for help just like me =)

**Comment by FlorianPfisterer** [comment]
Thanks so much! Tried it for ages now 😅

**Comment by Nominalista** [comment]
I replaced annotationProcessor with kapt but unfortunatelly it's still not working, I mean, ButterKnife is not generating _ViewBinding classes.  I'm using ButterKnife in java classes.

**Comment by gabrieloshiro** [comment]
But if you are using Kotlin than you don't really need Butterknife anymore. You can use  [Android Kotlin Extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html). It is just a suggestion (of course).

**Comment by JakeWharton** [comment]
Or property delegates

**Comment by Botz** [comment]
I had some problems switching from annotionProcessor to kapt because annotionProcessor disables java incremental builds by default and kapt doesn't. I had to disable it for my own

`compileOptions.incremental = false`

I think it is only necessary if you have a Base Class with @BindView fields.
