### ISSUE TITLE
Omit debugging information from release build

### ISSUE THREAD

**Issue by ok3141** [JakeWharton/butterknife#970]
Currently ButterKnife pass names of fields into methods of class `Utils`.

Even after obfuscation of fields in target class, these names will be visible after decompilation.

Anyway, nobody needs this information in release build.

In example below you can see, that names `newPartyButton`, `statusText`, `deckText` are exposed via `String` constants:

    target.newPartyButton = Utils.castView(view, R.id.new_party, "field 'newPartyButton'", TextView.class);
    if (view != null) {
      view2131492972 = view;
      view.setOnClickListener(new DebouncingOnClickListener() {
        @Override
        public void doClick(View p0) {
          target.onNewPartyClicked();
        }
      });
    }
    target.statusText = Utils.findOptionalViewAsType(source, R.id.status, "field 'statusText'", TextView.class);
    target.deckText = Utils.findOptionalViewAsType(source, R.id.deck, "field 'deckText'", TextView.class);

In my understanding, we need to apply changes in [FieldCollectionViewBinding](https://github.com/JakeWharton/butterknife/blob/master/butterknife-compiler/src/main/java/butterknife/compiler/FieldCollectionViewBinding.java#L56) and probably in some other places.

**Comment by JakeWharton** [comment]
Annotation processors don't get information about the variant so this is not feasible.

**Comment by ok3141** [comment]
Is it possible to extract parameter for annotation processor in order to be able to configure it manually?
