### ISSUE TITLE
Custom View (or elsewhere),all the click event is invalid after using 'getHandler().removeCallbacksAndMessages(null)'.

### ISSUE THREAD

**Issue by w1216220482** [JakeWharton/butterknife#972]
Custom View (or elsewhere),all the click event is invalid after using 'getHandler().removeCallbacksAndMessages(null)'.
I guess 'getHandler' is used for communication in butterknife,
that the Butterknife message was be removed when I was using 'getHandler' remove.
Now I have solved the problem through using the new Handler , 
of course,I hope Butterknife explain this problem in the document for us, or solve in the next version！

I use version is 8.2.1, I tried 8.6.0, but it has the same problems.

**Comment by JakeWharton** [comment]
ButterKnife does not use handlers. It calls findViewById and calls setter methods views for listeners. That's it.

If you can create a sample that demonstrates the failure is Butter Knife I'll take a look.

**Comment by w1216220482** [comment]
sample: https://github.com/w1216220482/ButterknifeDemo

**Comment by w1216220482** [comment]
`package butterknife.internal;

import android.view.View;

/**
 * A {@linkplain View.OnClickListener click listener} that debounces multiple clicks posted in the
 * same frame. A click on one button disables all buttons for that frame.
 */
public abstract class DebouncingOnClickListener implements View.OnClickListener {
  static boolean enabled = true;

  private static final Runnable ENABLE_AGAIN = new Runnable() {
    @Override public void run() {
      enabled = true;
    }
  };

  @Override public final void onClick(View v) {
    if (enabled) {
      enabled = false;
      v.post(ENABLE_AGAIN); // After the call ‘removeCallbacksAndMessages’, here may be a problem
      doClick(v);
    }
  }

  public abstract void doClick(View v);
}`

Maybe there are better ways Debouncing
try:
`public abstract class DebouncingOnClickListener implements View.OnClickListener {
    static boolean enabled = true;

    private static final Runnable ENABLE_AGAIN = new Runnable() {
        @Override
        public void run() {
            enabled = true;
        }
    };

    @Override
    public final void onClick(View v) {
        //    if (enabled) {
        //      enabled = false;
        //      v.post(ENABLE_AGAIN);
        doClick(v);
        //    }
    }

    public abstract void doClick(View v);
}`
