### ISSUE TITLE
Bind Dynamic String

### ISSUE THREAD

**Issue by LinArcX** [JakeWharton/butterknife#973]
Hi. in a certain situation i want to create dynamic string from xml and pass parameter to it.here is my strings.xml:
```
.
.
<!-- SnackBars -->
    <string name="snack_bar_change_language">Application Language Changed To: %1$s!</string>
<!-- SnackBars -->
.
.
```
and in code i want to pass these parameter to BindString, something like this:
```
    String language = "en";
    @BindString(R.string.snack_bar_change_language, "en")
    String snackBarChangeLanguage;
```
how to achieve that?
Thanks.

**Comment by JakeWharton** [comment]
If you're hardcoding `"en"` why don't you just have multiple strings that are suffixed with `_en` and bind them? I don't see a lot of value in adding this because arguments are typically bound dynamically and not statically.

**Comment by LinArcX** [comment]
they don't hardcoding!(for clarity, i delete those parts of code and hardcode theme.)
they are coming and read from preferencesManager and dynamically bind to that String variable.

**Comment by JakeWharton** [comment]
That's impossible with ButterKnife then, which operates only at compile time. All you can do is use the normal `getString(int, String...)` method unfortunately.
