### ISSUE TITLE
 Feedback BUG

### ISSUE THREAD

**Issue by TCQQ** [JakeWharton/butterknife#977]
I was useing translation, if con't understand I am sorry.
For example：in "activity_a.xml" i add this code：include layout="layout_b.xml"  if  i use butterknife to add from "layout_b.xml" of button of onClick ，It was invalid，but i use android original（findById）code to add onClick it was effective.

**Comment by TCQQ** [comment]
this is i add code
id=rl_sidebar_top_button is from layout_b.xml，but i was add this code：include layout="layout_b.xml in：activity_a

public class OneActivity extends Activity{

    @BindView(R.id.rl_sidebar_top_button)
    RelativeLayout rlSideBarTopButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentResId(R.layout.activity_a);

    ButterKnife.bind(this);
}

  @OnClick({R.id.rl_sidebar_top_button})
    public void sideBar(View v) {
        switch (v.getId()) {
            case R.id.rl_sidebar_top_button:
                showToast("It was invalid");
                break;
            default:
                break;
        }
    }
}

**Comment by JakeWharton** [comment]
Can you supply an failing test or reproducing sample that demonstrates the problem?

**Comment by TCQQ** [comment]
I have just test again, the problem still exists, but if delete the (build) folder in the （project） folder, and delete the (build) folder in the (app) folder, this problem will not exist

**Comment by TCQQ** [comment]
your（butterknife）library are very much good👍

**Comment by JakeWharton** [comment]
Sounds like a build system issue then. Again, without a way to reproduce there's no way to know.
