### ISSUE TITLE
can not access to view item layout on my holder class at recycler view

### ISSUE THREAD

**Issue by tazik561** [JakeWharton/butterknife#979]
hi sir.I've created a recyclerview adapter and then do inflate my row layout .
`public class NotificationRecyclerviewAdapter extends RecyclerView.Adapter<NotifyViewHolder> {

@Override
public NotifyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

    View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.notifylist2, parent, false);
    return new NotifyViewHolder(view);
}`
this is my NotifyViewHolder class:

    `class NotifyViewHolder extends RecyclerView.ViewHolder {

    @BindView(R.id.)
    public NotifyViewHolder(View itemView) {
        super(itemView);
        ButterKnife.bind(this, itemView);

        }
    }`
 in @BindView(R.id.) i do not access to any of my notifylist2 layout? i have imported R class of my project **import com.safarayaneh.notify.R**; whats your idea?

when i compile my app i get this error:

**Error:(52, 23) error: element value must be a constant expression**

I am sure i am using correct R class. and by findviewbyid i access to my resource without any problem.
i am using butterknife:8.5.1.

in my project i have a few module that i added to my project.

**Comment by JakeWharton** [comment]
Sounds like you're trying to use Butter Knife in a library module. You need the Gradle plugin and to use `R2` and not `R`. See: https://github.com/JakeWharton/butterknife#library-projects
