### ISSUE TITLE
butterknife:8.6.0 problem with adding to android studio

### ISSUE THREAD

**Issue by tazik561** [JakeWharton/butterknife#980]
I want to update butterknife from 8.5.1 to 8.6.0 but i got this error:
`Error:(42, 13) Failed to resolve: com.jakewharton:butterknife:8.6.0`
and `Error:Failed to resolve: annotationProcessor`
how can i fix it?

**Comment by JakeWharton** [comment]
Are you using the latest version of Android Gradle plugin?

**Comment by HulShun** [comment]
Maybe he is using the Android Studio 3.0
