### ISSUE TITLE
NPE on child class

### ISSUE THREAD

**Issue by mohittanwar94** [JakeWharton/butterknife#981]
Hello JakeWharton,
i am using butter knife but it gives me NPE on  view .the actual scenario is following...
i have a base activity all other activities extend this base activity .base activity have a frame layout inside it .
all the child activity layout content is dynamically replace inside this frame layout .no oncreate() method call on child activity so when i run this line of code it gives me NPE(Null pointer exception) on any view of child activity when i go for  binding .can you please tell me how to resolve this.

**Comment by JakeWharton** [comment]
Provide a failing test case or reproduction sample.

**Comment by mohittanwar94** [comment]
Hii JakeWharton ,

I added a sample plz check and let me know the issue.

https://drive.google.com/open?id=0B1VKsHyU8zWuWkFaY2YxRjJoYXc

**Comment by mohittanwar94** [comment]
please update on this

**Comment by zakir01913** [comment]
Hi mohittanwar94 ,
I have tested the issue on your provided sample app. I am able to fix it and run the app successfully. 
I think the problem is in the app side. Your MainActivity#onCreate method like this.

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);
         …………..
        replaceContentLayout(setUILayout(), R.id.container);
        ……........
}

Here before adding the fragment_splash layout in the main layout you are trying to bind it. So it gets NPE. I just reorder the method calls like this

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        replaceContentLayout(setUILayout(), R.id.container);
        ButterKnife.bind(this);
         …………..
}
and it’s run successfully.

**Comment by JakeWharton** [comment]
What @zakir01913 said. Butter Knife calls `findViewById` so ensure you view hierarchy is fully set up or bind to multiple objects for partial binding.
