### ISSUE TITLE
Android studio 3.0 preview not generate _ViewBinding class

### ISSUE THREAD

**Issue by xyggun** [JakeWharton/butterknife#985]
i`m use butterKnife version 8.6.0 ,and i`m  Configured correctly。
logcat in this pic
![image](https://user-images.githubusercontent.com/9079574/27426671-044be444-576f-11e7-9e97-83c5fa4435cb.png)

**Comment by JakeWharton** [comment]
Provide a sample or failing test case that demonstrates the problem.
