### ISSUE TITLE
Butterknife binding not working with Android 7.1.2

### ISSUE THREAD

**Issue by jaisonz** [JakeWharton/butterknife#987]
The version 8.6.0 was is working correctly till Android OS version 7.1.1. But after updating to 7.1.2 OS version the binding functionality doesn't seem to work. Device is Google Pixel. Could you please check?

**Comment by JakeWharton** [comment]
Butter Knife generates code that calls standard Android APIs. If the APIs that it use stopped working with a minor OS update every app would break.

If you can provide a sample that reproduces that issue I'll have a look, but Im tentatively closing.
