### ISSUE TITLE
Views in ViewHolder from different module null after Bind

### ISSUE THREAD

**Issue by anton46** [JakeWharton/butterknife#988]
I have a problem when bind `ViewHolder` that extend another `ViewHolder` from different module.

So here is the illustration
1. ViewHolderParent - Module A
```
public class ViewHolderParent extends RecylerView.ViewHolder {
	@BindView(R2.id.text) TextView text;
    
	ViewHolderParent(View itemView) {
		super(itemView);
		ButterKnife.bind(this, itemView);
	}
}
```

2. ViewHolderChild Module B
```
public class ViewHolderChild extends ViewHolderParent {
	@BindView(R.id.text_2) TextView text_2;
    
	ViewHolderParent(View itemView) {
		 super(itemView);
	}
}
```
If I bind the `ViewHolderParent` its works fine. But if I bind the `ViewHolderChild` all the views that `ViewHolderParent` has are was null. There is need some special config? 

Thanks

**Comment by JakeWharton** [comment]
I'm fairly sure this isn't supported.

**Comment by anton46** [comment]
@JakeWharton Ok thank you for the answer
