### ISSUE TITLE
Incorrectly type data found for annotation

### ISSUE THREAD

**Issue by christophecommon** [JakeWharton/butterknife#99]
Hi 

I'm inflating a custom view that extends FrameLayout.
Some code:
<code>
  @InjectView(R.id.txt_title)
    TextView mTxtTitle;

@Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        ButterKnife.inject(this,this);
    }
</code>

It worked on different projects, but not on this one. And I see no difference.
I looked at issue <b>62</b> but running the clean task doesn't help.

Any pointers where I can look or is this a bug ?

Thanks !
Christophe

**Comment by qeemiaomiao** [comment]
I got the same problem, there's no tips about the wrong import error,hope you can fix it.

**Comment by Marabita** [comment]
We get the same issue, thanks for posting about change R class

**Comment by lustigdev** [comment]
Fixed my issues as well. Great find with importing the wrong R class. So silly this is still an issue in Android...
