### ISSUE TITLE
The error code cannot be located.

### ISSUE THREAD

**Issue by yubaokang** [JakeWharton/butterknife#998]
When I am in the project use Butterknife and Dagger2 at the same time, if the control id can not find in the layout file, compile time will prompt a pile of dagger automatically generated file can't find the mistake - > symbol errors, but did not locate the real code errors.

![error_file](https://user-images.githubusercontent.com/7115700/27744564-8c13e564-5df2-11e7-8161-94e253bb62aa.png)

![inkedinkedh5drgs1_smk1wpud98 mon3_li](https://user-images.githubusercontent.com/7115700/27744745-578f34a0-5df3-11e7-9982-3d354677bfc6.jpg)

**Comment by JakeWharton** [comment]
There's not really anything this library can do about it. The errors aren't caused by Butter Knife.
